### ISSUE TITLE
vAmiga crash after exiting intro of Brataccas (1990)(Psygnosis)

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#104]
vAmiga crash after exiting intro of Brataccas (1990)(Psygnosis).

Report:
[report.txt](https://github.com/dirkwhoffmann/vAmiga/files/3404020/report.txt)

Game:
[Brataccas (1990)(Psygnosis)[cr Rectum Research].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3404021/Brataccas.1990.Psygnosis.cr.Rectum.Research.adf.zip)

**Comment by dirkwhoffmann** [comment]
Crash was easy to fix.

However, it now hangs in an infinite loop. The game does not detect any key press 😖. I didn't find out yet how exactly it polls the keyboard. 

<img width="893" alt="Screenshot 2019-07-18 at 10 52 47" src="https://user-images.githubusercontent.com/12561945/61444826-765e2200-a94c-11e9-8d1b-50c6be565638.png">

In SAE, I can run it up to this screen, but I don't know what to do next. Either the game is frozen or I am not smart enough to get it startet 🤔.

<img width="736" alt="Screenshot 2019-07-18 at 11 01 33" src="https://user-images.githubusercontent.com/12561945/61444983-c63ce900-a94c-11e9-90d4-85d84c9f1ded.png">

**Comment by Alessandro1970** [comment]
In that place the main character must be seen on the left...something hangs

**Comment by dirkwhoffmann** [comment]
OK, I'll let Rupert know.

**Comment by Alessandro1970** [comment]
Brataccas - Manual

READ ME FIRST
INTRODUCTION

Welcome to Brataccas the first Interactive Video. This product will work on
the Atari 520ST, the Commodore 512K Amiga and the Apple 512K Fat Mac. The
sticker on the front of the package indicates which you have purchased.

QUICK LOADING INSTRUCTIONS

To participate immediately in the Interactive Video, please follow these
instructions:
If you have difficulty at any stage, please refer to inside Brataccas for
more detailed instructions.

1.  Set up your computer but leave the power off.
2.  Insert the disk into your main or internal disk drive (Amiga owners
Kickstart first).
3.  You can now turn your system on.
4.  Brataccas will load automatically.
5.  The title screen will load, you should then wait for the main program
to load and the message "PRESS ANY KEY" to appear, if you do so, the main
program will load and run automatically.
6.  You can now control the hero Kyne, with the mouse on your computer and
begin your journey into Brataccas.

Note: a DOOR on the right is missing...

**Comment by dirkwhoffmann** [comment]
I also found out why vAmiga hangs...

When a key is pressed or released, the keyboard handler calls CIAA::setKeyCode(uint8_t keyCode) which is implemented as follows:

    void
    CIAA::setKeyCode(uint8_t keyCode)
    {
        debug(CIA_DEBUG, "setKeyCode: %X\n", keyCode);
    
        // Put the key code into the serial data register
        SDR = keyCode;
    
        // Trigger a serial data interrupt
        delay |= CIASerInt0;    
    }

However, I forgot to tell the CIA to wake up. If it is idle (sleeping), it simply ignores what we do here. And indeed, the event inspector shows that both CIAs are sleeping for a while. The bug is shielded most of the time, because CIA A is usually woken up by the VSYNC handler. 

<img width="980" alt="Screenshot 2019-07-18 at 12 23 23" src="https://user-images.githubusercontent.com/12561945/61450627-c5f61b00-a957-11e9-96e0-f33a92053df5.png">

**Comment by dirkwhoffmann** [comment]
Once found, it was really easy to fix:

    void
    CIAA::setKeyCode(uint8_t keyCode)
    {
    debug(CIA_DEBUG, "setKeyCode: %X\n", keyCode);
    
    // Put the key code into the serial data register
    SDR = keyCode;
    
    // Trigger a serial data interrupt
    delay |= CIASerInt0;

    // Wake up the CIA
    wakeUp();
    }

Now the game loads and I do see the main character.

<img width="893" alt="Screenshot 2019-07-18 at 12 58 08" src="https://user-images.githubusercontent.com/12561945/61452455-0ce60f80-a95c-11e9-921e-6b47f83e3a73.png">

However, the guy immediately starts doing all kind of stuff by itself 😳. How can I get him under control? In UAE, he is also running around like crazy.

**Comment by Alessandro1970** [comment]
Oh yes, I have choose this game ti test becouse mouse control movements... 🤪.   Very difficult.... but it’s only a test for the emulator. Like black lamp

**Comment by dirkwhoffmann** [comment]
>  I have choose this game ti test becouse mouse control movements... 🤪. Very difficult.

OK, the weird character movement is a feature and not a bug, then. Another issue solved 😀.
