### ISSUE TITLE
Eye of the beholder crashes

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#107]
Hi, vAmiga crashes while loading Eye of the beholder after intro:

Report:
[CRASH.TXT](https://github.com/dirkwhoffmann/vAmiga/files/3410026/CRASH.TXT)

disk1:
[Eye of the Beholder - Advanced Dungeons& Dragons (1990)(SSI)(Disk 1 of 3)[cr SKR - Fast Eddie].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3410027/Eye.of.the.Beholder.-.Advanced.Dungeons.Dragons.1990.SSI.Disk.1.of.3.cr.SKR.-.Fast.Eddie.adf.zip)

disk2:
[Eye of the Beholder - Advanced Dungeons& Dragons (1990)(SSI)(Disk 2 of 3)[cr SKR - Fast Eddie][v Byte Warrior].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3410028/Eye.of.the.Beholder.-.Advanced.Dungeons.Dragons.1990.SSI.Disk.2.of.3.cr.SKR.-.Fast.Eddie.v.Byte.Warrior.adf.zip)

disk3:
[Eye of the Beholder - Advanced Dungeons& Dragons (1990)(SSI)(Disk 3 of 3)[cr SKR - Fast Eddie].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3410029/Eye.of.the.Beholder.-.Advanced.Dungeons.Dragons.1990.SSI.Disk.3.of.3.cr.SKR.-.Fast.Eddie.adf.zip)

**Comment by dirkwhoffmann** [comment]
Seems to work with the latest version: 

http://www.dirkwhoffmann.de/vAmiga/vAmiga_0.29.1.zip

<img width="893" alt="Screenshot 2019-07-19 at 16 05 06" src="https://user-images.githubusercontent.com/12561945/61541776-8e16d280-aa40-11e9-8b1a-1cc89bedd5ec.png">
