### ISSUE TITLE
Rink a dink graphics error

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#108]
Reference (SAE): 

<img width="734" alt="Bildschirmfoto 2019-07-22 um 08 06 54" src="https://user-images.githubusercontent.com/12561945/61610254-ea543f00-ac58-11e9-9a96-f5020f80fe70.png">
<img width="734" alt="Bildschirmfoto 2019-07-22 um 08 03 31" src="https://user-images.githubusercontent.com/12561945/61610268-efb18980-ac58-11e9-9f57-11c1ef96e79b.png">

vAmiga 🙈:

<img width="893" alt="Bildschirmfoto 2019-07-22 um 08 05 00" src="https://user-images.githubusercontent.com/12561945/61610286-01932c80-ac59-11e9-967c-450997aa2a6b.png">
<img width="893" alt="Bildschirmfoto 2019-07-22 um 07 59 43" src="https://user-images.githubusercontent.com/12561945/61610293-03f58680-ac59-11e9-8d18-f7c8710bbe39.png">

**Comment by dirkwhoffmann** [comment]
😎 It works since multi-colour sprites are supported (sprites with the "attached" bit set).

<img width="858" alt="Bildschirmfoto 2019-08-08 um 08 20 22" src="https://user-images.githubusercontent.com/12561945/62679870-14766280-b9b6-11e9-8406-da10a9654a56.png">

<img width="858" alt="Bildschirmfoto 2019-08-08 um 08 20 34" src="https://user-images.githubusercontent.com/12561945/62679911-396ad580-b9b6-11e9-893b-f8494c88054d.png">

**Comment by dirkwhoffmann** [comment]
Watching Rink a Dink in the DMA debugger is almost as much fun as watching the original. They really do a lot of crazy stuff in this demo such as shifting the DMA window all over the place (2nd picture): 

<img width="858" alt="Bildschirmfoto 2019-08-08 um 18 35 50" src="https://user-images.githubusercontent.com/12561945/62721044-a492c700-ba0b-11e9-8398-bcda15be847d.png">
<img width="858" alt="Bildschirmfoto 2019-08-08 um 18 35 12" src="https://user-images.githubusercontent.com/12561945/62721051-ab213e80-ba0b-11e9-822e-d46ced2abd25.png">
<img width="858" alt="Bildschirmfoto 2019-08-08 um 18 35 59" src="https://user-images.githubusercontent.com/12561945/62721084-c12eff00-ba0b-11e9-9977-5011550a283d.png">

**Comment by mithrendal** [comment]
Amazing 🤤
