### ISSUE TITLE
Clock app graphics errors

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#11]
<img width="783" alt="Screenshot 2019-04-28 at 16 41 50" src="https://user-images.githubusercontent.com/12561945/56865997-b8726a00-69d4-11e9-82af-35cf1fd64761.png">

Todo: Find out if it's a line Blitter or a copy Blitter issue.

**Comment by mithrendal** [comment]
I bet its neither the blitter line nor the blitter copy operation. I think it is the fill operation, which is not working as expected.

have a look here: 
http://amigadev.elowar.com/read/ADCD_2.1/Hardware_Manual_guide/node0122.html


But I could also be wrong... It is just a feeling.

**Comment by dirkwhoffmann** [comment]
Yes, that's right, but the fill operation is not stand-alone. It is either part of a line operation or a copy operation. I hope it's the copy operation, because vAmiga doesn't support this, yet. The line Blitter is from WinFellow and hopefully correct and complete (I prefer not to touch that code 😬).

**Comment by mithrendal** [comment]
Oh boy, that fill mode was so far ahead in the days back then. It was 1987 clearly a machine from th future ... 😄

**Comment by dirkwhoffmann** [comment]
Yes, emulators are time-machines. It's been ages since I looked at the Workbench graphics in detail. I have to admit that it really looks a little primitive 😯.

**Comment by mithrendal** [comment]
But I can't see where it copys inside the clock window. I only see lines ... In fact it is a vector drawing of a analog clock.  If you stretch it, it will adapt to the windows new size.  Isn't this all done with lines only ? I know you don't want to touch it, but the more I think about it, the more I tend to bet it is the missing line Blitter fill mode.  Hopefully I am wrong 😳

**Comment by dirkwhoffmann** [comment]
I've run the clock with debug output enabled and captured the following: 

<img width="1180" alt="Screenshot 2019-04-29 at 08 48 56" src="https://user-images.githubusercontent.com/12561945/56880120-da62ff80-6a5b-11e9-8773-75838e5ac35e.png">

There are about 50 blit operation for drawing a single watch face. The ones marked with "D" are descending copy blits and the ones marked with "E" are those with exclusive-fill on. Hence, the bug is most likely caused by my copy Blitter code (which doesn't support fill modes yet). That's good news, because it means that I don't have to fully understand the WinFellow line Blitter code.

**Comment by dirkwhoffmann** [comment]
<img width="1030" alt="Screenshot 2019-05-12 at 10 10 01" src="https://user-images.githubusercontent.com/12561945/57579787-5f5d0880-74a1-11e9-91bb-35702a8ca8e8.png">

**Comment by mithrendal** [comment]
This clock is really iconic art. Must have been advised by Andy Warhol I think... looks still very modern

**Comment by dirkwhoffmann** [comment]
> This clock is really iconic art

This morning I first had this 😅:

<img width="219" alt="Screenshot 2019-05-12 at 09 24 32" src="https://user-images.githubusercontent.com/12561945/57585680-a243ce00-74eb-11e9-929a-8f9ee6b51003.png">

 Too modern for the 80s. On the other hand, it could be interpreted as a digital version of Dalí's melting clock. Maybe I should declare it as art and sell it 🤔.

**Comment by mithrendal** [comment]
Mhhm I am not sure about this one.  Looks more like a mosaic of a clock in a ancient roman bath. 😃
Mosaics have a long history, starting in Mesopotamia in the 3rd millennium BC. Pebble mosaics were made in Tiryns in Mycenean Greece; mosaics with patterns and pictures became widespread in classical times, both in Ancient Greece and Ancient Rome.

**Comment by mithrendal** [comment]
The process you are going through resembles the process of unearthing precious ancient treasures out of the mud and cleaning them afterwards. These treasures look first a bit damaged and broken, in a thoughtful and carefully process they have to be cleaned and put into the same sparkling shape they have been thousand years ago.
