### ISSUE TITLE
Rink A Dink graphics glitch

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#116]
If BFD is zero, Copper waits until Blitter has finished the current operation.

Rink a Dink seems to rely on it. It sets BFD to zero during this scene: 

 <img width="858" alt="Bildschirmfoto 2019-08-08 um 08 21 13" src="https://user-images.githubusercontent.com/12561945/62680222-037a2100-b9b7-11e9-9fc9-04bd11b3bcb6.png">

TODO: Verify if xAE also shows this bug if the fast / immediate Blitter is selected. Because "immediate blits" are performed immediately, the Copper never has to wait and the BFD flag should not have an effect.

**Comment by mithrendal** [comment]
YouTube Video for reference.  https://youtu.be/7cOjC-nhs_o

It does not show the graphic corruption

**Comment by dirkwhoffmann** [comment]
It's most likely not a BFD flag issue. Since the DMA inspector can display Blitter DMA now (orange), it can be seen that there is no direct Blitter / Copper interaction in that scene: 

<img width="853" alt="Bildschirmfoto 2019-08-22 um 15 26 18" src="https://user-images.githubusercontent.com/12561945/63519584-89d44e00-c4f3-11e9-94e5-1ee1e0e7c027.png">

Also, SAE shows a similar graphics error in all Blitter modes.

It might be related to #98. I bet it runs in UAE only with "compatibility = highest". This needs to be verified...

**Comment by dirkwhoffmann** [comment]
Does anybody know how the DMA debugger works in UAE? It would be super cool to have a comparison pic for that scene.

**Comment by mithrendal** [comment]
I just tried it. It works like this:

start WinUAE.
start a ADF-disk.
Pressing SHIFT+F12 opens a debugger console window.
type h, lists all winuae debugger console commands
the commands for enabling DMA debugger are v -1 to v-3

in 2016 toni wrotes on EAB this a post.
```
v -1 : enable only, no visual mode.
v -2 : enable + visual mode
v -3 : enable + visual mode + doubled horizontal pixels

Note that currently mode can't be changed after it has been enabled.

After it has been enabled (visual or not), v <vpos> <hpos> shows detailed scanline DMA/CPU usage. 
```

**Comment by dirkwhoffmann** [comment]
> start WinUAE.

Roger. Engines are running. 😎

> start a ADF-disk.

Roger. Ready to take off. 😎

> Pressing SHIFT+F12 opens a debugger console window (on a mac book FN+SHIFT+F12).

Maybe you're fooling me and it means "Eject" 🤔.
Anyway, let's do it. No risk no fun...

OMG, it opens up a build-in text adventure called "The Debugger" 😯.

> type h

There is no "go north", "go south" etc.? Seriously? 🤔

> v -2

Copied that. I guess this is the magic spell that teleports me right into the heart of the dungeon.

Yes, it does 🥳...

<img width="830" alt="Bildschirmfoto 2019-08-23 um 08 26 04" src="https://user-images.githubusercontent.com/12561945/63571362-4247d380-c580-11e9-8785-3ec1cca23721.png">

With some deeper knowledge of the magic arts, I'm sure the DMA usage could be overlayed at the actual pixel positions where the DMA takes place (like in vAmiga), but the image is good enough for now...

With my restricted knowledge about UAE, I cannot distinguish dark green / bright green / green, but I should check if there are line blits and fill blits going on in that scene. Both have a different timing than standard copy blits. vAmiga cannot emulate line blit timing yet and it treats fill blits like standard copy blits. If we had a DMA usage table for fill blits, exact timing could be easily implemented with the micro-programmable Blitter in vAmiga.

**Comment by dirkwhoffmann** [comment]
The good: No more polygon errors in Blitter level 2 😎

<img width="1012" alt="Bildschirmfoto 2019-11-01 um 14 12 47" src="https://user-images.githubusercontent.com/12561945/68027136-d5546680-fcb1-11e9-8a82-2aa084d9ee6e.png">

The bad: New graphics glitches appeared in scenes that worked before 😬.

TODO: Check if the glitches also appear with the FastBlitter

**Comment by mithrendal** [comment]
The new sexy activity monitor complete steals "rink a dink" the show. From what we can see here is that the audio of the demo is surely unbalanced (right channels hav to much power).  Audio balancing graph looks like small plants  with big roots under the earth. But nevertheless I like the sound of the demo a lot !

**Comment by dirkwhoffmann** [comment]
In v0.46.1, Rink a dink is completely broken with Blitter level 2 🤭:

<img width="875" alt="Bildschirmfoto 2019-11-14 um 12 29 30" src="https://user-images.githubusercontent.com/12561945/68853651-c2db2380-06da-11ea-9679-cfe311c5e011.png">

**Comment by dirkwhoffmann** [comment]
No longer broken in Blitter accuracy level 2.

**Comment by dirkwhoffmann** [comment]
Among the remaining graphics glitches, this one is the most severe:

<img width="841" alt="Bildschirmfoto 2020-03-13 um 09 04 19" src="https://user-images.githubusercontent.com/12561945/76601804-fa7f9e00-6509-11ea-8c80-6efbdcb7c7af.png">

The most likely reason is the dynamic modification of the bitplane shift values at specific horizontal positions. This is done by the second Copper list: 

<img width="421" alt="Bildschirmfoto 2020-03-13 um 09 03 50" src="https://user-images.githubusercontent.com/12561945/76601815-00757f00-650a-11ea-95ee-15a683be587f.png">

TODO: Write timing tests for BPLCON1

**Comment by dirkwhoffmann** [comment]
Related links: 

http://eab.abime.net/showthread.php?t=94080

http://www.stashofcode.fr/zoom-hardware-avec-bplxmod-et-bplcon1-sur-amiga/

The second one is in French and I don't a single word. But maybe Google translate can help...

**Comment by dirkwhoffmann** [comment]
In my eyes, there are no more issues with the demo in v0.64 😎.

There are some oddities in the very left and very right screen area in some scenes, but I am not sure if these area are visible on a real Amiga.

**Comment by mithrendal** [comment]
You could double check on A500 MMSE 💂🏾

**Comment by dirkwhoffmann** [comment]
> You could double check on A500 MMSE 💂🏾

Just compared with the YouTube version:

https://www.youtube.com/watch?v=7cOjC-nhs_o

The artifacts I was wondering about (such as the yellow stripe below) are all on the YouTube video, too 🥳.

<img width="851" alt="Bildschirmfoto 2020-03-15 um 18 24 26" src="https://user-images.githubusercontent.com/12561945/76706867-f8286a00-66ea-11ea-9b12-123dbffc7d2d.png">

After that worked out so well, I'll try my hand at more complicated things tomorrow: Shopping for groceries. I already tried on Saturday, but the store looked like one in Venezuela 😬.

Fruits and vegetables: Sold out
Pasta: Sold out
Bread: Sold out
Toilet paper: Sold out
Flour: Sold out
Eggs: Sold out

My fridge is full of frozen pizza now. This was the only item available in large quantities 😳.

**Comment by mithrendal** [comment]
The pizzas all have the same topping? 😳

just read that china is sending medical experts, kind of special forces I think, to italy in order to support us and fight against the plague. Hopefully fully equipped with all kinds of heavy armour and weapons.😎  See @Alessandro1970 help is coming ... hold out ... 

When they successfully cleaned Italy hopefully they don't forget the rest of europe ...

**Comment by Alessandro1970** [comment]
My friends, here is a disaster!  It seems that neither masks nor gloves are enough, you have to stay at home and make sure you haven't already been infected.  We hope that the German company CureVac from Tübingen will be able to find the solution.  Many people die every day, there is no medicine that can ...

**Comment by dirkwhoffmann** [comment]
> We hope that the German company CureVac from Tübingen will be able to find the solution.

I know nothing about this company, but I did my PhD in Tübingen. It was a picturesque and peaceful place back then. It is still picturesque, but they have problems with increasing criminality. Now a medical crisis is coming on top of that and nobody really seems to know how to deal with it. Yes, it’s all very sad...
