### ISSUE TITLE
Katakis hangs

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#121]
Katakis hangs after the trainer screen

[Katakis (1989)(Rainbow Arts)[cr Defjam - RSi][t +4 Defjam].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3489677/Katakis.1989.Rainbow.Arts.cr.Defjam.-.RSi.t.%2B4.Defjam.adf.zip)

**Comment by dirkwhoffmann** [comment]
The game executes the reset instruction of the M68000:

<img width="980" alt="Bildschirmfoto 2019-09-02 um 10 54 02" src="https://user-images.githubusercontent.com/12561945/64102458-56ee4d80-cd70-11e9-9ed5-05fc4d8d4134.png">

https://www.manualslib.com/manual/596159/Motorola-M68000.html?page=75

<img width="787" alt="Bildschirmfoto 2019-09-02 um 10 55 22" src="https://user-images.githubusercontent.com/12561945/64102446-4c33b880-cd70-11e9-9c5c-08079fdf0a6b.png">

TODO: Check what Musashi is doing when reaching this instruction. 
Next: Check what the Amiga is doing when the CPU executes this instruction

**Comment by dirkwhoffmann** [comment]
For reference: According to the A500 schematics at

https://www.amigawiki.org/dnl/schematics/A500_R6.pdf

the processors reset line is connected to Gary, Agnus, Paula, and the two CIAs. Denise has no reset pin.

**Comment by dirkwhoffmann** [comment]
The RESET instruction is executed in SAE, too, but the game doesn't work there either:

![Bildschirmfoto 2019-11-11 um 13 57 19](https://user-images.githubusercontent.com/12561945/68589159-836ac800-048b-11ea-8cf0-efe94de6189b.png)

We need to run it in UAE before debugging the issue further.

**Comment by dirkwhoffmann** [comment]
v0.55 (Moira Edition) 😎:

<img width="1012" alt="Bildschirmfoto 2020-01-15 um 06 04 59" src="https://user-images.githubusercontent.com/12561945/72406658-540f5a80-375d-11ea-999b-25108b36592a.png">

Please reopen if you experience more issues with this game.
