### ISSUE TITLE
Mouse disappears

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#123]
Using the workbench the mouse vanish on the right side of the screen:
<img width="857" alt="Schermata 2019-08-11 alle 10 40 07" src="https://user-images.githubusercontent.com/34916641/62831794-b4d1be80-bc24-11e9-9d96-233a21a3a818.png">

<img width="856" alt="Schermata 2019-08-11 alle 10 40 48" src="https://user-images.githubusercontent.com/34916641/62831795-b7341880-bc24-11e9-8516-4abc049eff41.png">

**Comment by dirkwhoffmann** [comment]
Seems like this release hasn't reached production quality yet 🙄. I need to talk to my in-house quality assurance team...

**Comment by dirkwhoffmann** [comment]
Fixed. Bug was in Denise::drawSprites(). If a sprite cannot be drawn completely, because it is too far right, the end position is cropped. The cropping code was wrong.
