### ISSUE TITLE
Buggy boy crashes while loading

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#127]
BuggyBoy crashes while loading the intro screen.

[BBoy.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3496280/BBoy.adf.zip)

[CRASH.TXT](https://github.com/dirkwhoffmann/vAmiga/files/3496282/CRASH.TXT)

**Comment by dirkwhoffmann** [comment]
Does no longer crash in  v0.33 which can be downloaded in the Releases section.

<img width="841" alt="Bildschirmfoto 2019-08-13 um 14 46 25" src="https://user-images.githubusercontent.com/12561945/62943285-66feb700-bdda-11e9-904f-ee9086d8e845.png">
