### ISSUE TITLE
Blitter checksum mismatch 

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#136]
Blitter is broken (checksum errors when launching with Kick 1.3).

Left: vAmiga, Right: SAE

<img width="1051" alt="Bildschirmfoto 2019-08-17 um 13 42 31" src="https://user-images.githubusercontent.com/12561945/63211308-b5bb9200-c0f5-11e9-8f16-e6d0e6358702.png">

Checksums were OK a couple of weeks ago.

**Comment by mithrendal** [comment]
Can we trust SAE blitter? Maybe yours is already a more correct emulation?

**Comment by dirkwhoffmann** [comment]
> Can we trust SAE blitter?

Yes, we can 😀.

**Comment by mithrendal** [comment]
I bet this is again something babarish. The changelog of blitter.cpp hints to this commit c575d5d00c01518c1f4881c47289799373d609b1 for #41.

**Comment by dirkwhoffmann** [comment]
🤓 It's neither a bug in SAE or in vAmiga.

SAE calls a special (quicker) function if the blit is very simple. In this function, no checksums are computed and therefore the output is wrong. If I comment this out, the checksums are identical: 

    if (blitfunc_dofast_desc[mt] !== 0 && !blitfill) {
	blitfunc_dofast_desc[mt](bltadatptr, bltbdatptr, bltcdatptr, bltddatptr, blt_info);
    }

**Comment by dirkwhoffmann** [comment]
Just verified the first 6000 blits when loading International Karate. Nearly all are identical (some mismatches occur, because a couple of data chunks are at different memory locations). 

Bottom line: This was a false alarm.
