### ISSUE TITLE
Graphics glitch in International Karate intro

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#138]
Reference (SAE, Kick 1.3, OCS chipset, Immediate Blitter): 

<img width="751" alt="Bildschirmfoto 2019-08-21 um 18 19 48" src="https://user-images.githubusercontent.com/12561945/63450010-651f9e00-c441-11e9-8d61-88edde9e70c0.png">

vAmiga 🙈:

<img width="853" alt="Bildschirmfoto 2019-08-21 um 18 20 58" src="https://user-images.githubusercontent.com/12561945/63450112-96986980-c441-11e9-9767-07cdae4c38c0.png">

**Comment by dirkwhoffmann** [comment]
After blit 6, there is a strange discrepancy in BLTREGA 🤔. 
(Both SAE and vAmiga do immediate blits)

<img width="1236" alt="Bildschirmfoto 2019-08-21 um 19 41 42" src="https://user-images.githubusercontent.com/12561945/63454819-d401f480-c44b-11e9-99f7-8486ad016ddc.png">

Needs investigation...

**Comment by dirkwhoffmann** [comment]
BLTREGA discrepancy solved. SAE has two variables for storing the pointers (local and global). I dumped the local one instead of the global one. 

New suspect: The line Blitter

<img width="1236" alt="Bildschirmfoto 2019-08-22 um 08 09 36" src="https://user-images.githubusercontent.com/12561945/63490220-748bff00-c4b4-11e9-8286-0195e61109b9.png">

**Comment by dirkwhoffmann** [comment]
vAmiga and SAE behave similar until blit 91. This blit is started with a different value in BLTDPT:

<img width="1230" alt="Bildschirmfoto 2019-08-22 um 08 32 20" src="https://user-images.githubusercontent.com/12561945/63491504-a2bf0e00-c4b7-11e9-9d4c-f4e1381c6ac7.png">

**Comment by dirkwhoffmann** [comment]
Blitter was falsely accused. Discrepancy is due to some code in Kickstart. If SAE and vAmiga are run with df0: only, all Blitter checksums are equal. 

Next suspect: Copper. There is Copper DMA going on just a few pixels ahead of the graphics glitch: 

<img width="853" alt="Bildschirmfoto 2019-08-22 um 09 53 21" src="https://user-images.githubusercontent.com/12561945/63496904-026ee680-c4c3-11e9-9343-767f38eaec25.png">

**Comment by Alessandro1970** [comment]
The copper, I have read that someone has written that the real nightmare of the Amiga emulation is only the copper...

**Comment by dirkwhoffmann** [comment]
>  the real nightmare of the Amiga emulation is only the copper...

Actually, there are multiple nightmares out there 😬

I just figured out what happens before the graphics glitch occurs: 

    [648] (148,112)  051DBA BCBSDA 4020 07C0 [03BB58] Copper: COPPC: 3BB58 move(BPLCON0, $4200) (16896)
    [648] (148,114)  051DBA BCBSDA 4020 07C0 Denise: pokeBPLCON0(4200)
    [648] (148,114)  051DBA BCBSDA 4020 07C0 Denise: pokeBPLCON0(3200,4200)

The intro switches from 3 actives bitplanes to 4.

**Comment by dirkwhoffmann** [comment]
I still have no idea where these bad pixels come from. I only found out the following: If you watch this intro for a long time, the balls turn into flying bananas. Which means that the programmer must have been pretty drugged.

<img width="853" alt="Bildschirmfoto 2019-08-23 um 15 08 45" src="https://user-images.githubusercontent.com/12561945/63595874-42fd5b80-c5ba-11e9-8665-08828957f596.png">

Besides, here is the relevant part of the Copper list for reference (not for the bananas, for the bug): 

<img width="980" alt="Bildschirmfoto 2019-08-23 um 15 22 46" src="https://user-images.githubusercontent.com/12561945/63595812-1f3a1580-c5ba-11e9-9b48-4d8f22a556b6.png">

**Comment by dirkwhoffmann** [comment]
I can definitely confirm that it's not the on-the-fly modification of BPLCON0. I've written more tests and vAmiga handles them correctly. All of them.

Amiga 500 ❤️: 

![bpu4_A500](https://user-images.githubusercontent.com/12561945/63604570-6fba6e80-c5cc-11e9-8929-2df7e38c2e2e.jpeg)

vAmiga 😎:

<img width="853" alt="Bildschirmfoto 2019-08-23 um 17 32 40" src="https://user-images.githubusercontent.com/12561945/63604591-7ea12100-c5cc-11e9-8714-b67491a1b37a.png">
 
SAE 🙈:

<img width="718" alt="Bildschirmfoto 2019-08-23 um 17 33 52" src="https://user-images.githubusercontent.com/12561945/63604673-ae502900-c5cc-11e9-9ad2-b2a15f2d98a4.png">

Therefore we can rule out BPLCON0 as a suspect. It must be the BPLxPT registers then. Let's arrest them.

**Comment by dirkwhoffmann** [comment]
It's not the BPLxPT registers. I verified the DMA data in line 0x94 manually and all data words match. The only remaining possibilities are: 

1. A color register issue.
2. An issue with the shift register contents inside Denise.

TODO: Rule out 2 by dumping the iBuffer (index buffer) in line 0x94. If it contains a repeating pattern, it must be 1. Add a function dumpIBuffer() to the debug functions.

**Comment by mithrendal** [comment]
Brilliant bug hunt strategy. You are the [hunter](https://youtu.be/VO8qCRVj8dI).

**Comment by dirkwhoffmann** [comment]
Here is what happens: 

    [1199] (127,209)  051DBA BCBSDA 4020 07C0 Agnus: denise->bpldat[PLANE4] = FF80 (from 3A1DE)
    [1199] (148,121)  051DBA BCBSDA 4020 07C0 Agnus: denise->bpldat[PLANE4] = 0 (from 3A510)

In line 127, BPL4DAT is set to $FF80. When we reach line 148, the number of active bitplanes is 3, so the value in BPL4DAT does not matter. When the intro switches to 4 bitplanes in line 148, BPL4DAT is transferred into the shift register and drawn. This causes the graphics glitch. In the rest of the line, BPL4DAT is loaded with 0 which is the correct value to draw the scene right.

Unfortunately, there is no direct indication of what is going wrong. It just explains why we see what we see.

**Comment by mithrendal** [comment]
Crosscheck and run international karate on the A500 MMSE? Maybe it also shows the glitch?

**Comment by dirkwhoffmann** [comment]
> Maybe it also shows the glitch?

OMG. It's really there 😳. 

![IMG_3521](https://user-images.githubusercontent.com/12561945/63634286-8a382a80-c654-11e9-9385-149d2d2ae676.jpg)

Bottom line: The intro has a bug that gets compensated by a bug in xAE. This was the least thing I expected 🤭.

Despite the fact that I wasted two days of my life hunting a phantom, this is good news. It shows that vAmiga is clearly improving 😎.

**Comment by mithrendal** [comment]
You should change the label from bug to feature. I believe in vAmiga. The rebel. The new source of trust. 👌😂

**Comment by dirkwhoffmann** [comment]
I think this can be closed then 😅.
