### ISSUE TITLE
Slow Blitter sometimes freezes the emulator

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#144]
The disk controller has started to freezes the emulator occasionally 😖.

<img width="853" alt="Bildschirmfoto 2019-08-26 um 11 45 21" src="https://user-images.githubusercontent.com/12561945/63681955-2863f600-c7f7-11e9-9002-495305a9850b.png">

Log: 

    Turbo-reading 7358 words from disk (offset = 1627).
    Turbo read Df0: cyl: 54 side: 0 offset: 3675 checkcnt = 7358 checksum = 1AE6C17B
    [787] (299,151)  FEA592 -CB-D- 602C 0000 DiskController: pokeDSKLEN(4000)
    [787] (299,151)  FEA592 -CB-D- 602C 0000 DiskController: dma = DRIVE_DMA_OFF

Note: The motor does not get switched off.

Maybe some uninitialised variable, because it does not always happen.

**Comment by dirkwhoffmann** [comment]
Seems to be a slow Blitter issue. Micro-instructions are OK. It's likely related to bus cycle usage (which turns out to be the critical part of accurate Blitter emulation).

This is likely the same issue I experienced earlier with Rink a Dink.

**Comment by dirkwhoffmann** [comment]
Just noticed that I completely forgot to implement the BLTPRI flag in DMACON 😬.

**Comment by mithrendal** [comment]
that is funny. BLTPRI aka "blitter nasty"

10 | BLTPRI | Blitter DMA priority (over CPU micro) (**also called "blitter nasty"**) (disables /BLS pin, preventing micro from stealing any bus cycles while blitter DMA is running)

**Comment by dirkwhoffmann** [comment]
Yes, it's nasty, especially because the available documentation is ambiguous 😖:

HRM: 

    „If DMAF_BLITHOG is a 0, the DMA manager will monitor the 68000 cycle requests. 
    If the 68000 is unsatisfied for three consecutive memory cycles, the blitter will release 
    the bus for one cycle.“

Amiga Intern: 

    „Wenn es gelöscht ist , bekommt der Prozessor jeden vierten geraden 
    Buszyklus vom Blitter .“

The HRM does not say anything about even cycles. Amiga intern explicitly mentions the even cycles („gerade Buszyklen“). This would mean that the CPU would have to wait up to 7 cycles, because the odd cycles don't count. 😟

**Comment by mithrendal** [comment]
Can’t we test the correct behavior with alpines blitspeed? We make a modified version of it in which we set the nasty bit. Then in theory from what I understand the blitter should execute somewhat  faster with the nasty bit on and more time should be left which in turn is just visualized by alpines test.

**Comment by dirkwhoffmann** [comment]
> We make a modified version of it in which we clear nasty bit and one where we set the nasty bit.

Although I haven't checked yet what Alpine9000 is doing in his test program to measure Blitter speed, I expect that something like that could be done.

However, I need to fix another bug first. When booting WB in Blitter mode 1, the emulator enters some infinite loop, but if reset is hit afterwards, it boots successfully 😩.

**Comment by dirkwhoffmann** [comment]
Wow, this one is really nasty and has no easy fix.

When resetting the Musashi core, the core calls peek16() to read the reset vector from memory. If the slow Blitter has been selected,  this function calls Agnus::executeUntilBusIsFree(). This means that Agnus is emulated  a couple of cycles during reset() which must be avoided by all means.

There are three solutions: 

1. Add an if statement to peek16(): `if (isRunnig) {do this } else { do that }`
2. Switch to the fast Blitter during reset and reselect the slow Blitter afterwards
3. Patch the Musashi core

Solution 1 is bad, because peek16() is called so frequently. It would slow down emulation. 
Solution 2 is bad, because it is ugly (there is already enough ugly software out there).
Solution 3 is bad, because the Musashi core cannot be updated easily any more.

Among those three bad solutions, solution 3 seems to be least worst to me.

**Comment by dirkwhoffmann** [comment]
Another bug  revealed:

Musashi core doesn't pick the reset vector from (the overlayed) Rom as it is supposed to be. It gets is from Ram, because the memory source table gets initialised after the CPU resets. This bug wasn't discovered earlier, because chip ram is initialised with zeroes which means that the CPU starts with the program counter set to 0. In that particular case, Kickstart shields the error, because it has a jump statement at the very beginning (right after the $1111 which is some command that is executed before the JMP):

       ; This match word is used when looking for ROMs.

    FC0000  1111

        ; The ROM can be started by jumping to its base address plus 2,
        ; or by mapping it at location zero and resetting.  Either way,
        ; the machine starts running at FC00D2 (in the latter case, because
        ; the 68000's PC is loaded from location 4 at cold start).

    FC0002  jmp       FC00D2

    FC0008  0000                        Garbage.
    FC000A  FFFF

**Comment by dirkwhoffmann** [comment]
> Among those three bad solutions, solution 3 seems to be least worst to me.

Is already solved in v0.35. Musashi has been patched successfully.
