### ISSUE TITLE
Running Logica Diagnostic in FS-UAE?

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#146]
Because SAE cannot boot Logica, I tried the Rom in FS-UAE. Unfortunately, I failed. Maybe I am doing something stupid and somebody else can give me a hint.

My issues are: 

- After booting Logica, I can't use the keyboard, albeit the keyboard controller is accepted with status "OK" 🙈.
- FS-UAE greedily retains the mouse 🙈. How can I get my Mac mouse cursor back without hiding the FS-UAE windows? Shaking like in vAmiga does not work.
- When I select the disk test menu with the mouse, I get this 🙈:

<img width="1072" alt="Bildschirmfoto 2019-08-29 um 08 13 23" src="https://user-images.githubusercontent.com/12561945/63915205-b4fbf780-ca35-11e9-8d88-d2a9c4cd7b71.png">

**Comment by Alessandro1970** [comment]
https://fs-uae.net/keyboard-shortcuts
