### ISSUE TITLE
Xcode hangs during release-builds

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#149]
"New Apple" shows its whole brilliance again 😖. 

Xcode is no longer capable to do a relate-build of vAmiga.
This is definitely an Apple bug, but I have to deal with it somehow.

**Comment by dirkwhoffmann** [comment]
I "solved" it by disabling Swift optimisations in both debug- and release-builds. The crucial part is the C++ part which is still optimised in release-builds.

Considering the fact that Swift is already a few years old, this is simply embarrassing for a formerly brilliant company.

I keep this issue open until one of the next Xcode updates hopefully fixes this.

**Comment by dirkwhoffmann** [comment]
Xcode 11 still has that bug.

**Comment by dirkwhoffmann** [comment]
Update: Xcode Version 11.0 (11A420a), v0.55 code base
Compilation did terminate (but it took nearly forever).

**Comment by dirkwhoffmann** [comment]
After porting back stuff from vAmiga, Virtual64 is now suffering from frozen builds, too. I crawled through the repo and I think I found the culprit. 

https://github.com/dirkwhoffmann/virtualc64/commit/b511d6238a8f56d5934defa96f4c6e850f8a5c96

In this commit, I changed the CPUInfo struct:

Old struct: 

```
typedef struct
{
    u64 cycle;

    u16 pc;
    u8 sp;

    u8 a;
    u8 x;
    u8 y;
    
    bool nFlag;
    bool vFlag;
    bool bFlag;
    bool dFlag;
    bool iFlag;
    bool zFlag;
    bool cFlag;

    bool irq;
    bool nmi;
    bool rdy;

    u8 processorPort;
    u8 processorPortDir;
}
CPUInfo;
```

New struct: Old struct plus

```
   // Disassembled instructions, starting at 'start'
   DisassembledInstruction instr[CPUINFO_INSTR_COUNT];

   // Disassembled instructions from the log buffer
   DisassembledInstruction loggedInstr[CPUINFO_INSTR_COUNT];
```

Bottom line: The Swift compiler has a runtime problem when large C structs are provided in the bridging header. For structures as large as the provided one, the Swift compiler hangs forever (in release builds). 

First, I thought providing data in form of large structs is a good idea, because it eliminates a lot of calls going through the ObjC proxy, but apparently it is not. Swift simply can't handle these structures 😖.

Todo: Analyze all exposed structures. Do no longer expose large structs and provide separate proxy functions for each data field.

**Comment by idrougge** [comment]
Have you tried reporting this on bugs.swift.org?

**Comment by dirkwhoffmann** [comment]
> Have you tried reporting this on bugs.swift.org?

No, not yet. A small test case has to be set up first.

**Comment by dirkwhoffmann** [comment]
The disassembler API has been changed. Structure "DisassembledInstr" is gone and so is the compile time issue.

I'm not really in a mood to file a bug report though... the more I use Swift, I am becoming less and less a fan of this language.
