### ISSUE TITLE
FastMem does not work as expected

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#15]
<img width="766" alt="Schermata 2019-05-07 alle 22 51 03" src="https://user-images.githubusercontent.com/34916641/57332753-afdc0b00-711b-11e9-8471-a981e69011dc.png">

NoFastMem app worked fine (reported by Alessandro)

**Comment by Alessandro1970** [comment]
Doesn't it turned over the right amount of memory?
...later, I relaunched the FASTMEMFIRST app and vAmiga re-added the memory! 
... I did not remember that once the RAM was removed using the FASTMEMFIRST it was re-enabled.

**Comment by mithrendal** [comment]
The reenabling is correct. In the description of the system documentation they say it behaves like a switch.

**Comment by mithrendal** [comment]
Oh no, sorry I did not read it carefully enough 😔. You said you clicked first NoFastMem and later on FASTMEMFIRST... I thought you clicked NoFastMem a second time.

**Comment by Alessandro1970** [comment]
In Winfellow if I select 512k chip + 512k (slow) I have this situation:

![Untitled 5](https://user-images.githubusercontent.com/34916641/57440191-d39c6f80-7247-11e9-82da-cd031ced363e.png)

If I run NoFastMem the memory is reduced:

![Untitled 2](https://user-images.githubusercontent.com/34916641/57440201-d8f9ba00-7247-11e9-890b-9fcc9b073f40.png)

I I run another time NoFastMem or FastMemFirst ...nothing happens like in the real Amiga; the FastMemFirst does not change memory only change the position of the usable memory FAST/CHIP.

**Comment by dirkwhoffmann** [comment]
Hmm, yes, I really need to work on this 😟

<img width="1030" alt="Screenshot 2019-05-10 at 16 53 47" src="https://user-images.githubusercontent.com/12561945/57567565-8c46e800-73db-11e9-8532-61e561e4a025.png">

**Comment by Alessandro1970** [comment]
Could In MacOs the adf files be associated to vAmiga changing the icon ?

...like the dark workbench as shown above

**Comment by dirkwhoffmann** [comment]
I just run Kick 1.3 with WB 1.3 in vAmiga:

- "NoFastMem" does act like a toggle switch. It removes Slow + Fast or reenables Slow + Fast.
- "FastMemFirst" has no visible effect (does internal reordering). 

I did run UAE and it seems to be the same there. 

Hence, either vAmiga is doing the right thing or I don't understand the bug 🤔.

Maybe I am just confused, because I first read "NoFastMem app worked fine" as "No FastMem app worked fine" 😅.

**Comment by dirkwhoffmann** [comment]
> Could In MacOs the adf files be associated to vAmiga changing the icon ?

I think this is difficult, because it would mean to extract semantic information from the ADF data. Furthermore, handling icon images in macOS is really a pain.

**Comment by dirkwhoffmann** [comment]
Can I close that one?

**Comment by mithrendal** [comment]
Digging even more back in history ... I have got an older V12 Workbench version with SlowMemLast 🤩 The icon is a 🐢I guess they renamed it in V13 to FastRamFirst which is logically the same or am I wrong ? 
<img width="203" alt="image" src="https://user-images.githubusercontent.com/17108995/57727269-56328e00-7691-11e9-8687-36cd0032a4f7.png">

I configured an Amiga with 512k Chip and 1MB Fast. 
WB12 reports 1446820 Bytes
If I doubleclick NoFastMem it reports 438552
If I doubleclick NoFastMem again it reports 1446820
If I doubleclick NoFastMem again it reports 438552
If I doubleclick NoFastMem again it reports 1446820
If I doubleclick SlowMemLast nothing visible happens it still reports 1446820

I would say close this one. We can always reopen in case

**Comment by Alessandro1970** [comment]
Ok, you can close it
