### ISSUE TITLE
vAmiga crashes when changing settings and hangs after restart

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#151]
VAmiga crashes while changing settings (I do not know which one) but after pressing Power On vAmiga crashes and after restarting crashes; I need to delete all vAmiga files and re-install it:

[CRASH.TXT](https://github.com/dirkwhoffmann/vAmiga/files/3563273/CRASH.TXT)

**Comment by dirkwhoffmann** [comment]
From CRASH.TXT

> Assertion failed: (isHPos(hpos)), function scheduleNextBplEvent

This is a strange one. Can you try to reproduce it? 

Considering the symptom, it could also be due to some uninitialised variable, but I just checked all variables when I made snapshot saving more robust. 🤔

**Comment by Alessandro1970** [comment]
also inserting a disk in df1:

rocess:               vAmiga [554]
Path:                  /Applications/vAmiga.app/Contents/MacOS/vAmiga
Identifier:            dirkwhoffmann.vAmiga
Version:               0.35 (0.35)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           vAmiga [554]
User ID:               501

Date/Time:             2019-09-01 10:40:31.543 +0200
OS Version:            Mac OS X 10.14.6 (18G87)
Report Version:        12
Anonymous UUID:        A987418F-3B0B-A48C-3B6D-07F5F973FEF8


Time Awake Since Boot: 1000 seconds

System Integrity Protection: enabled

Crashed Thread:        10

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Performing @selector(insertDiskAction:) from sender NSButton 0x600000e91810
Assertion failed: (!hasDisk()), function insertDisk, file /Users/hoff/vAmiga/Amiga/Drive/Drive.cpp, line 486.
 

Thread 0:: Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	0x00007fff77c764d0 type metadata accessor for _ContiguousArrayStorage + 0
1   libswiftFoundation.dylib      	0x00007fff77dfd4ec static Array._unconditionallyBridgeFromObjectiveC(_:) + 12

**Comment by Alessandro1970** [comment]
This one if I select blitter accuracy 2 and kick 1.3 without disks inserted:

Application Specific Information:
Assertion failed: (isHPos(hpos)), function scheduleNextBplEvent, file /Users/hoff/vAmiga/Amiga/Computer/Agnus/EventHandler.cpp, line 372.

**Comment by Alessandro1970** [comment]
Ok this two:

first crash enabling df1 and inserting a disk in df1 after inserted in df0 (removing df1 or df2 from setting no more crash)

second power up with kick 1.3 with blitter accuracy 2 o 3 on (removing blitter accuracy no more crash)

**Comment by dirkwhoffmann** [comment]
The disk crash issue has been fixed. I simply forgot to code the drive number into the scheduled event. Hence, when inserting a disk in df1, the new disk was inserted in df0. If there was a disk already, it crashed.
