### ISSUE TITLE
AMOS hangs

### ISSUE THREAD

**Issue by KenDFish** [dirkwhoffmann/vAmiga#152]
Prior to v0.33, AMOS (a BASIC-like programming language) would launch and be semi-usable, but the UI was seriously mangled

![image](https://user-images.githubusercontent.com/6280435/64075111-e3830800-ccab-11e9-8741-27e24a69bae9.png)

v0.33 fixes the graphical issues, but AMOS appears to hang - the mouse pointer doesn't move and the keyboard doesn't respond. vAmiga itself doesn't hang or crash.

![image](https://user-images.githubusercontent.com/6280435/64075072-60fa4880-ccab-11e9-8a16-de3401f9328b.png)

 I've tested this with my own copy of AMOS (an image of my original disks!), and a downloadable copy that I've found online at [https://www.planetemu.net/rom/commodore-amiga-applications/amos-the-creator-v1-31-19xx-europress-h-promus](url). I've attached this image in case it helps.
[Amos The Creator v1.31 (19xx)(EuroPress)[h Promus].zip](https://github.com/dirkwhoffmann/vAmiga/files/3563365/Amos.The.Creator.v1.31.19xx.EuroPress.h.Promus.zip)

**Comment by KenDFish** [comment]
Apologies - I'm in idiot. Somehow, I'd managed to "disable" both mouse/joystick ports, which means the mouse wasn't working. AMOS now appears to run fine, at least in my limited testing so far.

**Comment by dirkwhoffmann** [comment]
>  I'd managed to "disable" both mouse/joystick ports

This happened to me on the real machine. I thought the mouse was broken and the solution was to simply connect it.
