### ISSUE TITLE
Paradroid '90 crashes

### ISSUE THREAD

**Issue by KenDFish** [dirkwhoffmann/vAmiga#158]
Paradroid '90 (ADF attached) boots but doesn't get far - I can see lots of

`[14770] (219,224)  FC16A4 BC--D- 0000 1022 Memory: WARNING: peek16(FFFFFF): Address violation error (reading odd address)`

errors. After stalling for around 15 seconds (or much longer if "warp mode" isn't enabled), vAmiga then crashes with 

`Assertion failed: (IS_EVEN(addr)), function peekCustom16, file /Users/hoff/vAmiga/Amiga/Computer/Memory.cpp, line 1081.
`

Hope this is useful!
[KD0088 Paradroid '90.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3581144/KD0088.Paradroid.90.adf.zip)

**Comment by dirkwhoffmann** [comment]
In the latest version, the address violation errors seem to be gone and so seem the crashes.

The game ends up in an infinite loop with the power led flashing. 

P.S.: Paradroid was one of my favourite games on the C64 🤤.

**Comment by dirkwhoffmann** [comment]
Doesn't seem to work in SAE either. Maybe it's a copy-protected disk.

**Comment by dirkwhoffmann** [comment]
I've checked all Paradroid versions that are available on PlanetEmu:

<img width="554" alt="Bildschirmfoto 2019-10-17 um 09 57 24" src="https://user-images.githubusercontent.com/12561945/66989551-da67c200-f0c4-11e9-9ba1-d59f93b8ded2.png">

They all work, including the intros: 

<img width="866" alt="Bildschirmfoto 2019-10-17 um 09 48 02" src="https://user-images.githubusercontent.com/12561945/66989468-b4dab880-f0c4-11e9-9421-b90eb0418660.png">

<img width="866" alt="Bildschirmfoto 2019-10-17 um 09 47 16" src="https://user-images.githubusercontent.com/12561945/66989473-b86e3f80-f0c4-11e9-8b1a-4d63ad43e32d.png">

This backs my hypothesis that the original file has copy-protection. Can I close for now?

**Comment by mithrendal** [comment]
This game actually looks very modern to me ... Should have better been named maybe Paradroid 2090 ?  Because it was soo far ahead of time back then ... I would say you should close it...

**Comment by dirkwhoffmann** [comment]
I agree that graphics is really cool, but for me, the C64 version is more fun to play.
