### ISSUE TITLE
Kickstart rom 2.04 Crashes App

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#161]
<img width="511" alt="Screen Shot 2019-09-08 at 10 38 36 PM" src="https://user-images.githubusercontent.com/31462938/64500000-75c97400-d289-11e9-933a-3ad75c7fc84a.png">

Using KS 2.04 37.175 and the app recognizes it file, but on every boot it crashes.
Please Look into this.

Also have a 3.1 rom that works fine, but the app doesn't recognizes it.
<img width="489" alt="Screen Shot 2019-09-08 at 10 41 31 PM" src="https://user-images.githubusercontent.com/31462938/64500147-030cc880-d28a-11e9-9233-7998e98f6a70.png">

**Comment by dirkwhoffmann** [comment]
The crash is already fixed on the main branch and will be gone in the next release.

I never tried Kick 3.1 myself. There seem to be three A500 compatible versions out there in the wild: 

    Kickstart v3.1 rev 40.63 (1993)(Commodore)(A500-A600-A2000)[!].rom
    Kickstart v3.1 rev 40.63 (1993)(Commodore)(A500-A600-A2000)[b].rom
    Kickstart v3.1 rev 40.63 (1993)(Commodore)(A500-A600-A2000).rom 

The [b] version has size 524293 which doesn't match 512 KB. It is rejected by vAmiga right away.
The version without [] doesn't start in vAmiga. I decided to reject it, too. 

The [!] version runs just fine 😎: 

<img width="862" alt="Bildschirmfoto 2019-09-09 um 08 00 20" src="https://user-images.githubusercontent.com/12561945/64508328-7b50a980-d2dd-11e9-807c-6d2638c9ba0a.png">

Does anybody understand the naming scheme? What does [b] and [!] mean? b = raw binary, ! = verified ???. I stumble across these suffixes all the time.

**Comment by dirkwhoffmann** [comment]
Kick 3.1 is recognised in v0.37 which can be downloaded in the Releases section.
