### ISSUE TITLE
Kickstart 3.14 46.143

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#162]
Kickstart 3.14 46.143 is working but is also not recognized...
<img width="1215" alt="Screen Shot 2019-09-09 at 11 09 40 AM" src="https://user-images.githubusercontent.com/31462938/64543048-89f58b80-d2f2-11e9-9c8b-6ff4bbb43398.png">
<img width="618" alt="Screen Shot 2019-09-09 at 11 10 16 AM" src="https://user-images.githubusercontent.com/31462938/64543069-8eba3f80-d2f2-11e9-812b-02eb16bcf7f8.png">

**Comment by dirkwhoffmann** [comment]
v0.38 is out 😎.
