### ISSUE TITLE
vAmiga and HD0 (A2090 - A590)

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#164]
Is there any way to create and mount a HDF file to install wb 3.1 ?

**Comment by dirkwhoffmann** [comment]
> Is there any way to create and mount a HDF file 

No, hard disks are not emulated yet. Support shouldn't be added before everything else is stable (which won't happen in the near future I think).

**Comment by Alessandro1970** [comment]
When it will be the moment of hd support ...I have found a 4GB virtual hard drive file for Amiga with 3.1 WB that starts with kick 3.1.
For the emulator are needed 68020 CPU emulation and Z2 ram expansion at least 8MB.
There are a full games ready in WHLOAD format, they are preset and run without strange configurations, only main wb configuration as told above:
![Untitled 2](https://user-images.githubusercontent.com/34916641/70421978-31f23080-1a6b-11ea-8b1c-2bf964f88f26.png)

**Comment by dirkwhoffmann** [comment]
> For the emulator are needed 68020 CPU emulation

Actually, it's unlikely that vAmiga will get 68020 support in the near future. To improve emulation accuracy (which is the main goal at the moment), I need to move away from Musashi towards a custom CPU that is specifically tailored to vAmiga's software architecture. The custom CPU will be limited to the Motorola 68000 at first. Supporting the 68010 should be doable without too much pain, but supporting the 68020 and above will be difficult. From the 68020 on, Motorola implemented some kind of parallel instruction execution which is much more difficult to emulate than the rather primitive pipeline design used by 68000 and 68010.

**Comment by bluecursor** [comment]
@Alessandro1970 

Can you share a link to the 4GB virtual hard drive file for Amiga with 3.1 WB that starts with kick 3.1 that you found?

**Comment by Alessandro1970** [comment]
Hi,
I have reduced size of the hd to 2gb, but to be used you need a 68020, fast ram 8mb and kick 3.14 To boot.
I use it on Mister hardware.
I can try to upload with any filetransfer by mail. But I do not know if it is possible, it is a huge file.

**Comment by bluecursor** [comment]
Let me know, it will be used for my mist fpga as well.
https://workupload.com/ is a good service for large file sharing. No account is needed...

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
You need a 68020, fast ram 8mb, AGA and kick 3.14 ...if Minimig on Mist has those you'll ok.

To use Amigabasic ...switch to 68000 and remove fasr ram (but whdload won't work).

I'm trying to upload on workupload as you told me, I must include your mail ?

**Comment by bluecursor** [comment]
I have all the hardware needed.
No email address required just the link it creates

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
Ok
This is the third time that I try to uploag 2Gb file.
Next time I’ll try to split in in 3 part with 7zip (it’s free)

**Comment by bluecursor** [comment]
Ok, let me know...

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
1) Kick
https://workupload.com/file/6HKKEM8xEB8

**Comment by Alessandro1970** [comment]
Now I'll try 700mb per file...

**Comment by bluecursor** [comment]
Password?

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
64

**Comment by Alessandro1970** [comment]
https://workupload.com/ does not work with big files

Give me another one or mail for WeTransfer

**Comment by Alessandro1970** [comment]
If you do not want to write your mail here, you can send me it to Whatsapp or Messenger/facebook

**Comment by bluecursor** [comment]
Try we transfer

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
...your mail...

**Comment by bluecursor** [comment]
bluecursor@outlook.com

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
First of 4 is has begun its run...
![image](https://user-images.githubusercontent.com/34916641/79795580-72848380-8354-11ea-9451-73f2d8c7acf4.jpg)

**Comment by bluecursor** [comment]
I just setup a webdev @ http://www.finishfirst.ca:8030/ on server if you want to try to upload there ?

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
May I use filezilla to copy files ?
I need for filezilla:
Host:
User:
Pass;

**Comment by Alessandro1970** [comment]
Give a try, look your mail.
Has arrived first file ?

**Comment by bluecursor** [comment]
Host is www.finishfirst.ca:8030

And there is no username/password its anonymous

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
Filezilla says:
Errore:	Timeout connessione dopo 20 secondi di inattività
Errore:	Impossibile collegarsi al server

**Comment by Alessandro1970** [comment]
Now second file with WeTransfer is to go

**Comment by bluecursor** [comment]
Try www.finishfirst.ca:2121

No username/password

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
Stato:	In attesa di un nuovo tentativo...
Stato:	Risoluzione dell'indirizzo IP www.finishfirst.ca in corso
Stato:	Connessione a 174.95.214.115:2121...
Errore:	Timeout connessione dopo 20 secondi di inattività
Errore:	Impossibile collegarsi al server

None

**Comment by Alessandro1970** [comment]
Have you received first file ?

**Comment by bluecursor** [comment]
Yes

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
Ok we will use WeTransfer !

...next file is on the run

**Comment by Alessandro1970** [comment]
All files have been sent.
Ok ?

**Comment by bluecursor** [comment]
No missing 004

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
Done

**Comment by bluecursor** [comment]
Yes. Thank you for everything and your time!

Frank Michielli
Sent with iOS Spark!📱

**Comment by bluecursor** [comment]
It says it’s not a formatted drive. But works in fsuae. Can you send me the .rbf your using a lot with .cfg

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
In order to see the files you must use kick 3.14 not else

**Comment by bluecursor** [comment]
I am using the kick.rom you sent

Frank Michielli
Sent with iOS Spark!📱

**Comment by Alessandro1970** [comment]
You can download it here:

**Comment by Alessandro1970** [comment]
See release folder

**Comment by bluecursor** [comment]
Download the latest version. It doesn’t work on my mist.  Beta  v 1.2.3 works for me but not with your ,hdf

Frank Michielli
Sent with iOS Spark!📱
