### ISSUE TITLE
Disk in FS-UAE works, vAmiga...wont

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#165]
[Archive.zip](https://github.com/dirkwhoffmann/vAmiga/files/3619613/Archive.zip)
I used Xcopy to copy this .dms to .adf. The .adf file works fine in FS-UAE, but wont boot in vAMGA. I tried loadiing the disk in WB, but it reports the disk as 0% full.

**Comment by dirkwhoffmann** [comment]
On my machine, FSUAE doesn't recognise the ADF either: 

<img width="959" alt="Bildschirmfoto 2019-09-21 um 17 57 26" src="https://user-images.githubusercontent.com/12561945/65379652-5d018b00-dc99-11e9-9f0f-758542088114.png">

Which Kickstart version did you use with FSUAE?

**Comment by dirkwhoffmann** [comment]
Don't know how to reproduce this. Shall I keep the issue open?

**Comment by bluecursor** [comment]
Sorry, no can't reproduce it...
On Oct 3, 2019, 4:23 AM -0400, Dirk Hoffmann <notifications@github.com>, wrote:

Don't know how to reproduce this. Shall I keep the issue open?

**Comment by dirkwhoffmann** [comment]
> Sorry, no can't reproduce it...

OK, I'll close it for now. Please reopen if a similar issue occurs again. There are definitely bugs left in the disk controller implementation.
