### ISSUE TITLE
Systest fails

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#17]
VAmiga has not passed the Systest:
<img width="770" alt="Schermata 2019-05-11 alle 09 14 04" src="https://user-images.githubusercontent.com/34916641/57566606-fe650000-73ce-11e9-9778-4b8bdcacacc4.png">

Amiga simple tests:
[Amiga Systest.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3168753/Amiga.Systest.adf.zip)

Amiga SysInfo:
[SysInfo.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3168754/SysInfo.adf.zip)

**Comment by Alessandro1970** [comment]
With alpha 3 if I run Sysinfo in DF0 (boot from sysinfo) it hangs:

Report: 
[report.txt](https://github.com/dirkwhoffmann/vAmiga/files/3174871/report.txt)

**Comment by Alessandro1970** [comment]
With alpha 3 if I run **Systest** in DF0 (boot from systest) pressinf F6 from menu it hangs:

Report: 
[report.txt](https://github.com/dirkwhoffmann/vAmiga/files/3174885/report.txt)

**Comment by Alessandro1970** [comment]
With vAmiga_0.20 SysInfo app works well:

<img width="765" alt="Schermata 2019-05-18 alle 22 47 10" src="https://user-images.githubusercontent.com/34916641/57974859-93638c80-79bf-11e9-8f0d-0b311fb89913.png">

Systest no, it Hangs

**Comment by dirkwhoffmann** [comment]
Interestingly, the screenshot reveals that emulation is far from being accurate yet. We're 1.4 times faster than an Amiga 600. This is because neither the Blitter nor the Copper block the CPU. Right now, the bus can be used by multiple components at the same time which of course cannot happen in reality. 

<img width="297" alt="Screenshot 2019-05-18 at 23 16 10" src="https://user-images.githubusercontent.com/12561945/57975079-674a0a80-79c3-11e9-8b2e-f829b6b51802.png">

**Comment by dirkwhoffmann** [comment]
Also interesting: What did Commodore do to make the A4000 4 times faster than the A3000? Both run at 25 MHz 🤔.
