### ISSUE TITLE
3D World Soccer hangs

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#173]
It hangs here: 

<img width="990" alt="Bildschirmfoto 2019-10-04 um 15 09 48" src="https://user-images.githubusercontent.com/12561945/66212881-00519780-e6bf-11e9-8fcf-577be1be0bad.png">

The CPU runs in an infinite loop, polling VPOSR and VHPOSR: 

<img width="980" alt="Bildschirmfoto 2019-10-04 um 15 09 43" src="https://user-images.githubusercontent.com/12561945/66213049-4870ba00-e6bf-11e9-8bc7-ea7de832545a.png">

On a real A500, joystick actions are detected and result in this: 

![IMG_1969](https://user-images.githubusercontent.com/12561945/66213106-663e1f00-e6bf-11e9-82a5-a7220734fa9e.jpeg)

I didn't find a way to start the game on the A500 though.

**Comment by dirkwhoffmann** [comment]
Identifying as an Agnus 8372 is the key to make it work:

<img width="990" alt="Bildschirmfoto 2019-10-04 um 18 19 51" src="https://user-images.githubusercontent.com/12561945/66223619-2fbecf00-e6d4-11e9-9420-0caadd75cdfa.png">

Although it's really in 3D, the gameplay is 🤢.

**Comment by mithrendal** [comment]
Cool. How did you know that setting the correct agnus type was solving the problem. 👍🏻

**Comment by dirkwhoffmann** [comment]
>  How did you know that setting the correct agnus type was solving the problem?

In this particular case, it's all hidden in this screenshot 🧐:

<img width="980" alt="66213049-4870ba00-e6bf-11e9-8bc7-ea7de832545a" src="https://user-images.githubusercontent.com/12561945/66251595-13617780-e752-11e9-86de-ec120890ceba.png">

The soccer game reads VPOSR in a loop. It clears the upper most bit (the long frame bit which is always 1 in non-interlace mode) and compares the result agains the value in D0. To break the loop, the carry flag needs to be set which is only possible if the compare command (which performs a subtraction) compares agains a value that is greater than 0x2000. This is only possible if the ID bits are not zero. The ID bits do not exist in the old Agnus (they read as 0 on the A1000), hence, the loop can only be broken by newer Agnus revisions. To find out the correct ID bit, I used the image produced by test case vpos1 on the MMSE.
