### ISSUE TITLE
Thoughts about a better debug strategy

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#177]
Since progress on this project has slowed down a bit, I need to think about a smarter debug strategy. 

Maybe we should try to test Amiga games in a more chronological order. It is likely that older games (such as Defender of the Crown, Barbarian, Marble Madness etc.) do not rely as much on hardware specific behaviour as the newer ones do. Hence, they are likely to be  more emulator friendly. The worst case for debugging is when multiple errors interfere and such a scenario becomes more likely the newer a game is. 

Defender of the Crown is from 1986, so why not board a time machine and go back to this year? No? Oh, just seen on Wikipedia that 1986 wasn't all that lucky 🤭. Exploding reactors and spaceships had been the headline news back then.

**Comment by Alessandro1970** [comment]
...or switch sometime to VirtualC64 till 3.4 final release...

**Comment by mithrendal** [comment]
Time warp should be easy possible🖖🏻with the help of http://www.lemonamiga.com

Go to advanced search and set release year to 1985. Then you will find what is believed to be the first commercial game for the Amiga on this planet. It is called "monkey business" and only gets a rating of 1.67 out of 10 points🤭. But not too shabby for the very first one ...

**Comment by dirkwhoffmann** [comment]
> only gets a rating of 1.67 out of 10 points🤭

Maybe because it's just as bad as the Atari 2600 version of Donkey Kong 😂.

<img width="814" alt="Bildschirmfoto 2019-10-06 um 14 10 26" src="https://user-images.githubusercontent.com/12561945/66268969-20aa5f00-e843-11e9-8bc6-bbe1782c2986.png">
