### ISSUE TITLE
Is Virtual 64/VAmiga Catalina Ready?

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#183]
Is Virtual 64/VAmiga Catalina Ready?

**Comment by dirkwhoffmann** [comment]
I don't know yet. I'm not in the developer program and waiting for Catalina to be released...

**Comment by dirkwhoffmann** [comment]
I've just read the pretty detailed Catalina review on Ars Technica: 

https://arstechnica.com/gadgets/2019/10/macos-10-15-catalina-the-ars-technica-review/

After reading this, I am kind of disappointed. Firstly, I think Apple is running out of ideas.
Secondly, there is not a single feature that thrills me. Thirdly, ... read yourself:

> Apple's operating system releases have all seemed a bit rushed this year—go ahead and give the company a couple of months to patch Catalina before you install it, if you can.

**Comment by bluecursor** [comment]
Thanks for pointing out the review.Yeah, Even though system prefs shows the upgrade is now out, 'll probably wait til the new year to do so. Hopefully, both emulators will continue to work.

**Comment by dirkwhoffmann** [comment]
> Hopefully, both emulators will continue to work.

I'll make them work if they don't.

**Comment by Alessandro1970** [comment]
Hi,
Does this work in Catalina ?

From terminal window:

sudo spctl --master-disable

Then run all the app...

**Comment by Alessandro1970** [comment]
...oh yes !!!

https://www.reddit.com/r/MacOS/comments/c68gh9/solution_for_all_apps_not_opening_in_catalina/

**Comment by bluecursor** [comment]
before upgrading...

https://www.macworld.co.uk/feature/mac-software/apps-wont-work-catalina-3698142/

**Comment by Alessandro1970** [comment]
At the moment no problem with catalina!

**Comment by dirkwhoffmann** [comment]
> At the moment no problem with catalina!

Seems to be ready then. I haven't upgraded yet due to various reports claiming that Catalina is still beta quality.

**Comment by mithrendal** [comment]
The worst I think is the reported mail.app bug. They say catalina might delete mails from your mail archives.  This is of course absolutely unacceptable. We better wait for the .1 Release.
