### ISSUE TITLE
File names on PlanetEmu

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#187]
Does anybody know how the naming scheme on PlanetEmu works? 

A lot of common file name endings are used such as: 

- [cr]
- [a]
- [b]

What do they mean? 🤔

**Comment by Alessandro1970** [comment]
I think:
Cr cracked
A alternare version
B alternate version
Tr trainer
And so on

**Comment by Alessandro1970** [comment]
Info ADF:

[WB] to be run from Workbench

[a] [a1] [a2] An alternate ORIGINAL version of another ORIGINAL image, e.g. if a game was released, then re-released later with a small change (and the revision/version number is not known). [without any letter means final version]

[b] [b1] [b2] **Bad Dump**  The image is damaged. This is a general 'damaged/bad' flag, to be used when the type of damage does not fit into any of the other 'damaged' categories. It is likely this image will not work properly, or not at all.

[!] Image has had multiply person/multi dump verification to confirm it is a 100% repeatable and correct dump. 

[h] Compression type

[cr name] Cracked by [name]

[v name] Infected and not cleaned by virus [name]

(IT) (DE) (UK) Language

[F] Fixed 

[H] Hacked

[m] Modified from original

[t] Trained version

**Comment by dirkwhoffmann** [comment]
Alessandro, thanks for figuring this out 🥳.

**Comment by dirkwhoffmann** [comment]
I've moved the info to a newly created Wiki page.
