### ISSUE TITLE
ALL Kickstart 2 and higher graphic issues/Broken with v.0.42 and v0.421

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#195]
Still using OSX Mojave. Pics explains 1000 words here:
<img width="829" alt="Screen Shot 2019-10-16 at 3 50 55 PM" src="https://user-images.githubusercontent.com/31462938/66953765-17807580-f02d-11e9-91b1-a42a2399e41e.png">
<img width="880" alt="Screen Shot 2019-10-16 at 3 51 05 PM" src="https://user-images.githubusercontent.com/31462938/66953766-17807580-f02d-11e9-8913-a13a65265921.png">

**Comment by bluecursor** [comment]
Also, should it say locked at this state....
<img width="810" alt="Screen Shot 2019-10-16 at 6 07 50 PM" src="https://user-images.githubusercontent.com/31462938/66962863-199fff80-f040-11e9-971a-eeba65c45d0f.png">

**Comment by dirkwhoffmann** [comment]
Kick 2.x bug has been introduced with commit c1302d47058bf2.

In this commit, Agnus has been made configurable. From this release on, Agnus identifies itself  as Agnus 8372 instead of Agnus 8367 (if an A500 or A2000 is emulated) The distinction is made by a single bit in VPOSR. 

Kick 2.x only exhibits this bug in the 8372 setting. When the specific bit is VPOSR is set, Kick 2.x must do some special stuff which is not yet working in vAmiga. Maybe it thinks that we have an ECS chipset on board??

TODO:

- Write test case to see how Denise identifies itself on the A500 6A, 8A and the A1000.
- Hard-wire the VPOSR bit to 1 in SAE and see if Kick 2.0 launches when OCS is selected.

**Comment by dirkwhoffmann** [comment]
I wrote a new test case (vpos2) that visualises all bits in VPOSR by color bars. It can be used to see how Agnus is identifying itself. Here is what we get in SAE:

OCS Amiga: 

<img width="733" alt="vpos2_ocs" src="https://user-images.githubusercontent.com/12561945/67012641-0a798a00-f0f2-11e9-9ff2-02a705df083f.png">

ECS Amiga: 

<img width="733" alt="vpos2_ecs" src="https://user-images.githubusercontent.com/12561945/67012652-0d747a80-f0f2-11e9-8750-6ba94b67e129.png">

AGA Amiga: 

<img width="733" alt="vpos2_aga" src="https://user-images.githubusercontent.com/12561945/67012661-11080180-f0f2-11e9-8150-743cb5479341.png">

Now, here is the thing: All my original A500s (rev. 6A and 8A) show the bit pattern of the second image. Hence, they identify themselves as having an ECS Agnus, but an OCS Denise. Among the machines we have, only @mithrendal's A1000 identifies itself as having an OCS Agnus. 

I think, all Kick 2.x Roms cannot handle that situation. If they detect an ECS Agnus, they think they are running on an ECS machine. 

I did some experiments in SAE. When I hard-wire the ECS bit to 1 in SAE (and select OCS as chipset), it shows the same graphics glitches as vAmiga: 

<img width="733" alt="Bildschirmfoto 2019-10-17 um 15 17 31" src="https://user-images.githubusercontent.com/12561945/67012810-55939d00-f0f2-11e9-8440-b1ae82492499.png">

**Comment by mithrendal** [comment]
Then this is a Commodore Bug in the Kick 2.x Roms ? These Roms were not meant to run on OCS Denise with ECS Agnus ... 
vAmiga could detect kickstartversion>1.3 and automatically revert to OCS Agnus and disable the ECS Agnus setting? No?

**Comment by dirkwhoffmann** [comment]
> Then this is a Commodore Bug in the Kick 2.x Roms ?

I think so, but it could also be due to a bug that is shared by both SAE and vAmiga.

>  and automatically revert to OCS Agnus...

I think it's better to choose a path similar to the one VirtualC64 is going. This means: 

- We remove the model selection combo box "A500, A1000, A2000".
- We make all hardware items freely customisable (chip revisions, RTC yes/no etc.)
- We replace the "Reset factory settings" button by a menu offering "A500", "A1000", "A2000" as items.

Doing so allows the user to click together a non-existent machine (e.g., a machine with Kick-Rom (instead of a Boot-Rom) and an OCS (A1000) Agnus that is capable of running Kick 2.0). If the user wants to emulate a real machine, he can select, e.g., "Reset factory settings -> A1000" and all hardware options will be set accordingly.

**Comment by dirkwhoffmann** [comment]
Alessandro's A2000 has a Kick 3.1 on board.

<img width="362" alt="Bildschirmfoto 2019-10-19 um 11 44 07" src="https://user-images.githubusercontent.com/12561945/67142883-08383c80-f266-11e9-9b50-0c984968e534.png">

I therefore conclude that Kick 3.1 is supposed to work on the A500 / A2000 (with ECS Agnus and OCS Denise).

@Alessandro1970, any breaking news about the Gotek yet?

**Comment by Alessandro1970** [comment]
Gotek arrived
...but PSU id dead used for two ours only

Yes kick 3.1 and 3.14 works on my A2000 but is ECS

**Comment by dirkwhoffmann** [comment]
> PSU id dead

Oh no 🙈

>  A2000 but is ECS

I see, you've got an ECS Amiga 2000. Didn't know that such a thing exists. When ECS came out I already had a PC and struggled with MS DOS 🙄.

**Comment by Alessandro1970** [comment]
Amiga2000 rev 6.2 and < OCS
Amiga 2000 rev 6.3 ECS
I’m sure

**Comment by Alessandro1970** [comment]
https://en.m.wikipedia.org/wiki/Amiga_2000
See specifications in this page

**Comment by dirkwhoffmann** [comment]
> ...but PSU id dead used for two ours only

Did you send it back?

**Comment by Alessandro1970** [comment]
I have sent only MOBO

Now they told me to check the psu, but I have to find a tester and how to use it

**Comment by bluecursor** [comment]
still not working in v0.43

**Comment by dirkwhoffmann** [comment]
I've just seen a regular A500 with Kick 2.0 on eBay. Hence, I am unsure if Kick 2.0 should or shouldn't run with the new Agnus / old Denise combo we see in most A500's.

Maybe we should first check in UAE which Roms are supposed to be compatible.
Setting must be: ECS Agnus, OCS Denise

**Comment by PakkunKinoppi** [comment]
Settings:

_1] OCS_
_2] ECS Agnus_
_3] ECS Denise_
_4] FULL ECS_

![Untitled 2](https://user-images.githubusercontent.com/52820759/68107646-c6ee9080-fee5-11e9-97f6-3518db23e5a5.jpg)

**Comment by Alessandro1970** [comment]
Note: kick 2.0 custom was sold for all kind of Amiga 500 and 2000, but only **A500+** was sold with kick 2.04 (1mb chip ram and kick 2.04, called also A500 Plus)
**The Super Denise** (8373) was mounted in A3000 only (and some newer A600 ?).

BTW the settings in WINUAE:

**OCS:** for Amiga 1000 and most A500 (not puls version)
**ECS:** Agnus: Amiga 500 and Amiga 2000
_ECS Denise: **nonsense** (?), never used in Amiga models, only for WinUAE_
**FULL ECS:** for Amiga 3000 and newer A600 (to be read as Super Denise (8373) mounted instead the normal Denise)
**AGA:** A1200 and A4000

**Comment by Alessandro1970** [comment]
**Note:** kick 2.0 custom was sold for all kind of Amiga 500 and 2000, but only A500+ was sold with kick 2.04 (1mb chip ram and kick 2.04, called also A500 Plus)
The **Super Denise (8373)** was mounted in A3000 only (and some newer A600 ?).

BTW the settings in WINUAE:

**OCS:** for Amiga 1000 and most of the first revision of A500/2000
**ECS Agnus:** for newer Amiga 500, Amiga 2000 and A500+
_ECS Denise: nonsense (?), never used in Amiga models, only for WinUAE_
**FULL ECS:** for Amiga 3000 and newer A600 (to be read as Super Denise (8373) mounted instead the normal Denise)
**AGA:** A1200 and A4000

There are three version of Agnus:
Agnus/Fat Agnus: supports 512K of Chip RAM [OCS]
Fatter Agnus: supports 1 MB of Chip RAM [ECS]
Super Agnus: supports 2 MB of Chip RAM

– The original 8370 (NTSC) / 8371 (PAL) “fat” Agnus. Can control 1 MB of RAM, but DMA pointers are still 18-bit so only 512 KB chip RAM is supported (if present, the other 512 KB is typically mapped as $C00000 slow RAM).
Typically found on: Amiga 500 rev3 and rev5, Amiga 2000-B rev 4.x (US models), but can be found on very early rev6 Amiga 500 and Amiga 2000-B‘s as well (those boards also have a “refresh fix” additional small PCB).

– The enhanced (ECS) 8372A Agnus (model 318069-029, supports both NTSC and PAL, selectable via pin 41 at powerup and via software at anytime). Also supports additional video timings (requires the ECS Denise as well to provide these new modes). Controls still up to 1 MB of RAM but now can address all of it as chip RAM (19-bit pointers).
Unofficially called the “fatter” Agnus to signify the increased 1 MB chip RAM support.
Typically found on: Amiga 500 rev6A, Amiga 2000-B rev6.x, and the CDTV.

– The enhanced (ECS) 8372B Agnus (model 318069-03). Essentially an 8372A with 2 MB RAM support, all addressable as chip RAM (20-bit pointers). Some batches of the 8372B even use the 8372A packaging, with the B distinctly added after the 8372A part. These read like 8372AB, but internally they are 8372B parts.
Unofficially called the “obese” Agnus to signify the yet increased 2 MB chip RAM support.
Typically found on: Amiga 3000 (and also on some “megachip” 2 MB chip RAM upgrades). (**)

– The 8375 series, which are all ECS models. Some are 1 MB, some 2 MB, some are pin-compatible to the previous models, some are not. All can be software set to either PAL or NTSC but upon power up will default to their indicated variant. Most well known members of the series are:

++ 390544-01 (PAL) or -02 (NTSC), 2 MB support, not pin compatible to 8370/71/72A/72B models.
Typically found on: Rev8A(.1) Amiga 500 plus motherboards, early Amiga 600s (marked as A300), many “megachip” expansions.

++ 318069-10 (PAL) or -11 (NTSC), Vbb version of the 390544 model. 2 MB support, not pin compatible to 8370/71/72A/72B models.
Typically found on: Later Rev8A(.1) Amiga 500 plus motherboards (possible Vbb fix needed), later Amiga 600s, many “megachip” expansions.

++ 318069-16 (PAL) or -17 (NTSC). Vbb replacement to the 8372A. 1 MB support, pin compatible to the 8370/71/72A family.
Typically found on very late Amiga 2000-B systems (some require a small fix for stable operation with these chips – same when using them as a replacement to an existing 8370/71/72A).

++ 318069-18 (PAL) or 318069-19 (NTSC). Likewise, Vbb replacement to the 8372B. 2 MB support, obviously pin compatible to the 8372B model.
Typically found on very late Amiga 3000 systems. Possible Vbb “fix” needed when replacing an 8372B with its 8375 counterpart.

The AGA chipset incarnation of Agnus is the Alice chip. Both carry similar hardware and duties.

(*) Thin Agnus blitter bug: Upon instructed to begin a blit operation, the blitter will erroneously not report itself busy until it has actually fetched its first word of data. This can cause undesired behaviour. The easy solution is for the CPU to check twice if the blitter is busy – even if the 1st report is erroneous, the 2nd will always be correct.

**Comment by dirkwhoffmann** [comment]
According to

https://cloanto.com/amiga/roms/

all (working) v2.0 - v2.03 Roms have been made for the A3000. 

I think the main problem is that if one of the newer Kickroms detects an ECS Agnus, it thinks that there is an ECS Denise as well. 

BTW, from v0.46 on, vAmiga displays CRC-32 checksums for unknown Roms, because they are more common than FNV-1A checksums. Originally, I went for the FNV-1A checksums, because they are easier to compute.

**Comment by dirkwhoffmann** [comment]
> selectable via pin 41 at powerup and via software at anytime

what does that mean? 🤔

**Comment by mithrendal** [comment]
Agnus Pin 41 controls PAL vs NTSC. If pin has contact to mainboard it uses NTSC otherwise PAL. Later revisions (e.g. from 8372A onwards) could control this by software. 🤓
