### ISSUE TITLE
68881/82 emulation

### ISSUE THREAD

**Issue by PakkunKinoppi** [dirkwhoffmann/vAmiga#196]
Hi, could be added the emulation support for math coprocessor 68881 ?

![30495664-2c036112-9a4d-11e7-9bf2-568c73c87961](https://user-images.githubusercontent.com/52820759/66982638-e2206a00-f0b6-11e9-83c9-7607c55116c5.png)

**Comment by dirkwhoffmann** [comment]
As far as I know, the 68881/82 is only compatible with the M68020/30. vAmiga is limited to the M68000.

**Comment by Alessandro1970** [comment]
There where some cards that add the 68881 to Amiga 500 and 2000 (sculpt3D supported that co-porcessor).
For example:
Apphatron 68881 Expansion Board (directly on the 68000 soket)

    extends the 68000 with an FPU
    68881 @ 16 MHz, PGA, clocked asynchronously
    connects to the 68000's socket, the 68000 is replaced onto the board 

That was a great thing.
http://amiga.resource.cx/adcoll/adcoll.pl?id=alphatronfpu&pg=1

**Comment by PakkunKinoppi** [comment]
Also the Netch Computer Products 68881 Floating Point Coprocessor Board:

![Netch_1986-07](https://user-images.githubusercontent.com/52820759/67005109-1fe6b800-f0e2-11e9-8367-0a2c7e5fa34b.jpg)

 It was a good thing to add the 68010+68881

**Comment by PakkunKinoppi** [comment]
Is it possible to incorporate/add the 68881 core from the FS-UAE in vAmiga as an add-on?

**Comment by dirkwhoffmann** [comment]
> That was a great thing.

Interesting, but I have no idea at the moment how the 68000 talks to the FPU hardware-wise. 

> Is it possible to incorporate/add the 68881 core from the FS-UAE in vAmiga as an add-on?

Unlikely.

**Comment by UgoCaneFifone** [comment]
Yes, it would be great, I have ever loved the 68881.

MC68881 emulation, this one: https://sourceforge.net/p/euaeppcjit/code-0/23/tree/trunk/src/fpp.c

**Comment by UgoCaneFifone** [comment]
There is also the FPU core emulation on Github of the Mac emulator Shoebill:

https://github.com/pruten/shoebill

**Comment by UgoCaneFifone** [comment]
...or the common MC68881 emulation on github too:

https://github.com/FrodeSolheim/fs-uae/blob/master/src/jit/compemu_fpp.cpp

**Comment by dirkwhoffmann** [comment]
> That was a great thing. http://amiga.resource.cx/adcoll/adcoll.pl?id=alphatronfpu&pg=1

I agree that it was a great thing at the time. I also understand that some version of the Aztec compiler and the Modula 2 compiler can compile software using the FPU. But I doubt that it's really worth the effort. Most 68881/68882 applications seem to be designed with the more powerful M680xx processors in mind.

Or let me ask in a different way: Which software tools could benefit from a 68881 / 68000 combo except the already mentioned sculpt3D? I would not even know how to test the implementation due to the limited support by software.

**Comment by PakkunKinoppi** [comment]
Ok, the **full 68040** emulation can resolve all problem because is 99% comptible with 68000 and has the FPU.
There are some expansion card for the A500 and the A2000 that support the 68040 with FPU.

**Comment by PakkunKinoppi** [comment]
Better the 68080 software core emulation of the Amiga Apollo accelerator cards:

http://www.apollo-core.com/

**Comment by Alessandro1970** [comment]
Apollo 68080 CPU on Vampire V4 Amiga (it has an Integrated and Pipelined software FPU on the FPGA)

![sysinfo_compare](https://user-images.githubusercontent.com/34916641/68197844-37b3ac80-ffbb-11e9-923a-1ff2e0f28bf0.png)

**Comment by Alessandro1970** [comment]
...just for fun, let's see this demo running on the new **Amiga Vampire V4/SA** :

https://www.youtube.com/watch?v=1ceqEptW3nc

**Comment by Alessandro1970** [comment]
I have read that AmigaOs always detects and uses the FPU if it is present.
This is all that Gunnar from ApolloCore says about::

There is one thing you need to take care of here.
We need to mind, that AMIGA OS will detect FPU first.
If AMIGA OS detected FPU and "marked in Attenflags" that FPU is there. Then AMIGA programs and AMIGA libraries will of course use FPU instructions. So if you then just turn the FPU "off", then FPU using libraries will of course create Traps.
