### ISSUE TITLE
DMA slot allocation

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#2]
Based on what we've discussed in #1, I think a design decision has emerged. Instead of doing all the DMA stuff at an HSYNC event with intermediate updates (as it seems to be done in UAE / SAE), the DMA controller (Agnus) will be run whenever the CPU has processed an instruction. Hence, we have *instruction accuracy*. We cannot have real *cycle accuracy* (like, e.g., all decent C64 emulators have), because the CPU core computes a single instruction in one chunk (it would be too slow anyway). 

So my first code draft looks as follows: 

    void
    DMAController::executeUntil(Cycle targetClock)
    {
        // Determine number of master clock cycles to execute
        Cycle missingCycles = targetClock - clock;
    
        // Convert to DMA cycles
        DMACycle missingDMACycles = AS_DMA_CYCLES(missingCycles);
    
        // Execute missing cycles
        for (DMACycle i = 0; i < missingDMACycles; i++) {
            
            switch (vhpos) {
                case 0x07:
                case 0x09:
                case 0x0B:
                    // Do disk DMA
                    break;
                    
                case 0x0D:
                case 0x0F:
                case 0x11:
                case 0x13:
                    // Do Audio DMA
                    break;
                    
                // AND SO ON ...
                    
                default:
                    break;
                    
            }
            
            // Check if the rasterline end has been reached
            if (vhpos < 227) vhpos++; else hsyncAction();
        }
        
        // Note the completed cycles
        clock += DMA_CYCLES(missingDMACycles);
    }

The core is a big switch statement wich basically implements a state machine with the vhsync counter as the state. I expect a switch statement to be superior to a manually managed function table, because modern compilers translate big switch constructs to jump tables anyway (at least if compiled with optimizations switched on).

The hsync and vsync look as follows: 

    void
    DMAController::hsyncAction()
    {
        vhpos = 0;
        
        // CIA B counts HSYNCs
        amiga->ciaB.incrementTOD();
        
        // Check if the frame end has been reached
        if (vpos < 312) vpos++; else vsyncAction();
    }

    void
    DMAController::vsyncAction()
    {
        vpos = 0;
        
        // CIA A counts VSYNCs
        amiga->ciaA.incrementTOD();
    }

**Comment by mithrendal** [comment]
Hi Dirk,

just to rethink about your statement "We cannot have real _cycle accuracy_".

Why is the following naive approach to emulate the "real physic" not feasable ?  

Start logicChips each in a separate Thread

new 68KCPU(config)
new BLITTER(config)
new COPPER(config)
new DISKDMA(config)
new AUDIODMA(config)

  
the logicChips run at a common synchronised ClockSpeed
  getClock()

they all access memory only by 
	value readDMAMem(ChipName,adress)

	writeDMAMem(ChipName,adress, value)
	
these methods take care about when a certain chip can DMA. When it is not the time for the chip they wait the thread until time has come.

**Comment by dirkwhoffmann** [comment]
Hi Mithrendal, 

I did try such an approach in VirtualC64. My plan was to run the VC1541 in a separate thread, because a) it mimics reality, b) the drive CPU runs at a slightly different clock speed and c) the floppy and the C64 are isolated from each other by a very simple (IEC) bus. However,  I backpedalled quickly, because of the following two reasons:

- Synchronising threads is much more costly than I though. Although the emulator was now using two CPU cores (one for the C64, one for the drive), emulation speed decreased. I learned that synchronising threads on a such fine grained time scale is not a very good idea.

- The new code base was pretty difficult to handle. Because the system was now running asynchronously (with lots of synchronisation points though), it was much harder to debug. 

Based on this experience, I think it's much better to use one thread per emulator instance, only.

**Comment by mithrendal** [comment]
Thank you for the interesting insights. I already thought of the second point, too complex to debug and tons of race conditions ... Also the state of the machine would maybe not be so easy to be saved and restored.

Nevertheless thank you for pointing out the disadvantages of that approach... ;-)

**Comment by dirkwhoffmann** [comment]
Such discussions are very valuable, especially as fundamental design decisions have to be made at the moment.

**Comment by mithrendal** [comment]
I asked bloodline in the eab forum for a peek in the source code of his dma sequencer. He likes to put that onto github soon, but he writes that the code is still too messy and must be cleaned up a bit. Maybe we can learn from his implementation.

**Comment by dirkwhoffmann** [comment]
Very cool, that'll help 👍. The code cannot be more messy than UAE I guess 😂.

**Comment by mithrendal** [comment]
I am just reading about DMA time slot allocation. Fascinating stuff. 
Do you have/know this documentation ? 

http://amigadev.elowar.com/read/ADCD_2.1/Hardware_Manual_guide/node012B.html

**Comment by dirkwhoffmann** [comment]
The document you citied is the online version of the Hardware Reference Manual (HRM). There is a revision V3 out there as a PDF which is already in my iBook shelf. 

Executing CPU instructions in one chunk doesn't mean that we cannot have cycle accuracy. The reason ist that the CPU invokes memory callback functions to read and write memory cells and these functions can be used to emulate bus delays. Please have a look at the following UML diagram in the Wiki section: 

https://github.com/dirkwhoffmann/vAmiga/wiki/Run-loop

This is roughly how I plan to implement the emulator. The only problem is the "executeTilNow()" call right after a "peek(address)" call. To get timing 100% accurate, we would need to know the number of elapsed cycles between the instruction start and the point where the memory access happens. As far as I know, no available CPU core provides this information. Hence, my plan is to omit this ""executeTilNow()" call for now and only invoke "executeTilBusIsFree()". It shouldn't be a show stopper, because we only loose accuracy in situations where, e.g., the Blitter and the CPU access the same memory area at the same time.

**Comment by mithrendal** [comment]
Ah well now I understand. The CPU core must also call the DMAController for memory access. In case of any custom chip priority access (blitter) or due to the fact it is simply not the right slot (hpos)  the DMAController first finishes these other tasks until it peeks the memory for the CPU and that effectivly delays the CPU like in the real harware. Wow nice!

**Comment by mithrendal** [comment]
@h5n1xp (EAB member bloodline) has just put his bare metal emulator on github. Many thanks to @h5n1xp  🙂 !!

https://github.com/h5n1xp/Omega

I am interested how he solved the DMA sequencer thing. Maybe we can still study and learn some thing... I am just reading his source code now.

BTW: I just saw that he uses Musashi Core too !!

**Comment by h5n1xp** [comment]
Hi All,

Notice that my CPU emulation is essentially “free wheeling” with respect to the DMA. My Emulator isn’t supposed to be too rigorous at this stage, as it really is defined to provide just enough support to get AmigaOS booting.

**Comment by mithrendal** [comment]
Hi @h5n1xp 
yes I see it in the code. Have you taken a look at the runloop of dirks approach yet?  https://github.com/dirkwhoffmann/vAmiga/wiki/Run-loop

His concept does not need to use thread locking mechanisms.

**Comment by h5n1xp** [comment]
> Hi @h5n1xp
> yes I see it in your code. Have you taken a look at the runloop of dirks approach yet? https://github.com/dirkwhoffmann/vAmiga/wiki/Run-loop
> 
> His concept does not need to use thread locking mechanisms.

Hey there, at the moment cycle accuracy with respect to the CPU and DMA isn’t a priority for me, so I won’t be spending too much time worrying about that. A far bigger issue I have is my blitter code, which works well enough to get the graphics displayed, but when the trackdisk.device uses it, it just produces garbage...

**Comment by dirkwhoffmann** [comment]
Hi bloodline, 

thanks a lot for uploading your code to Github! I didn't look into the sources yet, but I did read the detailed README file. It’ll be great if you continue your project. Interestingly, our implementations are based on similar design decisions (DMA sequencer as the commander-in-chief, encapsulating C code in C++ objects without using too much fancy C++ stuff). Hence, I am pretty confident that we can benefit from each others work.

I agree that our emulators will most likely never be as good as UAE from a compatibility point of view, but I don't think they have to be. 

As we speak about UAE, let me briefly summarise my current experience with this emulator. 

- The good: 

    The compatibility of UAE is amazing. Over the years, the UAE team members have done an incredible job and I am skeptical if any other emulator will ever reach this level of compatibility. 

- The bad: 

    It is not designed for casual users (at leas not for casual users like me). Back in January, I tried to play a game in FSUAE, because I had a single hour of spare time. The result was that I did not play the game, but spent the whole hour  configuring the emulator. I cannot really tell what went wrong and maybe I didn’t act like the most clever person on the planet. Anyway, the result was disappointing: I didn’t play the game. 

- The ugly: 

    The code base. UAE is suffering the typical symptoms of ageing software. Over the years, while UAE got better and better from a compatibility point of view, it also covered more and more different hardware configurations. If you look at the current code base, everything is now covered with If statements (if old CIA do this, else that, if fatGarty do this else do that, if 68010 do this, if 68020 do that, if ActionReplay do this etc.). In short: One cannot see the wood for the trees any more. A couple of days ago, Mithrendal and I tried to find the place where the DMA sequencing stuff is implemented in SAE / UAE. As this part is really the core piece of an Amiga emulator, it should be easy to find, but it wasn’t. We crawled through the SAE / UAE code like in a maze.  
I’m not writing this to blame anybody in the UAE team. As I stated above, their emulator is a great one and it will serve as a reference implementation for me (like VICE when I wrote VirtualC64). But it explains my first major design decision, namely: Not to build on top of UAE, but to build the emulator from ground up. 

Overall, I’m pursuing the following goals: 

  - Provide an easy-to-use emulator. Loading a game should require one or two simple drag-and-drop operations only .
  - Provide an easy-to-use debugger. When I worked on VirtualC64, I spent a lot of time on implementing debug panels for the various C64 components. For me it's a lot of fun to run a C64 game and to watch what's going on internally at the same time. 
  - vAmiga will only support the old OCS machines (500,1000,2000), because those machines are the only ones I know. Fortunately, this makes emulation a lot easier. E.g., one can assume that word or long word memory accesses always occur on evenly aligned memory locations, addresses are always 24 bit etc.

**Comment by h5n1xp** [comment]
Hi Dirk!

Yup! I totally agree with you, UAE is basically the ultimate Amiga Emulator, but for a project like mine Where I just need enough functionality to boot AmigaOS on non Amiga hardware, it was just far too complex to pick the code apart without being able to spend a serious amount of time pouring over it.

I have tried to make my code as modular and as simple as possible, you should easily be able to follow the execution cycle through. If anything is unclear, please ask me (even if you think it might be a stupid question, it might actually be a flaw in my design). I hope if you find any parts useful, you should be able to link into your code easily!

**Comment by dirkwhoffmann** [comment]
I’m thinking out loud about the run loop design…

Up to now my plan was to run the CPU for one instruction. After that, the DMA controller is executed up to the point where the CPU is already. Now, there are many CPU instructions that don’t affect other components (such as setting a flag or loading a register with some number). In such cases, it would be smart to give the CPU a bigger time slice to speed up emulation. Let’s assume that there won’t be any interrupts in the near future nor will the CPU access Chip Ram or the custom chips. In that case, we could easily give the CPU a time slice of, let’s say, a complete horizontal line (we cannot give it an infinite time slice, because we have some real-time constraints. E.g., the audio units needs to be provided with sound samples in real-time). 

Hence, I think we should do the following: 

1. Hand over control to the CPU for a certain time slice. The maximum value of the time-slice will be a full horizontal line. If there will be an interrupt in the current line, we only execute to the point where the interrupts happen. 
2. If the CPU accesses Chip Ram or the custom chips, we let the DMA controller   emulate all missing cycles before the memory value is grabbed (as it is outline in the current run loop UML diagram).

All this is based on the assumption that we can foresee when the next interrupt happens. This assumption is true for Copper, CIA and Blitter interrupts, but false for: 

1. External interrupts such as keyboard or joystick events
2. Sprite collision interrupts

I hope I didn’t forget anything. The first group shouldn’t be a problem, because the IRQ is only delayed until the end of the current raster line. This means that joystick movements are recognised a littler later as they occur, but the delay is really minimal.

The sprite collision interrupts shouldn’t be a big problem, too,  I guess. It could be possible to trick out our emulator, but I don’t expect that normal programs do this (only some mean guys in the demo scene may be). And as far as I understand UAE at the moment, UAE is exactly doing the same thing. Sprite interrupts are served at HSYNCs only (I might be wrong, because my understanding of the UAE code is very limited yet).

**Comment by h5n1xp** [comment]
Apologies if I’ve misunderstood something, I don’t think sprites and keyboard/joysticks generate interrupts on the Amiga. You are expected to poll the relevant registers during the VBL.

**Comment by dirkwhoffmann** [comment]
Yes, you're right, I was too quick. I remembered myself that the CIAs come into play and whenever I hear CIA, I think of interrupts.

**Comment by h5n1xp** [comment]
> Yes, you're right, I was too quick. I remembered myself that the CIAs come into play and whenever I hear CIA, I think of interrupts.

Lol! Yes, the Amiga isn’t a C64 :)

**Comment by dirkwhoffmann** [comment]
Thanks to h5n1xp's recommendation, I looked at WinFellow in more detail. First I though that my mixed design (event handler + state machine with colorclk as the state) is superior, but now I am pretty convinced that it is not. Therefore I will adapt the WinFellow approach and build everything around the EventHandler. WinFellow is no easy software, but it is way easier to analyse than UAE. 

Has someone tried to run MacFellow on Mojave?

**Comment by mithrendal** [comment]
I do not find any MacFellow on the net ... do you have a link ? But I might try that with winebottler, thats a little app which wraps all the cocoa stuff around windows apps , might be possible that we can get run winfellow on a mac with it... i try and tell you both here whether thats possible.

**Comment by h5n1xp** [comment]
> I do not find any MacFellow on the net ... do you have a link ? But I might try that with winebottler, thats a little app which wraps all the cocoa stuff around windows apps , might be possible that we can get run winfellow on a mac with it... i try and tell you both here whether thats possible.
> 
> EDIT: Its possible... The latest release from https://github.com/petschau/WinFellow looks like this ...
> <img alt="bildschirmfoto 2019-02-27 um 22 33 52" width="804" src="https://user-images.githubusercontent.com/17108995/53524630-3ce16300-3ae0-11e9-9d37-5ffefac12aa6.png">
> 
> To be clear there is no need for a windows installation or license. In fact winebottler creates a native standalone mac app from a given .exe file and when you run that app it bridges all WINAPI calls to cocoa via wine.
> 
> <img alt="image" width="915" src="https://user-images.githubusercontent.com/17108995/53525854-03f6bd80-3ae3-11e9-9bf3-a294f916df63.png">
> 
> In case you need the "bottled" standalone app I can mail it to you. (Or should I drag the file into this issue ? )
> 
> The same approach might be possible for WinUAE too. Do we need that ? If yes I will to make a standalone mac app from it too.

FYI, I personally run WinUAE on my Macs using “Crossover Mac” (the paid for version of WINE) and have used WineBottler” in the past, I have submitted bug report to Toni running beta versions in this configuration and as such the latest versions of WinUAE run without issue.

**Comment by dirkwhoffmann** [comment]
I read about MacFellow on Wikipedia, but it doesn't seem to exist.

Winebottler looks really cool. I wasn't aware of it's existence. Unfortunately, it doesn't help for the purpose I had in mind: to compile Fellow natively on the Mac (with debug messages includes) and use it for debugging. Maybe it's easier to setup a VM with VisualStudio and compile it in VMWare.

**Comment by h5n1xp** [comment]
> Thanks to h5n1xp's recommendation, I looked at WinFellow in more detail. First I though that my mixed design (event handler + state machine with colorclk as the state) is superior, but now I am pretty convinced that it is not. Therefore I will adapt the WinFellow approach and build everything around the EventHandler. WinFellow is no easy software, but it is way easier to analyse than UAE.
> 

I think the event based approach will give best performance and make it easier to get consistent results. My Emulator is obviously built around state machines (so many 😆). 

It was my opinion that I would be able to get results more quickly, debugging would be clearer, and that I would be able to more easily split the emulation over multiple threads. Also I didn’t want to just do what Fellow and UAE have already done 😊

**Comment by dirkwhoffmann** [comment]
"debugging would be clearer"

I fully agree. Scheduling events at the proper cycles is error prone. To make errors explicit, I started to pave my code with assertion checks. Guess what, the first assertion hit within seconds 😂: 

    FATAL ERROR: Trigger cycle does not match.
    
     Master clock: 285176 master cycles
        DMA clock: 285160 master cycles (35645 DMA cycles)
    Beam position: (1,6) ($1,$6)
    
    Slot 0: no pending event
    Slot 1: no pending event
    Slot 2: no pending event
    Slot 3: no pending event
    Slot 4: Event ID: 1  Payload: 0  Triggers at: 285152
    Slot 5: no pending event
    Slot 6: Event ID: 1  Payload: 0  Triggers at: 286920

Slot 4 is the Copper slot. I will confront him, let's see what he's gonna say...
