### ISSUE TITLE
after speaking bravely he crashes 

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/vAmiga#20]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/17108995/57651917-be6c6b80-75ce-11e9-8209-0defeff1b206.png">

debug output
```
Current configuration:

   AmigaModel: Amiga 500
realTimeClock: no
          df0: yes Drive 3.5" DD
          df1: no Drive 3.5" DD
          df2: no Drive 3.5" DD
          df3: no Drive 3.5" DD

         warp: 0 (82763776) (77992)
Assertion failed: (IS_EVEN(addr)), function peek16, 
file .../vAmiga/Amiga/Computer/Memory.cpp, line 395.
```

points to here  ... addr is not even ... ends with 1.

```
uint16_t
Memory::peek16(uint32_t addr)
{
    if (!IS_EVEN(addr)) {
        debug("PC: %X peek16(%X) memSrc = %d\n", _cpu->getPC(), addr, memSrc[(addr & 0xFFFFFF) >> 16]);
        _amiga->dump();
    }
    
    assert(IS_EVEN(addr));
```

<img width="247" alt="image" src="https://user-images.githubusercontent.com/17108995/57652129-2fac1e80-75cf-11e9-85b1-3f4f667106e0.png">

I wanted to look at the root cause but I have no good idea. I traveled the stacktrace but this strategy does not really help here. Maybe it is some DMA scheduling problems ? Because when it crashes the mouse pointer sprite gets scrambled too?

**Comment by dirkwhoffmann** [comment]
Up to now, I simply assumed that memory is accessed at even addresses only (as far as I know, the 68000 CPU should trigger an internal exception, trap, or irq if the address is odd. Only the newer 68x models can handle odd addresses). 

Is the crash deterministic? If yes, I can run it against SAE and see what happens there. Either the odd address should not be odd (because of an earlier bug) or the CPU reaction is configured wrong.

**Comment by mithrendal** [comment]
Yes deterministic. Always the same odd address. Really odd. 🤪

**Comment by dirkwhoffmann** [comment]
Hmm, I cannot reproduce this either. I get some weird graphics errors instead: 

<img width="131" alt="Screenshot 2019-05-14 at 13 59 29" src="https://user-images.githubusercontent.com/12561945/57696256-a1787c80-7650-11e9-9481-e6d75cacd61e.png">

Which Kickstart and which Workbench did you use? I guess we're using two different versions.

Regarding the address violation issue, I've seen that I have boundary checks disabled in Musashi (which should be enabled). Before enabling it, I would like to check in SAE if the address violation happens there, too.

**Comment by mithrendal** [comment]
Kickstart 1.3, Workbench 1.2 .... I got the same graphics errors plus the assertion triggered.

**Comment by dirkwhoffmann** [comment]
Hmmmm, my WB is called "A2000 WB 1.2 D". Interestingly, my system folder is different to yours: 

<img width="550" alt="Screenshot 2019-05-14 at 18 08 03" src="https://user-images.githubusercontent.com/12561945/57713800-75babe00-7673-11e9-9362-49753cc77769.png">

I had to load the "Say" app from the Extras disk.

**Comment by mithrendal** [comment]
I used this one  
[problemdisk.zip](https://github.com/dirkwhoffmann/vAmiga/files/3179457/problemdisk.zip)

steps to reproduce:
1. kickstart 1.3
2. insert the disk
it boots in interlace
3. open preferences
4. interlace -> off
5. save
6.power amiga off and on
7. reinsert disk
it boots in non interlace now
8. open system drawer
9. let him say "I am an amiga"
--> isEven Assertion is violated

**Comment by dirkwhoffmann** [comment]
OK, I can reproduce it now. I'll check if the address violation also happens in SAE.

Oups, interleave mode seems to need some attention, too 😲.

<img width="906" alt="Screenshot 2019-05-15 at 11 47 45" src="https://user-images.githubusercontent.com/12561945/57766644-04791a80-7708-11e9-9ea6-e44d9b50ef3f.png">

BTW, after disabling interlace mode, you can use "Df0->Export ..." to save the modified disk to a new ADF file.

**Comment by dirkwhoffmann** [comment]
Haven't looked at the crash yet, but I'm making progress on interlace mode: 

<img width="283" alt="Screenshot 2019-05-17 at 12 42 07" src="https://user-images.githubusercontent.com/12561945/57923059-851f4e80-78a1-11e9-82ac-3723120a8aa3.png">

**Comment by Alessandro1970** [comment]
Do you succeed in loading the Pawn hi-res intro screen ?

**Comment by dirkwhoffmann** [comment]
> Do you succeed in loading the Pawn hi-res intro screen ?

Well, not really 😂: 

<img width="1030" alt="Screenshot 2019-05-17 at 12 59 32" src="https://user-images.githubusercontent.com/12561945/57923829-b9940a00-78a3-11e9-9199-eead8c5889ef.png">

**Comment by dirkwhoffmann** [comment]
Oh, I see, Pawn is using HAM mode which is not implemented, yet. 

<img width="152" alt="Screenshot 2019-05-17 at 13 07 52" src="https://user-images.githubusercontent.com/12561945/57924311-19d77b80-78a5-11e9-8eb2-3317f33ae63f.png">

The music plays nicely though...

**Comment by mithrendal** [comment]
Holy cow... HAM and Interlace at the same time !!! High load pressure on the chipram DMA ;-)

**Comment by dirkwhoffmann** [comment]
> High load pressure on the chipram DMA ;-)

Actually, it doesn't increase the load. If interlace is on, the Amiga draws 25 long frames and 25 short frames per sec (short frame means one rasterline less). If interlace is off, it draws 50 long frames. 

HAM only affects the way Denise synthesises RGB values. The amount of DMA data remains unchanged.

**Comment by dirkwhoffmann** [comment]
Fixed. Was caused by the "Blitter always runs when DMA gets enabled" bug.
