### ISSUE TITLE
Lotus Turbo II won't load

### ISSUE THREAD

**Issue by KenDFish** [dirkwhoffmann/vAmiga#200]
The attached ADF - a cracked (and "fixed") version of Lotus Turbo II doesn't appear to work (in 0.42). The intro text appears, but beyond that the loading text (which I think just has the game title) starts to glitch. After several seconds the screen background changes colour but it doesn't appear to progress into the game. Hope this helps!

[KD0472 Lotus Turbo II.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3747128/KD0472.Lotus.Turbo.II.adf.zip)

![image](https://user-images.githubusercontent.com/6280435/67150580-4eff5400-f2b1-11e9-988e-7a0aa80a9c4e.png)

**Comment by dirkwhoffmann** [comment]
It's different in SAE, but if doesn't work either (I get a Guru in all available modes (OCS, ECS, AGA)):

![guru](https://user-images.githubusercontent.com/12561945/67157935-ead0a480-f331-11e9-80c7-99ea584b6588.png)

**Comment by KenDFish** [comment]
Sorry, I hadn't tried it in a different emulator: it does the same in FS-UAE. Interestingly, if I set FS-UAE to emulate a A1200 (68EC020, Kickstart 3.1), it works fine

![image](https://user-images.githubusercontent.com/6280435/67160504-64c05800-f349-11e9-8525-22ae12892798.png)

![image](https://user-images.githubusercontent.com/6280435/67160513-84578080-f349-11e9-88bf-3a71660baa25.png)

Seems to be something about the "fixed" version that breaks it on an emulated OCS machine? Regardless, I don't think it's really a vAmiga issue, at least not for now.

**Comment by dirkwhoffmann** [comment]
Hi Ken,

> it does the same in FS-UAE.

thanks for investigating this!

> Regardless, I don't think it's really a vAmiga issue, at least not for now.

I agree. I'll close.
