### ISSUE TITLE
Shadow of the beast II hangs after intro screen

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#206]
Hi,

Shadow of the beast II hangs after inserting disk 2.
Note: to boot the game use disk 3 (boot disk)

[Archivio.zip](https://github.com/dirkwhoffmann/vAmiga/files/3774585/Archivio.zip)

**Comment by dirkwhoffmann** [comment]
Is it possible to skip the start-up sequence? No?

<img width="1033" alt="Bildschirmfoto 2019-10-26 um 10 58 37" src="https://user-images.githubusercontent.com/12561945/67617140-5d34ff00-f7e0-11e9-804f-1b2d2f87b368.png">

**Comment by Alessandro1970** [comment]
I did not succeed in doing it. it takes a while

**Comment by dirkwhoffmann** [comment]
Update: still broken in v0.55

**Comment by dirkwhoffmann** [comment]
Update: Not a bug, it hangs on the real machine, too (A500 8A).

There is a two disk version around that boots just fine:

Shadow of the Beast II (1990)(Psygnosis)[cr Angels](Disk 1 of 2).adf
Shadow of the Beast II (1990)(Psygnosis)[cr Angels](Disk 2 of 2).adf

<img width="910" alt="Bildschirmfoto 2020-02-05 um 18 19 57" src="https://user-images.githubusercontent.com/12561945/73867087-53428380-4846-11ea-849d-a30ec4193960.png">
