### ISSUE TITLE
Shadow of the beast III, graphics glitches

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#207]
Hi,
There is a graphic error on the main character of this game that remands me to a precedent bug in winter games or similar:
<img width="812" alt="Schermata 2019-10-26 alle 10 10 31" src="https://user-images.githubusercontent.com/34916641/67616458-5656be00-f7d9-11e9-80fa-61e7f752e806.png">

[Archivio 2.zip](https://github.com/dirkwhoffmann/vAmiga/files/3774595/Archivio.2.zip)

**Comment by dirkwhoffmann** [comment]
Hmm, well, yes, this guy has serious skin problems.

The game really pushes the Amiga hardware to the limit. Hard to spot any free DMA cycle 🤭.

<img width="838" alt="Bildschirmfoto 2019-10-26 um 10 40 04" src="https://user-images.githubusercontent.com/12561945/67616826-886a1f00-f7dd-11e9-814d-e445c7838d1c.png">

I also think it's an issue with "attached sprites". Like the issue with the skating lady in Winter Games.

**Comment by dirkwhoffmann** [comment]
I've written two new tests attached5 and attached6 that test thoroughly the AT bit stuff. vAmiga passes both. Hence, I think this is more likely a timing issue (when the AT bit is set or cleared) rather than an issue with sprite drawing itself.

**Comment by dirkwhoffmann** [comment]
There is also a scrolling issue in one of the middle layers:

<img width="979" alt="Bildschirmfoto 2019-10-26 um 15 09 05" src="https://user-images.githubusercontent.com/12561945/67620056-f2e18600-f802-11e9-8913-d582907e9ea0.png">

So sad that it's buggy yet. It's a really cool game 👍.

**Comment by dirkwhoffmann** [comment]
<img width="874" alt="Bildschirmfoto 2019-10-27 um 17 25 12" src="https://user-images.githubusercontent.com/12561945/67638107-7f627600-f8e1-11e9-9252-074829fee3ba.png">

Actually, I think the main character looks a bit boring now. I liked him more with the glowing skin. Looked like a superpower to me 😎.

The scrolling bug remains. We need to find out how the game draws the middle layer and come up with a test case isolating the error source.

**Comment by dirkwhoffmann** [comment]
This article explains the technical details of Shadow of the Beast I.

https://codetapper.com/amiga/sprite-tricks/shadow-of-the-beast/

To find the remaining graphics bug, it might be more fruitful to watch out for simpler intros / demos. The Beast series is the worst we can get w.r.t. technical complexity.

**Comment by dirkwhoffmann** [comment]
No longer an issue in v0.9.5:

<img width="1003" alt="Bildschirmfoto 2020-05-04 um 12 28 38" src="https://user-images.githubusercontent.com/12561945/80957116-d8681500-8e02-11ea-96e6-01e45f6f1dbf.png">
