### ISSUE TITLE
Test jump1c

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#209]
This test verifies Copper timing behaviour after VSYNC. 

A500 8A: 🥰

![jump1c_A500_8A](https://user-images.githubusercontent.com/12561945/67616666-c8300700-f7db-11e9-9f5f-59039432533a.jpeg)

UAE: 🤭

<img width="720" alt="jump1c_UAE" src="https://user-images.githubusercontent.com/12561945/67616672-d0884200-f7db-11e9-8455-8d7d647f8788.png">

vAmiga: 🤩

<img width="838" alt="Bildschirmfoto 2019-10-26 um 10 32 21" src="https://user-images.githubusercontent.com/12561945/67616704-2957da80-f7dc-11e9-8f9b-2945db40106b.png">

It'll be great to see if it's the same on the A1000.

**Comment by mithrendal** [comment]
![D0AA0A62-D955-4E64-9291-B8FBEEB883A0](https://user-images.githubusercontent.com/17108995/67630897-b52a3f00-f88e-11e9-8bc0-7c6aa82f6b83.jpeg)

A1000

**Comment by mithrendal** [comment]
After endless looking at the test pictures I finally spotted the difference. 

Spoiler alarm or Pro hint: Counting the steps between the gray blocks proves the difference

A1000 / A500 / vAmiga😎 are correct, UAE is not.

**Comment by dirkwhoffmann** [comment]
> Spoiler alarm or Pro hint: Counting the steps between the gray blocks proves the difference

Oh no, everybody knows the trick now 😖.

> A1000 / A500 / vAmiga😎 are correct, UAE is not.

vAmiga might be correct by coincidence though. UAE has some complicated code dealing with the VBLANK start which vAmiga hasn't. I don't think the UAE code is there for fun, but as usual, I don't really get what they are doing.

**Comment by dirkwhoffmann** [comment]
A1000 images have been uploaded 😎.

There are two new sprite DMA tests as well: sprdma16 and sprdma17. 
I hope to get sprite DMA right in the next release...

As usual, xAE passes both tests. The sprite engine in UAE seems to be 100% accurate.
