### ISSUE TITLE
Freemap WB 1.3 does not work

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#21]
Freemap utility does not work:

<img width="774" alt="Schermata 2019-05-14 alle 22 33 45" src="https://user-images.githubusercontent.com/34916641/57730645-38692700-7699-11e9-8d9a-afd9b76b4d58.png">

**Comment by dirkwhoffmann** [comment]
I think this error is related to a bug that is visible in WB, too. If you drag down the screen, it first vanishes (which is OK I guess) and then reappears (which shouldn't be the case). If Freemap is dragged to the top of the screen, it seems to work as expected. 

<img width="916" alt="Screenshot 2019-05-18 at 08 11 24" src="https://user-images.githubusercontent.com/12561945/57965467-ecdaa580-7944-11e9-933a-caaddf5def34.png">

**Comment by Alessandro1970** [comment]
Moving the Freemap window a little down it shows itself:
<img width="768" alt="Schermata 2019-05-18 alle 22 56 51" src="https://user-images.githubusercontent.com/34916641/57975021-20a7e080-79c2-11e9-9dc9-a525f195fbe0.png">

**Comment by dirkwhoffmann** [comment]
Seems to work now.
