### ISSUE TITLE
vAmiga crashes after loading snapshot

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#211]
I have stopped vAmiga, changed kick rom and than I have loaded previous snapshot to test game at that point with another kick:

[CRASH.TXT](https://github.com/dirkwhoffmann/vAmiga/files/3775630/CRASH.TXT)

**Comment by dirkwhoffmann** [comment]
> I have stopped vAmiga, changed kick rom and than I have loaded previous snapshot

This won't work, because vAmiga is supposed to save the Roms, too.

Of course it shouldn't crash.

**Comment by dirkwhoffmann** [comment]
Could you try again with v0.46? I wasn't able to reproduce such a scenario on my machine.

**Comment by Alessandro1970** [comment]
Hi, now it works well !
You can close
