### ISSUE TITLE
Bionic Commando Warp mode does not stop 

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#212]
To play bionic commando I have to disable warp loading otherwise the game goes too fast.
[Bionic Commando (1987)(GO!)[t HQC - Megaforce].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3775649/Bionic.Commando.1987.GO.t.HQC.-.Megaforce.adf.zip)
<img width="803" alt="Schermata 2019-10-27 alle 09 58 53" src="https://user-images.githubusercontent.com/34916641/67632189-bc5a4880-f8a0-11e9-8d19-a8b8e8c42ee4.png">

**Comment by dirkwhoffmann** [comment]
I just double-checked with SAE. Assuming SAE is correct, it's not a bug. The game does not turn off the drive motor:

```
> grep MOTOR ~/Desktop/sae.log 
amiga.js:299 (196,?)#MOTOR on
amiga.js:299 (271,?)#MOTOR off
amiga.js:299 (277,?)#MOTOR on
amiga.js:299 (239,?)#MOTOR off
amiga.js:299 (58,?)#MOTOR on
amiga.js:299 (99,?)#MOTOR off
amiga.js:299 (45,?)#MOTOR on
```

The game itself seems to run just fine.

BTW, you can force the emulator into a warp-always-on or warp-always-off mode by simply clicking the hourglass symbol in the status bar:

![Bildschirmfoto 2019-10-28 um 08 04 44](https://user-images.githubusercontent.com/12561945/67658749-c5a7eb80-f95a-11e9-999d-060877fb0dfc.png)

A small lock icon will appear instead of the hourglass.

**Comment by dirkwhoffmann** [comment]
Just checked with AmigaForever. The drive motor is not switched off there, too.

BTW, does anybody know where AmigaForever hides the Rom files? 🙄

**Comment by mithrendal** [comment]
There is just an msi file in the zip. Is it windows only?😳

**Comment by dirkwhoffmann** [comment]
> Is it windows only?

Yes, windows only. AmigaForever is essentially an ugly UI with UAE under the hood 🥴. 

<img width="594" alt="Bildschirmfoto 2019-10-28 um 20 27 34" src="https://user-images.githubusercontent.com/12561945/67716601-700c2700-f9cc-11e9-8cd8-b67734b9a6bb.png">

**Comment by mithrendal** [comment]
Only early kickstarts available.🙄 even for Amiga 1000 your picture says upgrade.  This is only a budget economy class wood hard sleeper edition. 😖

**Comment by dirkwhoffmann** [comment]
> your picture says upgrade

😲 Oups, I didn't recognise this before. Even WB 1.3 needs an upgrade?  Seriously? 

This release is 🤥. For EUR 6.90, I could have had two beer instead 🥺.

**Comment by mithrendal** [comment]
>Even WB 1.3 needs an upgrade? Seriously?

No. The picture says that A500, A2000 and WB1.3 is ready.  I therefore think the value edition really includes Kick1.3 rom and Workbench1.3.

Everything else it says upgrade. So no Kickstart0.7, 1.0 , 1.1, 1.2 and respectively none of their Workbench counterparts in this edition.

But wait my parents already bought me Kickstart1.1 and Kickstart1.2 some 33 years ago. So I have collected these already. Why does this remind me of the [Coupon Collector’s Problem](https://en.wikipedia.org/wiki/Coupon_collector%27s_problem) Do they really want us to collect all [ panini album stickers](https://de.wikipedia.org/wiki/Sammelbilderproblem) ?

**Comment by dirkwhoffmann** [comment]
> Do they really want us to collect all panini album stickers ?🥴

Oh yes, Panini. Before I had a computer, I spent my time with filling those two: 

![panini1](https://user-images.githubusercontent.com/12561945/67835406-29145380-faea-11e9-8682-0076a5e028fe.jpg)

<img width="331" alt="Bildschirmfoto 2019-10-30 um 07 51 14" src="https://user-images.githubusercontent.com/12561945/67835410-2b76ad80-faea-11e9-8217-e380bef4c056.png">

Unfortunately, my pocket money didn't suffice to complete at least one of them. Of course I didn't understand the math at that time.
