### ISSUE TITLE
Support 1 MB Chip memory

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#214]
When a Fat Agnus is selected, vAmiga should allow up to 1 MB Chip memory.

Test case: 

[Archivio 3.zip](https://github.com/dirkwhoffmann/vAmiga/files/3775673/Archivio.3.zip)

Error message shown on machines with 512 KB or less:

<img width="801" alt="Schermata 2019-10-27 alle 10 14 12" src="https://user-images.githubusercontent.com/34916641/67632426-663ad480-f8a3-11e9-8d52-d2c63874d3fe.png">

**Comment by Alessandro1970** [comment]
Option selection:
OCS -> 512Mb Chip Ram always
ECS -> 1Mb Chip Ram always
I do not think that there were/are Amiga with OCS and 1Mb Chip RAM, It could be a trick but it could be incompatible.

**Comment by dirkwhoffmann** [comment]
The next release will support up to the breathtaking amount of 2MB Chip RAM 😎:

<img width="980" alt="Bildschirmfoto 2019-11-09 um 12 53 35" src="https://user-images.githubusercontent.com/12561945/68528224-2d155200-02f0-11ea-8f52-25ccfb97e5e0.png">

The game itself doesn't work though. I think it requires ECS? No? 

<img width="916" alt="Bildschirmfoto 2019-11-09 um 12 48 46" src="https://user-images.githubusercontent.com/12561945/68528183-bb3d0880-02ef-11ea-92d3-5d279533dfb5.png">

<img width="916" alt="Bildschirmfoto 2019-11-09 um 12 50 32" src="https://user-images.githubusercontent.com/12561945/68528190-cf810580-02ef-11ea-984a-ecd434d1d404.png">

**Comment by mithrendal** [comment]
Hmm they write that it supports also OCS here http://www.lemonamiga.com/?game_id=1757  🧐

Maybe it is confused when it tests the vAmiga for the ECS chipset?

**Comment by mithrendal** [comment]
Here is a test article about the game. They say you need at least 1MB and a AGA Version is already in the works. So I think there were two versions out there. One OCS/ECS and one AGA. 

https://www.kultboy.com/index.php?site=t&id=16831&s=2

**Comment by mithrendal** [comment]
I spotted the two versions on the net. Normal version has 4 disks. The AGA version has 7 disks. So we got here the normal NonAGA version which needs 1MB. The remaining question is whether it depends on some ECS voodoo or not.

**Comment by dirkwhoffmann** [comment]
SAE with ECS Agnus: 

<img width="716" alt="Bildschirmfoto 2019-11-09 um 21 36 04" src="https://user-images.githubusercontent.com/12561945/68534862-eba99480-0339-11ea-88ea-7274f8676776.png">

SAE with OCS Agnus: 

<img width="716" alt="Bildschirmfoto 2019-11-09 um 21 41 44" src="https://user-images.githubusercontent.com/12561945/68534865-f5cb9300-0339-11ea-8f30-dc24084c984d.png">

I like the first one more 🧐.

**Comment by dirkwhoffmann** [comment]
I forgot that a lot of Agnus functions in vAmiga apply a hard-coded bit mask of 0x7FFFE to the DMA pointers. Hence, if 2 MB Chip Ram is selected, the CPU will see those 2 MB, but Agnus will still see only 512 MB 🙈.

**Comment by mithrendal** [comment]
Implementation of 8372a onwards is wrong then. Definitely 8372A identifies in vAmiga as 8372A but acts like its little sister chip the 8367RO10.😗

**Comment by dirkwhoffmann** [comment]
> Implementation of 8372a onwards is wrong then.

😢 Indeed.

This is because I am developing this project with PISDM(TM) (Priority Inversion Software Development Method) aka LITF: least important things first. As a result, the GUI can already detect misconfigurations 😎.

<img width="420" alt="Bildschirmfoto 2019-11-09 um 10 48 16" src="https://user-images.githubusercontent.com/12561945/68540594-efb6d000-0394-11ea-81b9-526f269e4042.png">

**Comment by dirkwhoffmann** [comment]
> Still this shows the gamedefinition database at lemonamiga ist not error free.

Yes, it definitely requires an ECS Agnus, because it requires 1 MB Chip Ram which is not supported by the old OCS Agnus. Interestingly, all my A500's already have the ECS Agnus.

**Comment by dirkwhoffmann** [comment]
BTW, when playing Heimdall in SAE and walking to the bottom of the screen, the main character vanishes. I am wondering if this is correct behaviour 🤔.

**Comment by mithrendal** [comment]
Maybe @Alessandro1970 can try on the A2000 which has 1MB chipram, what happens when the hero goes south ... 

Dirk a question,I remember your retrobrite beauties all do only have 512k chipram right? What is with the expansion card with the leaking battery, did you still have it ? If it still works then maybe one day you can convert it into a chipram expansion with this description http://amiga.resource.cx/manual/1MBChip_A500_A2000.pdf ...

**Comment by Alessandro1970** [comment]
My A2000 has 512 chip ram, but it does not work yet.
I finished that game in the A 2000 so many years ago...

**Comment by dirkwhoffmann** [comment]
> My A2000 has 512 chip ram, but it does not work yet.

Has the Gotek been fixed? 🤔

**Comment by mithrendal** [comment]
>My A2000 has 512 chip ram, but it does not work yet.

Poor A2000 what is the problem that it does not work ? 😳
You made a typo, ... it has definitly 1024 KB chip ram.😊

**Comment by Alessandro1970** [comment]
Removed add-on it worked with gotek without sound.
So after removed all the add-on card I have realized thet the mobo 6.2 revision has only 512 mb chip ram.
The newer revision must gave mounted 1mb chip ram

**Comment by Alessandro1970** [comment]
http://amiga.resource.cx/mod/a2000.html

**Comment by dirkwhoffmann** [comment]
The ECS nightmare begins 🙈. By supporting the old OCS Agnus only, I was able to code like this:

```
template <int x> void
Agnus::setBPLxPTH(uint16_t value)
{
    debug(BPLREG_DEBUG, "setBPLxPTH(%d, %X)\n", x, value);
    assert(1 <= x && x <= 6);

    bplpt[x - 1] = REPLACE_HI_WORD(bplpt[x - 1], value & 0x7);
}
```

Anybody spotting the ECS issue? Hint: `& 0x7` cuts off everything above 512 KB.
Now, I have to support varying register widths at various places 🤨. 

I shouldn't have started to ad the ECS Agnus revisions... On the other hand, Heimdall seems to be cool 😎. I want to have that supported 🤤.

**Comment by dirkwhoffmann** [comment]
> you can convert it into a chipram expansion with this description

It says I need a soldering iron and a sharp knife. As a theoretician I am not sure if I am allowed to use such tools 🙄. And considering what happened to the machine that is now known as the A500 MMSE, I better keep my hands off the mainboard.

**Comment by dirkwhoffmann** [comment]
If I haven't missed anything, only the following registers should be affected: 

```
DSKPTH
BLTCPTH
BLTBPTH
BLTAPTH
BLTDPTH
COP1LCH
COP2LCH
AUDxLCH
BPLxPTH
SPRxPTH
```

**Comment by mithrendal** [comment]
You are now in the same situation as the commodore hardware technicans were some 30 years ago. The only difference they hardware you software. 🥴

**Comment by dirkwhoffmann** [comment]
Much better now 😎

<img width="916" alt="Bildschirmfoto 2019-11-10 um 11 43 56" src="https://user-images.githubusercontent.com/12561945/68542848-c015c100-03b0-11ea-8f86-01e336dc015a.png">

Unfortunately, I cannot hear any sound 😖. Heimdall is supposed to have sound, isn't it?

**Comment by mithrendal** [comment]
The guy wears cool sports wear. 😂 and the helmet. This must be a funny game.

**Comment by dirkwhoffmann** [comment]
> Unfortunately, I cannot hear any sound

I just fooled myself (again). Heimdall doesn't turn off the drive motor. Hence, vAmiga runs in warp mode (hard to notice in debug mode) and therefore with sound disabled.

<img width="916" alt="Bildschirmfoto 2019-11-10 um 11 43 56" src="https://user-images.githubusercontent.com/12561945/68543120-4206e980-03b3-11ea-8166-3755ac578923.png">

Now, the remaining issue is how to scroll the screen. Interestingly, I can walk the guy with the cool underpants and helmet into the invisible area. The screen simply doesn't scroll. Is there some key combination for that? 

<img width="916" alt="Bildschirmfoto 2019-11-10 um 11 44 33" src="https://user-images.githubusercontent.com/12561945/68543143-93af7400-03b3-11ea-991d-912ccc53a050.png">

<img width="916" alt="Bildschirmfoto 2019-11-10 um 11 45 08" src="https://user-images.githubusercontent.com/12561945/68543144-95793780-03b3-11ea-8b1d-1e807b84a9f8.png">

And who is the girl in to status bar on top next to my main character? 🤔

**Comment by Alessandro1970** [comment]
https://youtu.be/H6HC29G1STE

**Comment by dirkwhoffmann** [comment]
> https://youtu.be/H6HC29G1STE

So it should scroll automatically then 😢

**Comment by dirkwhoffmann** [comment]
It scrolls in SAE if an ECS Denise is selected. This means we won't be able to play the game with the guy with the cool pants and helmet for a long time in vAmiga. So sad 😢.

<img width="728" alt="Bildschirmfoto 2019-11-10 um 12 36 24" src="https://user-images.githubusercontent.com/12561945/68543411-d32b8f80-03b6-11ea-8207-de45ba355c28.png">

**Comment by mithrendal** [comment]
I bet the girl in the status bar is the princess 👸🏻 in defender of the crown! So we can in the meantime just rescue her somewhere near nottingham forest. 🤗

**Comment by dirkwhoffmann** [comment]
I'll close this, because an ECS Denise won't be supported by vAmiga in the near future.

**Comment by Alessandro1970** [comment]
IIn WinUAE this game **works with OCS** and 1mb Chip RAM:

![Untitled 2](https://user-images.githubusercontent.com/34916641/68679304-e75ec080-055f-11ea-80c3-0399287ecfbc.png)

**Comment by mithrendal** [comment]
Hi @Alessandro1970 great find !
That is really a big surprise. But maybe it is only bug in WinUAE? Because dirk said scrolling worked only when he enabled ECS Denise in SAE... (but on the other hand it could also be a bug in SAE and vAmiga) 
To find out we have to check a real Amiga with 1MB chipram and OCS denise or to find the scrolling code and whether it uses the new ECSDenise stuff. Could it be that in the end lemmonamiga was right ?

**Comment by dirkwhoffmann** [comment]
> In WinUAE this game works with OCS and 1mb Chip RAM:

That's great! So we have a chance to get the game working some day.

I retried in SAE with 1 MB Chip + 512 KB Slow. 

If started with OSC Agnus + OCS Denise, it shows graphics errors and doesn't load.

If started with ECS Agnus + OCS Denise, it doesn't scroll 😢:

<img width="720" alt="Bildschirmfoto 2019-11-12 um 16 36 45" src="https://user-images.githubusercontent.com/12561945/68685733-d9fb0380-056a-11ea-8ec0-1d488fd3bbb0.png">

If started with ECS Agnus + ECS Denise, it scrolls.

Maybe @naTmeg knows what ECS Denise feature could be the reason to make it scroll? 🤔

**Comment by mithrendal** [comment]
when I rethink Allessandros settings in WinUAE then I am confused ...
OCS and 1MB ChipRam is not possible ! 
It could be that WinUAE switches automatically to ECS Agnus/Denise, if such an misconfiguration is selected... That means they maybe do not have these nice warning messages as vAmiga now has, but instead just silently do upgrade the custom chips ...

**Comment by Alessandro1970** [comment]
...I have used kick 1.3 and with ocs + 1mb chip, no scrolling problem, it worked well in wiunae

**Comment by mithrendal** [comment]
Hi dirk, maybe it does the trick when we identifiing vAmigas "virtual" Denise as ECS capable as described at the very end in http://amigadev.elowar.com/read/ADCD_2.1/Hardware_Manual_guide/node00A2.html ? Could it be that the game is checking these chip  identifications?

**Comment by dirkwhoffmann** [comment]
> when we identifiing vAmigas "virtual" Denise as ECS capable

I could try that. But I would be surprised if UAE really switches to ECS automatically when 1 MB Chip or more is selected.

**Comment by dirkwhoffmann** [comment]
The scrolling issue was most likely due to Blitter timing. Works well in v0.46.2 😎:

<img width="875" alt="Bildschirmfoto 2019-11-16 um 14 11 57" src="https://user-images.githubusercontent.com/12561945/68993788-2d779500-087c-11ea-849e-2c431ec4a34f.png">

<img width="875" alt="Bildschirmfoto 2019-11-16 um 14 12 51" src="https://user-images.githubusercontent.com/12561945/68993790-30728580-087c-11ea-92c9-5b41ea55d8e7.png">

<img width="875" alt="Bildschirmfoto 2019-11-16 um 14 13 57" src="https://user-images.githubusercontent.com/12561945/68993791-31a3b280-087c-11ea-8bed-7e708b169fdc.png">

**Comment by mithrendal** [comment]
Very cool 🤓 and what a surprise !!! I would never have thought that the scrolling bug was due to a blitter accuracy problem. What for a bright minded guy has found this reason 🤔?  Does that also mean that SAE has a better blitter accuracy when switching to ECS denise ?

**Comment by dirkwhoffmann** [comment]
> Does that also mean that SAE has a better blitter accuracy when switching to ECS denise ?

As far as I can imagine, the selected Denise revision shouldn't affect the Blitter. Having said this, there is indeed a difference in SAE: 

Test timing15 with OCS chipset and "waiting never":

<img width="731" alt="sae_ocs" src="https://user-images.githubusercontent.com/12561945/68998597-da6e0400-08b4-11ea-9056-ae9a15687e72.png">

Test timing15 with OCS Agnus and ECS Denise and "waiting never":

<img width="731" alt="sae_ecs" src="https://user-images.githubusercontent.com/12561945/68998569-6895ba80-08b4-11ea-8341-5f6028fd2583.png">

When another waiting mode is selected, e.g., "waiting auto", SAE does something completely strange (I think):

<img width="731" alt="Bildschirmfoto 2019-11-16 um 20 56 09" src="https://user-images.githubusercontent.com/12561945/68998572-7a775d80-08b4-11ea-8755-b867b775d38c.png">

On a real machine, it looks like this: 

![timing15_A500+](https://user-images.githubusercontent.com/12561945/68998632-49e3f380-08b5-11ea-9c38-79ec634878f8.jpeg)

@naTmeg: Hi Rupert, if you wish to look into the issue, you can find the test case (as well as others) in the vAmigaTS repo: 

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Blitter/timing
