### ISSUE TITLE
Activity monitor ideas

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#216]
My new love is this activity monitor thing. It is fun to look at demos or games and to learn how they are using the Amiga.  And it looks so nice.😍

While playing with it, I did asked me why can't we display the CPU activity as well, like in the activity monitor of macos?

Then I instantly rejected my question because I thought that it is maybe not possible to let the old 68k CPU do nothing.🥴 But I remembered that there was a special 68k command. 

```
NOP
Execution continues with the instruction following the NOP instruction. The NOP instruction does not begin execution until all pending bus cycles are completed.
```

Count all commands as activity except NOP ? My guess is that the CPU would always show 100%.😫🤪

What the heck is the macos CPU activity monitor showing us ? Maybe it counts only the bus activity?  🤨 

What about this strategy:  Whenever the 68k-CPU accesses memory there is CPU (bus)-activity, we could count that. Or maybe it is even better to count only CPU writes to the memory as activity? This way we could blame games which are moving graphical objects with CPU instead of the blitter.🙃

_Originally posted by @mithrendal in https://github.com/dirkwhoffmann/vAmiga/issues/205#issuecomment-546730926_

**Comment by dirkwhoffmann** [comment]
The activity monitor in v0.43 is just a first shot and leaves much room for improvement. I opened up this thread to collect ideas. 

Here are mine: 

- Add autoscaling. The scrolling banner image will automatically perform y-axis scaling according to the highest value. I am already doing a similar thing with the audio waveform. 

- Colorize. Auto-scaling will have the drawback that the user can't judge if a value is high or low. To cope with this, we could colorize the vertical bars from green (low value) over yellow (medium value) to red (high value). 

- Disk activity could be split into reads and writes. Each vertical bar could be separated into two segments (e.g., red = write, blue = read). Another idea is to start drawing in the middle. Reads will produce a line going up, writes will produce a line going down. This would visualize the data flow graphically (read = from drive, write = to drive).

**Comment by dirkwhoffmann** [comment]
> Count all commands as activity except NOP ?

I agree that monitoring the CPU would be cool, but I think it's hardly possible. Two reasons: 

- As you already pointed out,  in old CPUs there is no such thing as being idle.
- There are many many ways to fake idle state. NOPs are one possibility. Others are jump-loops which can be implemented with almost any branch command. 

What we could do is to visualize CPU bus activity. We can count reads and writes and display them the same way as disk activity. 

> What the heck is the macos CPU activity monitor showing us ? Maybe it counts only the bus activity?

To be honest, I don't really know how modern CPUs deal with idle state. I am pretty sure that they can be idle, because it won't make sense to run 31 out of 32 CPU cores in a NOP loop if only a single thread is running. Also, I am pretty sure that modern CPUs do have some hardware-based thread-management on board, but I never looked up the details. What I know is that modern CPUs do collect statistical information. e.g., about branching. With the right tools in hand, you can read from the CPU how many times branch-prediction was right or wrong. Unfortunately, I never found such a tool for macOS, but I know that it is possible on Linux.

**Comment by mithrendal** [comment]
Offtopic: in germany you can right now buy the "CT Retro 2019 - 16 Bit Revolution" magazin. Including a gratis "Amiga 8 forever" software licence. They mention all the 5 big amiga emulators out there. Oh no how could they dare and missed to mention our beloved vAmiga.

**Comment by dirkwhoffmann** [comment]
> Including a gratis "Amiga 8 forever" software licence

Does this include a license for the Amiga Roms? 

Oh, just found the answer: "die Software-Sammlung Amiga Forever 8 Value-Edition inklusive Kickstart-ROMs gibt es für Leser des Hefts praktischerweise gratis dazu." 

🤤

> how could they dare and miss to mention our beloved vAmiga.

☹️ Ignorants. 

Maybe we should invest more into marketing 🤔. vAmiga cups, vAmiga mouse pads, vAmiga cushions, vAmiga blankets, vAmiga umbrellas, vAmiga underpants...

**Comment by dirkwhoffmann** [comment]
> CT Retro 2019
 
Back from shopping. Bought a copy from my trusted magazine dealer. Busy reading ... 🤤

Amiga Roms for EUR 6,90. Awesome deal.

**Comment by dirkwhoffmann** [comment]
I did various experiments, but didn't find a satisfying solution yet: 

What I found out so far: 
- Auto-scaling is not a good idea. It confuses the viewer, because already drawn parts shrink and expand vertically. 
- Drawing with a gradient doesn't look as good as expected: 

<img width="720" alt="Bildschirmfoto 2019-10-29 um 17 25 13" src="https://user-images.githubusercontent.com/12561945/67787805-7d2f2180-fa71-11e9-8981-1edd25ca140f.png">

Next thing to try out: 

- Colorize the background according to the cumulative activity (green = low activity, yellow = medium, red = high). Overlay the activity graph with a semi-transparent color.

**Comment by dirkwhoffmann** [comment]
Another idea: Combine Blitter, Copper, CPU into a single graph similar to this: 

<img width="268" alt="Bildschirmfoto 2019-10-29 um 18 13 13" src="https://user-images.githubusercontent.com/12561945/67791570-f3cf1d80-fa77-11e9-82ee-cc58c3bb0058.png">

The graph will show the number of used bus cycles for each component.

**Comment by mithrendal** [comment]
yes I like the last one

**Comment by mithrendal** [comment]
Cool thing that you also plan to visualise bus activity of the CPU. But what if CPU operates on FASTRam? Is it the same bus?

**Comment by dirkwhoffmann** [comment]
> But what if CPU operates on FASTRam? Is it the same bus?

Hmm, I didn't think about that. It's a different bus. No reads or writes from or to this bus would show up.

**Comment by mithrendal** [comment]
When I look at the amiga dma slot diagram then it shows the slots dedicated to each component. Also some components have more priority and will reduce the maximal available free slots for lower priotized components. 
That said. I can also imagine separate graphs for each component as you had until now. The theoretical maximum amount of bus cycles for a component would be 100% in a graph. A red line would mark the left over buscycles e.g. after higher priotized components have reduced the possible amount of cycles. 

Maybe not so helpful for you? 👀

**Comment by dirkwhoffmann** [comment]
>  The theoretical maximum amount of bus cycles for a component would be 100% in a graph.

This was the idea I pursued first. The problem: In theory, the Copper can have half of the available bus cycles in a frame and the Blitter could have all, but in most cases, they only uses a fraction of it. The result is that the graph is hardly visible unser normal circumstances and only large if Shadow of the Beast or R-Type II is running. To solve this, I did experiment with auto-scaling algorithms which turned out to be confusing to the user.

**Comment by mithrendal** [comment]
The combined graph has also drawbacks. Imagine the used buscycle of the blitter (which is the orange color and sits on top of the other colors stacks) will increase slowly over time, you will not be able to see it because the NullPoint will constantly move, which is because the used buscycle of the other components (underlying e.g. higher priotized) is steadily changing. Do you get what I mean?

**Comment by dirkwhoffmann** [comment]
> will increase slowly over time, you will not be able to see it because the NullPoint will constantly move, which is because the used buscycle of the other components (underlying e.g. higher priotized) is steadily changing. 

I don't expect this to be an issue, because the user would see the orange area expanding (although the bottom line will vary).

For me, the main issue here is that such a graph looks 🤮 in reality. This is what Rink a Dink produces. 

<img width="268" alt="Bildschirmfoto 2019-10-30 um 15 02 10" src="https://user-images.githubusercontent.com/12561945/67864955-c2f9f180-fb26-11e9-8361-dd8bc3eb4747.png">

**Comment by mithrendal** [comment]
>  "pink bra from the 1940s"? 

Oh you discorvered the easter egg ! 

colors from the Miami Vice television series from 1984 to 1990 (Matches exactly the time of OCS !) ...

_In particular, the NBC television police series Miami Vice popularized what was already a growing trend even further as its lead character Sonny Crockett (Don Johnson) exclusively wore **pastel** shirts and suits, setting a fashion that stood popular years after the show ended. 
In particular, the NBC television police series Miami Vice popularized what was already a growing trend even further as its lead character [Sonny Crockett (Don Johnson) ](https://en.wikipedia.org/wiki/James_%22Sonny%22_Crockett)exclusively wore pastel shirts and suits, setting a fashion that stood popular years after the show ended._

**Comment by dirkwhoffmann** [comment]
BTW, I usually use the color table from here: 

https://www.rapidtables.com/web/color/RGB_Color.html

**Comment by mithrendal** [comment]
yes logaritmic scale is good, because we also want to measure some importance to the small values. I think this is very clever and will solve the scaling problem.

**Comment by dirkwhoffmann** [comment]
Logarithmic scaling in action. Much better than previous attempts: 

<img width="308" alt="Bildschirmfoto 2019-10-31 um 08 45 51" src="https://user-images.githubusercontent.com/12561945/67928325-0a31c200-fbbb-11e9-98ed-f84e464f062f.png">

**Comment by mithrendal** [comment]
Nice implementation  !!! Very good scaling.  

For the colors. I am not sure what is better. 

1.  The color interpolation of high and low values as in the picture above. 
_advantage:
 you see it not only from the graph but also from the red color when the component uses its max buscycles_

2. Or for each graph the solid color of the DMA debugger (e.g. for copper = yellow and for blitter = orange).
_advantage:
 you see don't have to look at the graph title description as you can identify the components graph soley by the color_

**Comment by dirkwhoffmann** [comment]
Using the DMA debugger colors results in this (running Rink a Dink): 

<img width="582" alt="Bildschirmfoto 2019-10-31 um 11 21 29" src="https://user-images.githubusercontent.com/12561945/67938962-d5c90080-fbd0-11e9-8eb1-61935ef3d469.png">

The gradient method (green -> yellow -> red) has the advantage that it visually supports the logarithmic scale. Values in the upper red area mean that the Copper resp. the Blitter do run full throttle.

BTW, I am planning to move the DMA debugger config stuff to a separate sheet. Doing so allows us to shrink the window horizontally. If the window is narrow, it can be displayed side by side to the main emulator window without overlap.

**Comment by dirkwhoffmann** [comment]
Dark mode: 

<img width="602" alt="Bildschirmfoto 2019-10-31 um 11 31 13" src="https://user-images.githubusercontent.com/12561945/67939494-f9d91180-fbd1-11e9-91cf-60010e9106c0.png">

**Comment by mithrendal** [comment]
Wow darkmode is beautiful like a beast. 🤤
I really like that clear solid color more. But I also see the advantage of the colorgradient. 
🤔
You decide.

**Comment by dirkwhoffmann** [comment]
This is what I have so far: 

<img width="468" alt="Bildschirmfoto 2019-10-31 um 14 47 33" src="https://user-images.githubusercontent.com/12561945/67952459-9fe64500-fbed-11e9-9580-b29557c1aa30.png">
<img width="468" alt="Bildschirmfoto 2019-10-31 um 14 47 52" src="https://user-images.githubusercontent.com/12561945/67952465-a1b00880-fbed-11e9-8883-a3180e441915.png">

There is still a lot of work to be done:

- CPU Rom accesses are not observed
- Chip Ram bus statistics needs verification and better scaling

**Comment by mithrendal** [comment]
Lovely! 🤤🤤🤤

**Comment by dirkwhoffmann** [comment]
Turns out to be nice toy to play around with: 

<img width="424" alt="Bildschirmfoto 2019-10-31 um 16 42 45" src="https://user-images.githubusercontent.com/12561945/67962680-b72d2e80-fbfd-11e9-9a1a-31975498c2c5.png">

> When the CPU runs in ROM OS-routines it is also counted as FASTRAM I think...

Yes, but it's easy to count them separately. The target for each memory access can be read directly from vAmiga's page mapping table.

Next step will be to turn the view into a "split view" that distinguishes between reads and writes.

**Comment by dirkwhoffmann** [comment]
Now, all monitors work with a logarithmic scale to make it consistent. In addition, most views draw an upper graph and a lower graph to distinguish between reads and writes (upper = reads, lower = writes).

Also, I tweaked the colors a little to make the monitor look better in light mode (the base color is a shaded blue for reads and a light pink for writes).

<img width="416" alt="Bildschirmfoto 2019-11-01 um 12 08 24" src="https://user-images.githubusercontent.com/12561945/68021384-8b638480-fca1-11e9-9601-afed934ae7f4.png">
<img width="416" alt="Bildschirmfoto 2019-11-01 um 12 08 44" src="https://user-images.githubusercontent.com/12561945/68021389-8c94b180-fca1-11e9-92f0-2c9f68ed16e1.png">

**Comment by mithrendal** [comment]
looks perfect. 

another fancy idea: For the Audio you could do four separate graphs. Each channel one graph. Give them different colours and mix them togehter. Or if that is too difficult maybe one separate graph for left and right channels?

**Comment by dirkwhoffmann** [comment]
> For the Audio you could do four separate graphs. 

This would hit performance, because I read directly from the audio ringbuffers. There are only two ringbuffers for performance reasons (one for the left and one for the right channel).

>  maybe one separate graph for left and right channels?

My plan is to incorporate both channels into a single graph. Right now, the lower part of the waveform is identical to the upper part (just mirrored). My plan is to use the upper part for the left channel and the lower part for the right channel.

**Comment by dirkwhoffmann** [comment]
The waveform view has been slit (upper half = left channel, lower half = right channel). 

<img width="416" alt="Bildschirmfoto 2019-11-01 um 14 04 02" src="https://user-images.githubusercontent.com/12561945/68026818-0bddb180-fcb1-11e9-8edc-d93f9dd9270f.png">

In the new code, it's also possible to apply different colours in light mode and dark mode.
If somebody wants to experiment with different colours, simply edit this function in Xcode: 

```
   func setupColors() {

        // Check for dark mode
        var darkMode = false
        if #available(OSX 10.14, *) {
            darkMode = NSApp.effectiveAppearance.name == NSAppearance.Name.darkAqua
        }

        if darkMode {

            color1 = NSColor.init(r: 102, g: 178, b: 255, a: 255)
            alpha1a = NSColor.init(r: 102, g: 178, b: 255, a: 50)
            alpha1b = NSColor.init(r: 102, g: 178, b: 255, a: 150)

            color2 = NSColor.init(r: 255, g: 102, b: 178, a: 255)
            alpha2a = NSColor.init(r: 255, g: 102, b: 178, a: 50)
            alpha2b = NSColor.init(r: 255, g: 102, b: 178, a: 150)

        } else {

            color1 = NSColor.init(r: 0, g: 102, b: 204, a: 255)
            alpha1a = NSColor.init(r: 0, g: 102, b: 204, a: 50)
            alpha1b = NSColor.init(r: 0, g: 102, b: 204, a: 150)

            color2 = NSColor.init(r: 204, g: 0, b: 204, a: 255)
            alpha2a = NSColor.init(r: 204, g: 0, b: 204, a: 50)
            alpha2b = NSColor.init(r: 204, g: 0, b: 204, a: 150)
        }
    }
```

**Comment by dirkwhoffmann** [comment]
I found this in a spam mail that asked me to change all my money to Bitcoins. I didn't buy the Bitcoins, but I liked the design of the chart. Maybe the activity monitor can be tweaked to look similar in a future release...

<img width="545" alt="Bildschirmfoto 2019-12-16 um 19 37 22" src="https://user-images.githubusercontent.com/12561945/70933363-2212b780-203c-11ea-9c8b-946a91f9df25.png">

**Comment by dirkwhoffmann** [comment]
Because I wasn’t in the mode to get back to low-level stuff, I decided to do some more GPU programming. As the last bigger feature before releasing vAmiga 0.9, I want to rework the monitor panel. Although I really liked it in the beginning, I now think that the panel doesn't look good enough for being included in the release version of vAmiga. Besides, I am never really used it 🙄. What I do like is vAmiga's DMA debugger, because it produces freaking cool overlays 😎. To make a long story short: I think overlays are the way to go.

My plan is 
- to clean up (by removing the old monitoring panel)
- to simplify (by visualizing bus usage only, similar to what the DMA debugger shows) 
- to spice up (by overlaying the emulator texture with bar charts)

Drawing bar charts via the GPU is 🥵, but I think I finally nailed it. Here is an experimental chart, filled with random numbers and superimposed onto the emulator texture: 

<img width="442" alt="Bildschirmfoto 2020-04-08 um 14 22 28" src="https://user-images.githubusercontent.com/12561945/78785980-55d96a80-79a8-11ea-93d1-4133f429dfbe.png">

In the final version, I’ll use the same colors that are used in the DMA debugger view.

**Comment by dirkwhoffmann** [comment]
Sorry, I posted an old picture. In the meantime, I played around a little bit with gradients and the alpha channel 😎:

<img width="442" alt="Bildschirmfoto 2020-04-08 um 14 33 39" src="https://user-images.githubusercontent.com/12561945/78786530-3131c280-79a9-11ea-9ab6-79bfde94037a.png">

**Comment by mithrendal** [comment]
>to simplify (by visualizing bus usage only, similar to what the DMA debugger shows)

Oh no ! 😢 I liked it so much to see the blitter / cpu chip ram / fast ram dma activity ... I liked it so much .... It showed me whether a game was a cheap AtariST conversion or a full flegde amiga release which used all the power of it...  It was so nice to see what is going on ...😭

😏Maybe tomorrow you change your idea and come back to the old concept

**Comment by dirkwhoffmann** [comment]
> It was so nice to see what is going on ...😭

But Blitter activity would still be there. My plan is to visualize:

- CPU bus usage (would only measure Chip and Slow Ram activity, no FastRam or Rom)
- Disk DMA activity
- Blitter DMA activity
- Blood pressure of princess 
- Copper DMA activity
- Sprite DMA activity
- Bitplane DMA activity

This requires 6 bar charts that fit nicely in the bottom part of the screen. 

<img width="958" alt="Bildschirmfoto 2020-04-08 um 16 20 26" src="https://user-images.githubusercontent.com/12561945/78795849-c8047c00-79b5-11ea-9e81-b2b026f1655a.png">

**Comment by mithrendal** [comment]
>This requires 6 bar charts that fit nicely in the bottom part of the screen.

but but  😪... are there labels for them so I can know what bar is what for ? vertical display of them has the advantage that the time axis begins at the same horizontal position 😢... do I have to display these bars  in the coming web version too ? 😏 Oh yes that is indeed an advantage, we can see these activity also in fullscreen 🤓

**Comment by dirkwhoffmann** [comment]
> but but 😪... are there labels for them so I can know what bar is what for ? 

No labels 🙄, but different colors 😇. See it from the positive side: No need for internationalization 😃.

> that the time axis begins at the same horizontal position 😢

This could be made customizable. Like the dock where you can choose to display vertically or horizontally. 

> do I have to display these bars in the coming web version too ? 😏

Definitely! A must have! Overlays are the future 😎.

> see these activity also in fullscreen 🤓

😬 Not yet. Fullscreen has it's own rendering routine which doesn't render the bar charts yet. The cool thing about GPU rendering is that we can rotate the canvases freely. We could slightly rotate them around the y-axis to get a cover flow like appearance. I need to experiment a little with the projection matrices 🤤.

**Comment by dirkwhoffmann** [comment]
The new view now runs side by side with the old view:

<img width="914" alt="Bildschirmfoto 2020-04-08 um 18 14 08" src="https://user-images.githubusercontent.com/12561945/78807994-1a00ce00-79c5-11ea-9bf3-8548b44343dc.png">

<img width="303" alt="Bildschirmfoto 2020-04-08 um 18 14 28" src="https://user-images.githubusercontent.com/12561945/78808020-22590900-79c5-11ea-82c1-4211ecc0e807.png">

I get your point that the new view misses labels. A possible solution could be to use separate background textures for all canvases and symbolize the data source in form of a pictogram (very subtle, dark grey on black or something). Unfortunately, there is no standardized symbol for the Blitter or the Copper. 🤔

**Comment by mithrendal** [comment]
I like the old view. Can we let it be live in parallel for some time until the fresh hot exciting overlay thing is robust enough 😳

**Comment by dirkwhoffmann** [comment]
> I like the old view.

I'm not giving up. I will sell this to you 😎. Stay tuned...

**Comment by mithrendal** [comment]
bro, your web cam live stream is on ... 😬 

https://media1.tenor.com/images/445148a0e7faf03b2b8379c7a2969375/tenor.gif?itemid=6186560

**Comment by dirkwhoffmann** [comment]
I've managed to wrap a CGContext around a buffer, write a string into it, and convert that buffer into a texture. This results in labelled overlays. It sounds easier than it is, because a lot of stuff has to be made right (pixel format, endianness etc.). In addition, Apples Core Graphics API is 🤮, especially when it comes to drawing text. Now it looks like this 😎:

![alienbreed](https://user-images.githubusercontent.com/12561945/78870403-59bbca00-7a46-11ea-8d19-459a6438b05c.png)

Still dislike it? Think about twice...

<img width="512" alt="Bildschirmfoto 2020-04-09 um 09 38 06" src="https://user-images.githubusercontent.com/12561945/78870443-6dffc700-7a46-11ea-9d5d-36c3ff8681c3.png">

**Comment by mithrendal** [comment]
better now I think 🤗... now I know what I am staring at ...  The colors ? Will there be different colors ? I guess you will stay with the bar diagram and not go with the log scale as before, no, yes ?  Before when the values became high you interpolated that with colorchange to red.... when value was low you stayed with a cool blue... these old rendering results where also nice (ok, ok I will shut my mouth  🤐... )  Your new stuff is more modern design 🤔 I guess ...

**Comment by dirkwhoffmann** [comment]
> not go with the log scale

I think, I'll use a log scale for the Copper and the Blitter view. For all others, a linear scale seems appropriate. 

> Will there be different colors ?

My colorization code is pretty flexible now. In this version, the chosen color is used for background drawing, too.

<img width="1000" alt="Bildschirmfoto 2020-04-09 um 11 06 19" src="https://user-images.githubusercontent.com/12561945/78878551-deace080-7a52-11ea-81ff-832410373255.png">

**Comment by mithrendal** [comment]
Oh yes ... now I see it ... it changes colors too when displaying high values... log scale for copper and blitter is cool too ... I am more and more loving the new overlay activity monitoring ...

![grafik](https://user-images.githubusercontent.com/17108995/78881507-377e7800-7a57-11ea-99a4-a9c71addc7f9.png)

what about CPU bus access ?

**Comment by dirkwhoffmann** [comment]
Grid lines are back:

<img width="915" alt="Bildschirmfoto 2020-04-09 um 12 15 41" src="https://user-images.githubusercontent.com/12561945/78885070-39970580-7a5c-11ea-9e5e-c0430cdf6884.png">

> what about CPU bus access ?

Hoped you forget about them. 🙄

See, other users are thrilled even without CPU metrics: 😃

<img width="168" alt="Bildschirmfoto 2020-04-09 um 12 07 48" src="https://user-images.githubusercontent.com/12561945/78885148-62b79600-7a5c-11ea-8c6c-65f34c6cf574.png">

**Comment by dirkwhoffmann** [comment]
I've added a perspective matrix to the canvas drawing code together with the option to specify a rotation angle. I think it doesn't make sense to rotate the panels when they are being used, but it enables me to add a cool animation effect when enabling / disabling the panels. Eventually, they will smoothly rotate in and out 😎. 

<img width="966" alt="Bildschirmfoto 2020-04-09 um 17 58 46" src="https://user-images.githubusercontent.com/12561945/78915485-492e4280-7a8c-11ea-84c6-3288b80f2b0e.png">

**Comment by dirkwhoffmann** [comment]
The latest code changes bring back memory observers 🥳. There are four different observers:  One each for Chip Ram, Slow Ram, Fast Ram, and Rom. The panels use the same split view style as the old ones (reads are displayed in the upper half in blue, and writes are displayed in the lower half in red). 

<img width="966" alt="Bildschirmfoto 2020-04-12 um 07 35 07" src="https://user-images.githubusercontent.com/12561945/79062033-ba414600-7c96-11ea-9426-7194ab20f317.png">

In addition, there are two new waveform panels. In the old version the waveform was displayed inside the monitor window. This window is still there, but it doesn't display any information any more. Now, it serves solely as the control center for the bus debugger and the activity monitors. 

<img width="802" alt="Bildschirmfoto 2020-04-12 um 07 36 05" src="https://user-images.githubusercontent.com/12561945/79062037-c0372700-7c96-11ea-9f86-f48f84baa0d8.png">

As you can see in the panel, the latest version supports different layout schemes. E.g., this one:

<img width="966" alt="Bildschirmfoto 2020-04-12 um 07 35 23" src="https://user-images.githubusercontent.com/12561945/79062040-c75e3500-7c96-11ea-814a-bef08a419f5a.png">

You don't like the flat design? Just bend the panels 😎:

<img width="966" alt="Bildschirmfoto 2020-04-12 um 07 35 33" src="https://user-images.githubusercontent.com/12561945/79062047-d93fd800-7c96-11ea-94f4-860c59424df0.png">

It's too opaque? Just increase the transparency level: 

<img width="966" alt="Bildschirmfoto 2020-04-12 um 07 35 55" src="https://user-images.githubusercontent.com/12561945/79062067-12784800-7c97-11ea-9106-cf93969b2623.png">

Anybody still loving the old panels? 

![gremlin](https://user-images.githubusercontent.com/12561945/79062092-4b182180-7c97-11ea-80e3-e182667dc9cc.jpg)

(No, there is no need to worry about me. It's just that I had a snack after midnight and  I didn't brush my teeth this morning. I'm a little worried about the black spots on my ears, though)

**Comment by mithrendal** [comment]
Oh this looks gorgeous... I am in love with the new panels ... 🙋🏿When keeping the correct aspect ratio of the Amiga 4:3 (the robin hood story) but we are displaying on a wide screen ... is it possible to get the activity panels out of the Amiga pixels and to display just left and right on the black empty sides ? Ok then this is no overlay anymore 😬... it is a HUD in the right and left black space

**Comment by dirkwhoffmann** [comment]
> but we are displaying on a wide screen (possibly fullscreen)... is it possible to get the activity panels out of the Amiga pixels and to display just left and right on the black empty sides ?

You've got a point here. Almost all modern display have a larger width/height ration than the old 4:3 monitors. Hence, we could just increase the window size horizontally when displaying the activity panels. Unfortunately, this is not so easy to implement. There are many projection matrices involved in the current implementation and it would almost certainly screw up everything. But it should be doable in fullscreen mode. If the aspect ratio is kept, there are two black stripes on the left and on the right. It should be easy to render the activity panels there.

**Comment by dirkwhoffmann** [comment]
Hmm, on my MacBook the unused areas are not as large as expected. It looks like this in fullscreen mode: 

![Bildschirmfoto 2020-04-12 um 10 39 34](https://user-images.githubusercontent.com/12561945/79064559-2f6a4680-7caa-11ea-8eae-ab9a759886ab.png)

I'm curious how it looks on my widescreen TFT. Unfortunately, I cannot connect my MacBook easily. The monitor has HDMI, but my MacBook only has USB C. I'll grab a hammer and make the connectors fit... stay tuned...

**Comment by dirkwhoffmann** [comment]
I didn't find a hammer, but I spotted an HDMI output on my wife's MacBook...

And here is the result: vAmiga goes widescreen... 😎

![Bildschirmfoto 2020-04-12 um 11 08 01](https://user-images.githubusercontent.com/12561945/79065219-0c8e6100-7caf-11ea-928d-7363f4c0b1e2.png)

![Bildschirmfoto 2020-04-12 um 11 08 29](https://user-images.githubusercontent.com/12561945/79065263-62fb9f80-7caf-11ea-9182-bb3051c38234.png)

But it's not perfect yet. vAmiga gets confused by the second monitor. Sometimes it grabs the wrong aspect ratio and I even managed to align the emulator texture to the very left (didn't know that my code is capable of doing that 🤔). But we're still in alpha phase, so nothing to worry about.

**Comment by dirkwhoffmann** [comment]
Changed clear color to black in v0.67. Aspect ratio should be correct on all monitors now.

**Comment by sy2002** [comment]
MEGA COOL! :-)
