### ISSUE TITLE
PerfMon (Extras/Tools 1.3) does not show menu options.

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#22]
The utility PerfMon, located in Extras/Tools (vers. 1.3) works fine apparently but do not show, with right mouse button, the menu for changing the timing.

**Comment by dirkwhoffmann** [comment]
I think I screwed up the right button altogether 🙄.

**Comment by dirkwhoffmann** [comment]
The right mouse button is back:

http://dirkwhoffmann.de/vAmiga/vAmiga_0.20.zip

(From now on, I'm using a more meaningful naming scheme:  V(calenderWeek).(revision) )

**Comment by dirkwhoffmann** [comment]
PerfMon seems to work now. Please reopen if not.
