### ISSUE TITLE
BC KID intro music bug

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#220]
BC KID hangs after intro screen with blitter accuracy 1 and 2:

<img width="782" alt="Schermata 2019-11-03 alle 11 28 00" src="https://user-images.githubusercontent.com/34916641/68083772-3bb1c400-fe2d-11e9-88b3-e0c9237bb8a3.png">

[Archivio.zip](https://github.com/dirkwhoffmann/vAmiga/files/3801443/Archivio.zip)

**Comment by dirkwhoffmann** [comment]
In v0.49, it doesn't hang any more, but the music plays way too fast. How can that be? 🤔

<img width="894" alt="Bildschirmfoto 2019-12-02 um 15 58 39" src="https://user-images.githubusercontent.com/12561945/69970112-f1039480-151d-11ea-98f9-efe3da96f77a.png">

**Comment by dirkwhoffmann** [comment]
Seems work fine in v0.55.
