### ISSUE TITLE
Deuteros hangs after boot screen

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#222]
Deuteros hangs after Activision intro screen.

[Archivio 2.zip](https://github.com/dirkwhoffmann/vAmiga/files/3801463/Archivio.2.zip)

**Comment by dirkwhoffmann** [comment]
I just tested the game with the latest code in dev branch and had no issues so far:

<img width="818" alt="Bildschirmfoto 2019-11-03 um 18 43 28" src="https://user-images.githubusercontent.com/12561945/68089521-eba52280-fe69-11e9-9535-6bedc55b06fd.png">

<img width="818" alt="Bildschirmfoto 2019-11-03 um 18 40 39" src="https://user-images.githubusercontent.com/12561945/68089523-ef38a980-fe69-11e9-83ad-df30cb583ccb.png">

I leave this issue open for now. We should double check when the next the release comes out.

**Comment by Alessandro1970** [comment]
The intro is too slow and the game seems to me to halt during the intro.
<img width="791" alt="Schermata 2019-11-04 alle 23 19 06" src="https://user-images.githubusercontent.com/34916641/68162943-8d576d00-ff59-11e9-904b-af63e774d354.png">

**Comment by PakkunKinoppi** [comment]
This game hangs in Blitter Accuracy 2 for me too. 
Why have I to set blitter accuracy 0 or 1 ?
Blitter accuracy 2 should require more resource from the Mac but should grant the best performance and compatibility for the vAmiga Emulator.

**Comment by dirkwhoffmann** [comment]
>  but should grant the best performance and compatibility for the vAmiga Emulator.

In theory yes. In practice no, because Blitter / CPU bus sharing is still buggy.

**Comment by dirkwhoffmann** [comment]
Seems to work in v0.49 with all Blitter levels. Please reopen if not.
