### ISSUE TITLE
LAst Ninja remix intro has graphic error

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#226]
Hi, there is a graphic error in the intro of this game:
[Archivio.zip](https://github.com/dirkwhoffmann/vAmiga/files/3828261/Archivio.zip)

<img width="774" alt="Schermata 2019-11-10 alle 10 00 29" src="https://user-images.githubusercontent.com/34916641/68541756-930ee180-03a3-11ea-944b-e65678a53d32.png">

**Comment by dirkwhoffmann** [comment]
Seems to run fine when vAmiga is launched in Blitter level 0.

If vAmiga gets startet in Blitter level 2, it looks like this 🙈:

<img width="916" alt="Bildschirmfoto 2019-11-10 um 15 12 40" src="https://user-images.githubusercontent.com/12561945/68545364-c31eaa80-03cc-11ea-91b1-fc38ee93f454.png">

When I switch the level back to 0 (while the emulator is running), I get the same picture that was posted by Alessandro.

**Comment by dirkwhoffmann** [comment]
Works great now 😎.
