### ISSUE TITLE
More Blitter infos needed

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#233]
By looking at various posts in the internet and the UAE source code, I understand the following (might be wrong though): 

The Blitter has a ramp-up phase of 2 or 3 cycles (depending whether the CPU writes to BLTSIZE or the Copper). I call these ramp-up states BLT_STRT0 .. BLT_STRT2:

- BLTSTRT0 : One cycle delay, the bus does not need to be free (only executed for Copper writes)
- BLTSTRT1 : First idle cycle. Bus is not allocated, but needs to be free
- BLTSTRT2 : Second idle cycle. Bus is not allocated, but needs to be free

Furthermore, I understand the following: 

All Blitter idle cycles (those who don't do DMA) still require the bus to be free. If it is not free, the Blitter does nothing and waits for the next free bus cycle. 

In the following article,  a "HRM revision errata" is mentioned.

http://eab.abime.net/showthread.php?t=72660

Unfortunately, the document is no longer available at the download link. Does anybody know where it can be found?

**Comment by mithrendal** [comment]
Hi Dirk,

I found it here https://web.archive.org/web/2012*/http://www.bombjack.org/commodore/amiga/books/pdf/Amiga_Hardware_Manual_Errata.zip

**Comment by dirkwhoffmann** [comment]
Awesome, the holy runes of the IT age. Just in front of us 🤤:

<img width="731" alt="Bildschirmfoto 2019-11-15 um 09 01 09" src="https://user-images.githubusercontent.com/12561945/68927077-3f2b4080-0787-11ea-9cd2-dd0d7a70c543.png">

This is the code to rule them all. It includes the mystical spells for fill and line blits that had long been forgotten...
