### ISSUE TITLE
State Art Demo hangs with Blitter Accuracy 2

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#235]
If blitter accuracy 2 is selected this demo hangs at start:
[Stateart.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3855341/Stateart.adf.zip)
<img width="807" alt="Schermata 2019-11-17 alle 08 56 49" src="https://user-images.githubusercontent.com/34916641/69004733-69603800-0918-11ea-819e-cc9b1bcdbcf1.png">

**Comment by dirkwhoffmann** [comment]
At some point, the CPU gets off the road:

<img width="980" alt="Bildschirmfoto 2019-12-05 um 14 30 00" src="https://user-images.githubusercontent.com/12561945/70239589-dcb4d700-176b-11ea-9d67-959e2d43a805.png">

**Comment by dirkwhoffmann** [comment]
Cool demo 😎. Running just fine with Moira:

<img width="858" alt="Bildschirmfoto 2020-01-16 um 12 41 06" src="https://user-images.githubusercontent.com/12561945/72522442-ff073d80-385d-11ea-89e0-93eea85cd437.png">
<img width="858" alt="Bildschirmfoto 2020-01-16 um 12 41 51" src="https://user-images.githubusercontent.com/12561945/72522445-00386a80-385e-11ea-88e4-1aa5dd91f508.png">
