### ISSUE TITLE
3D Demo doesn't work

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#236]
3D Demo does not work because for the speed or cpu too fast:

[3Ddemo2.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3855346/3Ddemo2.adf.zip)

<img width="804" alt="Schermata 2019-11-17 alle 08 59 43" src="https://user-images.githubusercontent.com/34916641/69004768-c6f48480-0918-11ea-89a5-c43354a404b9.png">

**Comment by dirkwhoffmann** [comment]
With the latest Blitter improvements (v0.49, v0.49.1), the accelerator card issue is gone.

However, we now get this 🤭:

<img width="828" alt="Bildschirmfoto 2019-12-05 um 14 20 53" src="https://user-images.githubusercontent.com/12561945/70239395-82b41180-176b-11ea-9c2d-da987f1a6860.png">

**Comment by dirkwhoffmann** [comment]
Works well in v0.55 (Moira edition) 😎: 

<img width="858" alt="Bildschirmfoto 2020-01-16 um 12 17 44" src="https://user-images.githubusercontent.com/12561945/72521138-2c062100-385b-11ea-8f77-22684afc997d.png">

<img width="858" alt="Bildschirmfoto 2020-01-16 um 12 20 10" src="https://user-images.githubusercontent.com/12561945/72521161-358f8900-385b-11ea-88bd-b5acb2238178.png">
