### ISSUE TITLE
Space Harrier Return has a graph error with Blitter Accuracy 2

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#237]
Space Harrier Return has a graph error with Blitter Accuracy 2 when the character reaches the top as in the screenshot:

[Space Harrier - Return to the Fantasy Zone (1989)(Elite)[cr Power Connection][t +2 Setrox].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3855365/Space.Harrier.-.Return.to.the.Fantasy.Zone.1989.Elite.cr.Power.Connection.t.%2B2.Setrox.adf.zip)

<img width="814" alt="Schermata 2019-11-17 alle 09 14 37" src="https://user-images.githubusercontent.com/34916641/69004948-1d62c280-091b-11ea-88be-a7082c304376.png">

**Comment by dirkwhoffmann** [comment]
It flickers in Blitter level 0, too. I think it's a flaw in the game, because it flickers in UAE as well:

<img width="581" alt="Bildschirmfoto 2019-12-05 um 14 17 03" src="https://user-images.githubusercontent.com/12561945/70238664-03720e00-176a-11ea-8bf5-312a7a77296c.png">

**Comment by Alessandro1970** [comment]
There is no flicker in upper screen with FSUAE on MacOS
<img width="1226" alt="Schermata 2019-12-08 alle 10 32 49" src="https://user-images.githubusercontent.com/34916641/70387522-6354f880-19a6-11ea-9c24-7d1b07e1797f.png">

**Comment by Alessandro1970** [comment]
There is no flicker issue in the upper screen with FSUAE on MacOS:
<img width="1155" alt="Schermata 2019-12-08 alle 10 38 11" src="https://user-images.githubusercontent.com/34916641/70387575-f1c97a00-19a6-11ea-8778-5f59afb79983.png">

**Comment by dirkwhoffmann** [comment]
I think it's just not visible with the default settings in FSUAE which crops the upper area. Can you try again with "Zoom amiga display" set to "Full frame"?

<img width="1052" alt="Bildschirmfoto 2019-12-11 um 14 09 28" src="https://user-images.githubusercontent.com/12561945/70624314-53484d80-1c20-11ea-909d-39e0d085abae.png">

It then looks the same as in UAE (and in vAmiga I think):

<img width="1072" alt="Bildschirmfoto 2019-12-11 um 14 10 57" src="https://user-images.githubusercontent.com/12561945/70624364-6d822b80-1c20-11ea-8932-096e905d8e5f.png">
 
BTW, this game is damned hard 😳. I didn't manage to survive longer than five seconds 😬.
