### ISSUE TITLE
vAmiga crashes before playing Toki

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#238]
vAmiga crashes before playing Toki

[CRASH.TXT](https://github.com/dirkwhoffmann/vAmiga/files/3855369/CRASH.TXT)

[Toki (1991)(Ocean)[cr Defjam][t +4 Setrox].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3855370/Toki.1991.Ocean.cr.Defjam.t.%2B4.Setrox.adf.zip)

**Comment by dirkwhoffmann** [comment]
Same as #194. The Change Recorder overflows, because bus timing is not emulated right.

**Comment by dirkwhoffmann** [comment]
Update (v0.55): 

The intro works well now:

<img width="858" alt="Bildschirmfoto 2020-01-16 um 12 12 35" src="https://user-images.githubusercontent.com/12561945/72520436-c49ba180-3859-11ea-8649-52caabdf18ee.png">

However, vAmiga freezes before the actual game starts:

<img width="858" alt="Bildschirmfoto 2020-01-16 um 12 13 21" src="https://user-images.githubusercontent.com/12561945/72520481-d9783500-3859-11ea-8c40-316e0f3f6b5d.png">

**Comment by dirkwhoffmann** [comment]
Works fine in v0.56 😎.

<img width="913" alt="Bildschirmfoto 2020-01-24 um 18 30 22" src="https://user-images.githubusercontent.com/12561945/73090143-0ff82480-3ed8-11ea-99c6-7207feafe455.png">
