### ISSUE TITLE
Integrate portable68000 as a second CPU core

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#239]
To improve accuracy, vAmiga needs to know how many CPU cycles were already consumed when the CPU performs a memory access. 

Useful links:

Discussion about 68000 microcode: 
http://gendev.spritesmind.net/forum/viewtopic.php?t=1091

Information about the prefetch queue:
http://pasti.fxatari.com/68kdocs/68kPrefetch.html

A cycle-accurate CPU implementation:
https://sourceforge.net/projects/portable68000/

It might be most promising to review the source code of this CPU core first since it must contain all the information we need (although not 100% accurate, because the author derived it from the 68000 patent description).

**Comment by dirkwhoffmann** [comment]
I just did a brief code-review of the portable68000 CPU. Findings: 

1. Source code quality / coding style is good.
2. It has a large set of unit tests which is excellent.
3. Functional quality is an unknown factor (I didn't find any known emulator using this core).
4. It is not as speedy as Musashi (as far as I can tell by just looking at the code).

Here is the plan: 

- Add portable68000 as a second CPU core.
- Add the possibility to run portable68000 side by side with Musashi. 
    This is a *must-have*, because of 3.

Once the core is integrated, vAmiga has full control over CPU bus-timing.

**Comment by dirkwhoffmann** [comment]
Why not contact the author of portable68000 and ask if the version I got from source forge is the most up-to-date one? Unfortunately, I have no contact data. Here is what I know:

Name: 
- PiCiJi

Location: 
- Germany (unfortunately, the country is too large for a brute-force search)

Last signs of life: 
- Checkin on bitbucket.org 15 hours ago
- Post on forum64.de 14 hours ago

I feel a little bit like a stalker now 🙄.  

Does anybody have a source forge, bitbucket or forum64 account to contact him?

**Comment by mithrendal** [comment]
I have one at bitbucket. I will do it 🥴then.

**Comment by mithrendal** [comment]
I found the latest version of the m68000 (2 days old) it is here in this public bitbucket repo of piciji:

https://bitbucket.org/piciji/denise/src/master/emulation/processor/

But I could not manage to send a pm to piciji so that we can tell him that we are planning to use it in vAmiga. I don't understand how to do that on the bitbucket website.  I will keep investigating how to contact him ...

**Comment by mithrendal** [comment]
It looks like piciji just made this bitbucket repo public two days ago ... He forgot to enable issues. So I can not write him anything... I will try the forum64.de ...

**Comment by dirkwhoffmann** [comment]
> I found the latest version of the m68000 (2 days old)

He is actively working on it. The committed version even has 68010 and 68020 support 🤩. This makes it more important to contact him, because we need a stable version to start with...

>  I will keep investigating how to contact him...

I don't know if it helps, but I used to play this one a lot:

<img width="441" alt="Bildschirmfoto 2019-11-17 um 15 51 39" src="https://user-images.githubusercontent.com/12561945/69009111-aba66b00-0952-11ea-8e82-8e5bad1c8a0a.png">

I learned that Mister X usually tries to escape by subway when the detectives are close (I mean we already discovered him on bitbucket with just two days delay, so he can't be far 👮🏻‍♂️)

**Comment by mithrendal** [comment]
He calls it Denise v1.0.6. This beast should also emulate an Amiga and it looks like it is also meant to be used on OSX as he writes something about supporting Mojaves darkmode .... Wow what a surprise 😲... We were true when we said 10 months ago that today everybody is writing new Amiga emulators... 😃

**Comment by dirkwhoffmann** [comment]
> We were true when we said 10 months ago that today everybody is writing new Amiga emulators...

But the log in 1.0.2 says:

> added floppy 1541-II support
> support for d64, g64 images

This is all C64 stuff. But the CPU is a Motorola 68k. Does it emulate both in one app? 😳

**Comment by dirkwhoffmann** [comment]
> I will take the bus to picadelly circus ...

I hope he doesn't have one of those left 😬:

<img width="391" alt="Bildschirmfoto 2019-11-17 um 16 18 42" src="https://user-images.githubusercontent.com/12561945/69009502-fc6b9300-0955-11ea-9552-6b4713758e3c.png">

**Comment by mithrendal** [comment]
I am reading on the c64 forum this thread 

https://www.forum64.de/index.php?thread/82277-denise-1-0-x-emulator/&pageNo=6

It looks like that picji aims to emulate both systems in one app ...

I will make a new account and then I will tell him that vAmiga is looking for another CPU core right ? And that he should enable issues in bitbucket 😉!

**Comment by dirkwhoffmann** [comment]
> It looks like that picji aims to emulate both systems in one app ...

😳 

I am really curious if this is going to work out. I once told Alessandro that this is impossible, because he had the same idea.

> I will make a new account and then I will tell him that vAmiga is looking for another CPU core right ?

Yes, we badly need his CPU core 🤤.

**Comment by mithrendal** [comment]
I send the message to the forum ... Now it tells me this ...

> Dieser Beitrag muss zunächst von einem Moderator geprüft und freigeschaltet werden, damit er für alle Benutzer sichtbar wird.

🙄

**Comment by dirkwhoffmann** [comment]
> Dieser Beitrag muss zunächst von einem Moderator geprüft und freigeschaltet werden, damit er für alle Benutzer sichtbar wird.

😲 What did you write? 

He has plenty of time to escape now 😟. He might well have one of those left: 

<img width="254" alt="Bildschirmfoto 2019-11-17 um 17 11 35" src="https://user-images.githubusercontent.com/12561945/69010180-65a2d480-095d-11ea-9dd1-db40c8b42599.png">

**Comment by dirkwhoffmann** [comment]
> Ok message is online

They have a speedy moderator then.

**Comment by dirkwhoffmann** [comment]
> Ok message is online

Well done, Captain Buck Rogers 🥳

<img width="308" alt="Bildschirmfoto 2019-11-17 um 17 14 58" src="https://user-images.githubusercontent.com/12561945/69010220-dea22c00-095d-11ea-8941-0735cd5879b2.png">

**Comment by mithrendal** [comment]
![877FCEDA-4722-4110-BD4D-91E582EE1287](https://user-images.githubusercontent.com/17108995/69011183-229a2e80-0968-11ea-8012-0ece0cb5f9b5.jpeg)

**Comment by dirkwhoffmann** [comment]
Contact established. Mission accomplished. 👍
