### ISSUE TITLE
Blitter test sblit<n>f and sblit<n>f2 fail

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#240]
I've added test cases that run the Blitter in fill mode. Here is sblit9f: 

UAE: 

<img width="718" alt="sblit9f_uae_ecs" src="https://user-images.githubusercontent.com/12561945/69007663-f3bc9200-0940-11ea-9096-0919d021f8a2.png">

vAmiga: 🙈

<img width="862" alt="sblit9f_vAmiga" src="https://user-images.githubusercontent.com/12561945/69007650-d2f43c80-0940-11ea-9cd1-a941cb6d9d80.png">

I did expect timing to be different, because I haven't yet implemented the magic ancient spells from the rune table excavated by Mithrendal.

But I didn't expect to see the following on a real A500+: 😳

![sblit9f_A500+](https://user-images.githubusercontent.com/12561945/69007627-8f99ce00-0940-11ea-974d-a38e717421a4.jpeg)

Bummer! 

To be honest, I can't really beliebe that UAE has the fill logic wrong, especially because the UAE picture matches what the HRM preaches.

Maybe I have a screwed up test case with uninitialised pointers? But the same test case works well if the fill bit is cleared (which is the only difference between sblit9 and sblit9f. 🤔

**Comment by dirkwhoffmann** [comment]
As expected, I did screw up the test cases. I didn't initialise the BLTREGA to BLTREGC.

Using the updated tests, UAE looks correct: 👍

<img width="718" alt="sblit9f_uae" src="https://user-images.githubusercontent.com/12561945/69447408-bef07680-0d56-11ea-9f8f-e72a2e875672.png">

SAE has timing issues, but computes the correct picture: 👍

<img width="733" alt="Bildschirmfoto 2019-11-22 um 18 38 33" src="https://user-images.githubusercontent.com/12561945/69447706-5a81e700-0d57-11ea-99dc-dc33c71edaf5.png">

vAmiga is broken: 🙈

<img width="862" alt="Bildschirmfoto 2019-11-22 um 18 35 23" src="https://user-images.githubusercontent.com/12561945/69447574-15f64b80-0d57-11ea-801a-c85ba9ac1a9e.png">

**Comment by dirkwhoffmann** [comment]
Almost good now, except for a timing mismatch in the large Emoji blit. The small blits seem to be time accurate.

<img width="879" alt="Bildschirmfoto 2019-12-02 um 15 18 32" src="https://user-images.githubusercontent.com/12561945/69966894-97986700-1517-11ea-91a8-38b9f1de2966.png">

**Comment by dirkwhoffmann** [comment]
Fixed.

Old micro-program for mode 9 fill copy blits: 

                {   // Full execution, fill
                    &Blitter::exec <FETCH_A | FILL | HOLD_D | BUS>,
                    &Blitter::exec <WRITE_D | HOLD_A | HOLD_B | BUS>,
                    &Blitter::exec <REPEAT>,

                    &Blitter::exec <FILL | HOLD_D>,
                    &Blitter::exec <WRITE_D | BUS | BLTDONE>
                }

Bug fix: 

               {   // Full execution, fill
                    &Blitter::exec <FETCH_A | FILL | HOLD_D | BUS>,
                    &Blitter::exec <WRITE_D | HOLD_A | HOLD_B | BUS>,
                    &Blitter::exec <BUSIDLE | REPEAT>,

                    &Blitter::exec <FILL | HOLD_D>,
                    &Blitter::exec <WRITE_D | BUS | BLTDONE>
                }

<img width="835" alt="Bildschirmfoto 2019-12-03 um 16 19 30" src="https://user-images.githubusercontent.com/12561945/70064081-36d95f00-15e9-11ea-9cc5-1d953c6d72f8.png">

**Comment by mithrendal** [comment]
Wow this looks very good! The blitter microprograms are so beautiful. Now the SlowBlitter is in a very good shape. I have to read about the microprograms in the source code now, so interesting stuff...🤓

**Comment by dirkwhoffmann** [comment]
Pursuing a micro-program based approach was the right decision I think. It's so flexible that nearly all oddities of the real machine can be imitated with little effort. Furthermore, there is no real runtime penalty, because it's completely template based. This means that vAmiga doesn't need to interpret the micro-programs at runtime. All programs are "compiled" by the C++ during app building. This is a very strong feature of C++ templates, of which I am a big fan now.
