### ISSUE TITLE
Psygnosis OperationGII hangs after intro screen

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#243]
Psygnosis OperationGII hangs after intro screen.

[Operation GII (19xx)(Psygnosis - Amiga Format)[t +10 Backlash].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3882233/Operation.GII.19xx.Psygnosis.-.Amiga.Format.t.%2B10.Backlash.adf.zip)

Used kick 1.2, 1.3 and 2.05

**Comment by dirkwhoffmann** [comment]
It could well be a disk drive issue, because it loads forever with the head continuously stepping. We should check if it loads in SAE and which drive mode is required if it does . 

Might be a good test case to debug the drive implementation.

**Comment by dirkwhoffmann** [comment]
It's definitely a disk drive issue. Behaviour in vAmiga depends on drive selection:

- Infinite drive: Loads just fine
- Original drive with FIFO buffering: Loads forever, continuous head stepping
- Original drive without FIFO buffering: Loads forever, no head steps at all

Blitter level doesn't matter.

**Comment by dirkwhoffmann** [comment]
Fixed in v0.56 😎.
