### ISSUE TITLE
Kickstart v3.14 rev 46.143 (A500-A1000-A2000) not recognized

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#244]
Hi, could this new A500-A1000-A2000 kickstart be recognized by vAmiga ?

**Kickstart v3.14 rev 46.143 (2018)(Hyperion Ent)(a500-1000-2000)**

**Comment by dirkwhoffmann** [comment]
Sure thing: 

<img width="523" alt="Bildschirmfoto 2019-11-23 um 11 09 30" src="https://user-images.githubusercontent.com/12561945/69477053-eb050980-0de1-11ea-813a-24809e402f86.png">

BTW, I also changed the icon for unknown Roms. I think this one is more sexy: 

<img width="523" alt="Bildschirmfoto 2019-11-23 um 10 58 34" src="https://user-images.githubusercontent.com/12561945/69477060-fc4e1600-0de1-11ea-9c8a-1e71185cd9a6.png">

Is the Hyperion Kickstart very different to the standard 3.14? (Is there a "standard" 3.14? 🤔)

**Comment by Alessandro1970** [comment]
Thanks
No this is the new kick from 2018

**Comment by Alessandro1970** [comment]
hyperion kickstart 3.14 come with workbench 3.14 compatible with Amiga 500/2000 and will let us to use hd without dedicated rom fir booting ! 
Read here please:
http://hyperion-entertainment.com/index.php/where-to-buy/direct-downloads/188-amigaos-314

**Comment by DaitarnIII** [comment]
Kick 3.14 - for A500 - A1000 - A2000
[Kick_314.zip](https://github.com/dirkwhoffmann/vAmiga/files/3891894/Kick_314.zip)

WB3.13 - for A500 - A1000 - A2000
[WB314_Amiga.zip](https://github.com/dirkwhoffmann/vAmiga/files/3891897/WB314_Amiga.zip)

**Comment by Alessandro1970** [comment]
Yes, that is the NEW workbench 3.14 for A500/2000 and it support the 68010 without the need of DECIGEL for compatibility.
I will order a copy of it for my collection.
I think that 3.14 is the best workbench for the Amiga, I like it very much but I have removed the border icon....

![Untitled 2](https://user-images.githubusercontent.com/34916641/69637081-3aed0600-1058-11ea-8302-d271c4282e9c.png)

**Comment by dirkwhoffmann** [comment]
Seems to work fine with the current version of vAmiga 👍: 

<img width="862" alt="Bildschirmfoto 2019-11-26 um 14 30 19" src="https://user-images.githubusercontent.com/12561945/69637650-60c6da80-1059-11ea-80e8-d49328f2d9e0.png">

**Comment by Alessandro1970** [comment]
...so can close ...and remove Daitarn's files... ehm ! ;-)

**Comment by mithrendal** [comment]
Hi allessandro have you typed the „hello dirk“ text on your A2000? Did you buy a 68010?

**Comment by Alessandro1970** [comment]
Yes I have written but not in the A2000 but in my Myster board that supports the 68010 in the FPGA core

**Comment by Alvarez81** [comment]
Hi, is there a Virtualc64/VAMIGA facebook page ?

**Comment by dirkwhoffmann** [comment]
> Hi, is there a Virtualc64/VAMIGA facebook page ?

I've successfully boycotted Facebook so far 🙄.

**Comment by mithrendal** [comment]
Hi alvarez
Isn‘t this not the same as Facebook but without the ads?  I don’t know Facebook and so I am curious what you are missing...

**Comment by dirkwhoffmann** [comment]
> I don’t know Facebook and so I am curious what you are missing...

Isn't Facebook mainly for sharing cat pictures? We can do the same here. See:

![IMG_0208](https://user-images.githubusercontent.com/12561945/69643376-89ec6880-1063-11ea-8a5d-6af230f5049c.jpeg)

**Comment by dirkwhoffmann** [comment]
On the other hand, UAE is already there... 🤔

<img width="1023" alt="Bildschirmfoto 2019-11-26 um 15 57 03" src="https://user-images.githubusercontent.com/12561945/69644840-7c37e280-1065-11ea-8b10-727859269db9.png">

**Comment by Alessandro1970** [comment]
![3233E825-4139-462E-BF08-BEEE7B768B4F](https://user-images.githubusercontent.com/34916641/69662693-270bc900-1085-11ea-8199-a089c7f59ef5.jpeg)

...It’s mine ;-)

**Comment by mithrendal** [comment]
Wow that one is retro-brightened... Except the ears and the nose ...

**Comment by dirkwhoffmann** [comment]
Hyperion Rom is recognised in v0.49.

![IMG_1612](https://user-images.githubusercontent.com/12561945/70023100-a4a86b00-1596-11ea-97c2-d0ce56351c85.jpeg)

**Comment by mithrendal** [comment]
I like the cat’s coloring... 😻
