### ISSUE TITLE
Another mouse buttons problem

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#245]
Cannot play Ork because the intro (trainer) request the **two mouse buttons pressed to exit, as can be read in the floating messages.**
Magic mouse does not works with pressing left and right mouse button at the same time.
Maybe some commands in the menu or in quick virtual keyboard must be implemented to solve this kind of problem, this is an emulator for mac...
The MBP trackpad does not work too.

[Archivio.zip](https://github.com/dirkwhoffmann/vAmiga/files/3882249/Archivio.zip)

...ehe... do not like pc mouses ...BTW could buy one ...but orrible look if left near a MBP

**Comment by mithrendal** [comment]
Maybe an option where cmd+click generates the two presses ?

**Comment by dirkwhoffmann** [comment]
> BTW could buy one ...but orrible look if left near a MBP

OK, I understand that. No PC mouse should come close to a Mac. 🥴

I could try to add Mouse emulation keys which would work the same way as the Joystick emulation keys. One could then bind the right button to, let's say, Alt or Right Shift.

**Comment by Alessandro1970** [comment]
...there was that game, Bermuda Project with menu on RMB

**Comment by dirkwhoffmann** [comment]
This is a visual prototype that shows how it could look like. It was kind of hard to get everything on one panel, so I decided to arrange stuff in columns: 

<img width="692" alt="Bildschirmfoto 2019-11-24 um 16 50 54" src="https://user-images.githubusercontent.com/12561945/69497211-bcb72500-0eda-11ea-8e15-64b1fa688dc3.png">

**Comment by dirkwhoffmann** [comment]
Seems to work fine in v0.49. Please reopen if I am mistaken.

BTW, this game has very cool parallax effects 😎:

<img width="835" alt="Bildschirmfoto 2019-12-03 um 16 28 01" src="https://user-images.githubusercontent.com/12561945/70064630-24abf080-15ea-11ea-9eb2-aeaa5c5fb12c.png">

I still have to figure out how to shoot the armoured turtles (like the one next to me). 🤔 

<img width="835" alt="Bildschirmfoto 2019-12-03 um 16 28 57" src="https://user-images.githubusercontent.com/12561945/70064862-82403d00-15ea-11ea-91e1-70ab01f19899.png">
