### ISSUE TITLE
Switchblade II hangs before playing

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#246]
Switchblade II hangs before playing and the disk light is flashing.
[Switchblade II (1991)(Gremlin)[cr CPY][t +6 Setrox].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3882275/Switchblade.II.1991.Gremlin.cr.CPY.t.%2B6.Setrox.adf.zip)

<img width="882" alt="Schermata 2019-11-23 alle 09 49 33" src="https://user-images.githubusercontent.com/34916641/69476180-da9b6180-0dd6-11ea-9585-0ff51a44ce19.png">

**Comment by dirkwhoffmann** [comment]
Produces a Guru in Blitter mode 0: 

<img width="765" alt="Bildschirmfoto 2019-12-01 um 12 49 55" src="https://user-images.githubusercontent.com/12561945/69913571-824d0b00-1439-11ea-8ebf-f87bd32b820c.png">

We should check whether it runs in SAE with option "Immediate Blitter".

**Comment by dirkwhoffmann** [comment]
Update: 

- There is a sound issue, way before the emulator hangs. 
- Works in SAE with lowest compatibility settings (immediate Blitter + turbo drive). 
- Audio IRQs are enabled which suggests the games utilises manual mode for audio playback. 

<img width="980" alt="Bildschirmfoto 2020-02-02 um 07 36 00" src="https://user-images.githubusercontent.com/12561945/73604321-f5384680-458e-11ea-8525-be0186a58087.png">

**Comment by dirkwhoffmann** [comment]
Commit 68fd9a8ba554d664ecc4b8c3120b08a84b6894df (timing-accurate audio) seems to fix the entire issue 😎.

<img width="910" alt="Bildschirmfoto 2020-02-15 um 07 51 46" src="https://user-images.githubusercontent.com/12561945/74583551-5ec14780-4fc8-11ea-9ffe-6b7d06c375ba.png">
