### ISSUE TITLE
Rubicon hangs 

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#247]
Rubicon hangs before leaving trainer-screen:

[Archivio.zip](https://github.com/dirkwhoffmann/vAmiga/files/3882283/Archivio.zip)

<img width="822" alt="Schermata 2019-11-23 alle 10 00 58" src="https://user-images.githubusercontent.com/34916641/69476273-62ce3680-0dd8-11ea-94a6-8b7287fe0565.png">

**Comment by dirkwhoffmann** [comment]
You need to push both mouse buttons to continue 🤭. What did the game and demo designers think back in the days? 🤔

<img width="879" alt="Bildschirmfoto 2019-12-01 um 12 31 51" src="https://user-images.githubusercontent.com/12561945/69913378-5892e480-1437-11ea-897a-93317ac1957c.png">

The game itself is playable, but exhibits some graphics glitches: 

<img width="879" alt="Bildschirmfoto 2019-12-01 um 12 35 20" src="https://user-images.githubusercontent.com/12561945/69913387-67799700-1437-11ea-9e98-e890e1f414d8.png">

Fortunately, keyboard emulation for mouse buttons is already implemented and will be available in the next release.

**Comment by dirkwhoffmann** [comment]
Graphics errors seem to be gone in v0.55. Cool game btw.
