### ISSUE TITLE
Extended rom

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#248]
Hi,
I have searched for this two Aros Roms:
aros-rom.bin
aros-rom 2.bin

[Archivio.zip](https://github.com/dirkwhoffmann/vAmiga/files/3882318/Archivio.zip)

But vAmiga does not recognize them, which roms do you have used ?
Where can be found ?

<img width="818" alt="Schermata 2019-11-23 alle 11 00 09" src="https://user-images.githubusercontent.com/34916641/69476947-741b4100-0de0-11ea-82bc-5433592a30cf.png">

Rif:
If you have MAPROM style hardware, or want to burn an
EEPROM, you can use the aros-rom.bin and aros-ext.bin
files. Both 512K images must be present in the Amiga
address space as follows:

  0xE00000 **aros-ext.bin**  (512K)
  0xF80000 **aros-rom.bin**  (512K)

**Comment by dirkwhoffmann** [comment]
The thing is, there are *many* Aros Roms around, maybe as many as there are nightly builds. To be honest, I am pretty disappointed how the Aros project is organised. There doesn't seem to be a place where stable, clearly revisioned Roms can be downloaded. Or maybe I'm just not smart enough to find this place. 

The Roms which I bundled with the emulator are labeled SVN 55696. I don't really remember where I found them 🙄. Most likely from the server where SAE is hosted.
