### ISSUE TITLE
Test programs

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#25]
I've found a couple of example programs that could help to debug the emulator: 

https://github.com/alpine9000/amiga_examples

However, I did not manage to compile the examples down to an ADF. Maybe it has to be compiled under Windows (don't know). 

Could somebody try to compile this? The result will be one or more ADFs.

**Comment by mithrendal** [comment]
me, me ...🙋🏿I like to do that !

**Comment by mithrendal** [comment]
I had a look at it. There is no need to build them. The binaries (ADF file) are already in the bin drawer of each example. What I like the most is, that you can run each example with just a click in SAE. Great.

**Comment by dirkwhoffmann** [comment]
> are already in the bin drawer of each example

Oooohhhhh, there is a bin drawer 😯🤭. How embarrassing 🙈. I swore it wasn't there yesterday. It may have appeared overnight. No? 🙄

**Comment by mithrendal** [comment]
But the site is great. He covers a lot of different hardware aspects.  We could let vAmiga exercise all tests and visually compare to SAE. Will it already pass 50% of them ? 😬 What is your bet ?

**Comment by dirkwhoffmann** [comment]
My bet is 20% (I didn't run any of the test cases yet).

**Comment by mithrendal** [comment]
Me neither did the tests. To win I should better bet 19% or 21% 🧐. But my bet is that will get 40% of the tests passed when being not too strict in judging differences.

**Comment by dirkwhoffmann** [comment]
Another testing software (we need more of those): 

<img width="929" alt="Screenshot 2019-06-15 at 12 39 51" src="https://user-images.githubusercontent.com/12561945/59550416-e56de280-8f6a-11e9-8c6a-39fdd12c8155.png">

😯 something wrong with my loopback cable? How does it read the Ring Indicator pin (RI)? Thought it's not accessible by SW.

<img width="929" alt="Screenshot 2019-06-15 at 12 39 27" src="https://user-images.githubusercontent.com/12561945/59550421-f585c200-8f6a-11e9-9732-133bcf658247.png">

**Comment by mithrendal** [comment]
Here is another one. 😃
[A500+A2000 Systest v9.1 (19xx)(-)[cr A-ha].zip](https://github.com/dirkwhoffmann/vAmiga/files/3293386/A500%2BA2000.Systest.v9.1.19xx.-.cr.A-ha.zip)
