### ISSUE TITLE
Karateka hangs

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#250]
Karateka hangs, it works on winuae (I think 1mb chip ram is needed)

[Karateka.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3906907/Karateka.adf.zip)
<img width="802" alt="Schermata 2019-11-30 alle 09 35 45" src="https://user-images.githubusercontent.com/34916641/69898109-02e60b80-1355-11ea-828a-053cf3daa0b7.png">

On winuae:
![image](https://user-images.githubusercontent.com/34916641/69898114-109b9100-1355-11ea-8ef9-0c27d1c26718.png)

**Comment by dirkwhoffmann** [comment]
I remember this game 😍. We need to get it working!

Development is somewhat stalled at the moment. To bring vAmiga to the next level, I think a custom CPU implementation is needed. Currently, I am investigating the best approach for this.

**Comment by mithrendal** [comment]
I remember the game from the c64 it has never been ported to the Amiga until recently by the EAB member meynaf. 

http://www.indieretronews.com/2016/02/karateka-meynaf-wows-amiga-community.html?m=1

But be aware this is not a real port rather an emulation. Its emulationlayer mocks a AtariST screenbuffer (I guess therefore it needs more chipram) and copies it to Amiga bitplanes. The sound emulation is also pretty simple as the soundchip in the ST was very limited. 

But still an awesome experiment and a great result I watched the youtube video. 

And again we have to rescue a princess. 👸🏻

**Comment by dirkwhoffmann** [comment]
>  it has never been ported to the Amiga until recently 

😳 This means I must know the game from the C64, too. 

> The object of the game is to rescue the princess Mariko who has been kidnapped by the evil Akuma who has also destroyed your homeland.

So many princesses to rescue 🥵. Yet I didn't manage to rescue the one from Defender of the Crown. I'm just not good enough at swordplay. And there is no auto-fire mode for the mouse 😟.

**Comment by dirkwhoffmann** [comment]
<img width="879" alt="Bildschirmfoto 2019-12-01 um 12 22 23" src="https://user-images.githubusercontent.com/12561945/69913225-592a7b80-1435-11ea-9135-ad7d0476132a.png">

What is V39+? 🤔

"May run on 68000" doesn't sound very promising either. In software engineering, "May run" usually means "Will definitely not".

**Comment by mithrendal** [comment]
V39.  Must be the kickstart versionnumber. I think 1.3 was V34. So maybe this one needs kick2.0 or above.

**Comment by mithrendal** [comment]
Correction it needs at least something above 3.0 🤭 It seems the emulation layer for the atariST is taking its price. 



![FCC2E908-C3F6-41C8-A10A-1B723E2A409A](https://user-images.githubusercontent.com/17108995/69918740-2ce31f00-1476-11ea-9ebf-e1b6eef13b6c.png)

**Comment by dirkwhoffmann** [comment]
I tried to run the game with latest Hyperion Rom and 1 MB Chip + 512 KB Slow in UAE. After the Broderbund intro screen, I get a read write error 🤭:

<img width="719" alt="Bildschirmfoto 2019-12-02 um 07 35 08" src="https://user-images.githubusercontent.com/12561945/69935978-b75b6b00-14d6-11ea-9ad5-79133b98b91e.png">

Alessandro, which Rom did you use?

**Comment by Alessandro1970** [comment]
Kick 1.3 
512kb chip
512kb slow
Try different blitter accuracy
Increase cpu speed ...and wait

**Comment by mithrendal** [comment]
I tried it in FSUAE3.0.2 and it worked only with the hyperion thing. I tried it with a 68000 which was so slow that it seemed to load endless, music played way to slow. After that I tried a 68030 and that played very fluently. But no checksum error...

When I try Kickstart1.2 and 68030 I get the unknown command message as in the first post o this issue.

**Comment by dirkwhoffmann** [comment]
> Only 68030 upwards is playable very fluently

Shouldn't we rather close this then and play the original in VirtualC64? 🤔

<img width="916" alt="Bildschirmfoto 2019-12-03 um 16 44 36" src="https://user-images.githubusercontent.com/12561945/70066213-9b49ed80-15ec-11ea-85c5-9917e50ad241.png">

**Comment by mithrendal** [comment]
>Shouldn't we rather close this then and play the original in VirtualC64? thinking

Yes I am with you. This ST emulation layer for the Amiga from meynaf is technically very cool but not the orignal... Also it is very demanding in terms of Amiga Hardware ... vAmigas current scope is a different one...
