### ISSUE TITLE
Slow Blitter / Fast Blitter mismatch

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#252]
[sblittmp.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3908416/sblittmp.adf.zip)

To reproduce:

1. Launch vAmiga with Blitter accuracy 2. The following (wrong) image comes up:

<img width="879" alt="Bildschirmfoto 2019-12-01 um 17 10 51" src="https://user-images.githubusercontent.com/12561945/69916686-542df200-145e-11ea-8631-124e795a9a97.png">

2. Switch to accuracy level 0. The image rectifies:  

<img width="879" alt="Bildschirmfoto 2019-12-01 um 17 11 00" src="https://user-images.githubusercontent.com/12561945/69916687-5e4ff080-145e-11ea-99fd-3c0d7a08b877.png">

Image doesn't switch back when accuracy level is reset to 2. This is a strong indication for an initialisation issue. 

Most likely related to #240

**Comment by dirkwhoffmann** [comment]
There is already a discrepancy while the ADF is being loaded:

<img width="1348" alt="Bildschirmfoto 2019-12-01 um 17 58 25" src="https://user-images.githubusercontent.com/12561945/69917294-a4a84e00-1464-11ea-8e22-5e27975c33ff.png">

**Comment by dirkwhoffmann** [comment]
Now it's getting creepy. Different values in INTENA 🧟‍♂️.

<img width="1214" alt="Bildschirmfoto 2019-12-01 um 18 18 01" src="https://user-images.githubusercontent.com/12561945/69917544-8c85fe00-1467-11ea-938d-6906a6d843d9.png">

**Comment by mithrendal** [comment]
it differs in the "Blitter has finished" bit 
this is the sixth bit

**Comment by dirkwhoffmann** [comment]
I think I nailed it. Let's reconsider how the Blitter works: 

![blitter](https://user-images.githubusercontent.com/12561945/69918130-8e06f480-146e-11ea-9afb-60c5c999903c.gif)

In my test case, channel B is disabled. As a result, my slow Blitter doesn't run the pipeline part on data path B which means that an outdated value in "B hold" is fed into the minterm logic. 

Here is my microprogram log:

<img width="1214" alt="Bildschirmfoto 2019-12-01 um 19 12 12" src="https://user-images.githubusercontent.com/12561945/69918154-ca3a5500-146e-11ea-8c41-26b6cbf8030f.png">

When I run the fast Blitter in between, "b hold" got updated and the bug vanished.

I need to modify my Blitter micro-programs such that all pipeline stages are run even if certain channels are disabled. 

If we're lucky, this bug is the root cause of other bugs as well 😄. At least I hope so...

**Comment by dirkwhoffmann** [comment]
Once identified, the fix was easy.

This microprogram 

                {   // Full execution, no fill
                    &Blitter::exec <FETCH_A | HOLD_D | BUS>,
                    &Blitter::exec <WRITE_D | HOLD_A  | BUS | REPEAT>,

                    &Blitter::exec <HOLD_D>,
                    &Blitter::exec <WRITE_D | BUS | BLTDONE>
                }

had to be replaced by this one:

                {   // Full execution, no fill
                    &Blitter::exec <FETCH_A | HOLD_D | BUS>,
                    &Blitter::exec <WRITE_D | HOLD_A | HOLD_B | BUS | REPEAT>,

                    &Blitter::exec <HOLD_D>,
                    &Blitter::exec <WRITE_D | BUS | BLTDONE>
                }

There was another bug though. With channel D disabled, my Slow Blitter never cleared the BZERO flag 🙄. 

P.S: The INTENA issue was a false alarm. Kickstart is changing INTENA multiple times and choosing the Slow Blitter has the effect that debug output is generates at very different cycle counts.
