### ISSUE TITLE
More precise IRQ timing

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#257]
Here is the thing: "Shadow of the Beast I" stopped launching with commit c0f2 which introduced an IRQ delay of one instruction. This delay has been added to make Freud launch. If I revert to the old IRQ handler, Shadow launches, but Freud hangs. 

This shows how crucial IRQ timing is for certain games. It also shows that neither the old nor the current implementation is 100% timing accurate.

The issue will (hopefully) resolve itself once vAmiga got a custom CPU that provides us with more control over IRQ timing than Musashi does.

With Shadow and Feud, we have at least two test cases to verify the new implementation.

**Comment by dirkwhoffmann** [comment]
Solved in v0.55.

**Comment by mithrendal** [comment]
cool both games at once ? Betting on Moira was a good choice ... 🤓
