### ISSUE TITLE
No kickstart screen

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#258]
With the new release 0.49.1 I cannot see the kickstart image at boot (booting without any disk in), only white screen (kick 1.3, kick 3.1 and 3.14).
<img width="805" alt="Schermata 2019-12-08 alle 10 02 29" src="https://user-images.githubusercontent.com/34916641/70387175-07887080-19a2-11ea-97a4-c9bf4e17133d.png">

<img width="806" alt="Schermata 2019-12-08 alle 10 04 39" src="https://user-images.githubusercontent.com/34916641/70387192-31419780-19a2-11ea-90fb-1cbf91443330.png">

**Comment by Alessandro1970** [comment]
I removed preference file from Library but none, I cannot load any games with this new version.

**Comment by dirkwhoffmann** [comment]
I think I introduced a bug when switching to the MTKViewDelegate design pattern. The screen should reappear when the window gets resized.

**Comment by Alessandro1970** [comment]
Yes, manual resize:

<img width="821" alt="Schermata 2019-12-08 alle 10 19 58" src="https://user-images.githubusercontent.com/34916641/70387326-4e776580-19a4-11ea-93eb-0201ebeac554.png">

**Comment by dirkwhoffmann** [comment]
Manual resizing should no longer be necessary in v0.55. Please reopen if I am wrong.
