### ISSUE TITLE
Sword and the rose hangs

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#259]
Sword and the rose hangs after intro screen.
[Sword and the Rose, The (1990)(Codemasters)[cr Mayhem][t +2 LGD - Masters].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3936070/Sword.and.the.Rose.The.1990.Codemasters.cr.Mayhem.t.%2B2.LGD.-.Masters.adf.zip)

**Comment by dirkwhoffmann** [comment]
Works well in v0.55 😎

<img width="967" alt="Bildschirmfoto 2020-01-15 um 16 31 55" src="https://user-images.githubusercontent.com/12561945/72446913-b5aee380-37b4-11ea-92bf-4283a5914931.png">
