### ISSUE TITLE
UAE CPU tester

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#262]
I'm trying to get "cputester" to work, but I didn't succeed yet.

What I did: 

- Edit `cputestgen.ini`
    - I had to reduce the memory size (`test_memory_size=0x1c000`) because otherwise, the generated memory contents files are too large to fit onto a single ADF.
- Run `cputestgen.exe` in Windows
- Create an ADF via xdftools:
    - `xdftool cputester.adf format cputester`
    - `xdftool cputester.adf write data`
    - `xdftool cputester.adf write cputest`
    - `xdftool cputester.adf boot install`

- Run UAE with that ADF
    - When the DOS proms comes up, I typed `cputest test.b' 
    - An error message comes up 🙈

<img width="717" alt="Bildschirmfoto 2019-12-30 um 08 46 52" src="https://user-images.githubusercontent.com/12561945/71572879-76f50a00-2ae1-11ea-8b4a-b8541b10f66b.png">

When I run `cputestgen.exe`, it already told me that 0 tests were being generated for each command. Hence, something must be wrong with my `cputestgen.ini` file 😢.

**Comment by mithrendal** [comment]
>Run cputestgen.exe in Windows

My plan was yesterday to test it too, but I failed because I have only a windows XP installation... And CPU tester don't like to run in WindowsXP... So I am already stuck here...

If  you upload the CPUtester generated files here, I can try to test it with FS-UAE and put it on a harddisk ...
