### ISSUE TITLE
CPU test or.w fails

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#265]
- The good: 
    Moira can boot the workbench with no issues now and the performance decrease is hardly noticeable 😎.

<img width="737" alt="Bildschirmfoto 2020-01-03 um 15 48 10" src="https://user-images.githubusercontent.com/12561945/71731005-f0735c00-2e43-11ea-91fe-0c19d877f7ce.png">

- The bad: 
    CPU test or.w (the only test I have at the moment) fails 🙈:

<img width="862" alt="Bildschirmfoto 2020-01-03 um 16 03 13" src="https://user-images.githubusercontent.com/12561945/71730854-95da0000-2e43-11ea-8258-fe18df2fe8fa.png">

- The ugly: 
    It's almost certainly not the OR instructions itself, but the surrounding testing code. There are some features of the M68000 CPU that are not implement yet such as tracing. Maybe the cputest frameworks makes use of it. Don't know 🤔.

**Comment by tonioni** [comment]
Most likely illegal instruction exception stacked PC field is wrong.

Tester logic is technically simple and does not require any CPU special features:

Take over the system, jump to supervisor mode, fill test memory regions, fill registers, set all exception vectors, fill both stacks, push test SR and PC to super stack, execute RTE -> test instruction is executed (generally in user mode), following instruction is $4afc (ILLEGAL) (this is simplified, in reality it alternates between NOP,ILLEGAL and ILLEGAL,NOP because it can make a difference when previous instruction caused bus or address error..), used exception vector is stored, registers are stored (and few other things).

Finally results are compared against expected values in dat file.

**Comment by mithrendal** [comment]
Musashi executes the test with a positive result ?

Is it possible to stop at the pc=30800

![grafik](https://user-images.githubusercontent.com/17108995/71734314-f66d3b00-2e4b-11ea-9526-974d76014d65.png)

and compare the CPU state/output values with the Musashi core ?

**Comment by dirkwhoffmann** [comment]
> Most likely illegal instruction exception stacked PC field is wrong.

Hi Toni,

yes, this perfectly makes sense. My test program for Moira (applied for unit-testing) runs Moira agains Musashi for each possible opcode with pseudo-randomly generated extensions words. And indeed, I am skipping all unused and illegal instructions in this loop. I’ll look into it asap. 

Let me take the chance to thank you once again for writing cputester. It comes with the perfect timing for me. It was just a couple of weeks ago when I took the decision to write a custom CPU for vAmiga and since then I’ve been racking my brain trying to figure out the right way to test it. Now, it’s clear which is the right way to.

**Comment by dirkwhoffmann** [comment]
> and compare the CPU state/output values with the Musashi core ?

This is the brute-force way to find the bug (in the (unlikely) event that it's not related to the illegal instruction exception). To make testing easier, Moira has a "Musashi compatibility" mode which emulates some of Musashi's quirks (wrong cycle numbers etc.). Using this mode,  I can basically run vAmiga up to an arbitrary cycle number (one run with Musashi and one run with Moira) and see where the execution trace starts to differ. The only issue with this approach it that's it's time consuming. I cannot simply dump the complete instruction trace into a file because of it's bare size.

**Comment by dirkwhoffmann** [comment]
As predicted by Toni, I was pushing a wrong PC to the stack. Now, it works perfectly well 😎:

<img width="862" alt="Bildschirmfoto 2020-01-04 um 11 03 34" src="https://user-images.githubusercontent.com/12561945/71763937-73e38a80-2ee2-11ea-9d38-3331ac00b9f6.png">

<img width="862" alt="Bildschirmfoto 2020-01-04 um 11 03 39" src="https://user-images.githubusercontent.com/12561945/71763941-7645e480-2ee2-11ea-82fd-3ca6b990f3fb.png">

As a side effect of updating my Musashi/Moira test runner, I have found three more Musashi bugs (already reported to them).
