### ISSUE TITLE
Moira on Raspberry Pi

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#268]
Has someone got a working Raspberry Pi toolchain installed? 

It would be interesting to see if Moira compiles out of of the box and if the test runner could be executed on the Raspberry (I am wondering how fast it would be 🤔). I have no plans to port vAmiga to the Raspberry, but I'd like to make Moira as portable as possible.

https://github.com/dirkwhoffmann/Moira

**Comment by dirkwhoffmann** [comment]
Here are some interesting runtime results:

With the latest version on Moira, it seems I have achieve the impossible: to outperform Musashi.

Moira on macOS (clang compiler, -O3): 😎  

<img width="967" alt="Bildschirmfoto 2020-01-12 um 15 31 34" src="https://user-images.githubusercontent.com/12561945/72220453-0920f780-3551-11ea-94a4-74d0994f7fa6.png">

Moira on Linux (gcc compiler, -O3): 😎

<img width="861" alt="Bildschirmfoto 2020-01-12 um 15 28 31" src="https://user-images.githubusercontent.com/12561945/72220461-1a6a0400-3551-11ea-9c1e-2851eb5852bb.png">

Moira on Windows (VisualStudio, release mode, runtime optimisation enabled): 😲

![visualStudio](https://user-images.githubusercontent.com/12561945/72220472-29e94d00-3551-11ea-8640-79e6dcefb8fd.jpg)

On Windows, Moira runs 50% slower than Musashi 🙈. How can that be? 🤔

BTW, when looking at absolute numbers, my old gaming PC still seems to be a performance beast compared to my MacBook Pro. So sad that it runs Windows, only.

Maybe I configured something wrong in VisualStudio. I am not familiar with it and had to google each and every step to make it (finally) compile my project.

**Comment by mithrendal** [comment]
Good news for the climate on mother earth. 😎👍🏻

Do you think it is possible to compile it to webassembly (wasm) ? maybe moira runs faster then the cpu of SAE?

**Comment by dirkwhoffmann** [comment]
I have trouble installing it on macOS Mohave. 

I grabbed it via `brew install emscripten` which worked out fine. After completion, it told me:

```
Manually set LLVM_ROOT to
  /usr/local/opt/emscripten/libexec/llvm/bin
and comment out BINARYEN_ROOT
in ~/.emscripten after running `emcc` for the first time.

```

I did exactly this, but when I run `emcc hello.c`, it terminates with an error message 😕:

```
...
cache:INFO: generating system asset: generated_struct_info.json... (this will be cached in "/Users/hoff/.emscripten_cache/asmjs/generated_struct_info.json" for subsequent builds)
cache:INFO:  - ok
shared:ERROR: BINARYEN_ROOT must be set up in .emscripten

```

Have you been more successful on your machine?

**Comment by dirkwhoffmann** [comment]
Installing on Linux Mint was much easier, so I tried to compile Moira there. Running emcc worked and it produced `a.out.js` and `a.out.wasm`. However, running `node a.out.js` aborts with an error 😢:

<img width="857" alt="Bildschirmfoto 2020-01-12 um 17 54 11" src="https://user-images.githubusercontent.com/12561945/72222439-f3b5c880-3564-11ea-862f-7ffdbbf6728a.png">

Some local count is too large. Any ideas? 🤓

**Comment by dirkwhoffmann** [comment]
OK, compiling with -O1 did the trick (I started with -O0):

<img width="857" alt="Bildschirmfoto 2020-01-12 um 18 05 18" src="https://user-images.githubusercontent.com/12561945/72222553-46dc4b00-3566-11ea-8133-b3547c2d0465.png">

I should be able to execute it Chrome, right?

**Comment by dirkwhoffmann** [comment]
OK, it worked. I can run Moira inside Chrome and I can see the output in the debug console:

<img width="1017" alt="Bildschirmfoto 2020-01-12 um 18 17 58" src="https://user-images.githubusercontent.com/12561945/72222691-0382dc00-3568-11ea-8c6b-79f049b3af17.png">

But please remind me. Why exactly are doing this? 🙄

**Comment by dirkwhoffmann** [comment]
Runtime comparison Web Assembly with `-flto -O3`: 

<img width="858" alt="Bildschirmfoto 2020-01-12 um 18 28 44" src="https://user-images.githubusercontent.com/12561945/72222870-a12adb00-3569-11ea-84c9-18b93dc17c30.png">

Moira feels like a lame duck against Musashi here... 🐥

**Comment by mithrendal** [comment]
Oh sorry, I am back just now. I was disturbed by my 👫...
>But please remind me. Why exactly are we doing this? 🙄

Yes it was only a question whether it is possible. But you just proved it, by doing it, nice. 
I had in mind to maybe investigate to convert vAmiga into a Webapp which draws itself into a HTML5 canvas. It is much quicker as I thought. Do I interprete the values right, when I say that webasm does the job quicker than  on macos ?? Oh no you did run that webasm version on your faster PC right, but still nearly catches up the values of the visual studio version...

**Comment by dirkwhoffmann** [comment]
> Oh no you did run that webasm version on your faster PC right

No, I did run it on my MacBook (Linux Mint runs on my MacBook in a VM and Chrome runs natively). It's almost certainly impossible that the webasm version runs faster. Hence, I expect that the timing measuring code is unreliable (at least when comparing the numbers across machines or operating systems).

**Comment by mithrendal** [comment]
>Have you been more successful on your machine?

I have an older version of emscripten on macos, which I downloaded two years ago and it is still working fine, never upgraded. I downloaded it back then directly from the projects site. But today I would also go the brew way...

I think webasm conversion is interesting but I do feel much more interested in seeing Moira fly in vAmiga now. Maybe I come back to the webasm stuff later. You have done such a huge step in completing a custom CPU which computes in a much more compatible way. Now I want to test out the Moira-Advantage on all those good and problematic games. What do you plan as the next steps ? Maybe to complete the slowBlitter Integration ?

**Comment by dirkwhoffmann** [comment]
> I think webasm conversion is interesting but I do feel much more interested in seeing Moira fly in vAmiga now.

Yes, that's my feeling too. I think Moira is well tested by now and probably the most reliable vAmiga component at the moment. 

> What do you plan as the next steps ?

The next natural step will be to implement bus sharing between Moira, Agnus, and the Blitter. Theoretically, it should be easy, because there are only two things to do:

- Add code to `Moira::sync()` that executes Agnus to the point in time the CPU has already reached. Now, since we have Moira instead of Musashi, the exact target cycle is known.
- If Chip or Slow Ram is accessed, check if the bus is free. If it isn't, execute Agnus until it is. The elapsed extra cycles are the wait states that have to be added to the CPU clock.

After that, all timing related vAmiga tests should be rerun. This will be the moment of truth. The outcome of these tests will tell us where the vAmiga project really stands.

**Comment by dirkwhoffmann** [comment]
Here are the results of the first medical examination. Pulse readings (aka interrupt timing) indicate that Moira is quite a healthy girl:

vAmigaTS test case Paula/INT/int1: 

Amiga 500 🥰:

![int1_A500_8A](https://user-images.githubusercontent.com/12561945/72357066-a2374600-36ea-11ea-9557-c6a97e4d3973.jpeg)

vAmiga (Musashi) 🤭:

<img width="892" alt="Bildschirmfoto 2020-01-14 um 16 25 57" src="https://user-images.githubusercontent.com/12561945/72357137-c2ff9b80-36ea-11ea-946f-2b904194afac.png">

vAmiga 0.55 (Moira) 😎:

<img width="892" alt="Bildschirmfoto 2020-01-14 um 16 25 33" src="https://user-images.githubusercontent.com/12561945/72357185-d6126b80-36ea-11ea-9e9d-61a2615909c7.png">

**Comment by mithrendal** [comment]
only Moiras last line does not match the original output, I am now looking into the test program ...

**Comment by dirkwhoffmann** [comment]
I didn't look into the test case in detail yet, but the faulty line could also be related to Paula. When INTENA or INTREQ are written, it needs some time until the new IRQ level shows up on the IPL pins of CPU. It might well be that the current delay is wrong by a cycle or two. Also, it might make a difference whether the CPU or Copper writes into those registers.
