### ISSUE TITLE
Bugs in Paccer

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#27]
All bugs that have been spotted so far are related to sprites: 

- Upper right sprite shouldn't be visible on startup (outside visible range)
- Sprite colors are wrong (all ghosts are drawn with the same color, Pacman should be yellow)
- From time to time, there are graphics glitches (Sprites do not get switched off after they were drawn. They are drawn in vertical stripes until the vblank area is reached). 

<img width="1030" alt="Screenshot 2019-05-19 at 09 52 06" src="https://user-images.githubusercontent.com/12561945/57979315-698c8300-7a1c-11e9-89eb-33bc9b4088e9.png">

**Comment by dirkwhoffmann** [comment]
Sprite colors are fixed. 

<img width="1030" alt="Screenshot 2019-05-20 at 08 13 37" src="https://user-images.githubusercontent.com/12561945/58014433-1b997d00-7af9-11e9-94f7-f77cb239413b.png">

**Comment by mithrendal** [comment]
Is this a multiplayer game?

**Comment by dirkwhoffmann** [comment]
No multiplayer, but the best PacMan clone ever. I've implemented it myself exactly 30 years ago (😯). This was the time when I learned how to program in C. I remember that I did not exactly understood the difference between x.y and x->y, so I ended up trying all possible combinations until the compiler accepted it 😅. It's on Fish 223 (best Fish disk ever 😎).

Somebody even made a long play video on Youtube: 

https://www.youtube.com/watch?v=gJi6lUTIamw

He really solved all levels 😳 (which I always thought to be impossible).

**Comment by mithrendal** [comment]
The player in the longplay plays incredibly good. Awesome ! Personally I like the blue level the most... ;-)

**Comment by dirkwhoffmann** [comment]
Narrowing down graphics bug: Bug usually occurs when PacMan eats a pill (culprit: sound ?!). In that case, Bitplane DMA gets switched off, but sprite DMA remains: 

<img width="649" alt="Screenshot 2019-05-20 at 15 39 47" src="https://user-images.githubusercontent.com/12561945/58026080-03842680-7b16-11e9-8a03-2fcd2e33f0aa.png">

Todo: Check DMA table handling code. 

BTW, the screenshot reveals how the Amiga stores sprites in memory. The first line is the control line containing the trigger coordinates. After that, graphics data follows.

**Comment by dirkwhoffmann** [comment]
Symptom is due to a huge bug in Agnus::updateJumpTable(int16_t to)

    // Build the jump table
    uint8_t next = dmaEvent[to+1];
    for (int i = to; i >= 0; i--) {
        nextDmaEvent[i] = next;
        if (dmaEvent[i]) next = i;
    }

must be: 

    // Build the jump table
    uint8_t next = nextDmaEvent[to];
    for (int i = to; i >= 0; i--) {
        nextDmaEvent[i] = next;
        if (dmaEvent[i]) next = i;
    }

Considering the severity of this error, it is a miracle that the emulator is already running so well.
