### ISSUE TITLE
Bitplane DMA bug

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#28]
Symptom: 

<img width="1030" alt="Screenshot 2019-05-20 at 12 15 13" src="https://user-images.githubusercontent.com/12561945/58014503-4a175800-7af9-11e9-9e0e-87f07b7b5007.png">

Cyan area: Bitplane DMA is enabled
Black line: Line 255

Copper list (for reference): 

<img width="980" alt="Screenshot 2019-05-20 at 12 14 43" src="https://user-images.githubusercontent.com/12561945/58014533-5e5b5500-7af9-11e9-8814-4b62a9985575.png">

Debug output (for reference):

    [14934] (252,  2)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(A302)
    [14934] (256,  2)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(302)
    [14935] (251, 86)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(302)
    [14935] (252,  2)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(A302)
    [14935] (256,  2)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(302)
    [14936] (251, 86)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(302)
    [14936] (252,  2)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(A302)
    [14936] (256,  2)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(302)
    [14937] (251, 86)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(302)
    [14937] (252,  2)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(A302)
    [14937] (256,  2)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(302)
    [14938] (251, 86)  FC0F58: PCBD 602C 1040: Denise: pokeBPLCON0(302)

**Comment by dirkwhoffmann** [comment]
Issue was caused by a Copper bug. Copper did not handle WAIT statements correctly if there were two of them in a row (which happens frequently). Now, the screen can be dragged smoothly until the bottom is reached. 

There is another issue in the lower right corner though:

<img width="880" alt="Screenshot 2019-05-20 at 14 12 44" src="https://user-images.githubusercontent.com/12561945/58023029-1cd5a480-7b0f-11e9-8e58-ed46b74e17a8.png">

Next step: Find out if the pixels are sprite pixels.

**Comment by mithrendal** [comment]
Looks like a c64 sprite. 😂

**Comment by dirkwhoffmann** [comment]
May be related to the "Sprite DMA not switched off" Paccer issue. I think it's best to fix Paccer first. 

> Looks like a c64 sprite

Indeed 😂. Maybe the emulator is still haunted by VirtualC64 somehow 🤔.

**Comment by dirkwhoffmann** [comment]
Findings: Graphics glitches happen at the last lores fetch in the lower area:

<img width="968" alt="Screenshot 2019-05-21 at 18 49 46" src="https://user-images.githubusercontent.com/12561945/58115022-6ef2f480-7bf9-11e9-88d6-29474e0e9eed.png">

Explanation:

Green:  Border area (outside display window)
Yellow: First pixel of a 32 bit chunk (lores)
Magenta: First pixel of a 16 bit chunk (hires)

**Comment by dirkwhoffmann** [comment]
Could be a Copper timing issue, so it might be better to postpone it for now. 

Looking at it in more detail, it could just as well be a message from the underworld. Not necessarily of course. It's just because I'm living next door to a graveyard 😬.

**Comment by mithrendal** [comment]
I personally don't believe in ghosts, but it could it be that someone buried his old Commodore C64 onto the graveyard... and this one is doing magic things now. (zombie sprites)... scaring !

**Comment by dirkwhoffmann** [comment]
DMA debugger already pays off. Seems like not all DMA slots get cleared when bitplane DMA is switched off. 

<img width="933" alt="Screenshot 2019-05-26 at 19 48 26" src="https://user-images.githubusercontent.com/12561945/58385383-cd501680-7fef-11e9-9ed7-8db1a66e7fef.png">

**Comment by dirkwhoffmann** [comment]
Fixed
