### ISSUE TITLE
Virtual Dreams & Fairlight: Crash

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#280]
[VD-AbsoluteInebriation-A.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/4172071/VD-AbsoluteInebriation-A.adf.zip)

This is supposed to come up: 

<img width="733" alt="Bildschirmfoto 2020-02-07 um 18 01 06" src="https://user-images.githubusercontent.com/12561945/74049280-199f8300-49d4-11ea-80c4-081e08c09be9.png">

Works in SAE with weakest settings: Immediate Blitter + Turbo drive.

**Comment by dirkwhoffmann** [comment]
Main problem solved: The demo boots.

<img width="910" alt="Bildschirmfoto 2020-02-09 um 13 00 21" src="https://user-images.githubusercontent.com/12561945/74102904-031a3880-4b48-11ea-9417-692250568ea4.png">

Next issue: Graphics glitches in one of the first scenes: 

<img width="910" alt="Bildschirmfoto 2020-02-09 um 13 00 58" src="https://user-images.githubusercontent.com/12561945/74102902-00b7de80-4b48-11ea-8d7c-282a73d2056e.png">

**Comment by dirkwhoffmann** [comment]
After a complete overhaul of the shift register logic in Denise it looks much better. Just the horizontal stripes are left. Looks like shift register contents of the previous line is dumped out. 🤔

<img width="1047" alt="Bildschirmfoto 2020-03-15 um 10 30 23" src="https://user-images.githubusercontent.com/12561945/76699106-4ec18400-66aa-11ea-8738-e5af1a6070fb.png">

**Comment by dirkwhoffmann** [comment]
Graphics error has been fixed 😎: 

<img width="1047" alt="Bildschirmfoto 2020-03-16 um 13 02 24" src="https://user-images.githubusercontent.com/12561945/76756819-bf3dd300-6786-11ea-985d-da5259d26441.png">

However, the demo crashes a little later 🙈:

<img width="1047" alt="Bildschirmfoto 2020-03-16 um 13 02 49" src="https://user-images.githubusercontent.com/12561945/76756920-f01e0800-6786-11ea-81ea-49feea993f28.png">

**Comment by dirkwhoffmann** [comment]
Fix for #304 fixes this issue, too. 

Now it goes well to the end: 

<img width="932" alt="Bildschirmfoto 2020-04-13 um 17 26 36" src="https://user-images.githubusercontent.com/12561945/79133332-26fa3480-7dac-11ea-82bc-4f75122a86f2.png">

**Comment by mithrendal** [comment]
Whoa that looks coool. Now with activity monitor  ... 😍
