### ISSUE TITLE
Misplaced HSYNC area

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#283]
When comparing vAmiga with UAE, it seems that the whole screen needs to be shifted a few pixels to the right.

UAE:

<img width="721" alt="Bildschirmfoto 2020-02-11 um 09 33 07" src="https://user-images.githubusercontent.com/12561945/74221107-9b7ffc80-4cb1-11ea-9141-9cf629572c4e.png">

vAmiga:

<img width="910" alt="Bildschirmfoto 2020-02-11 um 09 27 45" src="https://user-images.githubusercontent.com/12561945/74221116-a044b080-4cb1-11ea-976f-968ee6259650.png">

**Comment by dirkwhoffmann** [comment]
According to “Amiga Intern“, the HBLANK area covers DMA cycles $F - $35 and I implemented it this way in vAmiga. 

<img width="719" alt="Bildschirmfoto 2020-03-12 um 16 46 41" src="https://user-images.githubusercontent.com/12561945/76540007-d5dfe380-6481-11ea-9302-748111e8886a.png">

However, these values seem to be wrong. I can pretty much mimic the original machine and UAE if I let the HBLANK area span from $A to $30:

UAE:

<img width="719" alt="Bildschirmfoto 2020-03-12 um 16 35 54" src="https://user-images.githubusercontent.com/12561945/76540301-4129b580-6482-11ea-8c63-43c8453d5d1a.png">

vAmiga with HBLANK spanning from $A to $30:

<img width="913" alt="Bildschirmfoto 2020-03-12 um 16 34 50" src="https://user-images.githubusercontent.com/12561945/76540343-4f77d180-6482-11ea-997f-37545c7f18cf.png">

Unfortunately, a lot of stuff such as the Workbench looks misaligned with these values (also on the real machine). Hence, it might be best to make the HBLANK area adjustable in vAmiga. I could add a control to the Video settings that shifts the HBLANK area around a few DMA cycles 🤔.

**Comment by mithrendal** [comment]
In case of the workbench I know in preferences settings of the workbench is exactly the video setting you consider to add in vAmiga.

**Comment by dirkwhoffmann** [comment]
> preferences settings

Oh yes, of course, this explains the odd workbench look. It's just that the settings are screwed up.

> What happens if you choose the midvalue in preferences?

I tried the two corner cases (upper left, lower right) in UAE: 

<img width="720" alt="Bildschirmfoto 2020-03-12 um 22 56 52" src="https://user-images.githubusercontent.com/12561945/76570851-82d45380-64b6-11ea-8ecb-1a1837f712ed.png">

<img width="720" alt="Bildschirmfoto 2020-03-12 um 22 57 01" src="https://user-images.githubusercontent.com/12561945/76570861-87007100-64b6-11ea-927f-d27422fca531.png">

When I map the HSYNC area to $B - $31 (not $A - $30 as mentioned before), vAmiga looks pretty much the same: 

<img width="841" alt="Bildschirmfoto 2020-03-12 um 23 04 54" src="https://user-images.githubusercontent.com/12561945/76570967-c16a0e00-64b6-11ea-8e64-9943ac250134.png">

<img width="841" alt="Bildschirmfoto 2020-03-12 um 23 05 10" src="https://user-images.githubusercontent.com/12561945/76570973-c333d180-64b6-11ea-9326-c2c0e7105883.png">

I think I should simply go for these values...

**Comment by mithrendal** [comment]
Looks fine 🤤👍🏻

I just listened to the sound of octopus in red wine in firefox. Oh my god it really works 🙈.  I made a branch sound for it.

**Comment by dirkwhoffmann** [comment]
The next version will provide flexible means to adjust the texture cutout. There will be four circular sliders in the video settings: H CENTERING, V CENTERING, H ZOOM, V ZOOM (up to now, H ZOOM and V ZOOM were identical and just called ZOOM). The main difference will be that these sliders don't move the render cube any more. Now, they directly determine the texture area that is spanned over the render cube. 

The largest displayable area within the texture will be this: 

<img width="761" alt="cutout1" src="https://user-images.githubusercontent.com/12561945/77254182-c6218580-6c5f-11ea-948e-a9ddace82842.png">

Black area is unused, gray area is VBLANK and HBLANK area and thus not displayable.

Using H ZOOM, V ZOOM, the user can shrink the area, e.g., to this: 

<img width="761" alt="cutout2" src="https://user-images.githubusercontent.com/12561945/77254188-d46fa180-6c5f-11ea-8bad-f0c1244a7384.png">

Using H CENTERING and V CENTERING, the shrinked rectangle can be moved around like this:

<img width="761" alt="cutout3" src="https://user-images.githubusercontent.com/12561945/77254200-efdaac80-6c5f-11ea-83ed-19d9719254a9.png">

<img width="761" alt="cutout4" src="https://user-images.githubusercontent.com/12561945/77254201-f10bd980-6c5f-11ea-8342-9641c4732f96.png">

As "factory settings" I have chosen values that pretty much mimic what we see in UAE. We could also use Robin Hood for calibration, but we would need to know his real weight for this.
