### ISSUE TITLE
Atari 2600

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#297]
Since we might all be under quarantine soon 😷 (and Allesandro probably is already 😬), I thought I should prepare myself with some new old equipment...

![IMG_5756](https://user-images.githubusercontent.com/12561945/76320217-a34ab500-62e0-11ea-9fa5-93aa1e064367.JPG)

It wasn't so easy to connect, because most of my devices don't have a composite video port any more. But I finally managed to get graphics and sound 😃.

![IMG_0079 2](https://user-images.githubusercontent.com/12561945/76320301-c83f2800-62e0-11ea-9c45-e9cd397d4777.JPG)

To my surprise, graphics and sound are better than expected. Unfortunately, Phoenix is the only game that came with the console 😢.

Could be the next cool thing to emulate 😎. Fortunately, there is not much hardware involved:

![l6IGIygVLUPYeOwJ large](https://user-images.githubusercontent.com/12561945/76320401-f15fb880-62e0-11ea-87f7-30f45308b40b.jpeg)

- Orange: MOS Technology 6532 RIOT (Ram-I/O-Timer). Don’t know what’s that for
- Yellow: MOS Technology 6507 CPU (like a 6502 without interrupts)
- Green: TIA custom chip

The 6502 could be taken from VirtualC64. Hence, it’s mainly the TIA that has to be emulated and this chip seems to be documented decently:

[Atari_2600_TIA_Technical_Manual.pdf](https://github.com/dirkwhoffmann/vAmiga/files/4312869/Atari_2600_TIA_Technical_Manual.pdf)
 
On the other hand, VirtualC64web needs to be done... and vAmiga still has so many bugs... so I guess the console thing has to wait... 🙁

**Comment by Alessandro1970** [comment]
Quatantine! 😷

**Comment by Alessandro1970** [comment]
...better to try to emulate a VirtualZX 48k with virtual on-screen keyboard

**Comment by dirkwhoffmann** [comment]
> ...better to try to emulate a VirtualZX 48k with virtual on-screen keyboard

Yes, the Amstrad is a much better machine, but much more complicated. Compared to the Amstrad, the Atari is a piece of cake (no Ram, no keyboard, no disk drive, not even a full 6502). Could be done in a few weeks or so...

Anyway, the VirtualC64web idea fascinates me... this project should really be done.

**Comment by Alessandro1970** [comment]
Mmmm not amstradt but Sinclair zx spectrum ...the c64 enemy
Zilog z80 and ula

**Comment by Alessandro1970** [comment]
This one:
![C744552F-C391-41F7-A226-CA931048C49E](https://user-images.githubusercontent.com/34916641/76333424-ea8d7180-62f1-11ea-99c9-a08e8398a6e6.jpeg)

**Comment by KenDFish** [comment]
Spectrum (and Amstrad CPC) already has what I consider the equivalent to V64/VAmiga: [RetroVirtualMachine](https://www.retrovirtualmachine.org/en/). It's very similar in concept and functionality - great minds think alike 😄

**Comment by dirkwhoffmann** [comment]
![spaceInvaders](https://user-images.githubusercontent.com/12561945/79137425-fe296d80-7db2-11ea-9570-329597188153.png)

Does anybody know if this space invaders guy is protected by copyright?

**Comment by Alessandro1970** [comment]
I do not think that it is copyrighted, there were a lot if clones...and whit those colours...
But a Zx Spectrum emulator with a virtual keyboard could be a good idea too...

**Comment by dirkwhoffmann** [comment]
Hi Alessandro,

> I do not think that it is copyrighted, there were a lot of clones.

to be on the save side I can also modify it a bit. I can give it some Dracula like teeth, rabbit like ears, or nerdy glasses 🤓.

> But a Zx Spectrum emulator 

I am not sure if there will be a third emulator at all. I mainly painted that icon to distract myself. My trouble with the Amstrad or the Spectrum is not technology related. It is due to the lack of emotional connection to this machine. I am pretty sure that I won’t be able to finish such a complex project for a machine I haven’t had any contact to back in the days. Looking back, there are exactly three machines I have an emotional connection to: The C64, the Amiga, and (to some extend) the Atari 2600. The C64 was the first computer I owned. Not to 100% though, because I had to share it with my sister. Well, good for me, she lost interest pretty soon and from that time on, the machine was mine 😆 (Before we had a lot of fights because she always wanted to play Juice, but I liked Fort Apocalypse a lot better). Later, I had an Amiga 500 and I really missed that machine when it was gone (maybe that’s the reason why I have 5 now 😍). I never owned an Atari 2600 back in the day (now I do 😎), but this machine marks my very first contact with computers. An old college friend of my father owned such a machine and I exactly remember the evening when he showed it to us. We were all sitting in front of his television and played Pacman and Pitfall. I remember it very clearly, because the adults hardly handed the controllers over to us children because they all wanted to play themselves 😂. 

BTW, I am not sure if you are aware of the Virtual64web project which is hosted here:
https://github.com/dirkwhoffmann/virtualc64web

@mithrendal made huge progress in the last couple of days. Today, I was able to play Scramble in Safari with a keyboard emulated joystick in full screen mode without any issues 😎.

**Comment by dirkwhoffmann** [comment]
Just compiled my first Atari program in Atari Dev Studio for Visual Studio Code 😎.

There is a great Atari programming tutorial here: 
https://www.randomterrain.com/atari-2600-memories-tutorial-andrew-davie-01.html

I am wondering why they used only 16 colors for the C64. Even the Atari 2600 had 256 🤔. 

<img width="1225" alt="Bildschirmfoto 2020-04-23 um 10 25 16" src="https://user-images.githubusercontent.com/12561945/80076918-1cc6fb80-854d-11ea-80b2-7483f6d15aec.png">

<img width="1072" alt="Bildschirmfoto 2020-04-23 um 10 24 56" src="https://user-images.githubusercontent.com/12561945/80076933-20f31900-854d-11ea-9c32-71139d05d503.png">

**Comment by mithrendal** [comment]
🤤I like the colors. A bit like miami vice colors must have been very modern at that time 

![B38CBC86-68A9-4328-BECA-30A73C33B995](https://user-images.githubusercontent.com/17108995/80078979-2cd7de80-853f-11ea-8ca3-6f1341306973.jpeg)
