### ISSUE TITLE
X-Copy III nibble mode: No index signal

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#300]
Debugging the disk controller turned out to be a nightmare... but still better than watching the news... 🙁

<img width="990" alt="Bildschirmfoto 2020-03-19 um 13 07 42" src="https://user-images.githubusercontent.com/12561945/77066280-248e0000-69e3-11ea-8f2d-0f8078b52b3c.png">

Usually, the index signal works very well... 🤔

**Comment by mithrendal** [comment]
Whoa nibblecopy 🤤🤤🤤

The design of these copy apps is outstanding.

**Comment by dirkwhoffmann** [comment]
> The design of these copy apps is outstanding

Back in the day, I used to copy my disks with a program that had Copper bar effects and great music. But I don't remember the name... 😢

BTW, what is the English name for "Lagerkoller"? I already feel imprisoned after staying 2 days in the house.

**Comment by mithrendal** [comment]
why can‘t you make a walk into Schlosspark ? It is such a nice day... 

Don’t know but Lagerkoller thats how the enemy in archon feels when my sorcerer casts the imprision spell. When I remember it lasts at least two complete time shifts

**Comment by dirkwhoffmann** [comment]
> Btw I studied in KA nice place

Let me guess.... Physics... because you are so familiar with warp kernel technology.

> why can‘t you make a walk into Schlosspark

Because of my aching muscles. Since the sports institute pulled up the drawbridges last week, I started running again. Now, I can't move so well 🙈.

**Comment by mithrendal** [comment]
>Let me guess.... Physics.
No informatics... in the ninetees, I think I saw you at the campus, cafeteria or in the mensa back then ... 
... I still remember Steve Jobs famous next station at the bibliothek "am Fasanengarten" ...

**Comment by dirkwhoffmann** [comment]
> why can‘t you make a walk into Schlosspark ?

<img width="365" alt="Bildschirmfoto 2020-03-19 um 14 35 53" src="https://user-images.githubusercontent.com/12561945/77073179-2231a300-69ef-11ea-8662-5d0b113b7c82.png">

> No informatics... in the ninetees, I think I saw you at the campus

Small world. I started in 1992. Maybe we were sitting next to each other in one of the lectures 😂.

> ... I still remember Steve Jobs famous next station 🤤

They had a next station in the library? Really? 😲 I completely missed that.

**Comment by mithrendal** [comment]
Me 90. then late 92 continued studies at your current workplace. 

BTW: what happens when you push the "killsys!!" button 😱?

**Comment by dirkwhoffmann** [comment]
> BTW: what happens when you push the "killsys!!" button 😱?

Hmm, good question... let's try... 

This is how it comes up after launching: 

<img width="718" alt="Bildschirmfoto 2020-03-19 um 14 43 12" src="https://user-images.githubusercontent.com/12561945/77073829-2a3e1280-69f0-11ea-9524-61d406e35398.png">

OK, let's be brave... 😬 I'm going to hit that button in 10 9 8 7 6 5 4 3 2 1 

<img width="718" alt="Bildschirmfoto 2020-03-19 um 14 43 20" src="https://user-images.githubusercontent.com/12561945/77073922-4d68c200-69f0-11ea-85a5-fddc3df78a45.png">

🥴 Oh no, it seems to melt the CPU. Luckily the CPU is virtual.

**Comment by dirkwhoffmann** [comment]
> then late 92 continued studies at your current workplace.

😂 A very small world indeed.

**Comment by dirkwhoffmann** [comment]
Update: A red 7 in Xcode means "Long track". So the copy program thinks that there is some copy protection on my disk, but there isn't. 

The INDEX interrupt seems to be triggered correctly.

Maybe there is an issue with the DSKSYN word. The DSKSYN interrupt is only triggered in vAmiga when the drive is performing DMA or waiting to perform DMA. It's not triggered when the disk drive motor is on and no read operation is performed or scheduled. Maybe this is wrong 🤔.

**Comment by tonioni** [comment]
Unfortunately "read" operation is always running when drive is selected and motor is on (and no write DMA active). Check DSKBYTR register.

Extreme test case: game The Deep (1988) cracked version.

**Comment by dirkwhoffmann** [comment]
> Unfortunately "read" operation is always running when drive is selected and motor is on
 
This is definitely a huge bug in vAmiga (which is very good news 😁).

I’ve already written a test case for this. It simply starts the drive motor and visualizes the DSKSYN interrupt by yellow stripes. There are always two interrupts in a row since the SYNC word repeats two times.

<img width="718" alt="sync1_uae" src="https://user-images.githubusercontent.com/12561945/77159996-bf9bde00-6aa6-11ea-860e-af0f5c9e4f16.png">

vAmiga shows a blue screen without stripes.

I am still struggling to create more compatible test programs though. The easiest solution for me would be to have some example program in assembler where I could copy the initialization code into my test cases. The page you told me to look at does explain nicely what has to be done for a clean initialization, but all example code is written C (if I haven’t overseen something). Do you know if there exists some nicely written assembler program where I could copy the initialization code from? Because I never wrote Amiga programs back in the day, I am having a hard time with the easiest things (such as opening a library other than exec).

**Comment by tonioni** [comment]
Attached file here is in assembler: http://eab.abime.net/showpost.php?p=711170&postcount=5 (VBR stuff isn't really needed, it is always zero when booting floppies)

**Comment by dirkwhoffmann** [comment]
> Attached file here is in assembler

Excellent, works just fine 😃. I only had to comment out the `movec` command to make it compile for the 68000. Thanks a lot! 

```
.getit	; movec   vbr,d0
	rte				; back to user state code
```

XCopy is still broken though. It keeps in telling me there is no index signal 😫. If XCopy really talks about the INDEX signal and not the SYNC signal, there aren't many ways to read that signal. It's connected to the FLAG pin of CIAB, so XCopy could either read the ICR register directly or it could let the CIA issue an interrupt 🤔. That's it.

**Comment by dirkwhoffmann** [comment]
>  It keeps in telling me there is no index signal

Hmm, I have a suspicion 🤨. If it's confirmed, I'll have to fire me (again).

**Comment by dirkwhoffmann** [comment]
Woohoo, copying disks in nibble mode 😎.

<img width="990" alt="Bildschirmfoto 2020-03-20 um 18 22 29" src="https://user-images.githubusercontent.com/12561945/77189612-21287080-6ad8-11ea-80a5-c01c8ae61359.png">
