### ISSUE TITLE
System 7

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#305]
Hi,
But...
...is there any trick to use vAmiga with a Macintosh IIc ROM and boot with System 7 ?

The hardware required is quite the same: mc68k and 4MB Ram or little more...
🙈🙊🙈

**Comment by dirkwhoffmann** [comment]
> .is there any trick to use vAmiga with a Macintosh IIc ROM and boot with System 7 ?

No chance to do this. Although both systems are based on the same CPU, they differ in nearly every other aspect.

**Comment by mithrendal** [comment]
> No chance to do this.

I think it is possible by emulation read here for macOS
https://en.wikipedia.org/wiki/Emulation_on_the_Amiga?wprov=sfti1

Still in the 90tees I heard already heard the then spoken word that amigas are the better macs 🤤

**Comment by dirkwhoffmann** [comment]
> "Amigas have their own version of VICE and Frodo software emulators. VICE emulates the 8-bit machines made by Commodore, including C64, C128, PET, and VIC-20."

Really? We can run VICE inside vAmiga? 🤔

**Comment by mithrendal** [comment]
I had an c64 emulator on the Amiga1000 in 1989 or so. It was running... but slowly ... don’t remember the software name anymore

**Comment by dirkwhoffmann** [comment]
Found Frodo for AmigaOS... 🤤 Downloading...

Doesn't run in vAmiga 🤨. I guess it requires one of the newer Amigas with a 68020 or so. Haven't found any documentation yet.

<img width="976" alt="Bildschirmfoto 2020-04-14 um 07 21 22" src="https://user-images.githubusercontent.com/12561945/79188998-df61c000-7e20-11ea-86a5-fe19f3303359.png">

I also found VICE, but it's 63MB 😳. Unlikely that this can squeezed onto a single ADF. In some blog, somebody wrote about running VICE on an Amiga with a 68060 processor. I did not even know that such a processor exists 😯. But come on, those modern "Amigas" are no real Amigas. They are "modern" computers with a label "Amiga" on it. Only OCS is the real thing! 😎 And Aga is for beginners.

**Comment by dirkwhoffmann** [comment]
Frodo requirements 😬:

- A PowerPC Amiga or compatible
- 8 MB RAM
- WarpUP v4.0
- AGA or CGFX
- lowlevel.library for joystick support
- CGFX and a 384x272 screenmode if you want to see the borders

**Comment by dirkwhoffmann** [comment]
Are there any web browsers for OCS Kickstart 1.3? Maybe we can VirtualC64web 😃?

Oh, wait, a browser requires Internet, and Internet requires network support. Won't work in vAmiga 😪.

**Comment by mithrendal** [comment]
http://aminet.net/package/misc/emu/MagiC64 it was maybe this one. In the readme they say the fastest c64 emulator for 68k 🕺🏾

**Comment by dirkwhoffmann** [comment]
MagiC64 is 1.2MB. Doesn't fit on a single ADF 😪.

Go64 ... great... already comes as an ADF...

<img width="976" alt="Bildschirmfoto 2020-04-14 um 08 25 05" src="https://user-images.githubusercontent.com/12561945/79192746-995d2a00-7e29-11ea-8041-aad28f00afa8.png">

Let's give it a try 🤤

<img width="976" alt="Bildschirmfoto 2020-04-14 um 08 24 29" src="https://user-images.githubusercontent.com/12561945/79192772-a548ec00-7e29-11ea-8869-caa7dea33adb.png">

😂 It works. But what is SIS BASIC???

**Comment by mithrendal** [comment]
No System7 🙄 ? @Alessandro1970 don't you like to give it a try ? This one looks the most promising 

https://shapeshifter.cebix.net/ 

download directly from the developer ...

**Comment by dirkwhoffmann** [comment]
You mean to run shapeshifter on the (real) Amiga 2000? 

It requires "OS2.1, 68020 processor, 4MB of RAM".

**Comment by mithrendal** [comment]
Ok, ok I found another one
A-MAX  The Apple Macintosh (c) Emulator for the Amiga (c) personal computer.

http://crossconnect.tripod.com/AMAXHOME.HTML 

it seems not to need 68020 and therefore it may run in vAmiga  ...

**Comment by Alessandro1970** [comment]
...try to use a Mac/System 7 emulator with the vAmiga/VirtualC64 GUI personalize for... etc. etc. could be a great thing.
Basilisk II has a lot of problems and the worst is the GUI...

Better to remains happy with vAmiga ECS/OCS and VirtualC64... tons of software for free... that all ! 
May be 68020 + 68881 could be a great add-od for vAmiga ...there was a card, an expansion card, for the Amiga 2000 that had 68020+68881 👍

**Comment by Alessandro1970** [comment]
Commodore A2620 - 68020 + 68882 14 Mhz

http://amiga.resource.cx/photos/a2620,1

**Comment by dirkwhoffmann** [comment]
> tons of software for free...

Yes. Just watched "The Top 10 Worst Amiga Games of All Time" again this morning.
https://www.youtube.com/watch?v=zMZP5zB6fCw

Then, I played Dark Castle... 

<img width="976" alt="Bildschirmfoto 2020-04-14 um 08 05 02" src="https://user-images.githubusercontent.com/12561945/79211193-36c65700-7e46-11ea-814b-e36ba5bf35d5.png">

I can officially confirm ... it's ... 😶 (but the intro screen is pretty cool though). However, I'm not sure if it's worse than the Amiga Donkey Kong clone from 1985 which only runs on the A1000 🤔. I  forgot the name.

**Comment by mithrendal** [comment]
which character are you playing there 🙊 ? The one with the whip 😳 🙈? Reminds me on the scene in[ pulp fiction](https://www.youtube.com/watch?v=S8kPqAV_74M) 🙉 ...

**Comment by dirkwhoffmann** [comment]
> The one with the whip 

Unfortunately not. This is the only cool pal in the scene. 

I'm the boring looking guy on the left with red hair.

**Comment by mithrendal** [comment]
I have found it !!
What a rare precious game from 1985.. _The game had been lost until October 2018, when a member of the English Amiga Board was able to salvage a damaged disk image of an obscure European cracking group._

![grafik](https://user-images.githubusercontent.com/17108995/79216213-1948bb80-7e4d-11ea-841e-f678652c01f5.png)

**Comment by dirkwhoffmann** [comment]
Yeeaaaahhhh! Monkey Business. That's the game. 

This game is for the Amiga what E.T. was for the Atari 2600. The global minimum of the "game score graph". 

But wait. How could the game get a ranking of 1.5?? Assuming 1 is lowest, where do the 0.5 points come from? 🤔

**Comment by mithrendal** [comment]
0.5 points for being the first commercial game ... because when this game came out 1985 ... we were amazed with everything electronical they throw at us ... look here at this photo to get to get a sense of that  time
![grafik](https://user-images.githubusercontent.com/17108995/79227628-7c901900-7e60-11ea-9f56-f29c3dfe7ea6.png)

**Comment by dirkwhoffmann** [comment]
> what you are not seeing is the Amiga 1000 with preloaded monkey business in front of the boy. 

Maybe. Or he just spotted the neighbors girls who got a C64C that looks so much better than the breadbox model 😎:

<img width="364" alt="Bildschirmfoto 2020-04-14 um 15 15 44" src="https://user-images.githubusercontent.com/12561945/79229244-fc1ee780-7e62-11ea-9fbd-12e1b75834e7.png">
