### ISSUE TITLE
Ghost'n Goblins broken

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#312]
After hitting the mouse button to start a new game, the game is *very* slow. The system seems to operate normally: The CPU is running at the correct speed and audio output is fine, too (i.e., no debug output flooding). 

It runs fine in SAE with the following configuration:

 512 Chip + 512 Slow
ECS Agnus, OCS Denise
Accurate Blitter
Turbo drive
 

Findings: 
Runs well in v0.56
Broken in v0.60

**Comment by dirkwhoffmann** [comment]
Broken in commit 38fe25d, most likely by this change: 

<img width="1255" alt="Bildschirmfoto 2020-04-24 um 15 34 55" src="https://user-images.githubusercontent.com/12561945/80218254-3ba6ba00-8641-11ea-9a3d-26671ea1682a.png">

The game seems to utilize the sound state machine to trigger game events.

**Comment by dirkwhoffmann** [comment]
Partially fixed in v0.9.1. There are occasional hiccups left which are likely caused by a remaining state machine issue. 

TODO: Write test cases that abuse the audio state machine as a timer.

**Comment by mithrendal** [comment]
>The game seems to utilize the sound state machine to trigger game events.

That was soo mean of the game developer.  I bet he did not have emulators in mind when he designed the game.

**Comment by dirkwhoffmann** [comment]
> That was soo mean of the game developer

Yes, very mean 😫. But it's also clever. It's possible to use the sound circuitry as a timer that continuously triggers interrupts with a configurable time span in between. Never thought about that before 🤔.

**Comment by dirkwhoffmann** [comment]
I’ve written a couple of test cases that shamelessly misuse the audio state machine as an interrupt timer.

This is test case audtim3 on the A500 MMSE 🥰: 

![audtim3_A500_8A](https://user-images.githubusercontent.com/12561945/80282344-387aff00-8711-11ea-99d6-e76276811eac.JPG)

In vAmiga 0.9.1 it looks like this 🙈:

<img width="923" alt="Bildschirmfoto 2020-04-25 um 16 22 24" src="https://user-images.githubusercontent.com/12561945/80282367-5ba5ae80-8711-11ea-978e-dcfdd2f16f53.png">

The good: It's much better in vAmiga 0.9.2 😎. I haven’t spotted a single difference yet. 

<img width="923" alt="Bildschirmfoto 2020-04-25 um 16 23 03" src="https://user-images.githubusercontent.com/12561945/80282371-619b8f80-8711-11ea-813a-e25401f67498.png">

The bad: Neither it is related to a ghost nor to a goblin.

**Comment by shinra-electric** [comment]
Is this fixed? There are a couple of slowdowns, but overall it seems to work fine for me...

**Comment by dirkwhoffmann** [comment]
> Is this fixed? 

It's still broken. I need to find out where the slowdowns come from. I guess it's missing interrupts or something.

**Comment by dirkwhoffmann** [comment]
Still broken in v0.9.8

**Comment by dirkwhoffmann** [comment]
Hiccups (short freezes) seem to be gone in v0.9.8.2, but a sound issue remains. Background music sounds OK, but there is some strange noise when the main character jumps off and lands.

**Comment by dirkwhoffmann** [comment]
I'm unsure if the sound issue is a bug or not. Channel 3 (this is where the jump sound comes from) seems to be emulated correctly. Maybe it's just a problem due to the fact that vAmiga uses a simpler audio filter than the real machine. Don't know.

I'll close this issue for now, because the main problem (small sudden freezes) has been fixed.

**Comment by dirkwhoffmann** [comment]
v0.9.8.4 seems to fix the audio issue. The game appears to be fully supported now.
