### ISSUE TITLE
Gettysburg cracker intro flickers

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#316]
Gettysburg - The Turning Point (1988)(SSI)[cr Knight Hawks].adf

In UAE the last two or three lines are unstable. Below these lines, the screen is black:

<img width="721" alt="Bildschirmfoto 2020-04-27 um 17 37 40" src="https://user-images.githubusercontent.com/12561945/80391708-65184d80-88ae-11ea-946f-20b0cdc27e8e.png">

In vAmiga, the last two or three lines are unstable. Below these lines, the screen flickers:

<img width="1050" alt="Bildschirmfoto 2020-04-27 um 17 38 46" src="https://user-images.githubusercontent.com/12561945/80391726-6ba6c500-88ae-11ea-98f7-4333693602d5.png">

Next step: See how the game looks like on the real machine.

**Comment by mithrendal** [comment]
Look at these stunning colors.🤤 The Amiga is a real color machine 🤓... These programmers loved colors😍 ... maybe they were on a trip ?😎

**Comment by dirkwhoffmann** [comment]
As expected UAE gets it right: Bottom part is black on the real machine.

![IMG_5686](https://user-images.githubusercontent.com/12561945/80512059-41700880-897d-11ea-8979-6bab93ca6fe2.JPG)

vAmiga doesn't switch off bitplane DMA I guess.

**Comment by dirkwhoffmann** [comment]
> Look at these stunning colors.🤤

Which colors are you talking about? All pictures posted here are black and white. 

> maybe they were on a trip ?😎

Maybe... 🙄

**Comment by dirkwhoffmann** [comment]
No longer an issue in 0.9.4. I guess it was related to the LOF flipflop bug which has been fixed in that release.
