### ISSUE TITLE
Sprite effect testing

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#319]
I've found a nice page describing sprite tricks used in different games. 

https://codetapper.com/amiga/sprite-tricks/

The games on this site should be tested...

**Comment by mithrendal** [comment]
nice reading ... I was completely stunned when seeing the game stardust ...

**Comment by Gianmarco72** [comment]
> https://codetapper.com/amiga/sprite-tricks/ 
> The games on this site should be tested...

I tested all games, focusing on what is described on "Codetapper's Amiga".
The only problem I encountered is on "Brian the Lion": some sprites have small imperfections.
Comparison with UAE:

UAE:
![Brian on UAE](https://user-images.githubusercontent.com/45571833/80643928-27abef80-8a69-11ea-9a81-c5af3bcbe573.jpg)

vAmiga:
![Brian on vAmiga](https://user-images.githubusercontent.com/45571833/80643970-37c3cf00-8a69-11ea-9245-e28c9b5d4f20.jpg)

**Comment by Gianmarco72** [comment]
> nice reading ... I was completely stunned when seeing the game stardust ... I like the graphic effects.

Agree, the tunnel "head spin" effect is amazing!
I also tried the full game. The 1st level refers to the Atari's Asteroids of the 70s 😍

**Comment by dirkwhoffmann** [comment]
Ooups, seems like there's some air pollution in Brian's world now 🙈.

How can I get to the tunnel sequence in Stardust?

<img width="1003" alt="Bildschirmfoto 2020-04-30 um 08 16 46" src="https://user-images.githubusercontent.com/12561945/80678546-5f438780-8abb-11ea-8a0c-9ab4ada90880.png">
 
> The 1st level refers to the Atari's Asteroids of the 70s

Yes, pretty cool game so far 😎. 

<img width="1003" alt="Bildschirmfoto 2020-04-30 um 08 14 05" src="https://user-images.githubusercontent.com/12561945/80678586-7aae9280-8abb-11ea-9c52-02e7ad1c58b7.png">

**Comment by Gianmarco72** [comment]
> How can I get to the tunnel sequence in Stardust?

There's also a playable demo-version where's possible try some levels, including the tunnel. 😉

**Comment by dirkwhoffmann** [comment]
> There's also a playable demo-version

Ah, OK, I see, for people like me that don't manage to survive level 1 🤓.

Downloading now...

<img width="1003" alt="Bildschirmfoto 2020-04-30 um 08 36 56" src="https://user-images.githubusercontent.com/12561945/80679906-16410280-8abe-11ea-86b8-9839e03cd757.png">

Yes, the band begins to play... 🤤

<img width="1003" alt="Bildschirmfoto 2020-04-30 um 08 37 14" src="https://user-images.githubusercontent.com/12561945/80679940-28bb3c00-8abe-11ea-8942-ed0a99871ce3.png">

Wow, it really works... Yes, yes, yes, gaining speed. I'm such a good pilot 😎.

<img width="1003" alt="Bildschirmfoto 2020-04-30 um 08 37 53" src="https://user-images.githubusercontent.com/12561945/80679990-45577400-8abe-11ea-9080-f62a1ff902b4.png">

Oops 🙄

<img width="1003" alt="Bildschirmfoto 2020-04-30 um 08 37 28" src="https://user-images.githubusercontent.com/12561945/80680008-4e484580-8abe-11ea-8ea1-96bc42446b46.png">

**Comment by Gianmarco72** [comment]
> Ah, OK, I see, for people like me that don't manage to survive level 1 🤓.

Haha, me too! 😅

> Wow, it really works... Yes, yes, yes, gaining speed. I'm such a good pilot 😎.
> Oops 🙄

😁
Really cool effects on Amiga. Impressive!
