### ISSUE TITLE
Make Boing ball work

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#32]
Boing ball seems to be a good test case for testing soft scrolling: 

<img width="1025" alt="Screenshot 2019-05-27 at 12 27 16" src="https://user-images.githubusercontent.com/12561945/58414218-0bdee300-807b-11e9-809b-c25f3e1f1c2a.png">

**Comment by Alessandro1970** [comment]
Is it normal for the ball-app starts background and not on foreground of the workbench?

...and for seeing it we have to drop down the workbench bar.

**Comment by dirkwhoffmann** [comment]
Yes, I think that's normal. Regarding vAmiga, I think only the soft scrolling part is missing.

**Comment by dirkwhoffmann** [comment]
Works smoothly now:

<img width="916" alt="Screenshot 2019-06-02 at 16 19 50" src="https://user-images.githubusercontent.com/12561945/58762696-adba7000-8552-11e9-898d-ddc1441a71b9.png">

DMA debugger view: 

<img width="916" alt="Screenshot 2019-06-02 at 16 20 13" src="https://user-images.githubusercontent.com/12561945/58762691-a09d8100-8552-11e9-9e9b-28ab8af044fd.png">

There is still some strange Sprite DMA going on. Hence, I leave the issue open.

**Comment by dirkwhoffmann** [comment]
Sprite DMA in rasterline 254 for sprites 2 to 8 seems to be OK. Flickering mouse pointer in lower area has been fixed (sprite DMA state was not reset to SPR_DMA_IDLE in last rasterline).
