### ISSUE TITLE
Verification of test Agnus/VPOS/vhpos2 on the A1000

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#321]
@mithrendal: Could you perhaps run test vhpos2 on your A1000?

![shrekcat](https://user-images.githubusercontent.com/12561945/80626457-c70fb900-8a4e-11ea-8e8c-424842a9cb40.jpg)

Compared to the A500 MMSE image below, there should be an additional white line:

![vhpos2_A500_8A](https://user-images.githubusercontent.com/12561945/80625764-f671f600-8a4d-11ea-9bb3-801cb29f0821.JPG)

I thought we already did a similar test, but I can't find it any more. I thought that UAE shows the additional line (when OCS is selected), but it doesn't. Now I'm confused. 

The discrepancy is related to the line where Agnus performs the VBLANK interrupt. I thought OCS Agnus performs the interrupt in line 1 whereas ECS Agnus performs it in line 0 (which is consistent with the ECS image above).

**Comment by mithrendal** [comment]
Ohh that kitten is soooo cute 😍. Have to do the test...

**Comment by mithrendal** [comment]
![0060A911-8B3B-410C-928B-67A899CE0A0E](https://user-images.githubusercontent.com/17108995/80642113-347b1400-8a66-11ea-9ecf-b7773ee97870.jpeg)

**Comment by dirkwhoffmann** [comment]
Woohoo, I can see the additional stripe. I knew it was there 😃. Thank you so much. Now, I need to find out why I don't see it in UAE any more... 🤔

**Comment by dirkwhoffmann** [comment]
Found it... If the A1000 chipset is selected, the stripe appears: 

<img width="782" alt="Bildschirmfoto 2020-04-30 um 12 09 40" src="https://user-images.githubusercontent.com/12561945/80699085-b6595480-8adb-11ea-9662-6d324ac54e9f.png">

<img width="721" alt="Bildschirmfoto 2020-04-30 um 12 08 42" src="https://user-images.githubusercontent.com/12561945/80699095-b8bbae80-8adb-11ea-93bf-8af8c97f9887.png">

If the A500 chipset is selected, the stripe is gone 🤓. Makes sense, because we want to emulate, well, an A1000. But I don't remember that I've ever enabled the A1000 option 🤔. Anyway, sky is clearing up. I guess only the old Agnus OCS revisions have that "feature" of triggering the VBL interrupt in line 1 instead of line 0.

Image is part of the vAmigaTS repo now.
