### ISSUE TITLE
Hollywood Poker Pro (1989 reLINE) doesn't boot.

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#323]
After inserting the first disk on Df0: the screen turns black and the power led on the left down corner blink (but no "Guru Meditation").
Tested with both Kickstart 1.2 and 1.3.

**Comment by dirkwhoffmann** [comment]
It boots in 0.9.4 😎

<img width="1003" alt="Bildschirmfoto 2020-05-01 um 15 20 06" src="https://user-images.githubusercontent.com/12561945/80808179-41f7e180-8bbf-11ea-9d6b-1c474f9b1052.png">

However, this doesn't look exactly right 🤔.

<img width="1003" alt="Bildschirmfoto 2020-05-01 um 15 05 38" src="https://user-images.githubusercontent.com/12561945/80808634-3c4ecb80-8bc0-11ea-8d5c-ec053c9cc0ad.png">

Oh no, I think they mix HAM mode with normal mode 😳. Please tell me they don't. In vAmiga, HAM mode has a completely different drawing routine and the routine is fixed for each line 😖.

**Comment by Gianmarco72** [comment]
.. a censored version for the under 14 😜

**Comment by dirkwhoffmann** [comment]
> .. a censored version for the under 14

No more parental control in 0.9.5:

<img width="1003" alt="Bildschirmfoto 2020-05-04 um 08 47 13" src="https://user-images.githubusercontent.com/12561945/80943196-f162cd00-8de6-11ea-9513-641a3efc0784.png">

**Comment by mithrendal** [comment]
Still 4 versions left until v1.0 🤤. Or will there be a v0.100?

**Comment by dirkwhoffmann** [comment]
> Still 4 versions left until v1.0

Already though of that 😎
v0.9.x
v0.9.9.x
v0.9.9.9.x
...
