### ISSUE TITLE
Operation Wolf (Ocean): random characters during boot.

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#324]
Broken screen during boot. The "Operation" doesn't start and the epilepsy begins. 😵
![OpW1](https://user-images.githubusercontent.com/45571833/80811685-b2eec780-8bc6-11ea-9ac9-a2202adcc80d.jpg)
![OpW2](https://user-images.githubusercontent.com/45571833/80811697-bb470280-8bc6-11ea-9b34-d8b81d8664ba.jpg)

**Comment by dirkwhoffmann** [comment]
Very good test case 👍. It boots in SAE with the turbo Blitter and a turbo Drive.

**Comment by dirkwhoffmann** [comment]
I think this is an easy one. It seems that the disk has to be inserted before the Amiga is powered on (before the hand & disk logo shows up). If the disk is inserted later, UAE goes berserk, too:

<img width="719" alt="Bildschirmfoto 2020-05-01 um 18 18 32" src="https://user-images.githubusercontent.com/12561945/80821123-74fa9f00-8bd8-11ea-8952-90f29791fb9e.png">

To boot the game in vAmiga, simply hit reset after inserting the disk.

Side note: I've found multiple Wolf version on the internet. Before I close the issue, could you check if my "bug fix" works for your version, too?

**Comment by Gianmarco72** [comment]
Confirmed, it works also with my OW version.
![Opw](https://user-images.githubusercontent.com/45571833/80822353-d7ed3580-8bda-11ea-8d43-2007311a2d49.jpg)
Really strange behavior.🤔

**Comment by dirkwhoffmann** [comment]
OK, very cool. 😃

Please keep on reporting if you stumble across any weird behavior. 👍
