### ISSUE TITLE
No sound when reading a game from a snapshot file

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#327]
When a virtual machine with active audio output is saved, sound doesn't come back when the image is restored.

**Comment by Gianmarco72** [comment]
Confirmed. When restoring an image all channels are set to zero.
![Audio Panel](https://user-images.githubusercontent.com/45571833/80923362-8a5ffc80-8d83-11ea-984d-9cbecf3655b2.jpg)

**Comment by dirkwhoffmann** [comment]
Fixed in v0.9.5
