### ISSUE TITLE
X-Out (Rainbow Arts) doesn't load.

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#328]
After the Paranoimia's Logo screen vAmiga stops loading and the VM freezes.
Also tested with UAE and it's ok.

**Comment by dirkwhoffmann** [comment]
X-Out (1990)(Rainbow Arts)(Disk 1 of 2)[cr PNA].adf

Quick findings: 

SAE: Guru meditation (even with highest compatibility settings)

UAE:
Original drive + Accurate Blitter: Works
Original drive + Immediate Blitter: Works
Turbo drive + Accurate Blitter: Fails

<img width="718" alt="uae_accurate_turbo" src="https://user-images.githubusercontent.com/12561945/81078930-22c6c000-8eef-11ea-880a-a74420608c04.png">

Turbo drive + Immediate Blitter: Fails

<img width="718" alt="uae_immediate_turbo" src="https://user-images.githubusercontent.com/12561945/81079068-5570b880-8eef-11ea-913d-02eed48845e6.png">

Conclusion: It’s most likely a drive issue.

In all UAE modes: After the following message is displayed, the screen becomes solid blue.

<img width="1003" alt="Bildschirmfoto 2020-05-05 um 16 19 49" src="https://user-images.githubusercontent.com/12561945/81078990-35d99000-8eef-11ea-902e-e3253064e11b.png">

After that, a short flickering effect is shown. This effect does not show up in vAmiga. Hence, all modes are suitable to start debugging.

**Comment by dirkwhoffmann** [comment]
Seems to work in v0.9.8 😎. Could you please double check? 

<img width="995" alt="Bildschirmfoto 2020-06-06 um 08 24 27" src="https://user-images.githubusercontent.com/12561945/83937696-58e9af00-a7cf-11ea-900f-8517e8447cda.png">

<img width="995" alt="Bildschirmfoto 2020-06-06 um 08 24 54" src="https://user-images.githubusercontent.com/12561945/83937699-5dae6300-a7cf-11ea-9454-ba755d6fc206.png">

**Comment by Gianmarco72** [comment]
> Seems to work in v0.9.8 😎. Could you please double check?

Confirmed, now it works! 🙃
<img width="912" alt="Schermata 2020-06-06 alle 12 30 33" src="https://user-images.githubusercontent.com/45571833/83942188-8e9f8f80-a7f1-11ea-9f7f-08e31e56899b.png">

**Comment by dirkwhoffmann** [comment]
> Confirmed, now it works! 🙃

Perfect. Thanks!
