### ISSUE TITLE
Is it worth to implement an enhanced HAM mode?

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#33]
As you know, HAM mode always synthesizes two pixels, by either

a) reading directly from a color register or
b) by replacing a color component from the previous pixel.

Therefore it is easy to implement a slightly enhanced HAM mode which interpolates the first of the two pixels in case b). 

In this picture, the difference gets visible to some extend: 

![interpolatedHAM](https://user-images.githubusercontent.com/12561945/58578718-b278de80-8249-11e9-9315-73a0efbabf6b.png)

However, for most pictures I tested, the result is hardly visible with the human eye, so it might not worth to offer it as an option. It's easy to implement though (just a few lines of code) ...

**Comment by mithrendal** [comment]
Oh boy, the haircut is so eigthees. 🤓 
I think the **crop** of the enhanced HAM is definitly smoother. 
If it is easy and the code will not get messed up then I would do it, simply because the other emulators don't have it. vAmiga will be a little bit better in displaying HAM 💪 than the big emulators out there. But pssst, 🙊 better don't tell anybody that vAmiga is superior in this ...

**Comment by dirkwhoffmann** [comment]
If you wish to see a real haircut from the eighties, you just have to click to the next picture 😂:

![Untitled](https://user-images.githubusercontent.com/12561945/58613963-5f3d7500-82b7-11e9-8b09-a29dc72b0575.png)

Actually, this picture is a good examples how barely visible the enhanced HAM mode is. It's hardly impossible to distinguish both versions if they are drawn in normal size.

**Comment by mithrendal** [comment]
Yep definitly the 80ties, look at this freaky  hairs.  Maybe punk style?  The crop is a bit more blurred. Can‘t tell wether it is better in terms of quality though. Pretty close. Big picture seems to be identical. 
I bet this person is now already 60 years old. Maybe still the same hair cut, no? 🤭

**Comment by dirkwhoffmann** [comment]
😳😲🤭
