### ISSUE TITLE
Broken screen on Hollywood Poker (no PRO) [reLINE].

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#332]
This is what happens on vAmiga 😖:
<img width="912" alt="Schermata 2020-05-09 alle 16 25 49" src="https://user-images.githubusercontent.com/45571833/81476547-b9a6bb80-9212-11ea-9044-1debdf8d62d0.png">
.. and game and audio are still running.

On UAE 👍🏻:
![UAE](https://user-images.githubusercontent.com/45571833/81476615-20c47000-9213-11ea-88bb-5e0dade416be.jpg)

**Comment by dirkwhoffmann** [comment]
OK, that doesn't look right. Seems like vAmiga doesn't switch to the correct graphics mode 🤔. I'll look into it...

**Comment by dirkwhoffmann** [comment]
I am having problems to find the correct ADF. The one I've used doesn't work in UAE, too.
Is "Hollywood Poker (no PRO) [reLINE]" the exact filename?

**Comment by Gianmarco72** [comment]
> Is "Hollywood Poker (no PRO) [reLINE]" the exact filename?

Nope, sorry my mistake. 🙄
The correct name is "Hollywood Poker (1987)(reLINE)", let me know if you find it.

**Comment by dirkwhoffmann** [comment]
I think this one is simple. You need to disable SlowRam to make it work: 

<img width="932" alt="Bildschirmfoto 2020-05-10 um 09 47 26" src="https://user-images.githubusercontent.com/12561945/81493756-5add5280-92a3-11ea-813d-4246628bdb6e.png">

I guess you run the game in UAE with SlowRam disabled, right?

BTW, be careful with Heather. When I played poker with her the last time (for debugging purposes only, of course), I lost all my money within minutes. And I had really good cards. I think she cheats 😖.

**Comment by Gianmarco72** [comment]
> I guess you run the game in UAE with SlowRam disabled, right?

I remember it was enabled but I'm not sure.
I'm sorry but now I can't verify. I'll check in the afternoon.

> BTW, be careful with Heather. When I played poker with her the last time (for debugging purposes only, of course), I lost all my money within minutes. And I had really good cards. I think she cheats 😖.

Wow! Okay, I won't be playing with Heather!! Thanks for the info :-P

**Comment by Gianmarco72** [comment]
> I guess you run the game in UAE with SlowRam disabled, right?

You were right, in my configuration for Hollywood Poker on UAE the slow ram is disabled.😬

**Comment by dirkwhoffmann** [comment]
> You were right, in my configuration for Hollywood Poker on UAE the slow ram is disabled.😬

No problem. Please keep on reporting! vAmiga has really improved quite a lot over the last couple of weeks by all the bug reports coming in.

**Comment by Gianmarco72** [comment]
Really! 👍🏻
I'm happy to continue testing every day. I love vAmiga (as well Virtual C64) and I'm glad if it will become the best Amiga's emulator on macOS 😉
