### ISSUE TITLE
No warning message when 1MB of ram is required? [Syndicate]

### ISSUE THREAD

**Issue by shinra-electric** [dirkwhoffmann/vAmiga#336]
I was having trouble with Syndicate (Fairlight crack) until I realised it was due to the amount of RAM available. 

With 512K: 
![Screenshot 2020-05-11 at 10 12 48](https://user-images.githubusercontent.com/50119606/81521046-4450fd00-9370-11ea-8447-8aa7262c4474.png)

With 1MB: 
![Screenshot 2020-05-11 at 10 13 57](https://user-images.githubusercontent.com/50119606/81521052-4915b100-9370-11ea-94a0-cbb1c57f7828.png)

To be honest, I don't remember what a real Amiga did when you didn't have enough RAM. Is this behaviour the same on a 512K A500? (I only had an Amiga 500 for about a month before I got the RAM upgrade to 1MB). 

In any case, could it be possible to add a warning saying that the game had crashed/didn't work because there was not enough RAM available?

**Comment by dirkwhoffmann** [comment]
> In any case, could it be possible to add a warning saying that the game had crashed/didn't work because there was not enough RAM available?

This is extremely difficult, because it's hard for the emulator to determine that it has crashed and it would be nearly impossible to find out the  reason for it. I've opened up another thread (#338) where things like that can discussed.
