### ISSUE TITLE
Remember the latest hardware configuration for a game 

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#338]
It happens frequently that a game doesn't run, because the emulator has been started with an incompatible hardware configuration. In this thread, I'd like to collect ideas about how this could be avoided. 

Here are my two cents: 

- The emulator could remember the most recent hardware config in small file that is saved in the UserApplication folder. The emulator already saves screenshots there, so it might be possible to use a similar location for that. When the user drags in an ADF, the dialog could display the saved hardware config or inform the user about any discrepancy with the current setup. 

I didn't check what other emulators do yet...

**Comment by mithrendal** [comment]
Good idea. 👍🏻  
Always remember what disk title you dragged in. Then create that config file And also update it when changing any configuration in vAmiga. 

Then when you drag this title again into vAmiga ask the user whether the old config should be used. 

But then the question arises how to housekeep these files?🤭

Another approach would be the persistent snapshot thing like in vc64web, then the hardware config could be saved into the snapshot. This wouldn’t have the housekeeping problem.

**Comment by dirkwhoffmann** [comment]
> Another approach would be the persistent snapshot thing like in vc64web

I am wondering if snapshot / screenshot handling could be simplified further. At the moment, I am unsure if the distinction between auto-taken snapshots/screenshots and user-taken snapshots/screenshots really makes sense. Maybe one storage is enough. The feature would present itself to the user as follows: There is a snapshot and a screenshot storage and the user can save a snapshot or screenshot manually, e.g., by clicking the corresponding toolbar icon. In addition, he can ask the emulator to support him by automatically taking a snapshot or screenshot once in a while.

**Comment by mithrendal** [comment]
> Maybe one storage is enough. 

🤭True ...

**Comment by mithrendal** [comment]
But there is a big difference. Auto snaphots is a ring buffer.  Whereas user taken snapshots are not. That means you have to delete all the unwanted snapshots in your snapshot library manually. 🙈 not good. 

I already thought about to invent special overlay buttons for the autosnapshot row in the snapshot browser. A save button, with it you can copy the snapshot to the Game specific persistent store. That means at the end of a row below.

**Comment by dirkwhoffmann** [comment]
I close this issue for now. It's not forgotten, but it has very low priority. I don't want to keep it open for years.

The best solution for such a feature would still be an online database that can be queried by the emulator.
