### ISSUE TITLE
Alpine9000 test #2 fails

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#34]
SAE: 

<img width="902" alt="Screenshot 2019-05-30 at 21 57 15" src="https://user-images.githubusercontent.com/12561945/58660765-7c5d5c80-8326-11e9-9fb9-187625dc6202.png">

vAmiga: 

<img width="916" alt="Screenshot 2019-05-30 at 21 55 32" src="https://user-images.githubusercontent.com/12561945/58660775-80897a00-8326-11e9-8bed-d0d7868e3389.png">

**Comment by dirkwhoffmann** [comment]
Fixed. Bitplane modulo values had always been added for all active bitplanes (even if bitplane DMA was disabled). This caused some bitplanes to be shifted against others, resulting in bogus color register indices. 

<img width="916" alt="Screenshot 2019-05-31 at 10 20 13" src="https://user-images.githubusercontent.com/12561945/58692188-5e2b4700-838e-11e9-8a18-8608875f9451.png">

**Comment by mithrendal** [comment]
Maybe this also solves the "the pawn" color issue ?

**Comment by dirkwhoffmann** [comment]
> Maybe this also solves the "the pawn" color issue ?

No, it doesn't. I checked that immediately, because I had the same thought 😏. I think the Pawn bug has a similar cause though...
