### ISSUE TITLE
Rink a Dink broken

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#346]
Rink a Dink is broken (again) 😬. The sequence with the 3D polygon now looks like this: 🙈

<img width="1042" alt="Bildschirmfoto 2020-05-19 um 18 26 22" src="https://user-images.githubusercontent.com/12561945/82352538-6e549000-99fe-11ea-9e56-6e4ba2625eca.png">

Somebody's stolen the polygon 😖.

**Comment by mithrendal** [comment]
😱

**Comment by dirkwhoffmann** [comment]
This was collateral damage (happened while I adjusted Blitter interrupt timing). Repaired in v0.9.7.
