### ISSUE TITLE
Intro played at double speed (and no music) [Dune] and [Another World] 

### ISSUE THREAD

**Issue by shinra-electric** [dirkwhoffmann/vAmiga#347]
No screenshots, because...well...

Dune works fine in FS-UAE

**Comment by Gianmarco72** [comment]
Hmmm...very strage.
I tried DUNE and Another World but I haven't encountered any problems.
My versions works well, I hear the music and the intro is at normal speed.
<img width="912" alt="Schermata 2020-05-20 alle 17 19 10" src="https://user-images.githubusercontent.com/45571833/82464963-fb5f1e00-9abe-11ea-86e7-0ce40742b6ff.png">
What version of vAmiga do you have? v0.9.7 is now available.

**Comment by shinra-electric** [comment]
Oh, ok. Apparently I was in warp mode for some reason....

Complaint withdrawn....

**Comment by dirkwhoffmann** [comment]
> Oh, ok. Apparently I was in warp mode for some reason....

The same thing happened to me more than once in the past. I though the emulator is broken, but it was just running in warp mode. 

Maybe it's a good idea to display a mute icon in the status bar when audio is off. I remember that I had this idea before and I jeopardized it. But I don't remember the reason 🤔.

**Comment by dirkwhoffmann** [comment]
The new version will have a mute icon in the status bar: 

<img width="927" alt="Bildschirmfoto 2020-05-21 um 15 37 20" src="https://user-images.githubusercontent.com/12561945/82722870-ba3b5980-9cca-11ea-8519-f9fc23d0fc5e.png">

It also appears if the user sets both master volume levels to 0 in the audio configuration panel.

**Comment by Gianmarco72** [comment]
Great👍🏻
This feature will be useful.
