### ISSUE TITLE
Invisible mouse cursor in [Secret of Monkey Island] (Skid Row) (0.9.7)

### ISSUE THREAD

**Issue by shinra-electric** [dirkwhoffmann/vAmiga#350]
I can select verbs from the menu, but the crosshairs is missing: 

![Screenshot 2020-05-21 at 22 02 21](https://user-images.githubusercontent.com/50119606/82573563-21182000-9bb0-11ea-883b-bcfdeb62962d.png)

It should flash between grey and white like this in FS-UAE: 

![Screenshot 2020-05-21 at 22 14 24](https://user-images.githubusercontent.com/50119606/82573924-94219680-9bb0-11ea-816a-c33b4f71de86.png)

**Comment by dirkwhoffmann** [comment]
Hmm, this one is strange. I tried the QTX version (German) and the SKR version (English) and both worked here.

<img width="1042" alt="Bildschirmfoto 2020-05-22 um 07 14 45" src="https://user-images.githubusercontent.com/12561945/82633957-d7095b80-9bfc-11ea-81f4-51ecf64e370d.png">

<img width="1042" alt="Bildschirmfoto 2020-05-22 um 07 18 31" src="https://user-images.githubusercontent.com/12561945/82633959-d96bb580-9bfc-11ea-9d22-c35530edae07.png">

**Comment by shinra-electric** [comment]
I just checked again, and it still is not showing: 

![Screenshot 2020-05-22 at 12 46 48](https://user-images.githubusercontent.com/50119606/82635475-755fe600-9c2a-11ea-9393-58f795c3a242.png)

(note: it's probably not a good idea to try to turn on a pirate...)

I'm using this version: 
![Screenshot 2020-05-22 at 12 42 47](https://user-images.githubusercontent.com/50119606/82635508-8c9ed380-9c2a-11ea-8d4d-18b502bca9a7.png)

Could it be a settings thing?

**Comment by dirkwhoffmann** [comment]
> Could it be a settings thing?

Maybe yes. I run the game in v0.9.7 with an A500 + 512 Slow Ram (it doesn't boot without Slow Ram) and "Standard" compatibility settings. 

There is a debugging option for hiding sprites (Menu "Edit -> Debug -> Hide Sprites"). Can you check if there are checkmarks on certain sprite numbers? (There should be none by default.)

**Comment by shinra-electric** [comment]
This copy boots fine with just 1MB of chip RAM and no Slow RAM. I tried it with 512KB of Slow RAM, but it made no difference. 

I have no sprites hidden, and here are my settings: 

![Screenshot 2020-05-22 at 13 11 49](https://user-images.githubusercontent.com/50119606/82637198-77c43f00-9c2e-11ea-82ca-d96c9fa82ca3.png)

![Screenshot 2020-05-22 at 13 07 18](https://user-images.githubusercontent.com/50119606/82637182-7135c780-9c2e-11ea-86ab-942d80e11632.png)

**Comment by dirkwhoffmann** [comment]
I guess it's the Kickstart. Considering how old the game is, you are using a Rom from the future. Could you try to run the game with Kick 1.3?

**Comment by mithrendal** [comment]
Yes  the OS is maybe too modern 😁

**Comment by shinra-electric** [comment]
I don't have Kick 1.3, but I tried it out with Kick 2.04 (for an A500+) and the cursor is now visible. I can now accurately target the important-looking pirates. 

![Screenshot 2020-05-22 at 13 35 08](https://user-images.githubusercontent.com/50119606/82638493-32edd780-9c31-11ea-85d2-6052334873cd.png)

In the future I'll try a couple of Kickstart versions in my testing, but do you have any preference of what we should be testing with? The Rom from the future might hold the secret of why this title doesn't boot without slow ram in 1.3...

**Comment by dirkwhoffmann** [comment]
> Yes the OS is maybe too modern

We're dealing with pirates here. At that time, they did not even have color TV 😲.

**Comment by dirkwhoffmann** [comment]
> but do you have any preference of what we should be testing with?

I usually test with the A500 settings with an additional 512 KB of SlowRam, Kickstart 1.3 and the "Standard" Compatibility settings. The "Accurate" settings add collision detection, but only a very titles need this. Collision detection is time-consuming, so I usually have it switched off.

**Comment by shinra-electric** [comment]
Fixed in v0.9.10.1 by #399

![Screenshot 2020-08-05 at 17 54 04](https://user-images.githubusercontent.com/50119606/89404993-0d0ea400-d745-11ea-85a2-267284dcd445.png)

**Comment by dirkwhoffmann** [comment]
Monkey Island in Dark Mode. Very cool! 😎 But wait... this "Dark Mode" looks different than the "Dark Mode" posted above... is this vAmiga on macOS BigSur? 🤔

**Comment by shinra-electric** [comment]
Yep, it's been Big Sur-ified...
