### ISSUE TITLE
Crack screen graphics corruption - Ram issue? [Beastlord] (Felon) (0.9.7) (Kick 1.3)

### ISSUE THREAD

**Issue by shinra-electric** [dirkwhoffmann/vAmiga#353]
So, with Kick 1.3 and 1MB of Chip Ram, no slow ram and no fast ram the two crack screens look like this: 

![Screenshot 2020-05-23 at 12 11 07](https://user-images.githubusercontent.com/50119606/82722255-2af46d00-9cef-11ea-940c-f26ee0c0970f.png)
![Screenshot 2020-05-23 at 12 11 18](https://user-images.githubusercontent.com/50119606/82722257-2fb92100-9cef-11ea-8a5f-fc3f4f1fd5fb.png)

With 512k of chip Ram, and either 512k or no slow Ram: 

![Screenshot 2020-05-23 at 12 13 05](https://user-images.githubusercontent.com/50119606/82722286-7444bc80-9cef-11ea-9d51-0f1ca223c34b.png)
![Screenshot 2020-05-23 at 12 13 11](https://user-images.githubusercontent.com/50119606/82722291-77d84380-9cef-11ea-80ca-cfb17e80c487.png)

With any combination but also throwing in some fast ram, it's just a white screen: 
![Screenshot 2020-05-23 at 12 15 38](https://user-images.githubusercontent.com/50119606/82722296-93dbe500-9cef-11ea-869a-9410f3013c11.png)

**Comment by dirkwhoffmann** [comment]
I've just run the game in UAE and it behaves the same way (the logo is fine only if 1 MB Chip is selected). The logo is draw with sprite 6 and sprite 7 btw.

Throughout the day, I'll check 
- how the game looks like on my A500 (which has the most common 512 + 512 configuration)
- if it produces garbage output in UAE with FastRam enabled

**Comment by dirkwhoffmann** [comment]
Confirmed: UAE also shows the white screen with FastRam enabled and the icon appears black on a real A500 with 512 KB Chip + 512 KB Slow.

![IMG_3113](https://user-images.githubusercontent.com/12561945/82734190-7c195680-9d19-11ea-85be-125731a3b39d.JPG)

Please keep on posting. It doesn't matter if it's a false alarm.
