### ISSUE TITLE
Alpine9000 test case #5 fails

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#36]
Reference: 

![screenshot](https://user-images.githubusercontent.com/12561945/58703482-2251ab00-83a9-11e9-84fd-1ae9cdbd0b29.png)

vAmiga 🙈:

<img width="916" alt="Screenshot 2019-05-31 at 13 34 59" src="https://user-images.githubusercontent.com/12561945/58703503-34cbe480-83a9-11e9-90e3-c01542978429.png">

**Comment by dirkwhoffmann** [comment]
Fore reference (start of Copper list): 

<img width="371" alt="Screenshot 2019-05-31 at 13 40 16" src="https://user-images.githubusercontent.com/12561945/58703692-c20f3900-83a9-11e9-88e8-5ce4b9bb29ae.png">

**Comment by dirkwhoffmann** [comment]
Culprit is function Copper::nextTriggerPosition(). The function is super fast, but  plainly wrong 🥴. Need to think about a smart solution that is both correct and speedy ...

**Comment by dirkwhoffmann** [comment]
<img width="916" alt="Screenshot 2019-06-01 at 11 09 11" src="https://user-images.githubusercontent.com/12561945/58746448-969a5600-845e-11e9-9d6d-eb5dc1f82c63.png">

With the current architecture of vAmiga, this is the expected result. vAmiga draws the border at the end of each rasterline with the current background color. Hence, the left border always has the same color as the right border.

Todo: 

1. Use the new super-cool TimeRecorded<uint16_t> template class for all color registers (😎). 
2. After that, check color register timing (vAmiga doesn't emulate color register delays yet).

**Comment by dirkwhoffmann** [comment]
<img width="916" alt="Screenshot 2019-06-02 at 10 58 08" src="https://user-images.githubusercontent.com/12561945/58759166-f4de3c00-8525-11e9-88eb-cc9ba2d7760d.png">

Seems to be alright now.

**Comment by mithrendal** [comment]
Looks very neat 🤗
