### ISSUE TITLE
Demo "Fate" works, but is not supposed to

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#367]
[Fate.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/4776117/Fate.adf.zip)

<img width="939" alt="Bildschirmfoto 2020-06-14 um 11 11 18" src="https://user-images.githubusercontent.com/12561945/84589567-d34dab00-ae2f-11ea-88c8-54992fe56676.png">

This demo is *not* supposed to work. The screen remains black on both the real machine and in UAE 4.3.0. The demo is from 2010. It may rely on older UAE emulator bugs that have been ruled out in the meantime.

**Comment by mithrendal** [comment]
So the demo software works as intended in vAmiga 😎? Does this imply that vAmiga AND the demo is buggy then 🥴?

**Comment by Gianmarco72** [comment]
In SAE it works too.🤔

**Comment by dirkwhoffmann** [comment]
The demo stopped working in v0.9.10.1 (Woohoo 🥳)

The reason is the in initial state of the TOD clock (same as #364). Why is the initial TOD state so important? Because it decides if a TDO alarm interrupt is executed during the boot phase and the interrupt handler modifies some bit in INTENA (or was it DMACON? 🤔). Anyways. Some demos rely on the initial value of this register and fail if the alarm interrupt was executed.
