### ISSUE TITLE
Demo "1991 Dragonlance Calendar, The (1990)" not work

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#369]
[1991 Dragonlance Calendar, The (1990)(Vox Dei).adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/4776708/1991.Dragonlance.Calendar.The.1990.Vox.Dei.adf.zip)

Demo starts normally and music playing.
<img width="912" alt="Schermata 2020-06-14 alle 16 57 34" src="https://user-images.githubusercontent.com/45571833/84597224-d615c380-ae62-11ea-954a-1367b0ad658a.png">
After pressing the mouse button on this screen, the demo stops and Paula plays a sound like "car engine" 😖

It works on SAE:
![Sae1](https://user-images.githubusercontent.com/45571833/84597365-d5c9f800-ae63-11ea-9b52-1c8b79206bd1.jpg)
![Sae2](https://user-images.githubusercontent.com/45571833/84597367-db274280-ae63-11ea-84c0-b1cbed046ccb.jpg)

**Comment by dirkwhoffmann** [comment]
It works well in Blitter level 0 (FastBlitter). In level 1 and level 2, Paula emulates a formula 1 race 😬.

**Comment by Gianmarco72** [comment]
😂

**Comment by dirkwhoffmann** [comment]
Same with the calendar from 1988:
[VoxDei-drkalender88.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/4835327/VoxDei-drkalender88.adf.zip)

**Comment by dirkwhoffmann** [comment]
Hmm, my latest comment seems to have been removed...

Short version: It's not a bug, the sound is scrambled on the real machine, too. In UAE, the scrambled sound can be reproduced if neither "Immediate Blitter" nor "Wait for Blitter" is enabled.
