### ISSUE TITLE
Alpine9000 test case #7 fails

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#37]
Reference: 

<img width="743" alt="Screenshot 2019-06-02 at 11 22 13" src="https://user-images.githubusercontent.com/12561945/58759380-46d49100-8529-11e9-82ad-2178fbf5aa5e.png">

vAmiga 🤨:

<img width="916" alt="Screenshot 2019-06-02 at 11 20 12" src="https://user-images.githubusercontent.com/12561945/58759415-bf3b5200-8529-11e9-8396-23cc5d8a309a.png">

**Comment by mithrendal** [comment]
The overall masked blitter logic works, but from where are these distortions come from... and why only at the end of the blitted area ??

**Comment by dirkwhoffmann** [comment]
> but from where are these distortions come from...

![dirty-mouse-small](https://user-images.githubusercontent.com/12561945/58759552-438ed480-852c-11e9-8182-b83e57d68af9.png)

**Comment by dirkwhoffmann** [comment]
Blitter is working fine. Bug is due to a corrupted blending mask: 

<img width="280" alt="Screenshot 2019-06-02 at 12 28 28" src="https://user-images.githubusercontent.com/12561945/58759979-6de39080-8532-11e9-8b61-ebf4b602c7ba.png">

Todo: Find out why the mask is corrupted.

**Comment by dirkwhoffmann** [comment]
Unexpectedly, it turned out to be a problem with the disk controller: 

Log from the last sector read: 

    Turbo read Df0: checksum = AD3369E1 (dskptr = 59E0)
    BLITTER Blit 1176 (32,187) (0101) 4b1e 2320 0 2060 
    BLITTER check1: d172369 check2: a9b7a285
    BLITTER Blit 1177 (8,32) (1101) 229e 249e 0 7d9fe D
    BLITTER check1: bd0840c5 check2: 25d097c5
    BLITTER Blit 1178 (8,32) (1101) 26de 28de 0 7dbfe D
    BLITTER check1: 54417b1d check2: bbaaffc5
    BLITTER Blit 1179 (8,32) (1101) 2b1e 2d1e 0 7ddfe D
    BLITTER check1: f6b8fc09 check2: 67072fc5
    BLITTER Blit 1180 (8,32) (1101) 2f5e 315e 0 7dffe D
    BLITTER check1: 4d1ec24 check2: 32f427c5
    BLITTER Blit 1181 (8,32) (1101) 2d5e 2f5e 0 7ddfe D
    BLITTER check1: fc84e17f check2: 67072fc5

Compared to SAE: 

    amiga.js:295 Disk DMA: Checksum = AD3369E1
    blitter.js:370 BLITTER Blit 123 (32,187) (0101) 4b1e 2320 0 2060 
    blitter.js:480 BLITTER check1: d172369 check2: a9b7a285
    blitter.js:494 BLITTER Blit 124 (8,32) (1101) 229e 249e 0 7d9fe D
    blitter.js:598 BLITTER check1: bd0840c5 check2: 25d097c5
    blitter.js:494 BLITTER Blit 125 (8,32) (1101) 26de 28de 0 7dbfe D
    blitter.js:598 BLITTER check1: 54417b1d check2: bbaaffc5
    blitter.js:494 BLITTER Blit 126 (8,32) (1101) 2b1e 2d1e 0 7ddfe D
    blitter.js:598 BLITTER check1: f6b8fc09 check2: 67072fc5
    blitter.js:494 BLITTER Blit 127 (8,32) (1101) 2f5e 315e 0 7dffe D
    blitter.js:598 BLITTER check1: 4d1ec24 check2: 32f427c5
    amiga.js:295 Motor off

vAmiga performs an additional (bogus) Blitter operation. It writes to '2d5e' and therefore overwrites data that was generated by the previous Blit. The overwritten area is where the blending mask is located in memory. Yet I don't know why the disk controller is doing this additional Blit ...

**Comment by dirkwhoffmann** [comment]
Disk controller had beed falsely accused. There was another bummer in, guess what, the Blitter implementation. Up to now, the Blitter immediately triggered a Blit operation when it's DMA channel got turned on. However, this doesn't make sense at all.

I guess I need to have a serious word with the guy who wrote that code. What the hell did he think he was gonna do? 🙄

<img width="280" alt="Screenshot 2019-06-02 at 15 38 38" src="https://user-images.githubusercontent.com/12561945/58762295-ed7f5880-854e-11e9-81e4-5572c599ae1e.png">
