### ISSUE TITLE
ADF loads in vAmiga, but is not supposed to

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#370]
[lohi1.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/4820352/lohi1.adf.zip)

Real machine and SAE: Guru
vAmiga: No issues

**Comment by dirkwhoffmann** [comment]
False alarm. The Guru appears if 512 KB + 512 KB is selected (same config as on the real machine). vAmiga had no SlowRam, but FastRam enabled.

**Comment by mithrendal** [comment]
With apples own silicon now moving to the Mac they have now, like the Amiga then tons of custom chips accessing the memory. Is that memory called now chip ram too? Maybe in next MacOS they introduce „invent“ FastRam like Amiga did. 😎✊🏿

They are learning from great computers of the past. I have read in a book that Steve Jobs visited the Amiga before commodore bought it. Then he said something like „too many custom chips too complicated hardware design“
Now in 2020 Apple does just execute Jay Miners vision of a computer with todays possibilities.

**Comment by dirkwhoffmann** [comment]
I don't know if the latest Apple news is good news, because they continue to shift the Mac architecture towards iOS. It doesn't surprise me, because they simply go where the money is. Using the ARM platform, it's much simpler for them to "lockdown" the system. If this happens, applications such as emulators would no longer be possible.

**Comment by mithrendal** [comment]
>applications such as emulators would no longer be possible.

... web editions should work, no?

I am with you. They can optical streamline it to the iOS look. I mean it is just flavor and who cares. It’s comparable to fashion wear , clothes and that sort of stuff. 
The real big points are 
*function. 
*filesystem.  
*Ability to install and develop what you like to (without a developer fee)

If they don’t touch these important points they can come with a new fashion every year.

**Comment by mithrendal** [comment]
>"lockdown" the system.

https://youtu.be/Hg9F1Qjv3iU

See at 53:05 john gruber poses this important question of lockdown in an live interview directly to craigh frederighi

**Comment by dirkwhoffmann** [comment]
Oh, at 53:something, he directly responds to me: „These guys [like me] are total fools“ 🤓. OK, let’s hope it’s going to happen how he promises. But can we trust him? 🤔 I think he has creepy hair 😬. Maybe I'm just too suspicious these days, but the word „Lockdown“ strikes a raw nerve in me 🙁.

**Comment by mithrendal** [comment]
Total tools he said. 😂. He is actually very funny. I trust him.

**Comment by dirkwhoffmann** [comment]
Another problem will be the impossibility of running Windows in a VM. We won't be able to run UAE any longer 😳.

> I trust him

He has creepy hair. Don't you see that? 🤔

**Comment by KenDFish** [comment]
> Another problem will be the impossibility of running Windows in a VM. We won't be able to run UAE any longer 😳.

Well ... one of the screenshots in the keynote still has Parallels running, so maybe there's hope ...

![image](https://user-images.githubusercontent.com/6280435/85770410-c9bb2180-b712-11ea-92e4-20b44500330f.png)

**Comment by dirkwhoffmann** [comment]
> one of the screenshots in the keynote still has Parallels running, so maybe there's hope ...

I guess they will have to emulate native i86 code like they did back in the day when Apple was using the PowerPC architecture. So we'll have an emulator running in an emulator 😳.

<img width="411" alt="Bildschirmfoto 2020-06-25 um 19 44 48" src="https://user-images.githubusercontent.com/12561945/85771855-9a111700-b71c-11ea-81de-7de7d4e16026.png">

On the positive side, the vAmiga logo will be easy to port.

**Comment by mithrendal** [comment]
>Another problem will be the impossibility of running Windows in a VM. We won't be able to run UAE any longer 😳.

yes true, a real disadvantage ... but we still have our intel macs ... for years (look I am using mine for 13 years now)... until they break. And we have real Amigas and ACA500+.

>He has creepy hair. Don't you see that? 🤔


so is he ...
![grafik](https://user-images.githubusercontent.com/17108995/85771081-de4fe780-b71b-11ea-9d71-13df2a8d36f6.png)

why not trust him despite creepy hair ?
![grafik](https://user-images.githubusercontent.com/17108995/85771800-8cf42800-b71c-11ea-9db3-0f547e8df3a9.png)

I certainly would ... see here how he saves peoples live
https://www.youtube.com/watch?v=ZOoJoTAXDPk

**Comment by mithrendal** [comment]
>I guess they will have to emulate native i86 code like they did back in the day when Apple was using the PowerPC architecture. So we'll have an emulator running in an emulator 😳.

thats why the ARM Macs so desperately are in need of vAmiga v1.0 ... 😅 ... I think frode will deliver a FSUAE ARM build as well as he has done in the past a version of FSUAE for PowerPC ... 

hey dirk the whole world does now emit ARM builts ... Microsoft just delivered with the last version of Visual Code support for ARM (despite windows) and ms-office ...

**Comment by mithrendal** [comment]
```
Visual Studio Code - May 2020 (version 1.46)
Update 1.46.1: The update addresses these issues.

Welcome to the May 2020 release of Visual Studio Code.

Windows ARM64 support - New VS Code Insiders ARM64 builds are available.

```

**Comment by mithrendal** [comment]
😎 Parallels can now host ACORN Archimedes with the ARM1 Processor natively... without emulation, no ?

https://en.wikipedia.org/wiki/Acorn_Archimedes
