### ISSUE TITLE
Add support for encrypted Roms

### ISSUE THREAD

**Issue by mstoebe** [dirkwhoffmann/vAmiga#372]
I have a copy of amiga forever and all the kickstart-files from th DVD on my harddisk. But I can't install them. The only kickrom file that's accepted ist the aros-file that came with amiga forever (but it's not working). The kickstarts all (all that I tested at least...1.2, 1.3, 2.04) work fine with fs-uae, so I guess they are intact.

What am I doing wrong?

**Comment by markcox** [comment]
Amiga forever ROMs are encrypted.
https://eab.abime.net/showthread.php?t=63645

**Comment by mithrendal** [comment]
Encoding is okay ... but patching the rom files with illegal opcodes is so mean 🥴. If I understand this correctly they did this only to prevent hardware copies of rom chips and have an advantage of being the only seller rom chips to real amigas back then in 1997. 🙈

Hmm right but they also write 🤔that there are original unpatched And unecoded files somewhere in the forever PLUS edition now ... see here


—————-
Some original technical limitations, which were in part a legacy of a 1997 wish by some licensors that Amiga Forever not compete with the sale of "real" upgrade ROMs for Amiga computers, were later removed. These restrictions were implemented by using some "illegal opcodes" and a ROM encoding combined with a "rom.key" file, support for which was added to the UAE and Fellow emulation projects in 1997. Amiga Forever **Plus** Edition now includes the full set of original unencoded Amiga ROMs 
———-


In this article https://www.amigaforever.com/kb/13-145



Another option would be for vAmiga to also do the depatching/decoding of these unoriginal and patched rom files in the amiga forever edition to turn them in something runnable like fs and win UAE are doing.

**Comment by mstoebe** [comment]
Well, I was just askign because the vAmige homepage made me somehow believe that I could just drag 6 drop the AF roms.

`By purchasing a license of Amiga Forever™ you can acquire a legal Kickstart license. Rom image files can be added to vAmiga via drag and drop.`

Anyway, I have some original ROM-files on my Amiga 3000 that was equipped with eeproms to load a kickstart from my HDD...just have to find a way to get these out to my mac... :P

**Comment by mithrendal** [comment]
> made me somehow believe ...
@mstoebe 
I think you are completely right. This is confusing... when reading this one might really think it should work...

@dirkwhoffmann I think this should be either clarified in the text or the decode and depatch should be supported at least for vAmiga 1.0, no?

**Comment by dirkwhoffmann** [comment]
> This is confusing... when reading this

When I wrote this, I didn't know that older AmigaForever Roms were patched. Is there any documentation how the rom.key files work?

**Comment by mstoebe** [comment]
> @mstoebe do you have the plus edition?
> Maybe if you have the plus edition you might like to find the unpatched original romfiles and try to start vAmiga with these.

I have a Plus Edition but it's v6 and I couldn't find any unencrypted ROMs. Just searched through the ISO this morning. :( Maybe they were added with a later version. The linked article doesn't make it clear when they started shipping this, at least as far as I can see.

**Comment by mithrendal** [comment]
The patching is described in the eab link from markcox above. It was something like ... they turned a bit in each move.l op code.  

But the best approach would be to find the decode code in fsua, no?

**Comment by dirkwhoffmann** [comment]
I've read the article and I think it should be pretty easy to support Roms which are encrypted by a romkey file. I think the 3.0 and 3.1 Rom stuff can be ignored for vAmiga, because they require different (virtual) hardware anyway. 

Now the main problem is that I don't have any encrypted Roms 🙄. I checked the AmigaForever version that came with the c't Retro magazine, but I don't find any Roms there, just some strange files called "RetroPlatform file".

**Comment by mstoebe** [comment]
I also habe the ct-Wdition. I will have a look as well when I return from my weekend trip. :)

**Comment by mstoebe** [comment]
Ha, forgot that I finally enabled remote access to my NAS ;)

My ct-Edition is from 2013 and has three rom-Files in /shared/roms just like AF normally has but there is no key.rom to be seen anywhere. So maybe these are unencrypted rom indeed.

**Comment by dirkwhoffmann** [comment]
> So maybe these are unencrypted rom indeed.

But if they were original unencrypted Roms, vAmiga would accept them. Maybe the Cloanto Roms contain the same header signature as the encrypted ones? 🤔 Could you post the file size of the Kick 1.3 Rom please?

**Comment by mithrendal** [comment]
@mstoebe could you attach the public key file and only the first 32 Bytes of a rom.  Which should be absolutely ok and not violating any copyright issues but would provide @dirkwhoffmann a sufficient view on the data and let him develop and test the decoding...

**Comment by mstoebe** [comment]
So, back at home I just had a look at the kick1.3 romfile from AF c't-collection and from AF Plus 6 and both seem to be exactly the same. Maybe the keyfile in the c't-Edition got included somewhere in the executables? Anyway, Size for both is 262155 Bytes.

Here's the beginning of the file as dumped by bbedit:
00000000: 41 4D 49 52 4F 4D 54 59 50 45 31 2F 2F 70 D9 43 	AMIROMTYPE1//p.C
00000010: B0 4F 93 4E 54 B0 DF AE 02 43 49 4F 63 4E 56 B0 	.O.NT....CIOcNV.

As for posting the keyfile: I'm not sure if this is a good idea. It's part of the distribution and the license within the keyfile even says it must not be distributed outside the full AF distribution. I guess the best thing would be to ask Cloanto for permission and/or purchase an AF license for development. I'm throwing 10€ in the hat for a dev-license...

**Comment by mithrendal** [comment]
first I think that ... dirk has the AF value edition which came with the CT ...

![grafik](https://user-images.githubusercontent.com/17108995/86569335-8791ab80-bf6e-11ea-973b-6410c9fa682b.png)


https://shop.heise.de/katalog/ct-special-27-2019?wt_pdsrc=slider



second ... I have found this ... 

https://github.com/FrodeSolheim/fs-uae/blob/master/src/rommgr.cpp

```
int decode_cloanto_rom_do (uae_u8 *mem, int size, int real_size)
{
	int cnt, t, i;

	for (i = ROM_KEY_NUM - 1; i >= 0; i--) {
		uae_u8 sha1[SHA1_SIZE];
		struct romdata *rd;
		int keysize = keyring[i].size;
		uae_u8 *key = keyring[i].key;
		if (!key)
			continue;
```

**Comment by mstoebe** [comment]
Hm, I also got the retro issue but never bothered downloading the AF that came with it since I already owned an older c't-edition-AF from 2013 and meanwhile also bought a Plus-Edition on my own. :D And now the DL for the retro issue is closed. ;)

Anyway...somewhere in there must be some kick-roms for sure. But as with the free version from 2013 there maybe noch key-File to be found anywhere.

**Comment by dirkwhoffmann** [comment]
Just bought a Premium-Edition of AmigaForever 8 from Cloanto as well as a Limited Edition of AmigaForever 6 on eBay. Once the packages are here, sky should be clearing up...

**Comment by dirkwhoffmann** [comment]
First package has arrived 😎

![IMG_4251](https://user-images.githubusercontent.com/12561945/87638131-8cf7ae80-c743-11ea-9ccf-80866a9305a2.JPG)

It comes with an amiga-os-130.rom file and a rom.key file...

**Comment by mithrendal** [comment]
>It comes with an amiga-os-130.rom file and a rom.key file...

Ah I see ... due to the label "limited edition" on the package right ? But that is fine ... as 1.3 rom is probably the most used one in A1000/A500/A2000...

**Comment by mstoebe** [comment]
Great! Looks so absolutely retro...awesome!:D

What about that "build your own handheld"? What are they doing there...?

**Comment by dirkwhoffmann** [comment]
Running the protected Cloanto Rom in vAmiga: 😎

<img width="1018" alt="Bildschirmfoto 2020-07-16 um 11 58 33" src="https://user-images.githubusercontent.com/12561945/87658152-131fef00-c75c-11ea-844d-db05f5a0d3b6.png">

Let's check the Rom settings...

<img width="644" alt="Bildschirmfoto 2020-07-16 um 09 37 46" src="https://user-images.githubusercontent.com/12561945/87658298-4bbfc880-c75c-11ea-85b5-c18b4bb66e17.png">

😮 Oups, the decrypted Rom is unknown... so either the decryption routine is wrong or the Rom is strange...

Luckily, Cloanto provides a detailed overview of Roms here: https://cloanto.com/amiga/roms/

Here we go: The decryption routine worked and we got a A3000 SK Rom: 

    V. 1.3 | Dec 1987 | 34.005 | ROM |   | 262144 | FC0000 | 68000 | A3000 SK | Release | Good | 1.0 | E0F37258

Never heard of an A3000 SK before...

With some luck, the decryption routine will work for other Roms and key.rom files as well. If not, I can get them to work if somebody provides me the files...

**Comment by mithrendal** [comment]
Nice !! I can't see the key file in the rom settings ? Is it already preloaded inside vAmiga, and we only have to drag the encoded rom into it ?

**Comment by dirkwhoffmann** [comment]
>  I can't see the key file in the rom settings ?

Decoding takes place very early. When an encrypted Rom is dragged it, vAmiga immediately looks for a file named "rom.key" in the same directory and decodes the data on-the-fly. For the emulator, there is no difference between an encrypted and a non-encrypted Rom. Once the Rom has been loaded in, the emulator can't even tell where the Rom data came from. The user does not need to know anything about rom.key files. As long as the rom.key file is in the same directory, everything will work out of the box.

**Comment by mithrendal** [comment]
for vAmigaWebEdition I have to upload the rom.key too ... because the browser does not  give me the access to the same folder ... but I think that is fine ... I will let the user drag everything in vAmigaWeb and start the decoding when all pieces are uploaded ...

**Comment by dirkwhoffmann** [comment]
vAmigaWebEdition 🤤

**Comment by mithrendal** [comment]
First I have to fine tune vc64web. I still like to add one mighty feature. “custom key overlay buttons“ with that you can game specific add buttons on the screen... when that all is done I want to do vAmigaWeb 🤤

**Comment by dirkwhoffmann** [comment]
> First I have to fine tune vc64web

Yes, sure. vAmigaWeb is just something to dream about. And we shouldn't hurry too much. We need something to work on during the upcoming lockdowns... 😳

![IMAGE 2020-06-08 17:41:18](https://user-images.githubusercontent.com/12561945/87672046-9fd5a780-c772-11ea-9176-9ec609298bdc.jpg)

**Comment by dirkwhoffmann** [comment]
> What about that "build your own handheld"? What are they doing there...?

Not really sure (I had to watch it without sound). I think it's a remake of "The Silence of the Lambs" or something. Some story about a crazy guy torturing his poor Atari 2600 in his basement with different kinds of instruments. Scary stuff 😬. 

<img width="909" alt="Bildschirmfoto 2020-07-16 um 17 57 32" src="https://user-images.githubusercontent.com/12561945/87694075-03210300-c78e-11ea-9384-355bbcf934ce.png">

**Comment by dirkwhoffmann** [comment]
The second package has just arrived, including a large number of Roms: 😎

![IMG_5814](https://user-images.githubusercontent.com/12561945/88041216-5e664300-cb4a-11ea-8299-14404714e85a.JPG)

Interestingly, there is a rom.key file, just as there is in AmigaForever6: 😳

<img width="554" alt="Bildschirmfoto 2020-07-21 um 11 54 02" src="https://user-images.githubusercontent.com/12561945/88041326-85bd1000-cb4a-11ea-8264-abcecf653969.png">

Now, I am confused. It was my understanding that Cloanto stopped encrypting the older Roms at some point in time. But this doesn't seem to be true. 🤔

**Comment by dirkwhoffmann** [comment]
v0.9.9 is online.
