### ISSUE TITLE
DMS support

### ISSUE THREAD

**Issue by emoon** [dirkwhoffmann/vAmiga#378]
Hi,

Something that would be useful would be to support loading DMS images directly in vAmiga. DMS files (which are compressed Amiga images) are quite common and while it's possible to use a tool to extract them first being able to use them directly would make it less of a hassle.

Code for xdms can be found here https://gitlab.com/heikkiorsila/xdms.git and it's likely quite easy to just take out the code required for adding support in vAmiga for this

Example file https://files.scene.org/view/mirrors/amigascne/Groups/S/Sanity/Sanity-Arte.dms

**Comment by dirkwhoffmann** [comment]
Hi Daniel. Thanks a lot for pointing me to xdms. It was fairly easy to integrate. The next version of vAmiga will support the DMS format (as well as ADZ files):

<img width="895" alt="Bildschirmfoto 2020-07-09 um 10 27 32" src="https://user-images.githubusercontent.com/12561945/87016428-fc632080-c1ce-11ea-855b-e2287de1b776.png">

**Comment by emoon** [comment]
Awesome! :)

**Comment by mithrendal** [comment]
🤤

**Comment by dirkwhoffmann** [comment]
Supported in v0.9.9 which is now online.

**Comment by emoon** [comment]
Awesome :)
