### ISSUE TITLE
Graphics glitches in "Plasma Source - New stuff"

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#380]
[PlasmaForce-NewStuff.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/4911551/PlasmaForce-NewStuff.adf.zip)

vAmiga: 🙈

<img width="1018" alt="Bildschirmfoto 2020-07-13 um 11 25 39" src="https://user-images.githubusercontent.com/12561945/87288851-30ef1900-c4fc-11ea-82b4-44a17145de9f.png">

**Comment by tonioni** [comment]
Vertical sprite most likely is the usual not that rare bug: DMA was disabled while mouse pointer is visible (instead of doing it in vblank).

Horizontal glitch is the "real" glitch.

**Comment by dirkwhoffmann** [comment]
This is how it looks like with the latest code changes: 😎

<img width="1018" alt="Bildschirmfoto 2020-07-13 um 12 29 11" src="https://user-images.githubusercontent.com/12561945/87335792-25721100-c541-11ea-9c10-09bd6cc5d376.png">

The Icewind demo look slightly worse though: 😬 (I haven't implemented the SPRxPTR stuff yet. I only drop writes to BPLxPTR at the moment)

<img width="1018" alt="Bildschirmfoto 2020-07-13 um 14 40 52" src="https://user-images.githubusercontent.com/12561945/87335833-3884e100-c541-11ea-8525-ad9e1753f93c.png">

In UAE, it's definitely nicer: 😃

<img width="718" alt="Bildschirmfoto 2020-07-13 um 14 43 06" src="https://user-images.githubusercontent.com/12561945/87336074-9adde180-c541-11ea-8ac4-5b8e37e944d1.png">

**Comment by dirkwhoffmann** [comment]
Fixed in v0.9.9
