### ISSUE TITLE
Graphics glitches in "Icewind" demo

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#381]
[Icewind.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/4917385/Icewind.adf.zip)

 UAE: 😃

<img width="718" alt="Bildschirmfoto 2020-07-13 um 14 43 06" src="https://user-images.githubusercontent.com/12561945/87336074-9adde180-c541-11ea-8ac4-5b8e37e944d1.png">

vAmiga: 🙈

<img width="1018" alt="Bildschirmfoto 2020-07-14 um 10 00 25" src="https://user-images.githubusercontent.com/12561945/87400383-0616ca80-c5b9-11ea-867b-0158d8f9005f.png">

**Comment by dirkwhoffmann** [comment]
First findings (X ray): 😷

<img width="1018" alt="Bildschirmfoto 2020-07-14 um 10 24 49" src="https://user-images.githubusercontent.com/12561945/87403075-b33f1200-c5bc-11ea-8935-1a854ab201cf.png">

Upper region has 2 bitplanes enabled and looks OK. Middle region has 4 bitplanes enabled and is broken.

Relevant part of Copper list:

<img width="404" alt="Bildschirmfoto 2020-07-14 um 10 27 31" src="https://user-images.githubusercontent.com/12561945/87403152-c81ba580-c5bc-11ea-8983-51b281651aa6.png">

Could be a DDFSTRT, DDFSTOP timing issue.

**Comment by mithrendal** [comment]
https://youtu.be/IJEO3rmefmI

Maybe this wedding gun fireworks helps ... to make the bug go away and vanish????

It is very loud 🙉 ... keep your ears covered

**Comment by dirkwhoffmann** [comment]
> Maybe this wedding gun fireworks helps ... to make the bug go away and vanish, no????

Actually that helped 🥳. I think I know what it is...

**Comment by dirkwhoffmann** [comment]
Here is the thing: 

<img width="404" alt="87403152-c81ba580-c5bc-11ea-8983-51b281651aa6" src="https://user-images.githubusercontent.com/12561945/87876391-31921e80-c9d8-11ea-9f2d-fcc0bc4795aa.png">

In raster line $60, updateBplEventTable() is called twice. The first call is triggered by the write to BPLCON0 and the second one by the write to BPLCON1. But there is write to DFFSTRT in between which causes trouble. The Copper list is set up in a way that makes the raster beam not to hit the DDSTRT value. Hence, no DMA takes place in this line on the original Amiga. The DDFSTRT handler recognized this correctly and clears the bitplane event table. But then, the second call to updateBplEventTable() happens which lets vAmiga restore the original bitplane event table. Hence, bitplane DMA is emulated in the rest of the raster line which lets the bitplane pointers get out of sync 🙈.

**Comment by dirkwhoffmann** [comment]
Old code: 

```
bool
Agnus::inBplDmaLine(u16 dmacon, u16 bplcon0) {

    return
    ddfVFlop                 // Outside VBLANK, inside DIW
    && bpu(bplcon0)          // At least one bitplane enabled
    && bpldma(dmacon);       // Bitplane DMA enabled
}
```

Proposed fix: 

```
bool
Agnus::inBplDmaLine(u16 dmacon, u16 bplcon0) {

    return
    ddfVFlop                 // Outside VBLANK, inside DIW
    && ddfstrtReached != -1  // Raster beam hits DDFSTRT value
    && bpu(bplcon0)          // At least one bitplane enabled
    && bpldma(dmacon);       // Bitplane DMA enabled
}
```

And here is the result: 😎

<img width="1018" alt="Bildschirmfoto 2020-07-19 um 16 09 27" src="https://user-images.githubusercontent.com/12561945/87876774-a8c8b200-c9da-11ea-8ade-49b5e4662c12.png">


Unfortunately, `inBplDmaLine()`is a very critical function. I hope this change doesn't break too much. 🙄

**Comment by mithrendal** [comment]
Now I think we have to write that paper about declaring war to a bug and about the needed perseverance  to win ... ✌️🤤

**Comment by dirkwhoffmann** [comment]
> Now I think we have to write that paper...

Definitely. Now image we combined it with the so fruitful "Priority Inversion Approach". This is going to revolutionize industry... 😎
