### ISSUE TITLE
Support for zipped ADFs (ADFs zipped up)

### ISSUE THREAD

**Issue by bnice** [dirkwhoffmann/vAmiga#382]
Hi,
Nice to see ADZ and DMS support :-). It would however be nice to support zipped up ADFs.  They only have the file extension ".zip" . This is the format most downloaded ADFs are in, they work with FS-UAE. It also happens to be format my ~200 ADF collection are in, at moment I have to unzip each one in order it to use it with vAmiga.

Regards,

Ben.

**Comment by dirkwhoffmann** [comment]
Is it ".adf.zip" or just ".zip"?

**Comment by mithrendal** [comment]
I think bnice thinks of a zip file with an ADF inside ... I saw these package form too ... especially  c64 files are packed like this ... vAmiga (or vc64) could handle that like this ...

1.drag a zip file into emulator screen
2.open the zip and look if any "mountable" ADF, DMS  is inside the zip 
3.if there is any inside just open the first of it  ...

( --- luxus version only --- )
4. if there are many disks inside the zip bring some sort of a dialog which allows to change disks inside zip

**Comment by dirkwhoffmann** [comment]
> 1.drag a zip file into emulator screen
> 2.open the zip and look if any "mountable" ADF, DMS is inside the zip
> 3.if there is any inside just open the first of it ...

Of course, this is doable. The current code is much simpler though. It tries to unpack XXX.adz to XXX.adf and if that fails, the emulator knows that the zip file doesn't contain a proper ADF. If XXX.zip contained XXX.adf, I could keep that simple approach.

**Comment by mithrendal** [comment]
> Of course, this is doable.

👀wait wait wait .... I have to re-study some old papers from university ...https://en.wikipedia.org/wiki/Computability_theory

 🙋🏻  Yes true ... I can confirm ... it is doable ... 🤗

**Comment by bnice** [comment]
Hi,
Sorry just got back to this. The file extentions are just ".zip" not ".adf.zip". They also are zip format as opposed ADZ's that are gzipped (according to wikipedia anyway).

Ben.

**Comment by mithrendal** [comment]
>The current code is much simpler though. It tries to unpack XXX.adz to XXX.adf and if that fails, the emulator knows that the zip file doesn't contain a proper ADF. If XXX.zip contained XXX.adf, I could keep that simple approach.

🙋🏻🙋🏻🙋🏻me me me ... do it the simple approach ... but with a small tweak ... 

when found XXX.zip then load the first .ADF file in alphabetical ascending order which is inside XXX.zip 


reason1:
XXX.zip does not always contain XXX.adf but maybe YYY.adf (it must not be necessarily the same name ...)

reason2:
XXX.zip contains multiple disks

XXX_1.ADF
XXX_2.ADF

**Comment by dirkwhoffmann** [comment]
> when found XXX.zip then load the first .ADF file in alphabetical ascending order which is inside XXX.zip

I've started to implement it this way. The new code will do the following when a .zip, .gz, or .adz file is loaded:

- Create a tmp directory in the Application Support folder. If the directory is already there, empty it.
- Copy the zipped file into that folder.
- Invoke a decompression tool in the background.
   - If suffix equals ".zip", invoke "/usr/bin/unzip".
   - If suffix equals ".gz", invoke "/usr/bin/gunzip".
   - If suffix equals ".adz", try both.
- Collect all files in the temporary folder ending with ".adf", ".dms", or ".vAmiga" (snapshots). 
- Sort the list alphabetically.
- Return the first entry.

From this point on, the same code is executed that would have been executed with a normal (unzipped) file.

The new approach has the advantage that the user can also zip snapshots (either with zip or gzip) and vAmiga will have no trouble reading them. 

No, please don't ask me to save snapshots in gzip format by default 🙈.

**Comment by bnice** [comment]
Awesome :-)

**Comment by dirkwhoffmann** [comment]
Fixed in v0.9.10

**Comment by bnice** [comment]
Hi Dirk,

Downed and gave it quick try and can confirm it now reads my zipped adfs, great work :-).

Thanks,

Ben.

On August 4, 2020 at 1:58 AM, Dirk Hoffmann <notifications@github.com> wrote:


Fixed in v0.9.10
