### ISSUE TITLE
Interlaced rendering

### ISSUE THREAD

**Issue by emoon** [dirkwhoffmann/vAmiga#386]
This one might be a bit tricky to solve as interlacing may be hard to get right, but I wanted to report this anyway.

Running the demo https://demozoo.org/productions/5312 http://ftp.amigascne.org/pub/amiga/Groups/A/Anarchy/ANARCHY-3dDemo2.dms

It has a bunch of interlaced effects and still images. Here is one example 

![001](https://user-images.githubusercontent.com/350822/88085372-09e0b900-cb86-11ea-8881-a8a7fb509c42.png)

The effect of it is more obvious when running the emulator but for example the text on the lower left is quite hard to read with the current implementation.

**Comment by dirkwhoffmann** [comment]
In theory, interlace mode isn't a problem for the emulator. It writes long and short frames into separate textures and utilizes a GPU shader to merge them into the final texture. The GPU shader is also utilized to emulate the flickering effect (if requested). Here, it seems like the short and the long frame get out of sync by two lines. If the lines marked with red arrows get moved to the lines marked with green arrows, the text should be readable:

<img width="864" alt="Bildschirmfoto 2020-07-21 um 19 24 22" src="https://user-images.githubusercontent.com/12561945/88086876-5200db00-cb88-11ea-9776-a80e4e887cee.png">

The only thing vAmiga can't handle is writes to VPOS and VHPOS that change the vertical rastertine position. I think Alien Breed is using this to emulate a broken TV effect.

**Comment by dirkwhoffmann** [comment]
Nailed it. The error was inside the screen buffer handler, which has to ensure that long and short frames are drawn into the correct frame buffer and that the correct buffer is handed over to the GPU. To make a long story short: The code was quite old and was written at a time when I didn't quite understand how the LOF bit works. I completely rewrote the code, and the demo looks much better now 😎: 

<img width="1018" alt="Bildschirmfoto 2020-08-18 um 15 44 20" src="https://user-images.githubusercontent.com/12561945/90521505-e6039980-e16a-11ea-9ec3-4aaa3dd540db.png">

Up close (with interlace flickering enabled. The merge shader darkens all rows that have been merged in from the texture of the previous frame):

<img width="857" alt="Bildschirmfoto 2020-08-18 um 15 45 02" src="https://user-images.githubusercontent.com/12561945/90521574-fae02d00-e16a-11ea-9bcb-b7ec13c522a7.png">

**Comment by emoon** [comment]
nice :)

**Comment by emoon** [comment]
Another good test may be this game http://hol.abime.net/273 If I remember correct the whole game is in high-res lace

**Comment by dirkwhoffmann** [comment]
Works well in both v0.9.10.1 and (yet) unreleased 0.9.11:

<img width="899" alt="Bildschirmfoto 2020-08-19 um 20 54 42" src="https://user-images.githubusercontent.com/12561945/90678478-0745b200-e25f-11ea-8501-a44870a1df1d.png">

Graphics is low-res lace: 

<img width="899" alt="Bildschirmfoto 2020-08-19 um 20 54 36" src="https://user-images.githubusercontent.com/12561945/90678495-0c0a6600-e25f-11ea-9453-4ab123958eb6.png">

BTW, interlace flickering was broken in recent releases. To generate a flicker effect, odd and even scanlines need to be switched at 30 Hz. Recent releases flicker with a rate of 60 Hz which is hardly visible. In v0.9.11, the flicker rate will be back at 30 Hz.

**Comment by dirkwhoffmann** [comment]
Fixed in v0.9.11
