### ISSUE TITLE
Floppy-Disk-Drive Test v0.5 (1988) Commodore

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#39]
When I run Commodore's drive test 

[Floppy-Disk-Drive Test v0.5 (1988)(Commodore).adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3246440/Floppy-Disk-Drive.Test.v0.5.1988.Commodore.adf.zip)

in SAE, I get the following error message: 

<img width="731" alt="Screenshot 2019-06-03 at 09 49 40" src="https://user-images.githubusercontent.com/12561945/58785430-bd36c900-85e5-11e9-88dd-573943141e74.png">

Does someone know how to run this tool? Seems to be a good test case for drive speed etc.

**Comment by Alessandro1970** [comment]
Hi,
sorry, but for that kind of test you'll need a real DDD floppy.
Dysan DDD floppies are Digital Diagnostic Disks: http://deramp.com/downloads/mfe_archive/011-Non-S100%20Computers%20and%20Boards/Osborne/Software/Dysan%20Interrogator/Dysan_Interrogator.pdf

**Comment by Alessandro1970** [comment]
https://www.amiga-news.de/de/forum/thread.php?id=8973&BoardID=1

**Comment by dirkwhoffmann** [comment]
> Dysan DDD floppies are Digital Diagnostic Disks:

Never heard about that 😯. 

So we better close this.
