### ISSUE TITLE
"Marble Madness" madness

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#40]
Experiments with SAE: 

1. Slow memory disabled => Runs just fine
2. Slow memory enabled => doesn't start
3. Drive head position reset to 0 when a read begins => doesn't start

**Comment by dirkwhoffmann** [comment]
Hmmm, it seems to hang in SAE, too. 

This is strange, because I remember to got the game loading in Omega until the title screen came up.

**Comment by dirkwhoffmann** [comment]
Marble madness starts in vAmiga when the drive head is not reset in pokeDSKLEN. In conclusion, the loader seems to require the emulation of a rotation disk (it must rotate even when DMA is off).  

<img width="916" alt="Screenshot 2019-06-05 at 17 32 32" src="https://user-images.githubusercontent.com/12561945/58969767-89f86380-87b8-11e9-8866-2bfb12f1c59c.png">

There is another issue though: I can't see no sprite 🧐. To be honest, this makes the game a little boring ☹️.

<img width="916" alt="Screenshot 2019-06-05 at 17 31 27" src="https://user-images.githubusercontent.com/12561945/58969928-c1ffa680-87b8-11e9-9abe-4b688ec64a8f.png">

Strange enough, sprite DMA is being performed as the DMA debugger reveals: 

<img width="916" alt="Screenshot 2019-06-05 at 17 33 04" src="https://user-images.githubusercontent.com/12561945/58969864-aac0b900-87b8-11e9-9294-5f489cf14680.png">

**Comment by dirkwhoffmann** [comment]
😯 In the latest version, I screwed up sprites completely. Paccer is now a blind game, too.  

<img width="916" alt="Screenshot 2019-06-06 at 14 27 02" src="https://user-images.githubusercontent.com/12561945/59032826-7b1cba00-8867-11e9-8126-71533485485c.png">

**Comment by dirkwhoffmann** [comment]
Sprites are back 😎:

<img width="1032" alt="Screenshot 2019-06-06 at 16 29 25" src="https://user-images.githubusercontent.com/12561945/59041619-4154af00-8879-11e9-9832-21ff2c303709.png">

But it still doesn't work right: There is no sound 😖.

**Comment by dirkwhoffmann** [comment]
As expected, Marble Madness writes into the audio registers directly via the CPU:

    ....
    [7628] ( 47, 50)  FC41A2: GCBD 67AC 0040: AudioUnit: pokeAUD2PER(12E)
    [7628] ( 47, 50)  FC41A2: GCBD 67AC 0040: AudioUnit: pokeAUD2VOL(17)
    [7629] ( 94,211)  FC41A2: GCBD 67AC 0040: AudioUnit: pokeAUD2PER(12E)
    [7629] ( 94,211)  FC41A2: GCBD 67AC 0040: AudioUnit: pokeAUD2VOL(23)
    [7630] ( 92, 62)  FC41A2: GCBD 67AC 0040: AudioUnit: pokeAUD2PER(12E)
    [7630] ( 92, 62)  FC41A2: GCBD 67AC 0040: AudioUnit: pokeAUD2VOL(2F)
    [7631] ( 49,222)  FC41A2: GCBD 67AC 0040: AudioUnit: pokeAUD2PER(12E)
    [7631] ( 49,222)  FC41A2: GCBD 67AC 0040: AudioUnit: pokeAUD2VOL(2C)
    [7631] ( 76,215)  FC36FC: GCBD 27AC 0040: AudioUnit: pokeAUD2LEN(8)
    [7631] ( 76,221)  FC3702: GCBD 27AC 0040: Agnus: pokeAUD2LCH(4)
    [7631] ( 76,221)  FC3702: GCBD 27AC 0040: Agnus: pokeAUD2LCL(634)
    ....

Right now, only DMA based audio is implemented. 

Todo: Need to find a smaller test case for DMA-less audio ... maybe from some Amiga audio programming book...

**Comment by dirkwhoffmann** [comment]
non-DMA based audio is working 😎.

**Comment by mithrendal** [comment]
👍🏻Great. As this is also a great game for multiplayer.
