### ISSUE TITLE
Doesn't start on MacOS Catalina

### ISSUE THREAD

**Issue by sebeichholz** [dirkwhoffmann/vAmiga#400]
Hi there,

when I try to start the app on MacOS Catalina I get this error message:

> „vAmiga.app“ kann nicht geöffnet werden, da Apple darin nicht nach Schadsoftware suchen kann.

How can I start vAmiga ?

**Comment by dirkwhoffmann** [comment]
> How can I start vAmiga ?

Usually, you should be able to open it by clicking the app icon with the right mouse button. Select "Öffnen" and tell the OS that you trust the application.

**Comment by sebeichholz** [comment]
Yeah that worked, thanks!! (listening to Turrican 2 title :-)  )
