### ISSUE TITLE
Free memory mismatch after loading Workbench

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#405]
A500 8A (512 Chip + 512 Slow, no RTC): 🥰

<img width="1006" alt="Bildschirmfoto 2020-08-20 um 19 01 27" src="https://user-images.githubusercontent.com/12561945/90802890-31a77600-e318-11ea-9627-534f121500f5.png">

UAE: 👍

<img width="721" alt="Bildschirmfoto 2020-08-20 um 19 00 42" src="https://user-images.githubusercontent.com/12561945/90802943-4c79ea80-e318-11ea-8d0f-377dd910487e.png">

vAmiga: 🙈

<img width="857" alt="Bildschirmfoto 2020-08-20 um 19 00 08" src="https://user-images.githubusercontent.com/12561945/90802962-569be900-e318-11ea-8c25-503880e174de.png">

SAE is off, because it emulates an RTC. I haven't found an option to disable it:

<img width="717" alt="Bildschirmfoto 2020-08-20 um 19 04 21" src="https://user-images.githubusercontent.com/12561945/90803017-687d8c00-e318-11ea-81ac-120478c1be2a.png">

I need to come up with an idea how to debug this... I have no idea at the moment, but I have the strong feeling that this bug is an important one.

Update: In UAE, enabling or disabling the RTC doesn't influence the amount of free memory.

Update 2: UAE and vAmiga match for Kick 1.2:

<img width="717" alt="Bildschirmfoto 2020-08-20 um 19 21 30" src="https://user-images.githubusercontent.com/12561945/90804636-cb702280-e31a-11ea-9a0c-aa3faa1726c2.png">

<img width="857" alt="Bildschirmfoto 2020-08-20 um 19 22 58" src="https://user-images.githubusercontent.com/12561945/90804645-ce6b1300-e31a-11ea-9b06-147c8af4606b.png">

**Comment by mithrendal** [comment]
This is a real crime story ... I am super excited about the reason of the mismatch

**Comment by mithrendal** [comment]
Fire up the sysinfo app and select memory details ... perhaps it gives us a hint...

**Comment by emoon** [comment]
What I would do: 

1. First make 100% sure all settings are identical running testing both case.
2. Use regular memory tools to see ranges and see where it differs.
3. Start dumping memory from UAE and compare with vAmiga, see where it differs
4. Start dumping memory from startup with CPU writes to memory from UAE, do the same for vAmiga, try to match up.

**Comment by dirkwhoffmann** [comment]
Adjusting the bank map seems to do the trick: 

<img width="859" alt="Bildschirmfoto 2020-08-24 um 13 56 27" src="https://user-images.githubusercontent.com/12561945/91043113-46835280-e613-11ea-8b3a-714c49643cd7.png">

If I disable the RTC, I get this: 

<img width="859" alt="Bildschirmfoto 2020-08-24 um 13 58 38" src="https://user-images.githubusercontent.com/12561945/91043464-ee991b80-e613-11ea-8e3c-5885012006c5.png">

On the one hand, this doesn't seem to be correct, because my original A500 has no RTC. On the other hand, I've seen this exact value in FSUA before. This needs closer investigation. Maybe I have to return special values when reading the clock bank even if no clock is present. 

BTW, sysinfo is happy now, too:

<img width="714" alt="Bildschirmfoto 2020-08-24 um 14 00 02" src="https://user-images.githubusercontent.com/12561945/91043723-649d8280-e614-11ea-8437-ed2a79f648ed.png">
<img width="968" alt="Bildschirmfoto 2020-08-24 um 14 00 21" src="https://user-images.githubusercontent.com/12561945/91043727-66674600-e614-11ea-9325-1dac0b6e5f69.png">
<img width="717" alt="Bildschirmfoto 2020-08-24 um 14 00 52" src="https://user-images.githubusercontent.com/12561945/91043731-68310980-e614-11ea-8a86-855e39c855b5.png">
<img width="968" alt="Bildschirmfoto 2020-08-24 um 14 01 13" src="https://user-images.githubusercontent.com/12561945/91043732-69623680-e614-11ea-86ea-450f6b362ee1.png">

Unfortunately, it doesn't fix the Jetsons issue which I hoped for. 😢

**Comment by dirkwhoffmann** [comment]
Fixed in v0.9.11
