### ISSUE TITLE
Barbarian bugs

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/vAmiga#41]
Barbarian Psignosys hangs before show the first intro.

[Barb.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3258955/Barb.adf.zip)

**Comment by dirkwhoffmann** [comment]
The emulator hangs in an infinite loop: 

<img width="372" alt="Screenshot 2019-06-06 at 07 43 24" src="https://user-images.githubusercontent.com/12561945/59009676-e39b7500-882e-11e9-8e60-058efffbc1cb.png">

BFDD00 is the CIAB interrupt control register.

**Comment by dirkwhoffmann** [comment]
After the first bug had been fixed, a lot of new bugs came up: 

1. Game loader hangs if a drive other than a turbo drive is selected.

2. Hacker intro screen is scrambled:

<img width="1032" alt="Screenshot 2019-06-09 at 14 18 54" src="https://user-images.githubusercontent.com/12561945/59159879-216af880-8ad0-11e9-81bf-37bd906356e2.png">

Reference (SAE): 

<img width="1276" alt="Screenshot 2019-06-09 at 15 33 35" src="https://user-images.githubusercontent.com/12561945/59159880-292a9d00-8ad0-11e9-9473-7efc78e1e13e.png">

3. Psygnosys screen is not shown (black screen).

4. Intro where Barbarian hits the chain with his weapon is flickering (graphics timing errors)

**Comment by Alessandro1970** [comment]
Once the intro starts the turbo mode does not stop (0.29)

**Comment by dirkwhoffmann** [comment]
> Once the intro starts the turbo mode does not stop (0.29)

Good catch. Turbo mode is directly linked to the drive motor which hints to a disk controller bug (might be related to #87)

**Comment by dirkwhoffmann** [comment]
Barbarians are evil!

First, an excerpt from the UAE / SAE documentation: 

    /* OCS/ECS:
     * reading write-only register causes write with last value in chip
     * bus (custom registers, chipram, slowram)

I didn't implement this, because vAmiga does not store the last bus value yet and I thought that no decent programmer would do such weird things. Well, Barbarians do: 

Excerpt from my SAE debug log 😯: 

    amiga.js:295 READING WRITE-ONLY-REGISTER 96
    amiga.js:295 Custom.get16_real() 00dff096 read = ffff. value written = 0000
    amiga.js:295 READING WRITE-ONLY-REGISTER 88
    amiga.js:295 Custom.get16_real() 00dff088 read = ffff. value written = 0000
    amiga.js:295 READING WRITE-ONLY-REGISTER 88
    amiga.js:295 Custom.get16_real() 00dff088 read = ffff. value written = 0000

Register 0x96 is DMACON. However, this shouldn't be an issue, because if 0 is written, nothing happens. 

Register 0x88 is COPJMP1. Maybe this is the way for Barbarians to start the Copper?? 🤔 We'll see...

**Comment by dirkwhoffmann** [comment]
Enough for today. Latest findings: 

    READING NON-OCS OR WRITE-ONLY REGISTER 88  dmacon = 0 dmaen = 200

The read access triggers a write access into the strobe register

    COPJMP: vpos = 289 old_hpos = 0 wasstopped: NaN oldstrobe: 1 state: 15 vblank: 0 SAEV_Copper_enabled_thisline: 0
    amiga.js:295 dmacon = 0 dmaen = 200
    amiga.js:295 COPJMP(2): cop_state.state = 14

State 14 = COP_strobe_extra

    amiga.js:295 Custom.get16_real() 00dff088 read = ffff. value written = 0000

Second read that triggers a write

    amiga.js:295 update_copper(until hpos 68)
    amiga.js:295 update_copper(until hpos 78)
    amiga.js:295 COP_strobe_delay1: vpos = 289 ($121) hpos = 70 ($46) dmacon = $380 dmaen = $200

All of a sudden, DMACON has changed to $380 which means that Copper DMA is enabled. TODO: Check when DMACON changed and who changed it.

**Comment by mithrendal** [comment]
[Rink_a_Dink-REDUX_by_Lemon-Point_(final).adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3414816/Rink_a_Dink-REDUX_by_Lemon-Point_.final.adf.zip)

Dirk enough for today, relax and enjoy this demo ! Runs so cool in your emu.

**Comment by dirkwhoffmann** [comment]
Wow, this is really kind of cool 😎. 

<img width="893" alt="Bildschirmfoto 2019-07-21 um 19 08 47" src="https://user-images.githubusercontent.com/12561945/61594329-04573880-abeb-11e9-9016-3d6c6f2bccf0.png">

😂

<img width="893" alt="Bildschirmfoto 2019-07-21 um 19 10 20" src="https://user-images.githubusercontent.com/12561945/61594344-3bc5e500-abeb-11e9-9444-1d4d8c9171dd.png">

🤭 Uhhh, a lot of DMA going on here (Copper is yellow)

<img width="893" alt="Bildschirmfoto 2019-07-21 um 19 12 31" src="https://user-images.githubusercontent.com/12561945/61594395-a119d600-abeb-11e9-94af-021561271690.png">
<img width="893" alt="Bildschirmfoto 2019-07-21 um 19 12 43" src="https://user-images.githubusercontent.com/12561945/61594397-a2e39980-abeb-11e9-9bd7-6b28ac63dd5a.png">

**Comment by mithrendal** [comment]
vAmiga a well oiled demo machine. 😀 The sound was also very cool. a real showcase of the brilliance of vAmiga and its development state that it has already reached. ✌️

**Comment by dirkwhoffmann** [comment]
Doing a write when reading a write-only register really does the trick 😎: 

<img width="893" alt="Bildschirmfoto 2019-07-22 um 08 14 04" src="https://user-images.githubusercontent.com/12561945/61611027-00fb9580-ac5b-11e9-8cb0-9b5c7e170ea3.png">

However, the animation errors are still there 🙈: 

<img width="893" alt="Bildschirmfoto 2019-07-22 um 08 14 19" src="https://user-images.githubusercontent.com/12561945/61611120-40c27d00-ac5b-11e9-8b2a-ad8c18b685e3.png">

Todo: Run SAE against vAmiga with Blitter checksums enabled. I don't trust my Blitter.

**Comment by dirkwhoffmann** [comment]
Bug is identified. Here's the thing: 

vAmiga:

    …
    BLITTER check1: 9fabf42b check2: f2be6d45
    [1137] (  5, 60)  06119A BCBSD- 43A8 0042 Agnus: pokeDMACON(8440)
    [1137] (  5, 70)  0611A2 BCBSD- 43A8 0042 Agnus: pokeDMACON(40)
    [1137] (  5, 70)  0611A2 BC-SD- 43A8 0042 Agnus: Blitter DMA switched off
    [1137] (  6, 52)  06119A BC-SD- 43A8 0042 Agnus: pokeDMACON(8440)
    [1137] (  6, 52)  06119A BCBSD- 43A8 0042 Agnus: Blitter DMA switched on
    [1137] (  6, 62)  0611A2 BCBSD- 43A8 0042 Agnus: pokeDMACON(40)
    [1137] (  6, 62)  0611A2 BC-SD- 43A8 0042 Agnus: Blitter DMA switched off
    [1137] (  7, 44)  06119A BC-SD- 43A8 0042 Agnus: pokeDMACON(8440)


SAE:

    …
    BLITTER check1: 9FABF42B check2: F2BE6D45
    amiga.js:295 DMACON($8440,68)
    amiga.js:295 DMACON($40,78)
    amiga.js:295 BLTSIZE 12816 ($3210)
    amiga.js:295 DMACON($8440,58)
    blitter.js:362 BLITTER Blit 151 (16,200) (1001) 64a84 718e 0 78304 
    amiga.js:295 BLITTER check1: A960519 check2: 52C17C45
    amiga.js:295 DMACON($40,68)

In SAE, the Blitter is started immediately once it's DMA channel gets enabled. Not in vAmiga, because I didn’t know that the Blitter can be in a „pending“ state (waiting for the DMA channel to be enabled). My Blitter ignores any write to BLTSIZE if Blitter DMA is off.

This is a serious bug that is likely to affect many other programs, too. 

Before fixing it, I need to think about a suitable SW architecture though...

**Comment by dirkwhoffmann** [comment]
😎

<img width="893" alt="Bildschirmfoto 2019-07-22 um 13 01 55" src="https://user-images.githubusercontent.com/12561945/61628247-0b7d5580-ac82-11e9-8af0-8996f33dfb9d.png">


<img width="893" alt="Bildschirmfoto 2019-07-22 um 13 05 23" src="https://user-images.githubusercontent.com/12561945/61628131-ba6d6180-ac81-11e9-8f10-70aec662faf2.png">

I watched a long play video on Youtube about this game and it looked so easy 🤨.
Unfortunately, it is not. Game over after seconds 😖.

**Comment by dirkwhoffmann** [comment]
Obliterator is working, too. I used to play this a lot and still remember the very cool sound track 😎.

<img width="893" alt="Bildschirmfoto 2019-07-22 um 13 16 25" src="https://user-images.githubusercontent.com/12561945/61628655-374d0b00-ac83-11e9-945c-d0b2e7568ff7.png">

<img width="893" alt="Bildschirmfoto 2019-07-22 um 13 18 01" src="https://user-images.githubusercontent.com/12561945/61628665-3f0caf80-ac83-11e9-8052-12a5d1cac2b8.png">

**Comment by Alessandro1970** [comment]
...next step: Shadow of the Beast !!!
...then Agony...

**Comment by dirkwhoffmann** [comment]
I've never played Shadow of the Beast, but I read that it's is pushing the machine to it's limits. Will surely take a long time until it's working in vAmiga.

**Comment by Alessandro1970** [comment]
Does it not start on vAmiga ?

**Comment by Alessandro1970** [comment]
...the character could be a relative of the one used in Brataccas... very ugly...

**Comment by dirkwhoffmann** [comment]
> Does it not start on vAmiga ?

🙄 Noooooo

**Comment by Alessandro1970** [comment]
Strange! I remember to load it with version 0.2 or something like...
VAmiga had some graph error in the background, but the characther run...
There was an orrible load system...when the screen comes black, I remember to change disk and press mouse...

**Comment by mortinus** [comment]
...relatives... yes :+1: 

![Shadow_of_the_Beast](https://user-images.githubusercontent.com/41686391/61634245-34591700-ac91-11e9-8f0d-10db4c6738a5.jpg)
