### ISSUE TITLE
Macintosh Emulator A-Max hangs

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#410]
Emulator Disk Transformer v1.21 - A-Max - Go-64! V2.0 - BBC (1988)(-)(De).adf

To reproduce, select „Mac“ from the start menu…

UAE:

<img width="722" alt="Bildschirmfoto 2020-09-16 um 20 38 53" src="https://user-images.githubusercontent.com/12561945/93378821-44509480-f85d-11ea-904e-e773d205fea9.png">

vAmiga: 

<img width="900" alt="Bildschirmfoto 2020-09-16 um 20 39 56" src="https://user-images.githubusercontent.com/12561945/93378839-4a467580-f85d-11ea-929a-692bd8e8335f.png">

VAmiga hangs in an infinite loop waiting for bit 1 to be set in INTREQR. Bit 1 is the DSKBLK interrupt (Disk DMA finished).

<img width="980" alt="Bildschirmfoto 2020-09-16 um 20 40 10" src="https://user-images.githubusercontent.com/12561945/93378853-4e729300-f85d-11ea-9def-46f845c4aded.png">

**Comment by dirkwhoffmann** [comment]
This one is strange. The program changes the direction of the PRA bits in CIA A. Usually, only bit 0 and 1 are configured as output:

<img width="484" alt="Bildschirmfoto 2020-09-17 um 18 37 35" src="https://user-images.githubusercontent.com/12561945/93500847-eed7be80-f914-11ea-9b2a-94f8f1c308e2.png">

But here, bit 2, 3, and 4 are outputs, too.

<img width="980" alt="Bildschirmfoto 2020-09-17 um 18 34 36" src="https://user-images.githubusercontent.com/12561945/93500858-f26b4580-f914-11ea-9d65-20ade357882b.png">

Just before the freeze, the program sets the DSKCHG bit to 1. What could that be for? 🤔

<img width="980" alt="Bildschirmfoto 2020-09-17 um 18 32 41" src="https://user-images.githubusercontent.com/12561945/93500987-1e86c680-f915-11ea-94e7-2a71a02ee31b.png">

**Comment by dirkwhoffmann** [comment]
Interesting: This program writes into DSKLEN with no drive selected 😮. Definitely a smoking gun...

**Comment by dirkwhoffmann** [comment]
<img width="892" alt="Bildschirmfoto 2020-09-18 um 17 50 48" src="https://user-images.githubusercontent.com/12561945/93618524-af25db00-f9d7-11ea-9d90-d7b19881630a.png">

Now, I have a Mac in an Amiga in a Mac 😎. I guess A-Max wants to have a Macintosh disk now? No? 🤔

**Comment by tonioni** [comment]
It tries to access floppy port ROM adapter/dongle that comes with original A-max. Cracked version comes with ROM image and does not need the adapter but adapter access code is still active.
