### ISSUE TITLE
DiagRom memory detection - Strange result

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#412]
I run DiagRom 1.2 in UAE and vAmiga to compare results. There is a strange result when running the memory detection test:

<img width="721" alt="Bildschirmfoto 2020-09-25 um 17 11 38" src="https://user-images.githubusercontent.com/12561945/94284513-c70adb00-ff52-11ea-8207-26b5b6e01d2b.png">

Using a 512+512 memory configuration, vAmiga reports this:

<img width="899" alt="Bildschirmfoto 2020-09-25 um 17 06 56" src="https://user-images.githubusercontent.com/12561945/94284557-d5f18d80-ff52-11ea-96e9-1ed94083519e.png">

Unexpectedly, UAE reports this: 😳

<img width="721" alt="Bildschirmfoto 2020-09-25 um 17 12 00" src="https://user-images.githubusercontent.com/12561945/94284620-ee61a800-ff52-11ea-86ca-0c4a20255bf3.png">

What is going in address range A8 - B7???

**Comment by tonioni** [comment]
Don't use built-in AROS ROM? :)

**Comment by dirkwhoffmann** [comment]
> Don't use built-in AROS ROM? :)

But I only installed the DiagRom at boot time: 🤔

<img width="782" alt="Bildschirmfoto 2020-09-25 um 18 50 52" src="https://user-images.githubusercontent.com/12561945/94294490-32a77500-ff60-11ea-8dde-1a5b39d4e567.png">

**Comment by tonioni** [comment]
I can't duplicate this and it really looks like AROS ROM special config where 2M ROM space is used as a spare RAM for AROS boot allocations, to keep "normal" RAM space as free as possible. Check what debugger "dm" command outputs.

**Comment by dirkwhoffmann** [comment]
>  it really looks like AROS ROM special config where 2M ROM space is used as a spare RAM

Yes, for some reason, RAM is installed in the upper memory range although Aros is not selected in the configurator:

<img width="649" alt="Bildschirmfoto 2020-09-26 um 09 01 26" src="https://user-images.githubusercontent.com/12561945/94332655-417d3e80-ffd7-11ea-8c5d-0be4879f1f99.png">
