### ISSUE TITLE
Bit BPLCON0::ERSY is ignored

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#414]
ERSY: „External resync (HSYNC, VSYNC pads become inputs) (reset on power up)“ [HRM]

When ERSY equals 1, the vpos and hpos counters (the ones that are returned by VHPOSR) are no longer incremented. As a result, two consecutive reads from VHPOSR return the same result. This is not implemented yet.

„The Jetsons“ is a test case for this. While booting, it calls the following Kickstart routine which reads VHPOSR two times in a row.

<img width="980" alt="Bildschirmfoto 2020-09-28 um 15 53 50" src="https://user-images.githubusercontent.com/12561945/94442166-ef3d4880-01a3-11eb-8994-a3f354f2e7b8.png">

 In vAmiga, $102 is returned which is wrong. In UAE, 0 is returned because the ERSY bit is taken care of.

**Comment by tonioni** [comment]
KS uses ERSY=1 to detect if genlock is connected. If counters keep running with ERSY=1: genlock connected. If counters stop: no genlock. I think this slightly affects how KS uses CIA timers.
