### ISSUE TITLE
Eon by The Black Lotus - Graphics glitch at 1:16

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#418]
While working on the screen recorder, I noticed this graphics glitch that wasn't there before:

<img width="782" alt="Bildschirmfoto 2020-10-09 um 14 34 41" src="https://user-images.githubusercontent.com/12561945/95583672-c424e580-0a3c-11eb-9d99-544e22393175.png">

TODO: Check older releases to narrow down the erroneous checkin.

**Comment by dirkwhoffmann** [comment]
Error was introduced on 5 Aug with commit
https://github.com/dirkwhoffmann/vAmiga/commit/d45b49fc8467382db0065b91360713ea647fda75  (Fixed sprite bug (Kickstart 3.1))

Conclusion: My sprite bug fix for making Monkey Island work wasn't exactly right.

**Comment by dirkwhoffmann** [comment]
Fixed it (I think). 

Quote from #399 which was the bug I was trying to resolve with my erroneous checkin: 

> Here is what happened: When a sprite register gets changed, vAmiga records the change in a buffer. At the end of a raster line, the sprite drawing code replays that buffer and synthesizes sprite pixels. However, the sprite drawing code wasn't called inside the VBLANK area, because no sprites can be displayed there. Hence, if a sprite register was modified inside the VBLANK area, the register change wasn't recognized. It most cases, it still worked coincidentally, because the register records were not deleted at the end of a raster line and were replayed later (at their original horizontal coordinates which is wrong).

In the original fix, I decided to run the same code in the VBLANK area which I run when a sprite is disarmed. In this case, only the registers are updated. As it has turned out, this isn’t quite right, because some crucial side effects are omitted. In the new code, I am running drawSprites() everywhere which means that all side effects are taken care of. The only difference is when it comes to the point of drawing pixels. Here, I check the rasterline and skip the drawing part when the line belongs to the VBLANK area. This fixes the graphics glitches in the demo.

With the fix in place, Black Lotus looks like this 😎:

http://dirkwhoffmann.de/software/videos/BlackLotus.mp4

This time, I rendered it with a bit rate of 2048k and switched the DMA debugger off.

**Comment by mithrendal** [comment]
>This time, I rendered it with a bit rate of 2048k and switched the DMA debugger off.

 this looks much better than 1024 ... oh this demo is sooo unbelievable cooooool ...

**Comment by emoon** [comment]
:sunglasses:

**Comment by dirkwhoffmann** [comment]
Fixed in v0.9.13
