### ISSUE TITLE
Any plans to implement ECS Densie ?

### ISSUE THREAD

**Issue by alpine9000** [dirkwhoffmann/vAmiga#419]
Any plans to implement ECS Denise ?

One thing that is interesting about ECS Denise (I assume it's Denise) is the "ECS Border Blank" feature which also works on AGA.

A game that uses this feature is Traper Runner (2018) https://www.retroguru.com/trap-runner/

It has a menu option to enable it.

**Comment by dirkwhoffmann** [comment]
> Any plans to implement ECS Denise ?

Eventually: Yes. In the near future: No (there are still too many OCS bugs to rule out).

Nice game, btw 😎. 

<img width="974" alt="Bildschirmfoto 2020-10-11 um 13 20 58" src="https://user-images.githubusercontent.com/12561945/95677489-25c48b80-0bc6-11eb-9398-18b7e59091e0.png">

> "ECS Border Blank"

With a Denise ECS chip, the game is framed by a black border then?

**Comment by alpine9000** [comment]
> With a Denise ECS chip, the game is framed by a black border then?

Yes, there is a bit in BPLCON3 (bit 5 from memory?) that blanks the border region when set on ECS/AGA.

**Comment by dirkwhoffmann** [comment]
> Edit: on the game above you need to enable border blanking from the menu

Thank, found it. 

This is actually simple to implement, so I decided to support a fake Denise revision that is OCS Denise with the border blank feature added. 

<img width="277" alt="Bildschirmfoto 2020-10-21 um 10 32 06" src="https://user-images.githubusercontent.com/12561945/96694658-04fbf300-1389-11eb-8770-6bf092ba5e01.png">

With this revision, the border is drawn in pure black if bit 0 in BPLCON0 and bit 5 in BPLCON3 are both set.

OCS Denise: 

<img width="996" alt="Bildschirmfoto 2020-10-21 um 10 42 57" src="https://user-images.githubusercontent.com/12561945/96695706-3c1ed400-138a-11eb-942b-0ef8b13fb910.png">

OCS + BRDRBLNK Denise:

<img width="996" alt="Bildschirmfoto 2020-10-21 um 10 42 08" src="https://user-images.githubusercontent.com/12561945/96695761-4fca3a80-138a-11eb-9c41-21a9dfba594e.png">

**Comment by alpine9000** [comment]
Awesome! I will test it with Metro Siege which also uses border blank when you make the next release.

**Comment by alpine9000** [comment]
I ended up building vAmiga from master and the border blank worked perfectly on my game, great work!
