### ISSUE TITLE
Faery Tale Music

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/vAmiga#42]
Goodmorning everyone,
I tried the game Faery Tale, the one posted by Alessandro in the "Logbook for version 0.2" discussion with the new version 0.23 of the vAmiga.
Faery Tale was my first Amiga500 game, it seems to me that the soundtrack during the game is very different from the one played on a real Amiga, possibly I remember badly or the sound is slowed down and incomplete.

https://github.com/dirkwhoffmann/vAmiga/files/3238784/Faery.Tale.Adventure.The.1986.MicroIllusions.cr.adf.zip

**Comment by Alessandro1970** [comment]
Hello,
I'm sorry, I liked that game even though I never finished it, but I don't remember Faery Tale's music well.

Can anyone check on a real Amiga or on WinUAE?

**Comment by Alessandro1970** [comment]
Here it is ! 

https://www.youtube.com/watch?v=tV5r5ne-7Mg

wait for the introduction ... you can hear the music

**Comment by mortinus** [comment]
Mmmm...
On my MBP the volume is too low, and if I try to bring the volume of the Mac to maximum the sound of the vAmiga remains too low... To low for my ears...

**Comment by dirkwhoffmann** [comment]
To my ears, the YouTube video sounds a little different than vAmiga. It may be due to the Audio filter implementation (vAmiga uses a standard Butterworth filter). Unfortunately, Commodore did vary the audio filters between models, so the game might not sound the same on all Amigas. Also, it is possible to deactivate the filter by software on some machines (by turning the power led off via the CIAs (?!) ). This hasn't been implemented yet, too.

**Comment by dirkwhoffmann** [comment]
I just did a small code review and found this 🤭:

    // Convert sound samples to floating point values and write into ringbuffer
    ringBufferL[writePtr] = float(left) * scale; // filterL.apply(float(left) * scale);
    ringBufferR[writePtr] = float(right) * scale; // filterR.apply(float(right) * scale);

Seems like I disabled audio filtering in the past (most likely for debugging) and forgot to reenable it. In the next version, I'll add a check box to the Preferences that let's the user switch off the filters manually. Once we have that, we can compare both results.

**Comment by dirkwhoffmann** [comment]
Now, there is a setting "Audio Filter" in the Compatibility preferences panel which allows the user to manually disable or enable the audio filter. It'll be great if you could give it a try:

http://www.dirkwhoffmann.de/vAmiga/vAmiga_0.23.1.zip

With audio filters enabled, the game sounds pretty much like the original I think (at least to my ears).

**Comment by Alessandro1970** [comment]
Great sound, great emulation !

Just here 👍 
<img width="775" alt="Schermata 2019-06-07 alle 22 29 56" src="https://user-images.githubusercontent.com/34916641/59131922-0aaf8f00-8974-11e9-9c71-d54418cc6bad.png">

**Comment by Alessandro1970** [comment]
Before this screen:
<img width="777" alt="Schermata 2019-06-07 alle 22 38 13" src="https://user-images.githubusercontent.com/34916641/59132260-fd46d480-8974-11e9-90d4-51884d7cfc4e.png">

There is this graph error that cannot be seen in the original:
<img width="774" alt="Schermata 2019-06-07 alle 22 38 03" src="https://user-images.githubusercontent.com/34916641/59132295-1bacd000-8975-11e9-8d0d-3b4dc74613ab.png">

**Comment by rossimariolee** [comment]
It works well for me.
Thanks
