### ISSUE TITLE
Jumping Jackson fails to load

### ISSUE THREAD

**Issue by bnice** [dirkwhoffmann/vAmiga#427]
Hi,
Checked with normal, async FIFO, and  boost all failed, loads under FS-UAE.

image:
https://www.planetemu.net/rom/commodore-amiga-games-adf/jumping-jack-son-1990-infogrames-cr-mad-12

**Comment by dirkwhoffmann** [comment]
This is strange. Here, it loads without any issues: 

<img width="1028" alt="Bildschirmfoto 2020-10-30 um 20 40 32" src="https://user-images.githubusercontent.com/12561945/97750140-89204a00-1af0-11eb-8b5e-d85c15c083cc.png">

These are my settings: 

<img width="1028" alt="Bildschirmfoto 2020-10-30 um 20 41 39" src="https://user-images.githubusercontent.com/12561945/97750167-93424880-1af0-11eb-8f05-7e371b2e2dbb.png">

<img width="1028" alt="Bildschirmfoto 2020-10-30 um 20 41 53" src="https://user-images.githubusercontent.com/12561945/97750172-950c0c00-1af0-11eb-84f2-9a393c9dd23d.png">

<img width="1028" alt="Bildschirmfoto 2020-10-30 um 20 42 01" src="https://user-images.githubusercontent.com/12561945/97750175-96d5cf80-1af0-11eb-966a-609ad6f176fb.png">

This game is pretty cool, but I have no glue what I need to do. I found out that my hair color changes when I jump onto one of the red tiles 😳.

**Comment by bnice** [comment]
Hi,

Cool compared my settings to yours and found I had a 2mb chip, Agnus selected changed it and works fine.

To play the game you jump on the coloured squares when you get 3 coloured the same, a record of that colour appears take to same coloured turntable and press fire to play it. One the turntables are all full and playing, go to to a checked square and press fire and you will go to the next level :-)

Regards,

Ben.

**Comment by bnice** [comment]
To be clear no issue, can be closed. It didn't like my 2mb agnus setting.
