### ISSUE TITLE
Super Cars fails to recognise adfs as valid

### ISSUE THREAD

**Issue by bnice** [dirkwhoffmann/vAmiga#428]
HI,
This version of Super Cars files fails to recognise as valid adfs. I have tried the zips, uncompressed the zips, renamed the uncompressed adfs but still get the error "file appears to be corrupt". In fs-uae (3.0.5) both the zip and unzipped files work fine.

Images:
https://www.planetemu.net/index.php?section=roms&action=showrom&datSlug=commodore-amiga-games-adf&romSlug=super-cars-1990-gremlin-cr-pna-disk-1-of-2-5&

https://www.planetemu.net/index.php?section=roms&action=showrom&datSlug=commodore-amiga-games-adf&romSlug=super-cars-1990-gremlin-cr-pna-disk-2-of-2-2&

**Comment by dirkwhoffmann** [comment]
This is an easy one. The ADF is illformed in the sense that it contains an additional byte at the end ($00). 

<img width="871" alt="Bildschirmfoto 2020-10-30 um 20 21 08" src="https://user-images.githubusercontent.com/12561945/97749210-f501b300-1aee-11eb-93fd-56753af399d7.png">

The next version will accept those AFDs, too. The MFM encoder will simply ignore the additional byte if it is present.

<img width="1028" alt="Bildschirmfoto 2020-10-30 um 20 19 25" src="https://user-images.githubusercontent.com/12561945/97749264-0cd93700-1aef-11eb-94b8-4f1ef2027215.png">

**Comment by dirkwhoffmann** [comment]
Fixed in v0.9.14
