### ISSUE TITLE
Shadowgate Guru Meditation

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/vAmiga#43]
Why don't start Uninvited and Shadowgate ? 
They should be less complicated than marble maddness and Faery Tale ?

https://github.com/dirkwhoffmann/vAmiga/files/3238804/SGate.adf.zip

![Untitled 2](https://user-images.githubusercontent.com/41686391/59089672-ff744900-890a-11e9-86d5-b58781c20dbc.jpg)

**Comment by dirkwhoffmann** [comment]
Same with WinterGames. I expect this to be a disk controller problem.

**Comment by dirkwhoffmann** [comment]
Same in SAE. Maybe the ADF is corrupted or copy protected. We should try another ADF.

<img width="734" alt="Bildschirmfoto 2019-07-22 um 15 58 54" src="https://user-images.githubusercontent.com/12561945/61638455-bbaa8880-ac99-11e9-953e-aa1f521696bd.png">

**Comment by Alessandro1970** [comment]
Hi,
Shadowgate run in SAE only with **Kickstart 1.2** and only (I think so) using this version:

[Shadowgate (1987)(Mindscape)[cr ABC][KS1.2].zip](https://github.com/dirkwhoffmann/vAmiga/files/3426033/Shadowgate.1987.Mindscape.cr.ABC.KS1.2.zip)

![Untitled 2](https://user-images.githubusercontent.com/34916641/61783189-a5bad600-ae07-11e9-8d21-22716f5cc644.png)

**Comment by Alessandro1970** [comment]
...but that is not good, because Mortinu's disk (link above) works very good on WinUAE with kickstart 1.3 !!!

https://github.com/dirkwhoffmann/vAmiga/files/3238804/SGate.adf.zip

![Untitled 1](https://user-images.githubusercontent.com/34916641/61784468-08ad6c80-ae0a-11e9-8f63-e9dca3c6e56b.png)

**Comment by Alessandro1970** [comment]
...yes, in sgate.adf there is a file without the name......

**Comment by mortinus** [comment]
Yes in these adf games there is that boring disk protection, but WINUAE can read the game without any problem.
How can winuae resolve this issue ? 
What is the real problem ?

**Comment by rossimariolee** [comment]
...a new emulamer's nightmare has been found ?!

**Comment by Alessandro1970** [comment]
Uninvited on VAmiga 3.3 is working:
<img width="856" alt="Schermata 2019-08-14 alle 09 51 08" src="https://user-images.githubusercontent.com/34916641/63003768-37eb5280-be79-11e9-9154-8d88bfd59173.png">

**Comment by dirkwhoffmann** [comment]
> Uninvited on VAmiga 3.3 is working:

Which version did you use? The version posted by Mortinus still gives me a TASK HELD error.

**Comment by Alessandro1970** [comment]
Shadowgate:

1) the protected version run only on FSUAE/WinUAE
2) the cracked version now, on vAmiga3.3 run the intro then hangs:
[Shadowgate.1987.Mindscape.cr.ABC.KS1.2.zip](https://github.com/dirkwhoffmann/vAmiga/files/3500350/Shadowgate.1987.Mindscape.cr.ABC.KS1.2.zip)
<img width="854" alt="Schermata 2019-08-14 alle 09 54 31" src="https://user-images.githubusercontent.com/34916641/63004155-032bcb00-be7a-11e9-8842-62961b62a87e.png">
<img width="852" alt="Schermata 2019-08-14 alle 09 56 25" src="https://user-images.githubusercontent.com/34916641/63004162-0757e880-be7a-11e9-98a4-6aa7492e097b.png">

**Comment by Alessandro1970** [comment]
Only kickstart 1.2 for me.

Uninvited:
[Uninv.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3500354/Uninv.adf.zip)

**Comment by Alessandro1970** [comment]
On the first version ADF of shadowgate probably there is a disk protection that can run on Wiunae.

**Comment by dirkwhoffmann** [comment]
I can run the cracked version of Shadowgate with Kick 1.2 and 512 KB Chip, 0 KB Slow...

<img width="841" alt="Bildschirmfoto 2019-08-14 um 10 02 54" src="https://user-images.githubusercontent.com/12561945/63004497-d0360700-be7a-11e9-87f9-0bf5243b31c3.png">

Didn't experience a Guru so far, but I am just at the beginning of the game. The door is locked and my torch went out 😖.

**Comment by Alessandro1970** [comment]
Instead Uninvited now is playable:
<img width="853" alt="Schermata 2019-08-14 alle 10 04 27" src="https://user-images.githubusercontent.com/34916641/63004539-ecd23f00-be7a-11e9-9893-0bf76572872a.png">


The issue can be renamed only for shadowgate because Uninvited now works !

**Comment by Alessandro1970** [comment]
For me run but hangs when I "operate" key on door, disk run in loop:
<img width="854" alt="Schermata 2019-08-14 alle 10 12 38" src="https://user-images.githubusercontent.com/34916641/63005110-26f01080-be7c-11e9-8bf5-4cb7ffbb5585.png">

**Comment by dirkwhoffmann** [comment]
Where did you find that key?

**Comment by Alessandro1970** [comment]
...just only open the door without the key the games hangs for me...drive led flashing

**Comment by Alessandro1970** [comment]
Operate the skull
under there is a key

**Comment by Alessandro1970** [comment]
I used your configuration, the same ADF...
Drive speed 1x
but I cannot "open" the door, it goes in loop and drive light flashes

**Comment by dirkwhoffmann** [comment]
<img width="841" alt="Bildschirmfoto 2019-08-14 um 10 19 54" src="https://user-images.githubusercontent.com/12561945/63005589-22782780-be7d-11e9-9fcb-4d1ca8ee55c3.png">

OK, I got the key under the skull. Unfortunately, I burned the torch outside which wasn't a brilliant idea. Now I can't see anything 😖... Stay tuned...

**Comment by Alessandro1970** [comment]
Operate torch on burning torch...


But how can you run it ?
this is my kick: Kickstart 1.2 (33.180) (A500-A2000) (Commodore) (1986)

If I try to open the first door it turn light blue and it hangs...Mouse halted, drive led flashing.. see photo:

<img width="851" alt="Schermata 2019-08-14 alle 10 23 12" src="https://user-images.githubusercontent.com/34916641/63006008-ebeedc80-be7d-11e9-99f8-c9549f8404e8.png">

**Comment by dirkwhoffmann** [comment]
Strange, I still cannot reproduce the bug. Here is my HW config: 

<img width="841" alt="Bildschirmfoto 2019-08-14 um 10 24 53" src="https://user-images.githubusercontent.com/12561945/63006184-4e47dd00-be7e-11e9-973b-561115476dd7.png">

Oh, that's cool... using the key from the skull, I managed to get into the dungeon...

<img width="841" alt="Bildschirmfoto 2019-08-14 um 10 27 45" src="https://user-images.githubusercontent.com/12561945/63006222-60c21680-be7e-11e9-877f-02b942114099.png">

There is a book on the shelf...I HAVE to know what's written in there...

<img width="841" alt="Bildschirmfoto 2019-08-14 um 10 27 59" src="https://user-images.githubusercontent.com/12561945/63006283-7cc5b800-be7e-11e9-8342-cfaa8e18904a.png">

Oh no, that was a bad idea. Grabbing the book opens up a pit. So mean 😖.

**Comment by dirkwhoffmann** [comment]
> Kickstart 1.2 (33.180) 

I used that, too. Strange.

**Comment by dirkwhoffmann** [comment]
Is the Guru deterministic on your machine? I am desperately trying to reproduce the bug, but it doesn't want to show up here...

BTW, I'm dead again 😫

<img width="841" alt="Bildschirmfoto 2019-08-14 um 10 43 52" src="https://user-images.githubusercontent.com/12561945/63007292-a7b10b80-be80-11e9-9a49-8d2e7a63b580.png">

**Comment by Alessandro1970** [comment]
The only difference that I see now is that I have selected in the configuration the Amiga2000 not the A500.
But the game could be run in the A2000 too...

**Comment by dirkwhoffmann** [comment]
> Amiga2000 not the A500

This affects the appearance of the virtual keyboard, only. 

What about the compatibility settings? 

<img width="841" alt="Bildschirmfoto 2019-08-14 um 11 22 35" src="https://user-images.githubusercontent.com/12561945/63010079-0036d780-be86-11e9-9c72-fffdde90b0a2.png">

**Comment by Alessandro1970** [comment]
The same...

**Comment by dirkwhoffmann** [comment]
> The same...

Strange. The only remaining explanation is that v0.33 is cursed 🐀. Let's postpone this bug and recheck it in the next pre-release.

**Comment by Alessandro1970** [comment]
With version v3 Shadowgate work fine (512mb chip and kick 1.2 !)
<img width="887" alt="Schermata 2019-09-01 alle 09 24 42" src="https://user-images.githubusercontent.com/34916641/64073183-9f3b3c00-cc9a-11e9-87e9-d87f5b13dd1f.png">

for me you can close, with that configuration no more guru or any other issues.

**Comment by dirkwhoffmann** [comment]
OK, I'll close.

And remember not to take the book when you enter the dungeon. Although I'm still curious what's in it  🤔.
