### ISSUE TITLE
Add support for HD diskettes

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#430]
In v0.9.14, rudimentary support for OFS and FFS has been added. I.e., it is now possible to create a logical OFS or FFS volume, add files and directories, and create an ADF out of it. In v0.9.14, this functionality is utilized to enable drag and drop for plain Amiga EXE files. When such file is dragged in, an OFS volume is created that contains the provided EXE file. Furthermore, a boot block is installed and a startup-sequence added which loads the EXE file. After that, the volume is converted into an ADF and inserted into the drive.

I’d like to make my file system library more robust by adding HD disk support to vAmiga. 

Here are three test files created with adftools (which uses adflib):

HD disk, OFS formatted, Kick 1.x bootblock
[hdofs.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/5468834/hdofs.adf.zip)

DD disk, FSS formatted, Kick 2.x bootblock
[ddffs.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/5468835/ddffs.adf.zip)

HD disk, FSS formatted, Kick 2.x bootblock
[hdffs.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/5468836/hdffs.adf.zip)

User story (this must be possible in vAmiga):

- Install Kickstart 2.04 and connect an external HD drive
- Boot with both mouse buttons pressed
- Select df1: as boot medium
- Insert hdofs.adf into df1:
- If everything works fine, a demo launches

In UAE, hdofs boots just fine. Interestingly, booting the FFS volumes causes trouble:

ddffs: Boots, but the demo is corrupted
hdffs: Doesn’t boot

I don’t think it’s an issue with the disks, because the demo  runs just fine when launched from the CLI (for all three disks). My guess is that there might be a boot block issue. Maybe FFS media require a special bootblock. 🤔

**Comment by dirkwhoffmann** [comment]
Successfully booted from an HD disk for the first time (Kick 2.04, disk in df1:) 😎

<img width="890" alt="Bildschirmfoto 2020-11-01 um 19 52 30" src="https://user-images.githubusercontent.com/12561945/97811658-4d19f000-1c7c-11eb-9796-0f3561797012.png">

**Comment by mithrendal** [comment]
Maybe we can install classicwb. It comes with a webbrowser I think AWeb. 🤠

**Comment by dirkwhoffmann** [comment]
Things are shaping up. In the current version, it's already possible to drag in EXE files. In the next version, it will be possible to drag in directories, too. In this case, vAmiga tries to create an ADF containing all files in the host directory. If the directory fits on a single 3.5"DD disk, it can be mounted as usual: 

<img width="604" alt="Bildschirmfoto 2020-11-07 um 14 13 28" src="https://user-images.githubusercontent.com/12561945/98442251-e6755600-2103-11eb-8229-e88bdf8ab847.png">

If the directory is too large, vAmiga automatically tries to put the files onto a 3.5"HD disk. Note that HD disks can only be inserted into drives that are configured as HD drives (df0 is always a DD drive). 

<img width="604" alt="Bildschirmfoto 2020-11-07 um 14 14 03" src="https://user-images.githubusercontent.com/12561945/98442332-3522f000-2104-11eb-93a5-8b19e2ceabf7.png">

If no HD drive is connected, a warning message is displayed:

<img width="604" alt="Bildschirmfoto 2020-11-07 um 14 13 44" src="https://user-images.githubusercontent.com/12561945/98442274-fab95300-2103-11eb-873e-d79fa73901a4.png">

**Comment by dirkwhoffmann** [comment]
> At least the GAAE Edition should be possible no?

No, it requires a 80MB Hard Drive

**Comment by mithrendal** [comment]
Oh my fault. I did not look carefully enough and was confused by the HD acronym. It stands not for HardDrive in this context but for HighDensity right?

**Comment by dirkwhoffmann** [comment]
Yes, with HD I mean HD diskettes with a HUUUUGE capacity of 1,7MB.
The classicWB editions also require an ECS machine 😢.

**Comment by dirkwhoffmann** [comment]
In the next version, vAmiga will have a nice feature for browsing and debugging the file system of an ADF. If "Export Disk..." is selected, a dialog will come up (instead of a save panel): 

<img width="604" alt="Bildschirmfoto 2020-11-20 um 14 22 05" src="https://user-images.githubusercontent.com/12561945/99805078-40cad980-2b3c-11eb-9bec-21f6507bfa8d.png">

The user will be able to view the contents of all blocks. vAmiga automatically scans the block, informs the user about the role of each byte, and reports back any detected inconsistency. There is still some work to do. The beta code reports errors for intact disks 🙈 (e.g., the disk used in the above example is perfectly fine). Anyway, false positives are good for debugging...

**Comment by dirkwhoffmann** [comment]
My new toy turns out to be a nice tool. I’ve analyzed a couple of ADFs and found out that almost all of them contain a file system that is corrupted in one or the other way. E.g., here is „Gods“ with a wrong checksum in the bitmap block 🤭:

<img width="992" alt="Bildschirmfoto 2020-11-20 um 19 16 16" src="https://user-images.githubusercontent.com/12561945/99837498-f4958e80-2b67-11eb-91ef-e917829eefb5.png">

This is a block from „Defender of The Crown“ 😬:

<img width="992" alt="Bildschirmfoto 2020-11-20 um 17 37 37" src="https://user-images.githubusercontent.com/12561945/99837505-fb240600-2b67-11eb-91f4-62411966649a.png">

The displayed block is a „File List Block“. Such blocks contains a reference to the corresponding „File Header Block“ at the end. Instead of referencing this block, a pointer to the bitmap block is stored. 

And finally, the world’s best Pac Man clone ever made… with lot’s of errors in the data block headers 😳:

<img width="992" alt="Bildschirmfoto 2020-11-20 um 17 48 25" src="https://user-images.githubusercontent.com/12561945/99837538-0a0ab880-2b68-11eb-822f-21831781b41c.png">

 Again, the bitmap block is references instead of the file header block.

To cope with this situation, I think I should add a checkbox called „Strict checking“ and ignore a couple of common mistakes. Otherwise, the disk exporter would classify nearly every real-life ADF as being corrupted. 🤔

**Comment by dirkwhoffmann** [comment]
With the latest code changes, vAmiga can export disks to the Mac file system (i.e., all files and directories on the Amiga disk will be saved as single files and directories on the Mac). To export to a directory, simply select "Directory" as output format: 

<img width="542" alt="Bildschirmfoto 2020-11-22 um 14 34 05" src="https://user-images.githubusercontent.com/12561945/99905339-81f3f280-2cd0-11eb-9425-4b266f1b057e.png">

After exporting this disk (Workbench 1.2), all files are accessible on the Mac: 

<img width="856" alt="Bildschirmfoto 2020-11-22 um 14 19 59" src="https://user-images.githubusercontent.com/12561945/99905373-b5cf1800-2cd0-11eb-8761-6c31e74001bb.png">

**Comment by dirkwhoffmann** [comment]
Part of v0.9.15
