### ISSUE TITLE
Broken effect in Copper master by Angels

### ISSUE THREAD

**Issue by emoon** [dirkwhoffmann/vAmiga#438]
Steps to repo:

Tested with vAmiga 0.9.14

1. Download http://www.df.lth.se/~cato/demos/lI1.exe
2. Run in vAmiga 0.9.14 (kickstart 1.3)
3. After 3.24 min into the demo there is an effect that looks like this in vAmiga

![image](https://user-images.githubusercontent.com/350822/98460507-5daef680-21a5-11eb-8eb5-f9ca61aae824.png)

but it should actually look like this (tested in FS-UAE)

![copper](https://user-images.githubusercontent.com/350822/98460545-b54d6200-21a5-11eb-8179-a746cdb315ea.png)

Also see this video as ref https://www.youtube.com/watch?v=h3FLdtkToBU&t=3m24s

I think this is running in HAM mode so maybe related to #384 ?

**Comment by dirkwhoffmann** [comment]
Awesome demo 🤩

X-ray (for reference): 

<img width="1019" alt="Bildschirmfoto 2020-11-08 um 15 38 17" src="https://user-images.githubusercontent.com/12561945/98468097-31ad6880-21d9-11eb-8918-ff93b71d061e.png">

The faulty scene is (partly) drawn in HAM6 mode (just like #384). However, I don't think that #384 is directly related to HAM6. 
 
<img width="980" alt="Bildschirmfoto 2020-11-08 um 15 38 51" src="https://user-images.githubusercontent.com/12561945/98468101-36721c80-21d9-11eb-8a4f-f9f78a85175e.png">

**Comment by dirkwhoffmann** [comment]
When I think about it...  #384 utilizes HAM6 and everything except red is black. This demo here utilizes HAM6 and everything except red is black... 🤔

**Comment by emoon** [comment]
> However, there is also the possibility that both demos share the same code base for initializing stuff.

I highly doubt it. It's 25 years between the demos (Copper master released 90 and #384 released in 2015) by different coders.

**Comment by dirkwhoffmann** [comment]
> It's 25 years between the demos

OK, that's quite some time. But I confused myself above. HAM with 6 bitplanes is the standard HAM mode. I confused it with the "illegal" HAM mode where bitplanes 5 and 6 are excluded from DMA and set manually.

**Comment by tonioni** [comment]
First post seems have mixed two similar looking parts. First comes part with smaller bars (the one with the bug), after that comes similar effect with larger bars (comes after "Ok, It is quite cool, but we want more and more colors !!").

(No, I don't have any idea what is going wrong)

**Comment by emoon** [comment]
@tonioni yes you are correct, it actually looks correct the whole time in UAE. Updated the post.

**Comment by emoon** [comment]
looking a bit more on the effect going on above I don't think there is any race between Blitter and CPU in this case at least. The effect doesn't do much (very little in terms of copper activity as well). Sprites are here to cover the left and right sides (the "stripes") and only a small amount of blits runs outside of the the screen area.

Without knowing how vAmiga works it looks like the display of the HAM data is incorrect.

**Comment by dirkwhoffmann** [comment]
Fixed (same issue as #384)
