### ISSUE TITLE
Small graphics issue in Planet Rocklobster (Oxyron)

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#443]
<img width="1019" alt="Bildschirmfoto 2020-11-15 um 10 16 07" src="https://user-images.githubusercontent.com/12561945/99181370-5d2ad880-272e-11eb-9590-79b6f39e6781.png">

It's most likely a timing issue with BPLCON0 or BPLCON2 as the demo toggles graphics modes every other line.

**Comment by emoon** [comment]
The readme for the demo also states

```
Last thing to mention is the hiding of the HAM6 color-bleed with sprites.
```

But maybe the hiding is only being done on the left side (and not the right side)

**Comment by dirkwhoffmann** [comment]
> Last thing to mention is the hiding of the HAM6 color-bleed with sprites.

This might be it! I'll check that...

**Comment by dirkwhoffmann** [comment]
If all sprites are drawn in front and both playfields are cutted out, it looks like this:

<img width="1019" alt="Bildschirmfoto 2020-11-15 um 14 48 06" src="https://user-images.githubusercontent.com/12561945/99186832-4d71bb00-2753-11eb-9614-1b2c12e776ec.png">

Assuming that I didn't do anything stupid in my experiment, you are right. Sprites are only used to cover the left border.

**Comment by emoon** [comment]
Alright. Then it's likely a timing issue as you suggested

**Comment by dirkwhoffmann** [comment]
I think I figured out the cause of this bug. It becomes clear when the border is highlighted in a different color (red):

<img width="988" alt="Bildschirmfoto 2021-01-17 um 12 16 35" src="https://user-images.githubusercontent.com/12561945/104839598-7123bf80-58c2-11eb-99f5-4caf16b13080.png">

The red border is missing for all HAM lines. The emulator does draw the border, but the color is overwritten later in function `colorize()` (only HAM mode is affected, because of the way `drawBorder()` works): 

  ```C++
        // Translate bitplane data to color register indices
        translate();

        // Draw sprites
        drawSprites();

        // Draw border pixels
        drawBorder();

        // Perform playfield-playfield collision check (if enabled)
        if (config.clxPlfPlf) checkP2PCollisions();
        
        // Synthesize RGBA values and write the result into the frame buffer
        pixelEngine.colorize(vpos);
```

**Comment by dirkwhoffmann** [comment]
Fixed.

<img width="988" alt="Bildschirmfoto 2021-01-17 um 13 39 33" src="https://user-images.githubusercontent.com/12561945/104843478-2d818380-58cb-11eb-87e7-1272672aaa1d.png">

**Comment by emoon** [comment]
Sweet!

**Comment by dirkwhoffmann** [comment]
> Sweet!

Using your voxel test case, it was easy to debug 👍.
