### ISSUE TITLE
Original speed for floppy drive acts as 2x

### ISSUE THREAD

**Issue by nicolasbauw** [dirkwhoffmann/vAmiga#445]
Original speed for floppy drive acts as 2x and is not original speed. (that gives trackmos a strange behavior when accessing disk, for example with TSL / Global Trash)

**Comment by dirkwhoffmann** [comment]
Do your compatibility settings look like this? (Collision detection settings are irrelevant, of course)

<img width="639" alt="Bildschirmfoto 2020-11-24 um 16 52 19" src="https://user-images.githubusercontent.com/12561945/100118012-b3f28980-2e75-11eb-81a6-e8c1898d2fa2.png">

**Comment by nicolasbauw** [comment]
Exactly the same as your screenshot :-)

**Comment by dirkwhoffmann** [comment]
Hmm, OK. Strange. How did you find out that the drive is too fast?

**Comment by nicolasbauw** [comment]
The tracks were skipping like crazy, and the usual timing of the demo was broken. Additionally, when accessing disk, the whole animation was speeding up.

**Comment by dirkwhoffmann** [comment]
> The tracks were skipping like crazy

Could it be related to auto warp mode? 

<img width="758" alt="Bildschirmfoto 2020-11-24 um 17 42 20" src="https://user-images.githubusercontent.com/12561945/100124902-7e9d6a00-2e7c-11eb-8d57-e45e89b4aca7.png">

**Comment by nicolasbauw** [comment]
I'll have a look at this setting. Currently this computer is upgrading its OS version, so I can't use it right now.

**Comment by nicolasbauw** [comment]
That was totally the reason, indeed. So, there is no technical issue at all (feel free to close the issue), but that could be confusing. Some ideas:

- All drive settings should be at the same place ?
- Setting "original speed" should automatically disable / override warp mode ? This is a compatibility setting after all, and warp mode degrades not the compatibility itself, but affects the way some programs (trackmos in this case) are rendered.

Thanks for your very quick answers and the emulator.

**Comment by dirkwhoffmann** [comment]
OK, I'll see what I can do.
