### ISSUE TITLE
Scan ADFs for boot block viruses 

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#448]
Some ADFs come with a block virus free of charge. It would be nice if the ADF mounter scanned the boot block and warned the user if a contaminated disk is about to be inserted. In addition, the mounter should offer the option to overwrite the boot virus with one of the standard boot blocks.

**Comment by dirkwhoffmann** [comment]
First prototype is up and running 😎. 

If, e.g., Capone (1988)(Actionware)[h Golden Minds][v Byte Bandit].adf is dragged in, vAmiga shows this dialog:

<img width="603" alt="Bildschirmfoto 2020-12-05 um 17 13 43" src="https://user-images.githubusercontent.com/12561945/101248630-49ff9d00-371d-11eb-8dea-df22e4288d39.png">

If the user clicks the "Decontaminate" button, 

<img width="603" alt="Bildschirmfoto 2020-12-05 um 17 07 11" src="https://user-images.githubusercontent.com/12561945/101247927-8d0d4080-371c-11eb-80c9-41c2a295a16a.png">

the boot block is replaced by a standard one (standard OFS or FFS bootblock, depending on the file system on the disk). After clicking the button, the dialog looks as usual and the disk can be inserted safely in any drive:

<img width="603" alt="Bildschirmfoto 2020-12-05 um 17 07 32" src="https://user-images.githubusercontent.com/12561945/101247945-af9f5980-371c-11eb-98b8-da2ccf24ffd5.png">

I'm unsure if this functionality is of great use, but it's a lot of fun to implement.

**Comment by mithrendal** [comment]
I like the disk icon ... it looks very nice, like the disks I unboxed when I unboxed my Amiga back then ...

**Comment by dirkwhoffmann** [comment]
I am currently browsing through the latest `brainfile.xml` from the very cool Amiga BootBlock Reader 4.1 to borrow some virus signatures...

This database really is up to date 😲

```
<Bootblock>
    <Name>Corona Covid-19 Virus</Name>
    <Recog>471,111,211,233,100,0,244,209,328,0,390,12,439,68</Recog>
    <Class>v</Class>
    <KS>KS1.3</KS>
    <Bootable>Y</Bootable>
    <Data>N</Data>
    <CRC>B4F2CF1</CRC>
</Bootblock> 
```

**Comment by dirkwhoffmann** [comment]
Seems to work well now and will be part of the next release.

**Comment by DannyCork** [comment]
nicely implemented feature !
