### ISSUE TITLE
take a screenshot every x seconds feature

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#449]
This sounds like a great feature but how does it work?

I selected every 10 seconds but where does the output go? Would be nice to have a user defined path to save the images to. Would be even nicer if it created a directory with the adf name so that it would be possible to take screenshots of multiple ads without specifying the path each time.

![Screenshot 2020-12-08 at 00 13 29](https://user-images.githubusercontent.com/3512672/101420562-6270e280-38ea-11eb-8034-ca5a6e4eff22.png)

**Comment by dirkwhoffmann** [comment]
>  but where does the output go? 

The emulator saves all screenshots in the Application Support folder of vAmiga:

<img width="717" alt="Bildschirmfoto 2020-12-08 um 06 50 32" src="https://user-images.githubusercontent.com/12561945/101445477-dda1bb00-3921-11eb-9c6c-ad977ce75906.png">

The images are grouped by using a checksum computed for the boot disk (the first disk that is inserted into df0: after a reset). When an ADF is dragged in, vAmiga scans the corresponding folder and displays the recorded screenshots in the import window:

<img width="603" alt="Bildschirmfoto 2020-12-05 um 18 47 24" src="https://user-images.githubusercontent.com/12561945/101445641-26f20a80-3922-11eb-819e-94692b301d96.png">

There is an easy way to find the images. Open the screenshot browser (red arrow) and click the folder icon (blue arrow).

<img width="990" alt="Bildschirmfoto 2020-12-08 um 06 48 10" src="https://user-images.githubusercontent.com/12561945/101446232-2ad25c80-3923-11eb-8b71-f9da7534b0ba.png">

While writing this reply, I have discovered a bug: vAmiga creates a subfolder in the Application Support folder for any dragged in ADF. It is supposed to create these folders only when a screenshot is taken. Hence, most folders are empty. 

BTW, as part of my "simplification project", the auto-screenshot feature will go away in future releases.
