### ISSUE TITLE
amiga-> usb joystick adapter

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#450]
I am using this amiga->USB adapter 
https://www.amazon.com/Mayflash-Drive-Genesis-Controller-Adapter/dp/B00QRZ1HVS/ref=cm_cr_arp_d_product_top?ie=UTF8

vAmiga identifies it as usb device 
![Screenshot 2020-12-08 at 00 35 01](https://user-images.githubusercontent.com/3512672/101421863-399e1c80-38ed-11eb-8db6-67d0ab70e23c.png)

It sort of works but not quite. some of the directions work , some don't. Do I need to map controls somewhere ?

**Comment by dirkwhoffmann** [comment]
Thanks for reporting. Unfortunately, I don't know what to do about it. The Amazon site suggests that they no longer supply this device.

**Comment by dirkwhoffmann** [comment]
I close this for now. In case, the controller is going to ship again in future, it can be added to list of yet unsupported controllers:

https://www.amazon.de/hz/wishlist/ls/35K6X4B0FIEOF/ref=nav_wishlist_lists_2?_encoding=UTF8&type=wishlist

**Comment by dirkwhoffmann** [comment]
v0.9.16.1 has a new panel for configuring game pads. 

<img width="641" alt="Bildschirmfoto 2020-12-23 um 15 24 54" src="https://user-images.githubusercontent.com/12561945/103007344-86ac0080-4533-11eb-8291-c116b8a6dae3.png">

Could you connect you controller and post a screenshot here? This will provide us with the necessary information to add the controller to the list of known devices. Of course it would be interesting to know if you can make the controller work by selecting another mapping scheme.
