### ISSUE TITLE
drag, drop and boot executable

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#451]
[Quadriga-GBD.zip](https://github.com/dirkwhoffmann/vAmiga/files/5656055/Quadriga-GBD.zip)

Would be nice to be able drag and drag an executable and have it autoboot. Fs-uae does this.

Attached an executable I tested it on fs-uae with. It's zipped so that I could upload it to GitHub.

**Comment by dirkwhoffmann** [comment]
For exe files, vAmiga requires the filename to end with `.exe`. If the zip file is unpacked and `.exe` added, the file can be dragged in: 

<img width="990" alt="Bildschirmfoto 2020-12-08 um 06 38 08" src="https://user-images.githubusercontent.com/12561945/101444732-6881b600-3920-11eb-95c0-645c2215363d.png">

There is still a bug though. vAmiga is supposed to accept zipped .exe files, but it doesn't. I.e., if Quadriga-GBD.exe.zip is dragged in, nothing happens.

**Comment by dirkwhoffmann** [comment]
Zipped exe files are now recognized.
