### ISSUE TITLE
checkbox for 'Do you want to save the changes?' prompt

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#453]
Every time I quit vAmiga I get this prompt

<img width="286" alt="Screenshot 2020-12-08 at 11 47 34" src="https://user-images.githubusercontent.com/3512672/101480221-4baea800-394b-11eb-80ed-6b0e17151329.png">

I guess it may be of use to some but I don't see the benefit of this prompt. It would be great if there was a checkbox in the preferences to turn this on/off.

**Comment by dirkwhoffmann** [comment]
That's already supported: 

<img width="758" alt="Bildschirmfoto 2020-12-08 um 12 56 11" src="https://user-images.githubusercontent.com/12561945/101481067-dfd13d00-3954-11eb-9f0c-7562cfb8a3cf.png">
