### ISSUE TITLE
OS System "Open With" Command

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#458]
Unable to use OS System "Open With" Command with VAmiga. Comes up with Error Message. It would be nice to be able to use this like Virtual64 allows.

![Screen Shot 2021-01-05 at 5 35 32 PM](https://user-images.githubusercontent.com/31462938/103714228-2a61cb80-4f8c-11eb-99a5-96f0584f644c.png)

**Comment by dirkwhoffmann** [comment]
Does it open if you drag the ADF directly into the emulator?

**Comment by bluecursor** [comment]
Yes...

Frank Michielli
Sent with OSX/iOS Spark!

**Comment by DannyCork** [comment]
open with works fine for me.

**Comment by dirkwhoffmann** [comment]
Works here, too (tested with 1.0b2).
