### ISSUE TITLE
Faery Tale Adventure graphics error

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#46]
Reported by Alessandro: 

Before this screen:
<img width="777" alt="Schermata 2019-06-07 alle 22 38 13" src="https://user-images.githubusercontent.com/34916641/59132260-fd46d480-8974-11e9-90d4-51884d7cfc4e.png">

There is this graph error that cannot be seen in the original:
<img width="774" alt="Schermata 2019-06-07 alle 22 38 03" src="https://user-images.githubusercontent.com/34916641/59132295-1bacd000-8975-11e9-8d0d-3b4dc74613ab.png">

None picture are to be shown, that should be a clean screen.

**Comment by dirkwhoffmann** [comment]
Same in Sword of Sodan (most likely the same bug).

**Comment by naTmeg** [comment]
Seems like a modulus problem. Check BPL1MOD and BPL2MOD. Also maybe DDFSTRT and DDFSTOP.

**Comment by Alessandro1970** [comment]
The graphic error has been removed but the games crash if the spell TOTEM is casted:
<img width="884" alt="Schermata 2019-07-18 alle 00 04 43" src="https://user-images.githubusercontent.com/34916641/61415007-d2df2400-a8ef-11e9-9c0b-fa4e5c07c6cb.png">

**Comment by dirkwhoffmann** [comment]
Interesting. The bitplanes seem to get out of sync. Similar graphics glitches appear in #86 (R-Type II).

**Comment by Alessandro1970** [comment]
With 0.32 release there is again a graphic bug moving the mouse down a line is shown in the upper screen:
<img width="886" alt="Schermata 2019-08-11 alle 08 40 01" src="https://user-images.githubusercontent.com/34916641/62830778-86e47e00-bc14-11e9-9a49-b6b66cb7be0c.png">

Using the "Magic Totem" hangs, the totem in not easy to be found. Where are stored the snapshop ? 
Could I can save here the snapshot or is it too big ?

**Comment by dirkwhoffmann** [comment]
> Where are stored the snapshot ?

The snapshot feature is not really working yet in vAmiga 😬. There are two remaining issues: 

1. I forgot to serialise the contents of disks (if disks are inserted in one of the drives).
2. There must be some state variables missing in the list of items to be serialised (because loading snapshots often results in a frozen Amiga, even if no disk stuff is involved).

**Comment by Alessandro1970** [comment]
I have tryied to play Faery tale on SAE:

here is the suffered point where to try the magic "Totem":
<img width="870" alt="Schermata 2019-08-13 alle 10 52 08" src="https://user-images.githubusercontent.com/34916641/62928422-cea40a80-bdb8-11e9-95ab-9becf9b99151.png">

hereis after "cast totem" on SAE:
<img width="868" alt="Schermata 2019-08-13 alle 10 53 51" src="https://user-images.githubusercontent.com/34916641/62928483-e7acbb80-bdb8-11e9-91ca-ea4ac2857dee.png">


This strange and poor grapich effect does not work on vAmiga.

**Comment by Alessandro1970** [comment]
...the red point on the map...

if you reach that point ...you may fly ! :-D
<img width="858" alt="Schermata 2019-08-13 alle 10 58 41" src="https://user-images.githubusercontent.com/34916641/62928756-73264c80-bdb9-11e9-826d-88a3a4f0584f.png">

<img width="874" alt="Schermata 2019-08-13 alle 11 00 35" src="https://user-images.githubusercontent.com/34916641/62928869-9cdf7380-bdb9-11e9-8392-a08caf002dba.png">

**Comment by Alessandro1970** [comment]
With version v3 Faery Tales works well.
Totem Magic effects now works:
<img width="884" alt="Schermata 2019-09-01 alle 09 14 13" src="https://user-images.githubusercontent.com/34916641/64073065-47500580-cc99-11e9-86a1-8bf19445f6f6.png">

<img width="885" alt="Schermata 2019-09-01 alle 09 16 10" src="https://user-images.githubusercontent.com/34916641/64073068-4a4af600-cc99-11e9-9b0f-f135a4a5a7f9.png">

For me there are no more issues for this game, you can close.

**Comment by dirkwhoffmann** [comment]
Great to hear that the game is working 🥳. I'll close.

**Comment by Alessandro1970** [comment]
Hi, sorry but in the last version the effect to display map (see photo above) does not work, as before the games does not show the map using "totem" magic and the games hangs seeking for disk data (I presume).
<img width="802" alt="Schermata 2019-10-20 alle 10 35 03" src="https://user-images.githubusercontent.com/34916641/67156967-b951dc00-f325-11e9-8ee8-10f8e4555d20.png">

**Comment by Alessandro1970** [comment]
I played than using blitter accuracy 2 and vAmiga crashed using totem magic (show area map):
[CRASH.TXT](https://github.com/dirkwhoffmann/vAmiga/files/3747985/CRASH.TXT)

Accuracy 1 games hangs using totem

**Comment by Alessandro1970** [comment]
If accuracy is set to 0 games hangs:
<img width="992" alt="Schermata 2019-10-20 alle 17 23 05" src="https://user-images.githubusercontent.com/34916641/67161793-54ff3e80-f35e-11e9-807d-e89cb437546a.png">


Something in the last revision has recreated the problem

**Comment by Alessandro1970** [comment]
0.43 same problems:
<img width="804" alt="Schermata 2019-10-26 alle 09 32 07" src="https://user-images.githubusercontent.com/34916641/67616083-c9aa0100-f7d4-11e9-85b5-114d58ce1c76.png">
<img width="805" alt="Schermata 2019-10-26 alle 09 39 18" src="https://user-images.githubusercontent.com/34916641/67616085-cf9fe200-f7d4-11e9-96e8-2666a624f276.png">

**Comment by Alessandro1970** [comment]
ehm, sorry !

...while testing games, for the oldest... better before check all kickstart and disable fast/slow ram...

Sorry...

<img width="804" alt="Schermata 2019-10-27 alle 09 23 02" src="https://user-images.githubusercontent.com/34916641/67631968-88c9ef00-f89d-11e9-9479-7ceccc9c4f35.png">

The kickstart 1.2 was needed, I used other kickstrt but hangs, Faerytale works for me only with kick 1.2 and with this kick I can play without any problem and the vAmiga never hangs.

<img width="798" alt="Schermata 2019-10-27 alle 09 36 15" src="https://user-images.githubusercontent.com/34916641/67631971-93848400-f89d-11e9-8b58-e6b31d05c46b.png">
<img width="803" alt="Schermata 2019-10-27 alle 09 36 02" src="https://user-images.githubusercontent.com/34916641/67631975-9aab9200-f89d-11e9-835e-30e7bf88a994.png">

...You can close.

**Comment by dirkwhoffmann** [comment]
> The kickstart 1.2 was needed, I used other kickstarts but hangs

I've set up a Wiki page where special configuration needs can be noted: 

https://github.com/dirkwhoffmann/vAmiga/wiki/Compatibility
