### ISSUE TITLE
"gettothacopper" fails

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#463]
First reported here: 
https://github.com/tonioni/WinUAE/issues/188

[gettothacopper.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/5838213/gettothacopper.adf.zip)

vAmiga has the same bug:

<img width="988" alt="Bildschirmfoto 2021-01-19 um 20 35 16" src="https://user-images.githubusercontent.com/12561945/105084344-7b96b280-5a96-11eb-8fa2-9f2401321db3.png">

<img width="988" alt="Bildschirmfoto 2021-01-19 um 20 35 21" src="https://user-images.githubusercontent.com/12561945/105084358-7fc2d000-5a96-11eb-9575-bc5b861a4438.png">

**Comment by dirkwhoffmann** [comment]
@mankeli: Hi Markus. I run your Copper test program in vAmiga and it fails there, too. Is the source code of your program available? I would like to have a look at the Copper list.

**Comment by mankeli** [comment]
Hi, you can fetch a somewhat cleaned-up source from https://gist.github.com/mankeli/1ed7eec8ee8501d73e55c225b0d19166
Code at "fillcopper" generates the copperlist. Row 304 has a workaround that prevents the bug from occuring on real a500

**Comment by mankeli** [comment]
And to be clear, the bug occurs on _real_ A500. On WinUAE it doesn't happen. So the behavior on the first screenshot is the correct one.

**Comment by dirkwhoffmann** [comment]
> And to be clear, the bug occurs on real A500. On WinUAE it doesn't happen. So the behavior on the first screenshot is the correct one.

Thanks for the source code and thanks for the clarification! I thought it's the other way round (the bug does happen in the emulators and not on the real machine). 

I double-checked on an ECS A500 (8A, Kick 1.3). It's the same as on your OCS machine. 

![IMG_0837](https://user-images.githubusercontent.com/12561945/105141459-79b20b00-5af9-11eb-85c6-fdc4df16e922.JPG)

![IMG_0838](https://user-images.githubusercontent.com/12561945/105141470-7d459200-5af9-11eb-8021-643bf6d80411.JPG)

This means vAmiga is doing the right thing here 😎.

If you have more test cases of this kind, I'd be happy to run them in vAmiga. These programs are extremely valuable for every emulator developer.
