### ISSUE TITLE
External Device & Polling Click

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#465]
Same error that was happening in Virtual64...
Also Polling Click sounds like a machine gun!?!?

![Screen Shot 2021-01-24 at 11 08 48 PM](https://user-images.githubusercontent.com/31462938/105660679-863bb800-5e99-11eb-9f21-9fcb5c1df0e1.png)

**Comment by dirkwhoffmann** [comment]
In the next version, the game pad clipart will no longer show up for mice: 

<img width="758" alt="Bildschirmfoto 2021-01-29 um 12 03 18" src="https://user-images.githubusercontent.com/12561945/106268149-f8f6bb80-622a-11eb-9d40-2defa6541e45.png">

Polling clicks can be disabled here:

<img width="758" alt="Bildschirmfoto 2021-01-29 um 12 09 08" src="https://user-images.githubusercontent.com/12561945/106268198-0c098b80-622b-11eb-9701-c56bed2e814c.png">

**Comment by bluecursor** [comment]
Thanks... but, in the past, the polling click was 1 click per second (which sounded right) compared to now 3 click per second (which doesn't sound like an amiga). I liked the polling click on the way it sounded before....

**Comment by dirkwhoffmann** [comment]
> compared to now 3 click per second

Did you enable more than one drive?

**Comment by bluecursor** [comment]
yeah, that fixed it...Sorry
