### ISSUE TITLE
Toolbar graphic imperfection

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#467]
I've notice a little graphic imperfection on the toolbar: when the "Run/Pause" button is pressed, all buttons on the left have a little scroll to the right.

**Comment by dirkwhoffmann** [comment]
Just checked that. I think it's a Big Sur "feature". The icons are rearranged because the toolbar item description changes from "Pause" to "Run". I am not sure if this effect can be avoided.

**Comment by Gianmarco72** [comment]
Hm 🤔
If this effect cannot be avoided, perhaps it is possible to write "Run" with two space characters?
" Run "
Not very clean but maybe it can work.😇
It's just an idea.

**Comment by dirkwhoffmann** [comment]
I've managed to work around the issue by assigning an "explicit" size for the toolbar items (default is "automatic"). 

<img width="262" alt="Bildschirmfoto 2021-01-29 um 12 23 06" src="https://user-images.githubusercontent.com/12561945/106269596-03b25000-622d-11eb-82be-105ce40a7037.png">

With a size of 40, the toolbar stays stable 😎.

**Comment by Gianmarco72** [comment]
👍🏻😜

**Comment by dirkwhoffmann** [comment]
The "explicit size" approach does not work, because it is deprecated: 

`vAmiga[7750:181833] [NSToolbarItem] NSToolbarItem.minSize and NSToolbarItem.maxSize methods are deprecated. Usage may result in clipping of items. It is recommended to let the system measure the item automatically using constraints.`

I need to change it back.

**Comment by Gianmarco72** [comment]
😕

**Comment by dirkwhoffmann** [comment]
Maybe it's best to simply call the button "State" instead of changing the name contextually. 🤔
