### ISSUE TITLE
New experimental vAmiga spin-off

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#468]
I've started working on an experimental spin-off of vAmiga called vAmigaBM (vAmiga Bare Metal).

<img width="880" alt="Bildschirmfoto 2021-01-28 um 16 52 26" src="https://user-images.githubusercontent.com/12561945/106281320-58f75d00-623f-11eb-80ff-1ec733315ec7.png">

What’s the difference? The original version has a sophisticated GUI, but is limited to the Mac. The new version will have a very basic GUI based on SFML. SFML is available on many platforms and so will vAmigaBM. 

At the moment, I have
- a title screen,
- a running emulator instance capable of drawing the hand & disk logo,
- a debug console.

<img width="880" alt="Bildschirmfoto 2021-01-29 um 13 52 35" src="https://user-images.githubusercontent.com/12561945/106281430-7fb59380-623f-11eb-93ac-e0dd84de689a.png">

The debug console will be an important part of the new project, because most of the underlying stuff will be available via the command line interface, only (or a startup script using the same language). This brings me directly to the point: The definition of the command line language. If somebody has an idea how this language should look like, or if there is some kind of common standard for such purposes, please let me now.

Side note: The command line syntax needs to be simple, because I don’t want to write a sophisticated parser (KISS principle). And no, I don’t want to mimic the UAE / FSUAE scripting language which is basically a key / value coding with hundreds of different keys.

**Comment by idrougge** [comment]
As an Amiga user, a ReadArgs interface feels most natural to me.

Otherwise, have you looked into https://github.com/apple/swift-argument-parser ?

Another idea would to make the command language more "object-oriented", as in `object.verb` instead of `verb object`. That could lend itself well to context sensitive help and future extension.

**Comment by dirkwhoffmann** [comment]
I also like the object-oriented idea, because it would group stuff nicely even if the number of options is large. We could have a command format like 

    <component> <command> [<options>]

Example commands would be: 

```
amiga power on
amiga power off
amiga run
amiga pause 
amiga reset
amiga configure search_path "/tmp"

df0 insert „defenderOfTheCrown.adf“
df1 eject 
df1 inspect 

agnus about 
agnus configure model ECS
paula configure volume 130

breakpoint set FC304

dmadebugger on
```

Since the config stuff is already organized that way internally, implementing such an interface is not a big deal. In fact it would be a thin layer on top of what vAmiga already provides.

**Comment by mithrendal** [comment]
Maybe also allow shortcuts

e.g.

let the parser understand the long

amiga configure search_path ../floppies

and its corresponding short cut version 

a c sp ../floppies

**Comment by dirkwhoffmann** [comment]
I'll go for the object-oriented approach. The syntax will be something like this:

<img width="880" alt="Bildschirmfoto 2021-01-31 um 16 03 25" src="https://user-images.githubusercontent.com/12561945/106388362-6e56bd80-63de-11eb-868f-caee3933b20c.png">

**Comment by dirkwhoffmann** [comment]
First experimental prototype is working under Ubuntu:

<img width="750" alt="Bildschirmfoto 2021-02-17 um 16 09 46" src="https://user-images.githubusercontent.com/12561945/108225318-1e952780-713c-11eb-9981-470e349ac6e8.png">

The prototype is too slow to play the music at the right pace, but I think this is due to my VW configuration. I have lots of trouble to get Linux working in VMWare Fusion properly. 

I'll close this issue since the vAmiga BM repo is now public.
https://github.com/dirkwhoffmann/vAmigaBM
