### ISSUE TITLE
About vAmiga : www link not secure

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#470]
Great project Dirk!

using vAmiga0.9.16.2 & 0.9.17.1

I clicked on About vAmiga which opened a dialog with the version information. When I click on the www link in this dialog 

- I get an empty page( http://www.dirkwhoffmann.de/software/virtualc64.html )
- The browser (Safari and Chrome) issue a not secure warning 

![Screenshot 2021-02-01 at 23 56 08](https://user-images.githubusercontent.com/3512672/106533120-73ecfa00-64e9-11eb-99af-10469f7402ea.png)

**Comment by dirkwhoffmann** [comment]
Thanks for pointing this out! The Credits.rtf file still linked to the old server. The warning comes up because the old page does no longer exist and the server uses http instead of https. The next release will link to the new GitHub pages site: 

https://dirkwhoffmann.github.io/vAmiga/

**Comment by dirkwhoffmann** [comment]
Fixed in v0.9.17.2
