### ISSUE TITLE
Really Need Harddrive Emulation

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#475]
As much as I use VAmiga, I am moving away from it more and more as it does not support either .hdf files or mounting a folder as a hdf. Reasons, today I am trying to install WordWorth 7 which comes in .adf and .iso, but doesn't run from the .adf as it looking to install it somewhere. Also a lot of new Aminet files are coming bigger than 720k disks.

Please add as a future enhancement

**Comment by emoon** [comment]
See https://github.com/dirkwhoffmann/vAmiga/issues/446

**Comment by mithrendal** [comment]
>Also a lot of new Aminet files are coming bigger than 720k disks.

hmm 🤔 ... a typical Amiga floppy disk can store 880 Kb, no?  Well from the outside it is not so much floppy ... as the 3.5" floppy disk where the data is stored is embedded inside a plastic shelf. I am wondering, is the data stored on both sides of the disk ?

**Comment by emoon** [comment]
The point is that many files on Aminet is made to be stored on a hard drive, not floppy.

**Comment by dirkwhoffmann** [comment]
Currently, I'm busy bringing vAmiga to the Raspberry Pi 400...

**Comment by mithrendal** [comment]
spotted HD File support in ADFFile.cpp 🤓 line 231

```
// Determine the root block location
    Block root = size < ADFSIZE_35_HD ? 880 : 1760;
```

https://github.com/dirkwhoffmann/vAmiga/blob/master/Emulator/Files/DiskFiles/ADFFile.cpp 


so bigger files are possible ... up to 1,7MB

**Comment by dirkwhoffmann** [comment]
To make a long story short: For hard drive support, I don't see enough development resources coming any time soon.

**Comment by nyteshade** [comment]
Are you accepting pull requests from the public?

**Comment by dirkwhoffmann** [comment]
@nyteshade: I would love to see others writing enhancements for this project. Depending on the nature of the code changes, I would either adopt them directly (which I did, e.g., with the API cleanup done by @MaddTheSane), or reimplement them to keep the software design consistent (which I would probably do if someone comes up with a working vAmiga clone with hard drive support).

**Comment by dirkwhoffmann** [comment]
This is a little off-topic, but vAmiga is now able to run on the Raspberry PI 400 😎: 

<img width="1019" alt="Bildschirmfoto 2021-02-26 um 15 44 34" src="https://user-images.githubusercontent.com/12561945/109314648-e7b0c700-7849-11eb-8927-59a716157d25.png">

CPU load is on the edge though (especially in this scene with heavy Blitter usage). The test run was made in high-compatibility mode.
