### ISSUE TITLE
possible to rip sprites/audio?

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#479]
I see that the inspector allows viewing the internals of an application during runtime.
<img width="879" alt="image" src="https://user-images.githubusercontent.com/3512672/113425796-64dfd680-93ca-11eb-8232-34f90c61f5a2.png">

Is it possible to rip sprites and/or audio using vAmiga?
Thanks.

**Comment by dirkwhoffmann** [comment]
It is possible to record a video (see the Files menu). The video is encoded via FFmpeg which needs to be installed in /usr/local/bin.

**Comment by DannyCork** [comment]
ok I'll need a different tool to rip sprites so. Thanks.
