### ISSUE TITLE
snapshots query

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#480]
HI,
Are the snapshots stored in the same format as UAE and where are they saved to?
Thanks.

**Comment by dirkwhoffmann** [comment]
No, it's a custom format. All snapshots that are taken via CMD+T (or by clicking the icon in the toolbar) are kept in memory, only. If you want to keep a snapshot, you need to save it via "Save.." in the Files menu.

**Comment by DannyCork** [comment]
excellent, thanks!
