### ISSUE TITLE
swaptro No network capability found

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#482]
An amiga demo has been released which connects via the internet to check for content. Supposedly it should work in emulators however it gives an error in vAmiga

![image](https://user-images.githubusercontent.com/3512672/113570927-3c93ea00-960d-11eb-80de-aea5df8f233b.png)

This video explains what's happening https://www.youtube.com/watch?v=_tuMqB67pj0 
This is the adf [swaptro.zip](https://github.com/dirkwhoffmann/vAmiga/files/6257982/swaptro.zip)
There is also a website www.swaptro.de

Do I need to enable a preference in vAmiga?

**Comment by dirkwhoffmann** [comment]
This demo doesn't work. vAmiga has no network support.
