### ISSUE TITLE
Broken background on Lupo Alberto (Idea Soft)

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#485]
On vAmiga this is what happen 😩

<img width="950" alt="Schermata 2021-04-09 alle 21 49 56" src="https://user-images.githubusercontent.com/45571833/114234312-e1505780-997e-11eb-9cbb-a17cffbd2808.png">

This is how it should be (SAE):

<img width="722" alt="Schermata 2021-04-09 alle 21 56 39" src="https://user-images.githubusercontent.com/45571833/114234527-2d030100-997f-11eb-9b22-95934d907aeb.png">

**Comment by dirkwhoffmann** [comment]
Poor Lupo 🙁. Interestingly not all frames are screwed up. If the game is run in the DMA debugger, it can be seen that a frame is screwed up if and only if bitplane DMA starts unusually early in the first row of the main part of the window:

Good frame: 

<img width="1030" alt="Bildschirmfoto 2021-04-10 um 08 19 41" src="https://user-images.githubusercontent.com/12561945/114260744-01136a00-99d7-11eb-9eb9-52a60d6ac131.png">

Bad frame:

<img width="1030" alt="Bildschirmfoto 2021-04-10 um 08 19 12" src="https://user-images.githubusercontent.com/12561945/114260819-5fd8e380-99d7-11eb-9a13-507733d49927.png">

Hence, I suspect this is a timing issue of the bitplane DMA. Next step: Investigate the Copper list.

**Comment by dirkwhoffmann** [comment]
Fixed in v1.0b1
