### ISSUE TITLE
Many of my trackloaded games no longer boot

### ISSUE THREAD

**Issue by alpine9000** [dirkwhoffmann/vAmiga#489]
Since 0.9.17 many of my trackloaded games no longer successfully boot with vAmiga.

While the trackloader code is probably not technically compliant - these disks boot on all of my real Amigas (real floppies and floppy emulators) and most other emulators (including vAmiga V0.16 and earlier).

An example game can be found in the ADF contained in the following archive:

http://aminet.net/package/game/2play/ElseWeGetMad

**Comment by dirkwhoffmann** [comment]
I've loaded it successfully in both v0.9.18 and v1.0b1. Could you double check the compatibility settings for the disk drive?

<img width="1053" alt="Bildschirmfoto 2021-04-22 um 10 41 52" src="https://user-images.githubusercontent.com/12561945/115684398-9b6c9980-a357-11eb-9856-4195c2076ea1.png">

**Comment by alpine9000** [comment]
Yes! For some reason my Speed was set at Infinite - setting it to "original" resolves the issue

**Comment by dirkwhoffmann** [comment]
>  For some reason my Speed was set at Infinite

This is most likely my fault. From time to time, I renamed some of the "user default keys" which means that some settings can be lost when upgrading to another release.

**Comment by alpine9000** [comment]
> > For some reason my Speed was set at Infinite
> 
> This is most likely my fault. From time to time, I renamed some of the "user default keys" which means that some settings can be lost when upgrading to another release.

It's very possible I set that up at some point - "Infinite" speed sounds like something I would want!
