### ISSUE TITLE
Serial interface (UART)

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#49]
I've added UART emulation to vAmiga in order to make DiagROM boot. To test the UART implementation, I need to emulate a device that is connected to the serial port.

Does anyone remember a simple device that got attached to the Amiga's serial port? A modem would be far too complicated.

**Comment by dirkwhoffmann** [comment]
The best thing to have would be an already existing (emulated) device that can be talked to via a (emulated) serial port (via a file, some API or something). 

Currently, vAmiga emulates the UART shift register and some interrupts. Unfortunately, I cannot test the implementation thoroughly, because to outputted bits are not read by any other device. DiagROM is happy with the current implementation, but I'm sure my code is still full of bugs. Serial input is not implemented at all. I need some piece of software that acts as a data provider (i.e., some device that delivers data to the Amiga's serial port) and an Amiga program that reads from that device.

**Comment by dirkwhoffmann** [comment]
Game "B.A.T II" uses a hardware dongle that is connected to the serial port. This could be a perfect test case.

**Comment by mithrendal** [comment]
Flight II uses nullmodem to connect two amigas for multiplayer. Maybe a more fun testcase?

**Comment by dirkwhoffmann** [comment]
> type ser: > con:

Yes, that might be doable. I could probably pipe the serial data to some Unix stream for communication ...

**Comment by mithrendal** [comment]
I just searched the correct syntax  
the syntax in CLI goes like this  
type con: to ser:
type ser: to con:

you could also pipe the stream into an file
with 
type ser: to ram:mystream

or let it speak on the other side
type ser: to speak:

**Comment by dirkwhoffmann** [comment]
An even simper approach: Emulate a loopback cable and test with DiagROM:

<img width="808" alt="Screenshot 2019-06-12 at 16 07 35" src="https://user-images.githubusercontent.com/12561945/59359002-de0dc580-8d2d-11e9-8353-e7e699f59259.png">

I guess Connect 4-5-6 means wiring all three together 🤔.

**Comment by mithrendal** [comment]
https://www.amigaforever.com/kb/13-105

**Comment by dirkwhoffmann** [comment]
2-3: Connects TXD and TXR (Transmitted Data and Received Data). The actual loopback. 

> 4-5-6 = ready to send - clear to send - data set ready

Makes sense: RTS is driven by the Amiga side (to request something from the peripheral device). DSR and CTR are driven by the peripheral device to signal their readiness. Hence, the bit written to RTS needs to be reflected on CTR and DSR. 

8-20-22: Data Carrier Detect, Data Terminal Ready, Ring Indicator

DTR (20) is connected to PA7 of CIA B (driven by the Amiga side).

I'm unsure about DCD (8) and Ring Indicator (22). As far as I can see, they are not accessible inside the Amiga by software. Therefore I guess, the 8-20-22 can be ignored for emulating the loopback cable.

**Comment by dirkwhoffmann** [comment]
> type con: to ser:

I get an error when I try to open con: 🙁

<img width="184" alt="Screenshot 2019-06-14 at 16 19 00" src="https://user-images.githubusercontent.com/12561945/59515789-37a5f980-8ec0-11e9-8b44-96f0e5337d71.png">

This command is intended to automatically push the keyboard input to the serial port, right? 

Background: DiagROM is now happy with vAmiga's serial port. So my plan was to plug in my super cool virtual loopback cable into the serial port of my not yet so cool virtual computer and do some experiments in CLI.

<img width="808" alt="Screenshot 2019-06-14 at 15 35 43" src="https://user-images.githubusercontent.com/12561945/59515617-ce25eb00-8ebf-11e9-9d0a-8e8a2611efa8.png">

**Comment by mithrendal** [comment]
hmm. Maybe con: is writre only ? 

Try:
1.with notepad write a short text 'Hello world' into df0:mytestfile 
2.from workbench open two CLI windows
3.in the lower CLI:  type ser: to con:
4.in the upper CLI type df0:mytestfile to ser:

**Comment by dirkwhoffmann** [comment]
> type ser: to con:

Same error. Maybe an emulator bug. Unfortunately, I can't try this is SAE, because it requires ':' be typed.

**Comment by mithrendal** [comment]
Ok try without con:

In the lower cli: 
type ser: to ram:testfile

**Comment by dirkwhoffmann** [comment]
I tried the following in UAE:

<img width="355" alt="Screenshot 2019-06-14 at 18 08 13" src="https://user-images.githubusercontent.com/12561945/59522649-8018e380-8ecf-11e9-8e42-886c928c0f79.png">

`testfile` appears in the RAM disk, but it is empty (same in vAmiga). I would have expected the file to contain data.

Maybe, I have to terminate the `type ser: to ...` before the file size changes. Unfortunately, I have forgotten how to do this in AmigaDOS. Cntrl-C and Cntrl-D do not work.

**Comment by dirkwhoffmann** [comment]
Current situation: 

When I issue `type .info to ser:`, vAmiga writes to the serial port as expected. If my new cutting edge loopback cable is connected, all data bytes also appear in the UART receive buffer as expected.

The missing piece is `type ser: to ram:testfile` which creates an empty file `ram:testfile`. We need to find out how I can tell this command to stop reading from ser:

**Comment by mithrendal** [comment]
wait I am just pulling your super cool cable version. I will try to get it working...

**Comment by dirkwhoffmann** [comment]
It's on the ExRom branch.

**Comment by mithrendal** [comment]
Oh no, my TV is blocked by my kids. All the xcode stuff is on my mac mini which is connected to my TV.  I have to connect via remote "bildschirm freigabe" into the vAmiga. When the remote vAmiga grabs the mouse the Amiga mouse is not moving, it can not be moved. The macOS mouse moves. hhmmm. There was a way in AmigaOS to move the mouse by keyboard ALT+Amiga and cursor. Which combination is that in vAmiga ??
Otherwise I have to wait until they go to bed ...

**Comment by mithrendal** [comment]
Please have a look at the following instruction point 10.   

https://www.everythingamiga.com/2017/05/amiga-explorer-pc-to-amiga-data-transfer-without-a-gotek-or-compact-flash.html

They transfer a file from PC to Amiga via "type ser: to ram:file" on Amiga side. When done they press Ctrl-C on Amiga side (nothing happens there after pressing Ctrl-C that's normal) and after that they press stop on sending side (which is the PC).

**Comment by dirkwhoffmann** [comment]
> and after that they press stop on sending side (which is the PC).

You stumbled across the exact same sentence as I did. The PC must signal EOF in some way. Before reading your post, I thought it might be done by a software interrupt (IRQ line 2 can be driven manually by a serial port pin). It turned out to be not the case. As a positive side effect, INTREQ and INTENA are now user-editable in the Paula inspector panel. 

Ctrl-\ might be a smoking gun. 

If an English keyboard is selected in the hardware prefs, ' \ ' key can be pressed on the virtual keyboard. 

<img width="860" alt="Screenshot 2019-06-15 at 09 06 32" src="https://user-images.githubusercontent.com/12561945/59548261-0a535d00-8f4d-11e9-9b1d-d706a379e7f9.png">

**Comment by dirkwhoffmann** [comment]
From the German Wiki site: 

    "AmigaDOS benutzt Strg+\, das entspricht dem ASCII-Steuerzeichen File Separator 0x1C."

I hacked the code such that 0x1C is transmitted after 10 normal characters, but it had no effect. I guess, end of transmission is signalled by the peripheral device by changing some pins at the RS232 port. 

In PA register of CIA-B, the following pins show up: DTR, RTS, CD, CTS, DSR. Hence, they must be among those.

**Comment by mithrendal** [comment]
Thought1: Maybe the 0x1C must be send after CTRL-C the receiving type command. 
Thought2: Then  0x1C is the same as ^\  ?


It must be then like this: 

CLI1> type ser: to ram:testfile
CLI2>type .info to ser:
CLI1>CTRL-C
CLI2>type filewithEOF to ser:
CLI1>***break (is displayed)

where the filewithEOF must contain only ^\  which is probably 0x1C

**Comment by dirkwhoffmann** [comment]
I also found this: 

http://ltxfaq.custhelp.com/app/answers/detail/a_id/736/~/what-is-a-serial-break%3F

    A serial break is not a character. It is a signal that can be sent 
    using the TX line of the device sending the break.

    When a serial port is idle and no data is being sent the TX line 
    is in a logical 1 state. While data is being send the TX line rapidly 
    transitions between logical 0 and logical 1. Each frame of data  
    takes a certain period of time to send, depending on the bit rate 
    of the connection. This is called the "frame time" or "word time".

    A break occurs when the TX line is held to a logical 0 for longer
    than one frame time.

**Comment by dirkwhoffmann** [comment]
Interesting: When I emulate a faked break (holding down TXD for a longer time), the first CLI shows a prompt again. Seems like it really received a break (although "BREAK" is not displayed in text).

However, the created file in the RAM disk is still empty. 

<img width="688" alt="Screenshot 2019-06-15 at 10 29 27" src="https://user-images.githubusercontent.com/12561945/59549088-cbc39f80-8f58-11e9-9354-dced0caf6868.png">

**Comment by dirkwhoffmann** [comment]
I've done some experiments with A-Talk III:

<img width="929" alt="Screenshot 2019-06-15 at 10 58 47" src="https://user-images.githubusercontent.com/12561945/59549370-be101900-8f5c-11e9-9398-fc74272a476f.png">

When I type in text, the characters are sent out to the serial port. If the loopback cable is plugged in (hardware preferences panel), the data is fed back and shows up in the receive buffer. 

    ...
    [10996] ( 99,201)  C110A0 GCBD 682D 1040 UART: pokeSERDAT(154)
    receiveBuffer: 54: T
    [11009] ( 80,122)  C110A0 GCBD 682D 1040 UART: pokeSERDAT(161)
    receiveBuffer: 61: a
    [11014] ( 78, 32)  C110A0 GCBD 682D 1040 UART: pokeSERDAT(16C) 
    receiveBuffer: 6C: l
    [11024] ( 77, 10)  C110A0 GCBD 682D 1040 UART: pokeSERDAT(16B)
    receiveBuffer: 6B: k
    [11054] ( 80,100)  C110A0 GCBD 682D 1040 UART: pokeSERDAT(120)
    receiveBuffer: 20:  

What we need is a terminal program, that can send and receive at the same time. Don't know if this is possible with A-Talk...

**Comment by dirkwhoffmann** [comment]
Update: 

- AmigaTestKit uses the UARTBRK bit in ADKCON to ground TXD which was not yet implemented. 
- It is possible to access RI (Ring Indicator) via software. It shows up on CIAB::PA2. In fact, it is hard-wired to the SELECT pin coming from the parallel port which can be seen in the (A500) schematics:

<img width="591" alt="Screenshot 2019-06-16 at 11 26 21" src="https://user-images.githubusercontent.com/12561945/59563440-81b2ea80-903a-11e9-9169-ebae6e954980.png">

AmigaTestKit is happy now:

<img width="572" alt="Screenshot 2019-06-16 at 13 20 29" src="https://user-images.githubusercontent.com/12561945/59563415-12d59180-903a-11e9-93ef-039f608ba8fd.png">

**Comment by dirkwhoffmann** [comment]
I'm closing this for now. Unless we don't know that the "type <file> to ser:" stuff really works with a loopback cable, we risk to run into a dead end here. As far as I know, UAE cannot emulate a loopback cable (?!), so we are not able to easily test it there.

**Comment by mithrendal** [comment]
The secret why `type ser: ram:somefile` resulted always in an empty file continues…  see https://github.com/vAmigaWeb/vAmigaWeb/issues/154

And is solved partly … look here the file has 400 bytes …
![39A55F4A-7BD8-4907-904F-811FEC8A9F51](https://user-images.githubusercontent.com/17108995/227795701-d1cdfbeb-425e-483c-8bfd-b7a41598b8c9.jpeg)

new findings serial device writes in 200 byte chunks only …
