### ISSUE TITLE
SmartyAndTheNastyGluttons freezes

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#490]
[SmartyAndTheNastyGluttons.adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/6384547/SmartyAndTheNastyGluttons.adf.zip)

When booting the disk, the background turns blue and the loading process freezes almost immediately (the drive does not move away from track 0).

Observations: Works well in UAE and FS-UAE with lowest compatibility settings (turbo drive, immediate Blitter). Does not boot in SAE.

**Comment by dirkwhoffmann** [comment]
It's most likely a CPU issue, related to the implementation of the STOP command.

<img width="980" alt="Bildschirmfoto 2021-04-28 um 10 21 48" src="https://user-images.githubusercontent.com/12561945/116372000-4a075300-a80c-11eb-8417-d908647d86aa.png">

The STOP command is executed at address $D2 (debug entry point was $C4) with a payload that has the trace bit set. In vAmiga, this immediately triggers a trace exception which is most likely wrong. 

Next steps: Check if cputester can generate adequate test cases for the STOP command. If not, write vAmigaTS tests for STOP with different values for the trace bit.

**Comment by dirkwhoffmann** [comment]
Fixed 😎

<img width="854" alt="Bildschirmfoto 2021-04-29 um 06 38 00" src="https://user-images.githubusercontent.com/12561945/116559452-c67b5e00-a900-11eb-8526-499995200b8d.png">

**Comment by emoon** [comment]
I'm surprised to see a game to use the `stop` instruction. I wonder for what purpose it's being used.

**Comment by dirkwhoffmann** [comment]
> I'm surprised to see a game to use the stop instruction. I wonder for what purpose it's being used.

The game utilises `STOP` frequently. I didn't look into all details, but I got the impression that the programmer used it to sync the code with the frame rate (by waking up the CPU with the VBLANK interrupt).

Overall, the code is a real mess. It contains self-modifying code with the effect that good looking code is replaced by illegal instructions in order to invoke code inside the exception handler. All this happens in UAE, too, so I guess this was really the intention of the programmer. There is a positive side of all this: Every emulator that is capable of handling all these oddities is doing a whole lot right.

**Comment by emoon** [comment]
Interesting. That sound like a really odd way to do it for sure, but yeah great that it's working :)
