### ISSUE TITLE
vAmiga 1.0b1 failing to compile on Xcode 12.5

### ISSUE THREAD

**Issue by shinra-electric** [dirkwhoffmann/vAmiga#491]
Xcode 12.5 has a problem with this function: 

![Screenshot 2021-04-27 at 15 07 20](https://user-images.githubusercontent.com/50119606/116256260-f0028100-a76a-11eb-9d1f-6c2756359a63.png)

**Comment by dirkwhoffmann** [comment]
Seems like Xcode 12.5 comes with a new version of Swift. It's a minor thing, but I need to update my OS first...

**Comment by dirkwhoffmann** [comment]
Finally... update completed 🥱.

The default operator `??`is not needed here, because the element `addrCache[row]` always exists. Hence, the fix was super easy: 

```
       case "addr":
            return last ? "Add address" : addrCache[row]!
```

I've checked in the fix and merged it into the main branch. Now, it should compile without issues.

**Comment by shinra-electric** [comment]
Yep, building fine now. 

👍🏼
