### ISSUE TITLE
The provided download "requires macOS 10.15 or later" 

### ISSUE THREAD

**Issue by mooli** [dirkwhoffmann/vAmiga#492]
Hi,

I routinely decline Apple's frequent nags to "upgrade" (downgrade) to Catalina and Big Sur and keep my machine running Mojave. Unfortunately, the vAmiga v1.0 Beta 1 download will not launch on Mojave (10.14.6 in my case) because it is built to require a minimum of Catalina (10.15).

Presumably this was just an oversight in the build settings when creating this binary and vAmiga does not actually require specific Catalina functionality? It would be a bit odd for an Amiga emulator to require one to be using a bleeding-edge Mac!

**Comment by dirkwhoffmann** [comment]
Quick analysis: 

macOS 10.14 is required because of:
scollableTextView(), selectedContentBackgroundColor, alternatingContentBackgroundColor 

macOS 10.15 is required because of:
monospacedSystemFont

The 10.15 requirement can be dropped easily, the 10.14 requirements can't.

**Comment by dirkwhoffmann** [comment]
Fixed in v1.0b2
