### ISSUE TITLE
Hat mapping is incorrect with Xbox One wired controller (v1.0r3)

### ISSUE THREAD

**Issue by warpdesign** [dirkwhoffmann/vAmiga#498]
I could not reopen the previous [issue](https://github.com/dirkwhoffmann/vAmiga/issues/495).

With the latest v1.0r3:

pressing up: OK
pressing Down: pulls Right instead
pressing Left: pulls Down instead
pressing Right: pulls Left instead

**Comment by dirkwhoffmann** [comment]
Perfect! 

BTW, another method of using the Xbox controller is to connect it via the Magic-NS stick (in case the Xbox driver won't work in future OS releases). Via the stick, the game pad presents itself as a Nintendo Switch controller. It worked out of the box in vAmiga. 

![magic-ns](https://user-images.githubusercontent.com/12561945/117820123-84400e00-b26a-11eb-8e79-51d769b2e51b.png)
