### ISSUE TITLE
FPS / Emulation speed relative to original?

### ISSUE THREAD

**Issue by warpdesign** [dirkwhoffmann/vAmiga#499]
Is there an FPS or speed metter that would show the speed of emulation relative (100% would mean speed is on par with original, 80% would mean it's slower,...) to the original computer? Didn't see it in prefs.

My MacBook (i3/2017) appears to be slower than the real thing but I have no way to measure it.

**Comment by emoon** [comment]
if you press the "unlock" you can see it going into warp mode (and thus it will run as fast as your machine can run (or something like that at least)
