### ISSUE TITLE
Confirmation/OK button not working on the Monitor inspector

### ISSUE THREAD

**Issue by shinra-electric** [dirkwhoffmann/vAmiga#503]
Expected the OK button to close the window, but it doesn't.

Also, for a bonus issue, somehow Chanel No. 2 got it's way into the Audio preferences... 

![Screenshot 2021-05-23 at 20 08 15](https://user-images.githubusercontent.com/50119606/119273394-b35b6580-bc02-11eb-9daa-6af2aaffcb5e.png)

I think it needs to be bumped to the latest version, Chanel No.5....  😄

**Comment by dirkwhoffmann** [comment]
The perfume-issue is fixed. 

> Expected the OK button to close

It closes the window here. Which OK button did you press?

**Comment by shinra-electric** [comment]
The OK button in the bottom right of the Monitor inspector. 

Neither clicking or return will close the window. 

(I'm on v.1 by the way, Intel Mac) 

https://user-images.githubusercontent.com/50119606/119361991-27017f00-bca4-11eb-9e02-d90bb2d3ccf5.mp4

**Comment by dirkwhoffmann** [comment]
Oh, I see, the "OK" button in the monitor panel. I was checking the OK button in the perfume panel. 

It'll work in the next release.
