### ISSUE TITLE
Only one mouse works

### ISSUE THREAD

**Issue by koxman73** [dirkwhoffmann/vAmiga#504]
I have an Apple touchpad and a Logitec M705 mouse connected. Only Touchpad works. Second input device (mouse) does not work.

**Comment by koxman73** [comment]
vAmiga 1.0
iMac Retina 27" 2017
MacOS Big Sur

Tested with "Hibernated Directors Cut" Game. Kick 1.3 and default settings.

**Comment by dirkwhoffmann** [comment]
If multiple pointing devices are attached, the toolbar menu should look similar to this: 

<img width="289" alt="Bildschirmfoto 2021-05-24 um 16 18 30" src="https://user-images.githubusercontent.com/12561945/119361461-fb829280-bcab-11eb-9a70-3d9d3214faff.png">

The first mouse icon is the internal mouse, the second one is the external mouse. In theory, both the Logitech mouse and the external touch pad should map to the external mouse (second symbol).

**Comment by koxman73** [comment]
<img width="198" alt="Screenshot 2021-05-24 at 16 35 48" src="https://user-images.githubusercontent.com/74765127/119363623-4d2c1c80-bcae-11eb-94b0-513b17017fed.png">

Touchpad connects to "Mouse" .. Logitech Mouse to "USB Receiver" .. so you can switch but they are different

**Comment by dirkwhoffmann** [comment]
> If switching is OK

That's the intended behaviour. BTW, it's interesting to see that the Touch Pad cannot be distinguished from the primary mouse.
