### ISSUE TITLE
Space Key of real Keyboard does not work

### ISSUE THREAD

**Issue by koxman73** [dirkwhoffmann/vAmiga#505]
vAmiga 1.0 (default settings)
Kickstart 1.3 (and 3.1)
iMac 27" 2017
MacOS BigSur 13.3.1

The Space Key of the real Keyboard (Apple Bluetooth Keyboard with NumPad) does not work with the Emulator (tested Workbench 1.3.1 (Cloanto) and Hibernated Directors cut) .. The Space Key of the Virtual Keyboard does work.

**Comment by dirkwhoffmann** [comment]
> The Space Key of the real Keyboard does not work 

Is a keyboard-emulated joystick connected to one of the two control ports?

**Comment by koxman73** [comment]
After restart the spacekey works .. might be my fault. Issue can be closed
