### ISSUE TITLE
Crash when drag/drop ROM Image on M1 MacBook Pro

### ISSUE THREAD

**Issue by koxman73** [dirkwhoffmann/vAmiga#506]
vAmiga 1.0
MacBook Pro M1 (16GB)
MacOS: Big Sur 11.3.1
When drag/drop Kickstart ROM to Droparea, vAmiga crashes:

Crashlog added as text
<img width="755" alt="Screenshot 2021-05-24 at 16 45 17" src="https://user-images.githubusercontent.com/74765127/119364711-74371e00-bcaf-11eb-87c7-891abbc0654f.png">
[vAmiga Crashlog.txt](https://github.com/dirkwhoffmann/vAmiga/files/6533152/vAmiga.Crashlog.txt)

PS: Sorry for opening so many bugs (especially for the no bugs one)

**Comment by dirkwhoffmann** [comment]
Does it happen with all Roms or with a particular one? If the crash is deterministic and happens with a particular Rom only, could you drop me an email with an attachment?

**Comment by koxman73** [comment]
This is very strange. I had this issue with an 1.3kick (with wrong crc) and an 3.1 kick which was working correctly.
I Now tried to reproduce and I could drag'n'drop. I had a crash when powering up. Trying to reproduce leads into an working Bootscreen. Also Kick 3.0 works now ... Will reboot to reproduce

**Comment by dirkwhoffmann** [comment]
Also important: Are you Kickstart files zipped? We had trouble with zipped files before, but didn't manage to track the issue down (it never occurred on my development machine).

**Comment by koxman73** [comment]
After reboot my usual ROMs worked .. but the cloanto rom crash. on my Intel Mac I only get an error message that the key is missing.

Tried "amiga-os-204.rom and "amiga-os-310-a1200.rom" (from Cloanto DVD) .. both are crashing when drag&drop
Can send if necessary

**Comment by koxman73** [comment]
PS: cloanto rom crash on intel too

**Comment by dirkwhoffmann** [comment]
> Can send if necessary

Yes, please.

**Comment by dirkwhoffmann** [comment]
I don't need the Roms at the moment. I've overseen this in the log before: 

> terminating with uncaught exception of type VAError: MISSING_ROM_KEY

**Comment by koxman73** [comment]
Beta Version gives now correct errormessage 'No "key.rom" file found' if key.rom is not present in folder.
Tested with iMac 27" 2017 (intel i7) and MacBook Pro M1 (Apple) with the same results.

**Comment by dirkwhoffmann** [comment]
Thanks for confirming.
