### ISSUE TITLE
dms fails to open : drag operation fails

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#514]
I note in #378 the vAmiga supports dms images. When I attempt to drag and drop a dms eg
http://ftp.amigascne.org/pub/amiga/Groups/M/mdma/MDMA-BallaBorntro.dms
or
http://ftp.amigascne.org/pub/amiga/Groups/M/mdma/MDMA-XmasSprengtro.DMS

I get an error
![image](https://user-images.githubusercontent.com/3512672/124048140-8ffbb580-da0d-11eb-8135-f5804217e0f5.png)

If I attempt to insert the disk via Df0 --> insert 
I get a different error.

![image](https://user-images.githubusercontent.com/3512672/124048242-c5080800-da0d-11eb-8c4e-e6fc14eb1dc9.png)

Vamiga Version 1.0.1 (1.0.1)

**Comment by dirkwhoffmann** [comment]
Confirmed. I can no longer read DMS files either, not even in older vAmiga releases. Maybe it's related to some recent macOS update. Needs investigation...

**Comment by dirkwhoffmann** [comment]
This one is strange. I cannot load DMS files with any older release on my dev machine any more, but compiling the project with the latest Xcode release seems to fix the problem.

Could you give v1.0.2 a try? It's a recompilation of the project with the latest Xcode release.

**Comment by DannyCork** [comment]
1.0.2 looks much better 


upon inserting a dms I get a dialog like so


![Screenshot 2021-07-04 at 21 38 07](https://user-images.githubusercontent.com/3512672/124398919-31d21980-dd10-11eb-8ca2-17f4124711b0.png)

and the dms boots.

Great !

**Comment by dirkwhoffmann** [comment]
> upon inserting a dms I get a dialog like so

Great! This is how it is supposed to look like.
