### ISSUE TITLE
vAmiga title always Untitled

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#516]
I've noticed that the vAmiga title is always 'Untitled'
![image](https://user-images.githubusercontent.com/3512672/125006880-0aa08280-e057-11eb-979d-fe16322191aa.png)

I expected that when I dropped an adf the title would update.

**Comment by dirkwhoffmann** [comment]
This is not a bug. The displayed name is the name of the snapshot file that is associated with the emulator instance. If no snapshot has been saved, the name is always "Untitled".

**Comment by DannyCork** [comment]
True but it would be a nice feature :)

If Snapshot 
  Display Snapshot name
Else
  If adf/dms mounted
     Display image name 
  Else
     Display untitled 

"Untitled" doesn't add any value (IMO).

**Comment by dirkwhoffmann** [comment]
> "Untitled" doesn't add any value (IMO).

Yes, that's true, but the app does it automatically. vAmiga complies to what Apple calls a "document based Cocoa app" and the result is what we're seeing here.

**Comment by DannyCork** [comment]
Even thought the compilation of an "document based Cocoa app" results in Untitled, could it be modified to display the adf/dms image name ?

**Comment by dirkwhoffmann** [comment]
I don't think it's a good idea to diverge from the standard here. E.g., I don't know what macOS will do if I assign an URL to an ADF and select "Revert" from the "File" menu (by default, "Revert" calls the code for loading snapshots). From the macOS side, the app would be inconsistent and we can't be sure how the OS would react on it in various situations.
