### ISSUE TITLE
Open image from Finder, redundant dialog box

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#517]
- With vAmiga closed.
- Double click on adf in finder
<img width="305" alt="image" src="https://user-images.githubusercontent.com/3512672/126627092-859e1837-3e85-485b-b6de-2b0e433b0cab.png">

Observation
- vAmiga opens a dialog asking the user to select a disk drive.
![image](https://user-images.githubusercontent.com/3512672/126627216-c06f47c3-e9b9-4266-9f08-f5d4b7d1057a.png)

Improvement:
- In this scenario automatically select Df0 and don't display the dialog.

Notes:
- Selecting Df0, Drag and drop target isn't of use in this scenario as that is only used when a drag and drop takes place, not open an image from Finder.
- If a user double clicks on an adf in the Finder then Df0 is what the user wants. I don't believe it is possible or very unlikely that the user wants to boot from a different drive.

**Comment by dirkwhoffmann** [comment]
In v1.1, an ADF will be inserted automatically into df0 if 
- it was double-clicked or
- dragged onto the app icon in the dock.

**Comment by dirkwhoffmann** [comment]
V1.1b1 is available.
