### ISSUE TITLE
Paradox Intro (from game Wings) bitplane misaligned

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#518]
Sorry, don't have a Mac, this is my webassembly port :)
The scroll text seems to have one bitplane misaligned in this intro, works correctly on WinUAE (OCS 512K+512K KS1.3)

![paradox](https://user-images.githubusercontent.com/3858768/132681682-2a470993-36ff-489e-a341-105b10195430.png)
![paradox_winuae](https://user-images.githubusercontent.com/3858768/132681695-88d4632b-4ec7-4dbc-a340-640ff3ab82f6.png)

**Comment by chris70c** [comment]
Forgot the intro (attached zip file contains exe)
[paradox.zip](https://github.com/dirkwhoffmann/vAmiga/files/7136271/paradox.zip)

**Comment by dirkwhoffmann** [comment]
A webassembly port 🤤. This is exciting news.

v1.0.1 shows the same issue:

<img width="710" alt="Bildschirmfoto 2021-09-09 um 14 33 02" src="https://user-images.githubusercontent.com/12561945/132686822-5214ec19-9bc9-433d-8b64-e1297d5049f6.png">

**Comment by mithrendal** [comment]
@chris70c do you have any url to try the webport?

**Comment by dirkwhoffmann** [comment]
For reference... 

 X-ray:

<img width="886" alt="Bildschirmfoto 2021-09-09 um 14 35 08" src="https://user-images.githubusercontent.com/12561945/132686985-37065d56-2cca-4487-96d4-02bcbb79221c.png">

Copper list 1:

<img width="372" alt="Bildschirmfoto 2021-09-09 um 14 33 40" src="https://user-images.githubusercontent.com/12561945/132687055-ed9a3cbc-d6ae-4ced-89fc-8e78b968d6b8.png">

Relevant part of Copper list 2:

<img width="357" alt="Bildschirmfoto 2021-09-09 um 14 34 47" src="https://user-images.githubusercontent.com/12561945/132687104-22413953-1ca3-434c-81c4-c144a312f359.png">

**Comment by chris70c** [comment]
@mithrendal, I'm in the process of moving my domain to a new company so my site is gonna be down for at least 10 days, after that hopefully it will be back, they're not publicly available yet but if I can send you an email with the address to see it.

**Comment by mithrendal** [comment]
@chris70c 

I just send you a pm (email).

I bet the problem lies in the mergeTexture logic ...
https://github.com/dirkwhoffmann/vAmiga/wiki/GPU

do you have the source code somewhere so that we can look into that matter ?

**Comment by dirkwhoffmann** [comment]
Fixed by commit 54e2419

**Comment by dirkwhoffmann** [comment]
Fixed in vAmiga 1.1b2
