### ISSUE TITLE
Prestige Intro (from game JetStrike AGA) text jumping

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#519]
In this Prestige (from the game JetStrike AGA) (zip attached)
every time the text change there is a small jump (top left) right before the scrolling effect,
works fine in WinUAE (OCS 512K + 512K KS1.3).
[prestige_jetstrike.zip](https://github.com/dirkwhoffmann/vAmiga/files/7136331/prestige_jetstrike.zip)

**Comment by dirkwhoffmann** [comment]
I need help with that one. I run it in FSUAE and to me it seemed to look the same as in vAmiga 1.0.1 and vAmiga 1.1b. I didn't notice any jump.

**Comment by chris70c** [comment]
Need to make a small video, or see if I can capture a couple of screenshots exactly when it happens.

**Comment by dirkwhoffmann** [comment]
Here is a short video recorded with vAmiga 1.1b1:

http://dirkwhoffmann.github.io/vAmiga/videos/prestige.mp4

**Comment by chris70c** [comment]
Here's both video vAmiga and WinUAE

https://user-images.githubusercontent.com/3858768/132693841-7702f737-4e86-4311-9097-66d48c86b19e.mp4


https://user-images.githubusercontent.com/3858768/132693849-463cdf3e-5f0a-4387-b1fd-1ec541be2d40.mp4

**Comment by dirkwhoffmann** [comment]
It seems like an issue in the webassembly version, only. My first guess is that is has something to do with the merging of the two half images that are coming from the emulator. But this is really just a guess.

BTW, I'll be offline for a couple of days...

**Comment by chris70c** [comment]
@dirkwhoffmann: I've sent you an email with some information.

**Comment by dirkwhoffmann** [comment]
Solved: The issue vanishes if the Blitter runs in accuracy level 2.
