### ISSUE TITLE
Tarkus Team Cracktro 2

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#523]
Bitplanes garbage.

![vamiga](https://user-images.githubusercontent.com/3858768/132803913-85760251-73f6-4563-84d9-d80601bcdc4c.png)
![winuae](https://user-images.githubusercontent.com/3858768/132803921-d33c0f01-4a48-42b8-b6ee-31b6c15490dc.png)

[Tarkus_Team.crack08.zip](https://github.com/dirkwhoffmann/vAmiga/files/7141466/Tarkus_Team.crack08.zip)

**Comment by dirkwhoffmann** [comment]
Broke with commit b022b45. In this commit, "register write dropping" got enabled by default. In fact, if the latest code is compiled with debug option

    static const int NO_PTR_DROPS    = 1; // Never drop a pointer register write

the graphics glitches are gone. Bottom line: A pointer write is dropped erroneously. Needs investigation...

**Comment by dirkwhoffmann** [comment]
Fixed in vAmiga 1.1b2
