### ISSUE TITLE
Tarkus Team Cracktro 3

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#524]
Missing bottom part of the center effect.

![vamiga](https://user-images.githubusercontent.com/3858768/132804286-fffce2d7-1474-43d6-833b-54e3be1c3c9c.png)
![winuae](https://user-images.githubusercontent.com/3858768/132804139-28fff2e3-6558-4286-8de4-9464dbfd9ae7.png)

[Tarkus_Team.crack09.zip](https://github.com/dirkwhoffmann/vAmiga/files/7141463/Tarkus_Team.crack09.zip)

**Comment by dirkwhoffmann** [comment]
The intro must be run with Blitter accuracy level 2. In level 0 or level 1, the bottom part gets cropped.
