### ISSUE TITLE
Darkside Intro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#529]
Bitplane misaligned, text alignment seems quite off.

![vamiga](https://user-images.githubusercontent.com/3858768/133134340-57219be4-c8e2-4192-b904-be8fb7e443cc.png)
![winuae](https://user-images.githubusercontent.com/3858768/133134343-20928291-352c-4f5c-8c7e-30400175378c.png)
[Darkside 2D.zip](https://github.com/dirkwhoffmann/vAmiga/files/7156481/Darkside.2D.zip)

**Comment by mithrendal** [comment]
Text says: greetings go out to all forgotten ones! They refer to us 🤩… From the past.

**Comment by dirkwhoffmann** [comment]
Looks good with the latest code changes:

<img width="853" alt="Bildschirmfoto 2021-09-15 um 17 07 52" src="https://user-images.githubusercontent.com/12561945/133469476-c361e646-4f46-43ca-9c69-bd16a6b0b909.png">

**Comment by dirkwhoffmann** [comment]
Fixed in vAmiga 1.1b2
