### ISSUE TITLE
Paradox Magician Crack

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#530]
Bitplane misaligned on scroll text, similar to Paradox (from Wings).

![vamiga](https://user-images.githubusercontent.com/3858768/133192464-bfe785bc-3950-4e0c-a4d6-63a6f2f0bc2c.png)
![winuae](https://user-images.githubusercontent.com/3858768/133192469-677278c5-3e0f-4525-8f4e-1d23f0e24883.png)
[Paradox-CrMagician.zip](https://github.com/dirkwhoffmann/vAmiga/files/7158779/Paradox-CrMagician.zip)

**Comment by dirkwhoffmann** [comment]
Looks good with the latest code changes:

<img width="853" alt="Bildschirmfoto 2021-09-15 um 17 09 54" src="https://user-images.githubusercontent.com/12561945/133469804-37ec10f8-4d8c-4c22-bc75-4c0771b5be60.png">

**Comment by dirkwhoffmann** [comment]
Fixed in vAmiga 1.1b2
