### ISSUE TITLE
IC Import Intro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#531]
Font gfx problems...

![vamiga](https://user-images.githubusercontent.com/3858768/133299814-a8904c6d-3e0e-44e0-b81f-4475a1ad6319.png)
![winuae](https://user-images.githubusercontent.com/3858768/133299822-747ef2cf-4ebc-4a35-be2a-c13ea1671fbf.png)
[IC-AnotherImport.zip](https://github.com/dirkwhoffmann/vAmiga/files/7163725/IC-AnotherImport.zip)

**Comment by dirkwhoffmann** [comment]
Oh yes, I remember this one 😀. It's the intro with the flying bananas.

The text is fine now:

<img width="853" alt="Bildschirmfoto 2021-09-15 um 17 12 31" src="https://user-images.githubusercontent.com/12561945/133470457-0be96ef6-fa01-4892-9cf7-fc0c5896fbf0.png">

Don't get confused by the marked graphics glitch. A couple of month ago, I had a hard time to find the "bug" until I found out that it's a feature (as you can read here: #138)

**Comment by dirkwhoffmann** [comment]
Fixed in vAmiga 1.1b2
