### ISSUE TITLE
Sect Import Intro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#532]
Middle section is way off to the right.

![vamiga](https://user-images.githubusercontent.com/3858768/133300185-61620d4f-8b4c-451e-ba28-723529f66515.png)
![winuae](https://user-images.githubusercontent.com/3858768/133300190-2d6f54c2-0772-4893-ad05-de0b6c985e6c.png)
[Sect-AnotherImport.zip](https://github.com/dirkwhoffmann/vAmiga/files/7163734/Sect-AnotherImport.zip)

**Comment by dirkwhoffmann** [comment]
X-ray:

<img width="853" alt="Bildschirmfoto 2021-09-15 um 18 06 20" src="https://user-images.githubusercontent.com/12561945/133478812-6e4b1637-7378-4282-a142-e78b8ee2c508.png">

First findings:

There is a lot of sprite activity in the erroneous area which is most likely not related to the bug (sprites are used to draw the star field). Dual-playfield mode is utilised. Cropping everything except PF2 yield the following image which means the faulty text is drawn in playfield 2:

<img width="853" alt="Bildschirmfoto 2021-09-15 um 18 07 44" src="https://user-images.githubusercontent.com/12561945/133479200-8c7655d6-77c0-4aa2-af5c-f8628b73cc79.png">

Beginning of the Copper list:

<img width="980" alt="Bildschirmfoto 2021-09-15 um 18 10 28" src="https://user-images.githubusercontent.com/12561945/133479247-4472dee0-c458-45c3-89b5-0f78adf290aa.png">

Interestingly, there is no WAIT at the beginning. However, as can be seen in the X-ray, Copper activity starts in the middle of the screen. This means the CPU is involved in starting and stopping the Copper which smells like a smoking gun to me...

**Comment by dirkwhoffmann** [comment]
Update: This code is from `Agnus::setBPLCON0`:

```
    // Check if the hires bit or one of the BPU bits have been modified
    if ((oldValue ^ newValue) & 0xF000) {
        
        // Update the DMA allocation table
        updateBplEvents(dmacon, newValue, pos.h);
```


If the last line is changed to ...

        updateBplEvents(dmaconAtDDFStrt, newValue, pos.h);

... the demo looks just fine.

<img width="853" alt="Bildschirmfoto 2021-09-17 um 09 47 51" src="https://user-images.githubusercontent.com/12561945/133756854-baa2812f-b444-49f4-96ea-c11d8bcd47ca.png">

Background: The demo modifies both DMACON and BPLCON0 in the middle of scanline 141. There is some interplay between these registers, but I am unsure about the details. At the moment, this is just trial and error. I would need more details about the internal working of Agnus to really see what's going on.
