### ISSUE TITLE
Razor 1911 New Stuff

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#533]
Weird bar to the left.

![vamiga](https://user-images.githubusercontent.com/3858768/133300506-ab5abece-9d05-4e76-938d-c987d156fc8f.png)
![winuae](https://user-images.githubusercontent.com/3858768/133300510-8524673b-ca92-44d4-a2b6-710bd192b884.png)
[Razor1911-NewStuff.zip](https://github.com/dirkwhoffmann/vAmiga/files/7163751/Razor1911-NewStuff.zip)

**Comment by dirkwhoffmann** [comment]
This is not a bug in the emulator, but in the demo. See Toni's comment in #380: "DMA was disabled while mouse pointer is being drawn".

Sometimes the bug hits (which happens here, e.g., when the disk was inserted at the time  the emulator was reset): 

<img width="853" alt="Bildschirmfoto 2021-09-15 um 20 12 17" src="https://user-images.githubusercontent.com/12561945/133495228-365ee39f-8014-43e7-83ef-961a9ad9ecb4.png">

Sometimes it doesn't (which happens most of the time when the disk is inserted manually after a reset):

<img width="853" alt="Bildschirmfoto 2021-09-15 um 20 07 48" src="https://user-images.githubusercontent.com/12561945/133494895-b69cf126-14ee-4c7b-8505-a9cf89a93413.png">
