### ISSUE TITLE
AFL Crack Disklab V12

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#535]
Slow and jerky, at alternate frames the Triton logo at the bottom right becomes white.

[AFL-CrackDisklabV12.zip](https://github.com/dirkwhoffmann/vAmiga/files/7163803/AFL-CrackDisklabV12.zip)

**Comment by dirkwhoffmann** [comment]
I can't reproduce this one. For me, it looks similar to what I see in FSUAE:

<img width="853" alt="Bildschirmfoto 2021-09-16 um 09 40 03" src="https://user-images.githubusercontent.com/12561945/133580743-c1314ba0-eed3-4d8b-b3bc-55df35aafa4f.png">

**Comment by chris70c** [comment]
Need to investigate the main loop and check if there are skipped frames.

**Comment by chris70c** [comment]
Yes, looks perfect now, confirmed :)
