### ISSUE TITLE
Coast Premiere Crack

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#537]
Freezes when it starts.

[Coast-CrackPremiere.zip](https://github.com/dirkwhoffmann/vAmiga/files/7166426/Coast-CrackPremiere.zip)

**Comment by dirkwhoffmann** [comment]
Needs investigation. It doesn't freeze in the desktop version:

<img width="853" alt="Bildschirmfoto 2021-09-16 um 10 21 41" src="https://user-images.githubusercontent.com/12561945/133586607-079a94d2-fb33-407e-9fdf-32e21fbd8907.png">

**Comment by dirkwhoffmann** [comment]
Seems to work fine now 

<img width="744" alt="Bildschirmfoto 2021-10-17 um 17 53 16" src="https://user-images.githubusercontent.com/12561945/137635002-da566933-b365-465e-b169-6f2de983440d.png">
