### ISSUE TITLE
Cardinal Turrican Crack

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#538]
Serious speed issues, fast slow fast slow.

[Cardinals-CrackTurrican.zip](https://github.com/dirkwhoffmann/vAmiga/files/7166431/Cardinals-CrackTurrican.zip)

**Comment by dirkwhoffmann** [comment]
I don't experience any speed issue in the desktop version. However, I noticed that the demo doesn't turn the drive motor off. This means that it runs in warp mode if the GUI has auto-warp-mode enabled (auto-warp means that warp mode is enabled when the drive motor is on). Did you implement something similar in the web version?

**Comment by chris70c** [comment]
No, right now there is no warp mode at all, I need to verify the main loop and see if it is skipping frames.

**Comment by dirkwhoffmann** [comment]
Seems to work now (I didn't spot a difference to what I can see in the Desktop version or in UAE)
