### ISSUE TITLE
Crystal Arabian Nights Cracktro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#539]
Middle line should reach the bottom straight, weird line on top of scrolltext to the right.

![vamiga](https://user-images.githubusercontent.com/3858768/133373890-1ecae2da-fddb-4cd0-b478-2dd786f3a507.png)
![winuae](https://user-images.githubusercontent.com/3858768/133373895-2fa7dd63-e022-4267-8b5b-c0d1710c9512.png)
[Crystal-CrackArabianNights.zip](https://github.com/dirkwhoffmann/vAmiga/files/7166883/Crystal-CrackArabianNights.zip)

**Comment by dirkwhoffmann** [comment]
Strange. I can't reproduce this one either. This is how it looks like in the Desktop version v1.1b1:

<img width="853" alt="Bildschirmfoto 2021-09-16 um 10 46 38" src="https://user-images.githubusercontent.com/12561945/133590501-0bc117bf-ae5e-463e-91f1-ac7bbb222f5f.png">

Maybe it's related to some setting discrepancies. Here are mine:

<img width="853" alt="Bildschirmfoto 2021-09-16 um 10 46 12" src="https://user-images.githubusercontent.com/12561945/133590610-bcb50f42-9051-4a9d-8626-16f3ce52b7a3.png">

<img width="853" alt="Bildschirmfoto 2021-09-16 um 10 46 30" src="https://user-images.githubusercontent.com/12561945/133590580-d7abb7f8-5aab-4912-8b41-4da1f18c83bf.png">

<img width="853" alt="Bildschirmfoto 2021-09-16 um 10 46 23" src="https://user-images.githubusercontent.com/12561945/133590596-3b0a65c7-8169-4f54-a4c2-26ac9360adaf.png">

**Comment by chris70c** [comment]
This has been fixed with yesterday master branch.
