### ISSUE TITLE
Thrust Empire Cracktro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#540]
Wrong color in the bottom picture or bitplane misaligned.

![vamiga](https://user-images.githubusercontent.com/3858768/133374118-05699780-5486-4cf2-95bd-6b0752e06228.png)
![winuae](https://user-images.githubusercontent.com/3858768/133374144-62f3a7f6-d317-4be2-85fe-68e12f25b5a5.png)
[Thrust-CrackEmpireV205.zip](https://github.com/dirkwhoffmann/vAmiga/files/7166894/Thrust-CrackEmpireV205.zip)

**Comment by dirkwhoffmann** [comment]
Strange. Seems to work in the desktop version (even in v1.1b1 which has the DDF bug):

<img width="853" alt="Bildschirmfoto 2021-09-16 um 10 54 47" src="https://user-images.githubusercontent.com/12561945/133592165-63afc2ef-9910-4166-b211-89e6e281ca46.png">
