### ISSUE TITLE
Human Target Intro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#545]
This one is a bit weird, in WinUAE with 512K+512K it gets stuck here:
![winuae](https://user-images.githubusercontent.com/3858768/134213903-75abdb19-21dd-4666-a953-a3a5698f15d1.png)
which is correct because it requires 1MB chip ram.
In vAmiga it runs with 512K+512K but without any audio.
[MD-HumanTarget.zip](https://github.com/dirkwhoffmann/vAmiga/files/7204928/MD-HumanTarget.zip)

**Comment by dirkwhoffmann** [comment]
Findings: 
- With 512K+512K, it now freezes at the position mentioned above.
- With 1024K+0K, it freezes here:
    <img width="744" alt="Bildschirmfoto 2021-10-17 um 18 08 09" src="https://user-images.githubusercontent.com/12561945/137635601-ba5729bb-8bd6-4a48-9600-bafb1a0c9e76.png">

    Important: Agnus 8372 is needed to address 1MB of chip memory.

- With 1024K+512K, the demos runs just fine.

This is exactly what happens in the desktop version as well as in UAE. Bottom line: All good.
