### ISSUE TITLE
Chryseis Cracktro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#579]
When the intro starts the logo ARKEL on the right leaves a trail behind.
![vamiga](https://user-images.githubusercontent.com/3858768/138802992-0d6b1a0e-4df5-4e70-b04d-732394511a4b.png)
![winuae](https://user-images.githubusercontent.com/3858768/138802996-83fe6e75-e71d-40a7-82b2-7c1b915f8ebf.png)
[Chryseis.tr01.zip](https://github.com/dirkwhoffmann/vAmiga/files/7414877/Chryseis.tr01.zip)

**Comment by dirkwhoffmann** [comment]
Confirmed.

**Comment by dirkwhoffmann** [comment]
Fixed in v1.1b8
