### ISSUE TITLE
Crystal Crack #14

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#584]
Gfx corruption to the right.

![crystal](https://user-images.githubusercontent.com/3858768/138888154-410075c3-32f0-4743-8aa4-ba2cf1a1af1b.png)
vAmiga

![winuae](https://user-images.githubusercontent.com/3858768/138888184-720382df-655d-4f88-a3f8-af2454460eff.png)
WinUAE

[crystal.crack14.zip](https://github.com/dirkwhoffmann/vAmiga/files/7418497/crystal.crack14.zip)

**Comment by dirkwhoffmann** [comment]
Weird. Compared to the real machine, the whole scene seems to be shifted. 

![IMG_1864](https://user-images.githubusercontent.com/12561945/140606991-c4850d62-ba97-44c4-b2a2-baf1f702c063.JPG)

**Comment by dirkwhoffmann** [comment]
Related to #575. The texture needs to be shifted to the right (HBLANK area adjustment).

**Comment by chris70c** [comment]
WinUAE 4.4 display panel...

![Untitled](https://user-images.githubusercontent.com/3858768/151173041-b6a65d2e-352e-4df9-9ca4-b9004e50259b.png)

**Comment by dirkwhoffmann** [comment]
Fixed in v1.1b9. It matches the real machine with geometry settings "Overscan".
