### ISSUE TITLE
Accession Crack

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#585]
Works only with 512k chip and no slow ram in vAmiga, works fine both way in WinUAE.
[accession.crack03.zip](https://github.com/dirkwhoffmann/vAmiga/files/7418582/accession.crack03.zip)

**Comment by chris70c** [comment]
I guess we can close all these intros which have problem with the ram init pattern, what do you think?

**Comment by dirkwhoffmann** [comment]
> I guess we can close all these intros which have problem with the ram init pattern, what do you think?

Yes, I think we can close them ("all zeroes" is the default init pattern already. It seems to be the most compatible one).
