### ISSUE TITLE
Atomic Castlevania Cracktro

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#587]
There is no scroll at all in vAmiga.
![vamiga](https://user-images.githubusercontent.com/3858768/138987456-475afc9c-d471-43f4-8572-fe29e163c1ee.png)
WinUAE:
![winuae](https://user-images.githubusercontent.com/3858768/138987459-d5d6b4cd-621c-49dc-aeca-4487c93031ba.png)
[Atomic_Castlevania.zip](https://github.com/dirkwhoffmann/vAmiga/files/7422592/Atomic_Castlevania.zip)

**Comment by dirkwhoffmann** [comment]
Confirmed.

**Comment by dirkwhoffmann** [comment]
Will be fixed with the next release:

<img width="976" alt="Bildschirmfoto 2022-01-21 um 21 15 52" src="https://user-images.githubusercontent.com/12561945/150594334-9136b194-43b2-4aba-afc5-6939d113ad1a.png">

**Comment by dirkwhoffmann** [comment]
Fixed in v1.1b8
