### ISSUE TITLE
Little Endian / Big Endian snapshot issue? 

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#592]
@chris70c and me are experiencing a snapshot issue. If a snapshot that was created in the web emulator is loaded back in the desktop version, the emulator crashes.

This could well be a LE/BE issue,  because (Intel) Macs are LE and WebAssemble is BE (I think). As far as I know, the new M1 Macs are BE, too. Could somebody who owns both an Intel Mac and an M1 Mac try to save a Snapshot on one of the machines and load it back on the other machine?

I can't do this experiment by myself because I don't have an ARM-based Mac, yet.

**Comment by idrougge** [comment]
The M1 Macs are little-endian like most ARM machines.

**Comment by dirkwhoffmann** [comment]
> The M1 Macs are little-endian like most ARM machines.

Hmm, OK, so this experiment won't help.

**Comment by chris70c** [comment]
Actually wasm is only little-endian at the moment, while buffers created on js side are using the machine architecture unless you use a dataview, if you do that you can set the endianness for each call.
