### ISSUE TITLE
Power up the emulator with a pre-saved snapshot

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#595]
@chris70c brought up a feature request concerning snapshots: It should be possible to power on the emulator with a pre-saved snapshot. This was not at all easy in the current implementation, because the following sequence did not work:

```
Amiga amiga();
amiga.loadSnapshot(…);
amiga.powerOn();
```

It didn’t work because `powerOn()` calls `reset()`. As a workaround I’ve added a variable `Amiga::startupSnapshot`. Now, `powerOn()` checks for this variable. If it is not NULL, the snapshot is loaded after calling `reset()`.

I think there is a better (less complex) solution. It requires the following:

- Call `reset()` inside the constructor of the Amiga class (already done, no change)
- Remove the call to `reset()` inside `powerOn()`
- Add a call to `reset()` at the end of `powerOff()`

If I haven’t overseen anything, this should make the above sequence (loading a snapshot before `powerOn()`) work. In addition, the additional variable startupSnapshot won’t be necessary any more. 

I’ll try this out in the next couple of days…

**Comment by dirkwhoffmann** [comment]
I’ve changed the state model a little. In future, the emulator has to be launched as follows:

```
// (1) Create a virtual Amiga
Amiga amiga();

// (2) Press the power switch
amiga.powerOn()

// (3) Start emulation
amiga.run()
```

In contrast to my original plan which I outlined above, powerOn() still performs a hard reset (simply because if I hadn’t written this function myself I would expect it to put the machine into a clean state). However, powerOn() does no longer perform the isReady() check. As a result, the Amiga can be powered on even if there is no Kickstart or if the amount of Chip Ram is incompatible with the selected Agnus revision. The isReady() check is performed solely in (3). If no Kickstart is present, run() will throw an exception. This provides an easy way to start off from a pre-saved snapshot. Like so: 

```
Amiga amiga();
amiga.powerOn()
amiga.loadSnapshot(…);
amiga.run()

```
Variable startupSnapshot is gone, because it is no longer needed. 

Please note that run() does no longer call powerOn() automatically. The emulator will hit an assertion if run() is called in power-off state.

@chris70c, @mithrendal: I would like to switch to C++ 20 which is now offered by Xcode. Is this fine for you or would it create issues with WASM?

**Comment by chris70c** [comment]
C++20 should be fine in Emscripten, I know that LLVM/CLang does not support some features about Concepts, Modules and some other things so I guess it depends on what Apple supports and what are you gonna use :)
Here's a page with features support (C++20, C++2b) in CLang:
https://clang.llvm.org/cxx_status.html

**Comment by dirkwhoffmann** [comment]
> Here's a page with features support 

OK, great, I think it's gonna work out. The main reasons why I want to switch to C++ 20 is the support of semaphores, [[likely]] / [[unlikely]], and the new `consteval` expression. The latter one is only partially supported, but that shouldn't matter much. In the unlikely event that `consteval` causes trouble, it could be removed easily.

**Comment by dirkwhoffmann** [comment]
In the next version, there will be another architectural change. Inserting and ejecting a disk is no longer done via the DiskController. All relevant functions have been moved to the Drive class. While doing this, I’ve cleaned up the API a little: 

```
    // Ejects the current disk with an optional delay
    void ejectDisk(Cycle delay = 0);
    
    // Inserts a new disk with an optional delay
    void insertDisk(std::unique_ptr<Disk> disk, Cycle delay = 0) throws;
    
    // Replaces the current disk (recommended way to insert disks)
    void swapDisk(std::unique_ptr<Disk> disk) throws;
    void swapDisk(class DiskFile &file) throws;
    void swapDisk(const string &name) throws;

    // Replaces the current disk with a factory-fresh disk
    void insertNew() throws;
```

The recommended way to insert a disk is by calling the new API function `swapDisk()` which emulates a realistic disk change (formerly, this was done by insertDisk()). I.e., swapDisk() will

1. eject the current disk,
2. wait for 1.8 seconds (adjustable via OPT_DISK_SWAP_DELAY),
3. insert the new disk.

Note: If the drive is empty, steps 1 and 2 are skipped. If emulation is paused, step 2 is skipped.

**Comment by chris70c** [comment]
Quite nice, only thing slightly less easy than now is that I'll have to use a bunch of if/then to use the correct drive (df0, df1, etc.) while now I just pass the drive id.

**Comment by dirkwhoffmann** [comment]
This array already exists:

    // Shortcuts to all four drives
    Drive *df[4] = { &df0, &df1, &df2, &df3 };

Every component has access to this array.

**Comment by chris70c** [comment]
good to know, lol
so I can use somethings like:

amiga->df[0].insertDisk(std::make_unique(exe), 0);
amiga->df[1].insertDisk(std::make_unique(exe), 0);
etc.
