### ISSUE TITLE
Tarkus Team & Switch intros

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#598]
Both these files are not recognized by the emulator, it just doesn't load them; both works fine in WinUAE.
Might be related to the faulty adf creation?
Also looks like when using isCompatibleName the emulator does not like if the extension is ExE, works fine with exe and EXE but not the former :)
[intros.zip](https://github.com/dirkwhoffmann/vAmiga/files/7490644/intros.zip)

Never mind, turns out they're zip archives, lol

**Comment by dirkwhoffmann** [comment]
All `isCompatible(const string &path)` functions have been changed to be case-insensitive now. E.g.:

```C++
bool
EXEFile::isCompatible(const string &path)
{
    auto suffix = util::uppercased(util::extractSuffix(path));
    return suffix == "EXE";
}
```
