### ISSUE TITLE
Agnus::isOCS() is probably wrong

### ISSUE THREAD

**Issue by M-a-r-k** [dirkwhoffmann/vAmiga#599]
Agnus::isOCS() const
{
    return config.revision == AGNUS_OCS_PLCC || config.revision == AGNUS_OCS_PLCC;
}

**Comment by dirkwhoffmann** [comment]
Yes, that was wrong. Thanks for reporting!

**Comment by dirkwhoffmann** [comment]
Fixed in vAmiga 1.1b7.
