### ISSUE TITLE
vAmiga does not boot if Slow Ram is plugged in.

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#6]
Hi,
I was looking forward to this moment, great ! Thanks !

vAmiga hangs after having configured and does not restart, something in the preferences...

[report.txt](https://github.com/dirkwhoffmann/vAmiga/files/3050260/report.txt)

**Comment by Alessandro1970** [comment]
...I think it was the 512k slow ram activated

**Comment by dirkwhoffmann** [comment]
> ...I think it was the 512k slow ram activated

Yes, that makes sense. Slow and Fast Ram must remain disabled for now (not tested yet).

To my shame, I just noticed that I did not change the user storage keys when migrating VirtualC64 to vAmiga. Hence, if you run vAmiga, it overwrites the VirtualC64 user settings 🙄. I'm going to change that in the next release. 

BTW, if you wish to know the currently saved settings, you can read the user default storage with a simple shell command in the console app (like I did here): 

<img width="682" alt="Screenshot" src="https://user-images.githubusercontent.com/12561945/55666737-4e422b80-5853-11e9-8888-d397067a9535.png">

**Comment by dirkwhoffmann** [comment]
Slow Ram is working now.
