### ISSUE TITLE
68881 Floating Point Coprocessor Board For Amiga 500/2000

### ISSUE THREAD

**Issue by Alvarez81** [dirkwhoffmann/vAmiga#601]
Hi, could you implement a 68881 FPU for vAmiga, please ?

Info A/2000: http://amiga.resource.cx/search.pl?cat=fpu&product=

**Comment by Haroldo64** [comment]
### The best Amiga expansion is the real expansion card A2620:
This card worked with Kick 1.2 or 1.3, it doesn't boot with kick 2.0 or above.
So the best implementation for VAmiga (for me) is the A2620 with fpu and clock selectable, this will cover all software for Amiga 2000 and other. I hope that will be supported.

The CARD:
**68020 @ 14 MHz, synchronous with the motherboard**
**68851** memory management unit
**factory installed 68881** @ 14 MHz, supports FPUs up to 68882 @ 25 MHz
can be upgraded to 68030 with the Harms Professinal-Pack 030 board
memory
2 or 4 MB 32 bit RAM
16 or 32 256k×4 page mode ZIPs 80-100 ns
not expandable
RAM can be disabled or autoconfigured by setting a jumper

**Comment by Alessandro1970** [comment]
Hi, 68882 would be a great add on for vAmiga.
The instructions set should be te same as 68881 but it is faster.
For the 68010 … I have alteady mounten on my A2000…👍🏻

**Comment by Alvarez81** [comment]
Thanks. Such an improvement for vAmiga is more than welcome.

**Comment by Haroldo64** [comment]
> I might implement 68010 support for fun at some point time

This is a good idea, I liked use the mc68010 and 68881 with the aminet CPU-patch called Decigel
[https://aminet.net/package/util/boot/Decigel]

**Comment by dirkwhoffmann** [comment]
I've received an 68010 from eBay today. That was really quick as I ordered it just yesterday.

![IMG_1902](https://user-images.githubusercontent.com/12561945/141450999-dce5aacc-892c-4488-a965-f4c9aa6ee7ce.JPG)

However, as I said above, support won't come soon. There is still much other stuff to do with higher priority.

**Comment by Alessandro1970** [comment]
... oh yes, we'll wait, of course :smiley: 

But yours is a MC68010 12Mhz clock (P12)

**Comment by dirkwhoffmann** [comment]
> 12Mhz clock (P12)

It doesn't matter. It only means that the chip works reliably with clock frequencies up to 12Mhz.

**Comment by dirkwhoffmann** [comment]
Today, the ordered hardware has arrived from Spain: A Terrible Fire 534 + Kickstart 2.05, 2 Gotek drives, and a trapdoor Ram extension. Maybe I'll install the new stuff over the weekend. This is also a good opportunity to record the exact revision numbers of the custom chip in my different A500s. 

![IMG_1996](https://user-images.githubusercontent.com/12561945/143294737-285a0c3c-b0e5-4ad1-b022-ceba0325b2aa.JPG)

**Comment by dirkwhoffmann** [comment]
I've upgraded one of my machines with the 68010 today.

![A500_1_small](https://user-images.githubusercontent.com/12561945/144754913-663bac76-1df6-4e43-b73d-8ba6c0d5b166.jpg)

Due to a mishap, pin 1 is about to break off, but it all seems to work nonetheless. Hoping that pin 1 won't stop working anytime soon, we do have a test machine for the 68010 CPU now. 

![IMG_2003](https://user-images.githubusercontent.com/12561945/144755046-c48fbb41-8a63-47cc-8b27-e63064645478.JPG)

**Comment by Alessandro1970** [comment]
Great! 
I have PcTask 3 emulator for amiga that run with 68010!
This is a pc emulator for Amiga 😂😂😂

**Comment by Alessandro1970** [comment]
![1](https://user-images.githubusercontent.com/34916641/144822972-f41a1aa7-e834-438d-8d7e-1fb4fdeea11e.png)
![3](https://user-images.githubusercontent.com/34916641/144822996-8c8ea403-a159-4bbc-909e-4a4af7c84f64.png)
![2](https://user-images.githubusercontent.com/34916641/144823007-774a7a1f-f9a1-4184-9f14-55e973b331b6.png)

**Comment by dirkwhoffmann** [comment]
Today, I had some time to upgrade my fifth machine. Originally I thought I only have one revision A6 board, but this one has a R6 board, too: 

![A500_2_orig_small](https://user-images.githubusercontent.com/12561945/146039853-ba722716-9c67-4446-8551-4ef86a06363b.jpg)

The same machine after installing Kickstart 2.05 and replacing the original CPU with the Terrible Fire board 😎:

![A500_2_upgrade_small](https://user-images.githubusercontent.com/12561945/146047779-9ca4b87d-9e10-4e19-988f-310ae65f8636.jpg)

![IMG_2012](https://user-images.githubusercontent.com/12561945/146047831-6e3109dc-512c-457c-80a1-7472747d5d84.JPG)

**Comment by Alessandro1970** [comment]
68882 on Amiga wow!
…so we could hope for 68039+68882 running on vAmiga!!! 
…yes 🥰 …or not 😫

**Comment by dirkwhoffmann** [comment]
A couple of days ago, I've seen an interesting A500 on eBay which is now mine. As the logo indicates (instead of a silver label it's engraved in the chassis), it's one of the older (and rarer) revisions. It comes with Kickstart 1.2 and an OCS Agnus. 

![IMG_2017](https://user-images.githubusercontent.com/12561945/146927391-49802886-44c1-49ca-830e-25acfb8371d5.JPG)

Now, we have test machines for almost all Agnus revisions: Old OCS Agnus (Mithrendal's A1000), OCS Agnus (this A500), ECS Agnus (all other A500's I own). 

I'm curious about the condition of the logic board (I haven't opened it up yet).

**Comment by dirkwhoffmann** [comment]
Overall, the computer seems to be in pretty good condition.

![A500_5_small](https://user-images.githubusercontent.com/12561945/146957748-8db92ef0-3dfe-4049-93c0-52575170c0fb.jpg)

According to https://sites.google.com/one-n.co.uk/amiga-guides/a500-motherboard-revisions the board is a Rev. 3 (type 2) board. Next step will be to install a Gotek drive and a RAM expansion. After that, it's ready to serve as a test machine.

**Comment by dirkwhoffmann** [comment]
Looks good so far:

![IMG_2021](https://user-images.githubusercontent.com/12561945/146966241-95ac440c-3026-4bfe-ad46-50c522683d6c.JPG)

This one suprised me at first. Only 506 KB slow memory???

![IMG_2020](https://user-images.githubusercontent.com/12561945/146966317-4168dddc-23f8-4d52-86fe-31d2c2313a45.JPG)

Fortunately, that's normal. vAmiga reports the same. 

Everything seems to work except the keyboard. It doesn't recognise all keys and sometimes, wrong key codes are transmitted (hitting 's' result in nothing, 's', or 's' + return). I could try some contact spray or I could watch out for a replacement keyboard.

**Comment by dirkwhoffmann** [comment]
I have looked into this topic a bit closer. FPU support only makes sense for the 68020 and its successors. The 68020 is the first CPU in the 680x0 series that comes with a coprocessor port. Such a port is essential for the CPU to quickly dispatch an FPU instruction to the coprocessor. Using the 68881 or 68882 in combination with the 68000 or 68010 is only possible through a detour. Any FPU instruction throws a line exception on these processors which means that an exception handler is invoked. Inside the exception handler, the FPU can be invoked manually via memory mapped I/O. However, this approach is so incredibly slow that it almost completely eats up the speed gain obtained from the FPU. Bottom line: Without 68020 support, which is not planned in vAmiga, FPU emulation makes no practical sense. 

By the way, recent versions UAE takes this into account. As soon as a 68000 or 68010 is selected, the 68881 and 68882 options are greyed out.
