### ISSUE TITLE
In the last beta palette menu does not work

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#605]
Hi, in the last beta if I change from standard colors it cannot be reverted untill quit and restart.
![76AFCCAA-97E8-47B2-8354-97068D029D3F](https://user-images.githubusercontent.com/34916641/141670687-04c3976d-5a9a-44a5-bcdd-0d9ab9da74d1.jpeg)

**Comment by dirkwhoffmann** [comment]
Thanks for reporting! I've checked in a fix on the dev branch.

**Comment by dirkwhoffmann** [comment]
Fixed in vAmiga 1.1b7.
