### ISSUE TITLE
Add the ability to redirect the CPU's program counter manually

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#608]
A debug function shall be added that allows the GUI to redirect the CPU's program counter to a certain address.

Note: Modifying variables `pc` and `pc0` is not enough. To make this work, the prefetch queue has to be refilled with suitable values.

Requested by @chris70c.

**Comment by dirkwhoffmann** [comment]
In fact, this one was extremely easy. There is a new API method

```
void
CPU::jump(u32 addr)
{
    suspended { debugger.jump(addr); }
}
```

It calls the following function in the CPU debugger:

```
void
Debugger::jump(u32 addr)
{
    moira.reg.pc = addr;
    moira.fullPrefetch<POLLIPL>();
}
```

The new functionality is also available as a shell command: 

<img width="857" alt="Bildschirmfoto 2021-11-18 um 16 34 49" src="https://user-images.githubusercontent.com/12561945/142447322-4346315e-365f-400d-a4ec-fba506cefbac.png">

**Comment by chris70c** [comment]
Thanks Dirk :)

**Comment by dirkwhoffmann** [comment]
Part of vAmiga 1.1b7.
