### ISSUE TITLE
Fish 001 (trackdisk): Blitter issue?

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#61]
Program "Trackdisk" produces graphics artefacts on Fish 001. Likely a Blitter issue.

<img width="885" alt="Screenshot 2019-06-18 at 22 45 32" src="https://user-images.githubusercontent.com/12561945/59718821-428fbf80-921b-11e9-8329-8485ed78157d.png">

**Comment by dirkwhoffmann** [comment]
Same in SAE (if same Workbench is used (WB 1.2))

**Comment by Alessandro1970** [comment]
But on WinUAE trackdisk with WB1.2 works fine (A500 settings):
![Untitled 2](https://user-images.githubusercontent.com/34916641/59846898-580f0180-9361-11e9-9d8f-122bd57b07ac.jpg)

**Comment by dirkwhoffmann** [comment]
To reproduce the error, you need to move the CLI window down as much as possible (if I remember correctly). The graphics errors appear at the bottom of the screen and will be scrolled up together with the text output.

**Comment by Alessandro1970** [comment]
Ok, you are right! ...in WinUAE too

**Comment by dirkwhoffmann** [comment]
BTW, did you figure out an easy way to read in a Fish disk? I did convert the .lha files manually to an ADF with lha and xdftool which is a little cumbersome.

**Comment by Alessandro1970** [comment]
Yes, I unzip with 7zip the .lha than I make the adf manually
