### ISSUE TITLE
3D Games Disk Intro (Australian Crackers United)

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/vAmiga#610]
This one works fine in WinUAE with KS1.3 and 512K chip only but does not in vAmiga (works only with 512+512 slow).

[3D Games Disk [intro] (Australian Crackers United).zip](https://github.com/dirkwhoffmann/vAmiga/files/7558782/3D.Games.Disk.intro.Australian.Crackers.United.zip)

**Comment by mras0** [comment]
Guru's for me in WinUAE latest beta (3.9.0b40) and also in 4.4.0 w/ 512K chip only + KS1.3 (and I see the same result in my own emulator):
![image](https://user-images.githubusercontent.com/9952017/142472486-30945078-38cc-4c8f-a4f9-8d2f832082ec.png)

Looks like it ends up destroying some internal exec structures while decompressing (haven't debugged it further). Are you running it stand-alone or from a disk with a non-standard bootloader (this tripped me up earlier)?

**Comment by chris70c** [comment]
Standalone but you're right I can't make it work anymore in WinUAE either with only 512K chip, either I had a wrong config before or it was one of those 1 in a 1000 cases were it works :)

**Comment by mras0** [comment]
Memory is "only" corrupted when interrupts runs, so you can get "lucky" with timing in 512K only config I think (maybe it's less if you only have one drive, but it's not enough). Don't know if it's 1 in 1000 though :)

P.S.: hope you don't mind me double-checking some of these report for the "sport" as I find it interesting :)

**Comment by chris70c** [comment]
No problem at all, any help is welcome :)
