### ISSUE TITLE
Apidya hangs after trainer

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#613]
Hi, this games hangs after trainer, on my friend's winuae it works.
He uses only df1:  kick1.3 and 1Mb chip.

[Apidya [Disk 1].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/7574176/Apidya.Disk.1.adf.zip)

[Apidya [Disk 2].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/7574177/Apidya.Disk.2.adf.zip)

...delete the zip if these are not abandonware, I don't know about (sorry).

**Comment by dirkwhoffmann** [comment]
The game appears to hang here: 

<img width="976" alt="Bildschirmfoto 2022-01-21 um 21 33 10" src="https://user-images.githubusercontent.com/12561945/150596921-0c8ae5f7-514e-4326-a4c1-f53b60bfcbe9.png">

The CPU inspector reveals what's going on:

<img width="980" alt="Bildschirmfoto 2022-01-21 um 21 32 55" src="https://user-images.githubusercontent.com/12561945/150596982-fb08f4e8-4ab2-42cd-b8c6-dc55037f9bce.png">

The `btst`command checks for the left mouse button. The `andi.w` command checks for the right mouse button. Indeed, when pressing both buttons, loading continues:

<img width="976" alt="Bildschirmfoto 2022-01-21 um 21 37 07" src="https://user-images.githubusercontent.com/12561945/150597189-f48c029f-38ed-4fb2-8ecf-d53e379fb114.png">
