### ISSUE TITLE
Upfront - Cool Fridge, Smooth Copper Part doesn't look right

### ISSUE THREAD

**Issue by mras0** [dirkwhoffmann/vAmiga#616]
[Pouet link](https://www.pouet.net/prod.php?which=1467),  [direct download](https://files.scene.org/get/mirrors/amigascne/Groups/U/Upfront/Upfront-CoolFridge.dms). Press LMB to enter the part (moving mouse up and down selects other parts, and they seem OK from a quick check. I did manage to get a guru from clicking around in the different parts, but I'll add a different report if I can reproduce it and only then if it's vAmiga specific).

This one might be a little "unfair" (so feel free to mark as wontfix), since it has a special hack in WinUAE [link](https://github.com/tonioni/WinUAE/blob/6d72bc918ab0a8b573e0acc536a3138d5bb2149b/custom.cpp#L6046). I'm only adding it because you seem fearless in taking on hard compatibility issues :)

Old description from Toni ([EAB link](http://eab.abime.net/showpost.php?p=1096784&postcount=774)):

> Demo writes to VHPOSW, changing horizontal counter value exactly by one, this causes copper waits to end 1 cycle earlier (or later) which basically means same behavior as copper using odd cycles to update custom registers. (2 lores pixel resolution, like the demo loader screen says)
> 
> Because this also changes bitplanes, it uses BPLCON1 to compensate for bitplane corruption, by scrolling exact same amount to opposite direction of corruption caused by VHPOSW writes.
> 
> There is another VHPOSW at the end of each scan line that compensates previous VHPOSW adjustment, syncing Agnus and Denise counters again and preventing hsync problems.

Looks like this in latest WinUAE (and presumably on the real hardware):
![image](https://user-images.githubusercontent.com/9952017/142773167-0d810a34-2326-4d1d-a6d2-e4edf6a64d03.png)

Like this in vAmiga (latest commit, 33e24693aed2ffea21943a1044f59aad815dd353). Standard CONFIG_A500_OCS_1MB full screen buffer shown:
![image](https://user-images.githubusercontent.com/9952017/142773174-4a58e85e-e638-4f12-9faa-a99c15983ee2.png)

**Comment by dirkwhoffmann** [comment]
Wow, what a cool trick to change Copper resolution. Currently, vAmiga ignores any manual write to the horizontal counter. This is because changing variable `agnus.pos.h` brings the event scheduler into an inconsistent state. To emulate this properly, many events would have to be rescheduled. It's not easy, but not impossible either. It could be a nice feature for version 2.1 (the next official release will be labelled 2.0).
