### ISSUE TITLE
CRC of AmigaOS 3.2

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/vAmiga#617]
does anyone have a AmigaOS 3.2 kickstart flying around ? It would be interesting to know its CRC checksum in order to add this to the list of well known kickstart system roms in vAmiga.

the CRC can be determined in the rom dialog ... see here for example a patched commodore kickstart 1.2 rom...

![image](https://user-images.githubusercontent.com/17108995/143592057-96d394c6-ab4d-4b8f-8f7e-e4f5c3baf707.png)

when AmigaOS 3.2 is mounted into vAmiga it will probably also show this unknown icon...  once the correct CRC is added into vAmiga we should see a beautiful hyperion rom icon 

for reference: https://www.hyperion-entertainment.com/index.php/news/1-latest-news/290-amigaos-42-for-all-classic-amigas-released-and-available

**Comment by chris70c** [comment]
Amiga OS 3.2 is already in there, I've added it together with the other changes to the roms.

        case 0x8173D7B6: return ROM_HYP320_47_96_A500;
        case 0xBD1FF75E: return ROM_HYP320_47_96_A1200;
        case 0xF3AF46CC: return ROM_HYP320_47_96_A3000;
        case 0x9BB8FC93: return ROM_HYP320_47_96_A4000;
        case 0x9188A509: return ROM_HYP320_47_96_A4000T;

These are the crc32 taken from my original cd of OS3.2.

**Comment by mithrendal** [comment]
thanks @chris70c 😍
