### ISSUE TITLE
OSDebugger

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#620]
I've opened up this thread to remove some traffic from #618 which is concerned with GDB integration.

What I did yesterday is to add some sanity checks to my code. I.e., when the debugger traverses a list, it checks if the pointer is even and points to valid memory. Furthermore, infinite loops due to circular structures can't happen any more. I've also changed the segment scanner as proposed by @mras0. It now mimics the UAE code by applying the following rule:

- If `pr_CLI` is not null AND `pr_TaskNum` is not 0, then `pr_CLI->cli_Module` is taken as a pointer to a (single) segment list. 

I don't really understand the AmigaDOS logic behind it, but it seems to give a reasonable result, at least in this example:

<img width="974" alt="Bildschirmfoto 2021-12-09 um 22 03 58" src="https://user-images.githubusercontent.com/12561945/145525986-11fc81ff-9d07-451f-9a5b-4d30bfc49717.png">

Interestingly, among the 7 processes, only the last one (Background CLI) matched the condition `pr_CLI != null && pr_TaskNum != 0`. 

For all other task, the debugger gets the segments from the segment list array referenced by `pr_SegList`.

**Comment by dirkwhoffmann** [comment]
After testing my new code with the Workbench, I've also tested it with some demos. Here is the task list when running Emoon's demo:

<img width="974" alt="Bildschirmfoto 2021-12-10 um 06 57 47" src="https://user-images.githubusercontent.com/12561945/145527040-16bdb710-d746-4a89-86dd-85531f059aef.png">

I guess the demo takes over the system and just doesn't care about the exec structs any more. The task list supposedly points to some memory area that is used by the demo, because the output changes every time I invoke the command. 

UAE doesn't care about corrupted data structures either:

<img width="803" alt="Bildschirmfoto 2021-12-10 um 06 54 27" src="https://user-images.githubusercontent.com/12561945/145527447-51d11944-30b3-4191-9743-7068cd68995b.png">

I am wondering if it makes sense to add some consistency check. I.e., the debugger could do some plausibility check and terminate the list when it fails. Overall, this has low priority at the moment. The most important point here is that the debugger doesn't crash when scanning corrupted structures.

**Comment by mras0** [comment]
You can add some basic sanity checks for execbase. AmigaOS checks the following:

- Address should be in RAM and at an even address
- Long word at $26 (ChkBase) should be the bitwise complement of the address
- The 16-bit checksum of [$22, $54[ should be $ffff
- MaxMemLoc/MaxExtMem are 256K aligned and sane (Kick 1.2 gets this wrong and assumes there is never more than 512K chip ram)

First three should be sufficient.

I do the same [here](https://github.com/mras0/AmiEmu/blob/99e0f42f82fffbf56e15686cedf9b558531c0335/m68kdisasm.cpp#L4332)(with an additional check that the MaxMemLoc/MaxExtMem) match what I expected.

BTW I found a bit more info on the contents of pr_SegList: http://eab.abime.net/showpost.php?p=1444660&postcount=22

Entries 1&2 should just be ignored.

**Comment by dirkwhoffmann** [comment]
> You can add some basic sanity checks for execbase.

Thanks! I've added the checks you mentioned.

> Kick 1.2 gets this wrong and assumes there is never more than 512K chip ram

Running Kick 1.2 with 1MB Chip Ram results in this:

<img width="974" alt="Bildschirmfoto 2021-12-12 um 09 56 19" src="https://user-images.githubusercontent.com/12561945/145708323-1a1627ca-0ca2-482e-b95a-de6b3644f439.png">

It seems to recognise the upper Chip Ram bound correctly.

**Comment by mras0** [comment]
Yeah, it can detect it just fine, but I was referring to this part of the ROM (disassembly [here](http://wandel.ca/homepage/execdis/exec_disassembly.txt)):

```
FC0196  move.l    $3E(A6),A3        Get end address of chip memory.
FC019A  cmp.l     #$080000,A3       Greater than 512K?
FC01A0  bhi.s     FC01CE            If so, it must be invalid.
FC01A2  cmp.l     #$040000,A3       Less than 256K?
FC01A8  bcs.s     FC01CE            If so, it must be invalid.
```

I.e. it decides execbase isn't valid if `MaxLocMem > 512K`. Looks like this was also an issue in KS.1.3, but was [fixed](https://retrocomputing.stackexchange.com/questions/372/why-are-there-two-different-kickstart-1-3-roms-with-the-same-34-5-version-numb?rq=1) in the rev34.5 version that shipped with the A3000. Anyway, just a bit of trivia :)
