### ISSUE TITLE
DDF logic

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#624]
In vAmiga there is one thing that isn't emulated accurately yet: the display data fetch logic.

For the OCS implementation, we can make use of an old [schematics](https://github.com/nonarkitten/amiga_replacement_project/blob/master/agnus/MOS_Agnus_compressed.pdf) that was published as part of the [Amiga replacement project](https://github.com/nonarkitten/amiga_replacement_project). We find the relevant part on sheet 8: 
<img width="1204" alt="Bildschirmfoto 2022-01-05 um 14 01 04" src="https://user-images.githubusercontent.com/12561945/148221697-470e5c0d-5405-4971-a249-3b432e105656.png">

I've looked at it for some time yesterday and already developed a good understanding of how it works. Hence, it's time to trash the old DDF code and rework it based on what we see here. A major role play signal BPRUN which is connected to the reset lines of the two T-flipflos which form the upper two bits of the fetch-unit counter.

As usual, I'll start with writing test-cases that will fail in vAmiga. By knowing the schematics, that's a pretty easy task.

**Comment by mithrendal** [comment]
🤤 awesomeness

**Comment by dirkwhoffmann** [comment]
Here is a preliminary breakdown of the 6 D-flipflops for reference (might not be 100% correct yet, but it gives the idea):

Signals: 

```
BMAPEN: BPLEN bit (Bit #8 in DMACON)
SVB: Line 0 
BPVSTART: Vertical start (from DIWSTRT)
BPVSTOP: Vertical stop (from DIWSTOP)
BPHSTART: Horizontal start (from DDFSTRT)
BPHSTOP: Horizontal stop (from DDFSTOP)
SHW: Left hardware stop
RHW: Right hardware stop
```

Flipflop 1:

```
FF1 = !(!(FF1 | BPVSTART) | BPVSTOP | SVB)
    = (FF1 | BPVSTART) & !BPVSTOP & !SVB
```

- Set in line BPVSTART
- Cleared in SVB line (line 0)
- Cleared in line BPVSTOP

=> Meaning: "Inside vertical display area"


Flipflop 2:

```
FF2 = !(!(FF2 | SHW) | FF5)
    = (FF2 & SHW) & !FF5
```

- Set with SHW (left hardware stop)
- Cleared by FF5 (Stop DMA)

=> Meaning: "Left hardware stop passed, bitplane DMA can happen"


Flipflop 3:

```
FF3 = !(!BMAPEN | !FF1 | !(BPHSTART | FF3) | !FF2 | EndOfFetch)
    = BMAPEN && FF1 && (BPHSTART | FF3) && FF2 && !FF5
```

- Set at BPHSTART if 
     - BMAPEN (bitplane DMA enabled)
     - FF1 is set (line is a DMA line)
     - FF2 is set (left hardware stop has passed)
- Cleared by FF5 (Stop DMA)

=> Meaning: "Do bitplane DMA"


Flipflop 4:

```
FF4 = !(FF5 | !(FF4 | (RHW & BPRUN) | BPHSTOP))
    = !FF5 & (FF4 | (RHW & BPRUN) | BPHSTOP)
```

- Set at RHW (if BPRUN) 
- Set at BPHSTOP
- Cleared by  FF5 (Stop DMA)

=> Meaning: "DMA should stop"

Flipflop 5:

```
FF5 = !((FF5 & CNT == 0) | !(FF5 | (FF4 & CNT == 0)))
    = !(FF5 & CNT == 0) & (FF5 | (FF4 & CNT == 0))
    = (!FF5 | CNT != 0) & (FF5 | (FF4 & CNT == 0))
    = (FF5 -> CNT != 0) & (!FF5 -> (FF4 & CNT == 0))
```

- Cleared if CNT != 0
- Set if "DMA should stop" and CNT == 0

=> Meaning: "Stop DMA"

**Comment by dirkwhoffmann** [comment]
Done in v1.1b8.
