### ISSUE TITLE
Workbench 2.0 questions

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#63]
<img width="929" alt="Screenshot 2019-06-20 at 13 50 54" src="https://user-images.githubusercontent.com/12561945/59847365-922cd300-9362-11e9-9b43-d35c69d419df.png">

It's the first time I see Kickstart 2.0 (with WB 2.1) in action. Maybe someone can answer some of the following questions: 

1. Why do I get an error message when clicking on "Shell" (see screenshot)
2. Why can't RexxMast be opened (says some math lib cannot be opened)
3. Why did Commodore make the "new" OS so ugly? 😲

P.S.: I get the same errors in SAE.

**Comment by Alessandro1970** [comment]
I used WinUAE + KICK 2.04 + WB2.1 ...all is working

**Comment by Alessandro1970** [comment]
It works also with OCS + 512K Chip
Try to change adf...

http://the-eye.eu/public/rom/Amiga/Most_Extensive_Collection_Online/Operating%20Systems/Workbench/

**Comment by Alessandro1970** [comment]
I loaded in SAE my kick 2.04 rom and my copy of wb2.1 and Rex starts and the cli runs fine

**Comment by dirkwhoffmann** [comment]
I had wb2.1 WB in df1: and wb2.1 install in df0:

When I just use wb2.1 Workbench, it works 😀.

<img width="929" alt="Screenshot 2019-06-20 at 15 41 55" src="https://user-images.githubusercontent.com/12561945/59853936-2d797480-9372-11e9-874c-fabff9321297.png">

Thanks for helping. I think this issue can be closed.
