### ISSUE TITLE
Mouse does not work

### ISSUE THREAD

**Issue by TomDev234** [dirkwhoffmann/vAmiga#632]
The mouse pointer does not move.

**Comment by dirkwhoffmann** [comment]
Have you plugged in a mouse into port 1?

<img width="976" alt="Bildschirmfoto 2022-01-20 um 20 19 37" src="https://user-images.githubusercontent.com/12561945/150407534-3652837b-0f69-4441-bce9-9a8801be78b8.png">

**Comment by TomDev234** [comment]
Yes.
I am using vAmiga 1.1b7. I am getting this warning:

**Comment by dirkwhoffmann** [comment]
Please try v1.1b8. Thanks.

**Comment by TomDev234** [comment]
Still the same problem. Mouse does not move.

**Comment by dirkwhoffmann** [comment]
Could you perhaps record a video? Otherwise, it's impossible for us to see what's going wrong.

**Comment by TomDev234** [comment]
This is the warning I get:

![Screen Shot 2022-01-20 at 23 14 34](https://user-images.githubusercontent.com/6132135/150866028-ff231811-35d3-4415-ab48-26d0c1792e17.png)

**Comment by dirkwhoffmann** [comment]
OK, it seems like macOS treats this device as a non-standard mouse. This is not supported by vAmiga. When it comes to external USB devices, vAmiga only accepts devices that act as a joystick.
