### ISSUE TITLE
Make the emulator core a Git submodule

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#635]
I have tried to migrate the emulator core into a separate repo before, but didn't do it in the end (mostly because I am not a Git expert). Since there are already a number of emulator spin-offs out there, I want to give it another try. 

Things to do: 
- Move `config.h` to the `Emulator` directory to make it self-contained.
- Split the Emulator folder out into a new repo as explained here: 
  https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository
  https://stackoverflow.com/questions/17413493/create-a-submodule-repository-from-a-folder-and-keep-its-git-commit-history
- Push the new repo to `vAmigaCore` which has already been created.

**Comment by RishiKumarRay** [comment]
I would like to try this, assign me..

**Comment by dirkwhoffmann** [comment]
> I would like to try this, assign me..

I am still unsure about the right approach. My first experiment was to delete the Emulator directory and to add the vAmigaCore repo as a submodule instead. This worked nicely on the Git side, but I had problems in Xcode to access the submodule repo.

After that, I gave Git subtrees a try, but it behaved weirdly. After creation, the vAmigaCore repo comprised about 4000 checkins. Then, I did a test commit and pushed the change to the vAmigaCore repo via:

    git subtree push --prefix Emulator https://github.com/dirkwhoffmann/vAmigaCore.git master 

After doing this, the vAmigaCore repo consisted about 6000 checkins 😳. This is definitely not what I want.

**Comment by dirkwhoffmann** [comment]
After doing some experiments with submodules and subtrees, I think it's best to not change anything. Submodule integration into Xcode doesn't seem to be perfect, so I would have to do a lot of stuff via the command line. At the end, my workflow would get more complicated rather than easier.
