### ISSUE TITLE
Winter games in SAE/UAE? 

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#64]
I tried to play WinterGames in SAE, but I failed badly. I always get: 

<img width="319" alt="Screenshot 2019-06-20 at 14 55 28" src="https://user-images.githubusercontent.com/12561945/59850875-8d205180-936b-11e9-8047-b329535233a1.png">

Does somebody know which special options need to be set to get the game going?

**Comment by Alessandro1970** [comment]
It works both with kick 1.2 and kick 1.3 but on WINUAE **not on SAE**.

**On Winuae** it works with or without blitter options, also it works with ocs or ecs... It works with **512k chip only**, **without slowram**; Cycle exact (full) is not important, it works without too.

For me SAE has some **disk drive incompatibilities**.

**Comment by dirkwhoffmann** [comment]
That's great information! Interestingly, it doesn't require an original drive in UAE. It also works with a Turbo Drive. 

I'll inform Rupert about it. Maybe it's a real bug in SAE.

**Comment by Alessandro1970** [comment]
I have seen into the disk image that there is a 280K file without any name...

That 4 space file is Herndon copy protection on track 1 of the disk. Usually 1 or 2 sectors of track 1 have a deliberate checksum error in them at the DOS level.
Maybe this one could be the problem...

![Untitled 2](https://user-images.githubusercontent.com/34916641/59905181-bc839c80-9405-11e9-95d3-16d0e5bb7c3b.jpg)

**Comment by dirkwhoffmann** [comment]
Copy protection. So mean 😖.

**Comment by Alessandro1970** [comment]
This version of WinterGames works on SAE with 512K Chip and kick 1.2 (Floppy speed 1x)
The "no name file" in this adf was removed...

[Winter Games (1987)(U.S. Gold)[cr ECA].zip](https://github.com/dirkwhoffmann/vAmiga/files/3371339/Winter.Games.1987.U.S.Gold.cr.ECA.zip)

![Untitled 2](https://user-images.githubusercontent.com/34916641/60861954-70fe2a80-a21c-11e9-8400-7b06a1264e2c.jpg)

**Comment by Alessandro1970** [comment]
Wintergames works on vAmiga ...some graph error, but now it starts:
<img width="885" alt="Schermata 2019-07-19 alle 09 51 43" src="https://user-images.githubusercontent.com/34916641/61518907-f77bee80-aa0a-11e9-9011-3e572955af06.png">

**Comment by dirkwhoffmann** [comment]
<img width="893" alt="Bildschirmfoto 2019-07-20 um 13 05 32" src="https://user-images.githubusercontent.com/12561945/61577967-4733e600-aaef-11e9-93c8-9248a1cd450b.png">

The DMA debugger shows that the skater is a sprite . Furthermore, the Denise inspector panel shows that sprite 2 has the "Attached" bit set. I'm not sure if the inspector panel is 100% reliable (not well tested), but it seems like Winter Games is using "attached sprites" (two sprites are linked together). This is a missing feature yet and probably the root of the error.

**Comment by dirkwhoffmann** [comment]
<img width="893" alt="Bildschirmfoto 2019-08-03 um 14 24 23" src="https://user-images.githubusercontent.com/12561945/62411896-905d5d00-b5fa-11e9-88f8-67ec0558fbf7.png">

What a beauty 🥰
