### ISSUE TITLE
Action Replay Mk III v3.09 (1991)(Datel Electronics) 

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/vAmiga#65]
Hi, is there any way to run this cartridge in VAMIGa ?

https://the-eye.eu/public/rom/Amiga/Most_Extensive_Collection_Online/ROMs/Action%20Replay%20Mk%20III%20v3.09%20%281991%29%28Datel%20Electronics%29%5Bm%5D.zip

**Comment by dirkwhoffmann** [comment]
Unfortunately not. It'll take a long time until such a cartridge can be supported. 

I'm closing the issue for now, because it would stay open for a very long time. We can reopen it when the emulator got more stable.
