### ISSUE TITLE
GUI hard drive integration

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#654]
This is a follow-up to issue #651. Since hard drive support is coming to vAmiga, a couple of design decisions need to be made regarding GUI integration. Let's start with some use cases. I think typical users might want to do the following:

- Attach an existing HDF.
- Attach an empty hard drive, specified by size or other drive parameters.
- Convert an existing macOS folder to an HDF file on-the-fly. 

The third functionality would be similar to what is already supported for disks. If a folder is dragged into the emulator window, vAmiga automatically tries to convert the folder contents to an ADF. On success, the ADF can be inserted as as disk in any connected drive. A similar functionality could be implemented for HDFs.

A major difference to ADFs will be that hard drives don't support hot-plugging. An HDF can only be attached if the Amiga is powered off. 

Another issue is "write-through". vAmiga's philosophy is to keep the original media files untouched. This means that modifying a disk inside the emulator won't have any effect on the original ADF. I.e., nothing is written back automatically. If the users want to keep the changes, he needs to export the disk manually. At the moment, I don't want to break with this philosophy for HDF files because of consistency reasons. However, I could imagine that some users might expect the hard disk to be persistent and don't want to export any change manually (which always results in duplicated files).

**Comment by Alessandro1970** [comment]
> At the moment, I don't want to break with this philosophy for HDF files because of consistency reasons. However, I could imagine that some users might expect the hard disk to be persistent and don't want to export any change manually (which always results in duplicated files).

...a button bar, menu command, or something like to directly overwrite / update the hard drive file could be useful, quick and easier

**Comment by mras0** [comment]
Just some brainstorming, so disregard (and/or consider as future/advanced options) as necessary:
  - If it's a plain HDF maybe the user wants to name it something other than 'DH0'
  - Supporting multiple partitions/disks? Can multiple HDFs be attached?
  - RDB support for reading (could show obvious incapabilities etc.)
  - Folder mounting: What will be the size of the new HD? Can it be increase to allow saving extra data? Will it boot in KS1.3?
  - Folder mounting use case: Adding new software to an existing harddrive, can you mount a folder (or large LHA file) to ease installation?
  - Folder mounting use case: How do you get things you create out again? Re-written HDF is OK, but how do I access my cool module etc.
  - Folder mounting for real (pie in the sky at the moment :))
  - Creating a new HDF: If RDB is supported can e.g. new partitions/filesystems be added via the GUI?

Most of these things can probably wait, but just something to consider for the GUI (WinUAE is quite hard to use in this regard).

**Comment by mras0** [comment]
I don't know if it's a good idea to expose a "block size" setting, AFAIK 256 bytes is only partially supported and larger than 512 requires KS2+ (and entering a non-power of two values is probably going to have exciting consequences).

Also I don't think the boot block matters (and/or it requires extra work in the expansion ROM).

Finally there's the issue of FFS and KS earlier than 2.0. It's trickier that I thought to get to work, if a proper version of the FS driver isn't loaded early, things just won't work out (it's not enough to have WB1.3 in a drive unfortunately). I'll update the other issue with some more details, but basically this isn't going to happen at first. So you probably want to restrict the filesystem to OFS for KS versions < 2 for now (and thus also the disk size). UI-wise this probably also entails re-doing the check if the user switches ROM. Maybe you even want to restrict it to small OFS disks for now (except for testing purposes) until things are more stable.

**Comment by dirkwhoffmann** [comment]
At the moment, I am doing some basic infrastructure work (splitting the existing code into a HardDrive class and a HdrController class, defining error codes, etc. etc.).

There are a lots of obstacles to get around. E.g., there is this annoying problem that HDFs without an RDB don't store the drive geometry. I've seen that `xdftools` has two prediction algorithms, but they don't appear too cleaver to me. I think I need to add another dialog box that comes up if equation `cyls * heads * secs * 512 = fileSize` has multiple reasonable solutions. The emulator would then ask the user to specify the drive geometry manually.

**Comment by mras0** [comment]
> There are a lots of obstacles to get around. E.g., there is this annoying problem that HDFs without an RDB don't store the drive geometry. I've seen that `xdftools` has two prediction algorithms, but they don't appear too cleaver to me. I think I need to add another dialog box that comes up if equation `cyls * heads * secs * 512 = fileSize` has multiple reasonable solutions. The emulator would then ask the user to specify the drive geometry manually.

Just had a quick look and I think that the logic is probably based on [*UAE](https://github.com/tonioni/WinUAE/blob/3f42a74762affbf23d80bef92d402265850bcbe0/hardfile.cpp#L237) (other parts are a bit above that). Seems to be trying different approaches and seeing if that results in getting a valid root block. This seems like a good way to narrow down possible solutions.

**Comment by dirkwhoffmann** [comment]
OK, maybe something like this: 

<img width="675" alt="Bildschirmfoto 2022-02-18 um 18 32 48" src="https://user-images.githubusercontent.com/12561945/154733321-be7fda64-0c88-4bbd-aee9-556d3dae176d.png">

This dialog will come up if the user attaches an HDF for which the emulator is unable to derive the geometry (either because there is no RDB or multiple c/h/s combinations match the file size). The Geometry popup button will show "Custom" by default. In this case, the user can enter the drive geometry manually. In addition, the popup button will be initialised with all the c/h/s combinations that were produced by my matching algorithm.

**Comment by mras0** [comment]
> > This seems like a good way to narrow down possible solutions.
> 
> I am unsure if the algorithm has a high success rate. Here are some real-life examples from http://lclevy.free.fr/adflib/adf_info.html#p4

I meant the part about seeing if it results in reading a valid rootblock (section 4.2 in that link gives the calculation from C/H/S to block number).  [Here](https://github.com/tonioni/WinUAE/blob/3f42a74762affbf23d80bef92d402265850bcbe0/hardfile.cpp#L261) it validates the checksum and see if `type == T_HEADER && header_key == 0 && high_seq == 0 && sec_type == ST_ROOT`.

**Comment by dirkwhoffmann** [comment]
> BTW did you check that CHS mismatch is actually a problem?

No, I haven't checked that yet. If I remember correctly, all commands that need to be handled by the HDR controller use LBA, so it shouldn't matter. Hence, my new plan is to predict the drive geometry under the hood and to select the first one if there are multiple choices. In case the user needs to change the geometry, he or she can do this manually by opening up a user-dialog for that. 

I've also reworked my prediction algorithm. Based on [this site](https://www.win.tue.nl/~aeb/linux/hdtypes/hdtypes-4.html), I've set up an array with common sector sizes and the prediction algorithm will only try to match the file size against those.

    static i8 sizes[] = {
        
        16, 17, 24, 26, 27, 28, 29, 32, 34,
        35, 36, 38, 47, 50, 51, 52, 53, 55,
        56, 59, 60, 61, 62, 63
    };

For my example hard drive, this limits down the possible geometries to two:

```
c: 10 h: 1 s: 32
c: 20 h: 1 s: 16
```

The first one is the one which  I used to create the drive. 

 >  I can't get latest vAmiga dev branch to work either for some reason

Sorry for that. Everything is a big construction zone at the moment. I'll make it work again in a couple of days.

**Comment by mras0** [comment]
> Sorry for that. Everything is a big construction zone at the moment. I'll make it work again in a couple of days.

No worries, I have no expectation that the dev branch is in any kind of working state. Just wanted a quick sanity check as my own repo is in a similar disorganized state 😁  I was able to test what I wanted on an earlier commit, and it seems to be working again now (or maybe I had an error on my side).

> I've also reworked my prediction algorithm. Based on [this site](https://www.win.tue.nl/~aeb/linux/hdtypes/hdtypes-4.html), I've set up an array with common sector sizes and the prediction algorithm will only try to match the file size against those.

Sounds like a good idea, and I could have sworn I had issues with mismatching geometry at some point, but for whatever reason it doesn't seem to be an issue now. Oh well.

**Comment by dirkwhoffmann** [comment]
Just a brief update. Before moving the focus to the device driver (again), I'll try to improve the basic infrastructure and make it accessible via the GUI. Today, I've started to rework the Export panel which will look as follows: 

<img width="958" alt="Bildschirmfoto 2022-02-21 um 11 50 49" src="https://user-images.githubusercontent.com/12561945/154941670-aedf4b5c-9bd2-44b5-8560-db7da09943c9.png">

The disk can be exported by either clicking the Export button (which will open a Save panel) or by dragging the drive icon into some Finder window.
 
Instead of using the HDF format, the user may choose to export all Amiga files to the macOS files system. 

<img width="537" alt="Bildschirmfoto 2022-02-21 um 12 00 21" src="https://user-images.githubusercontent.com/12561945/154946638-026aaea6-824a-40eb-8e4b-ea0f9a63603f.png">

Dragging the folder icon also works. I.e., if the folder icon is dragged into a Finder window, vAmiga will create a new folder and export all Amiga files one by one.

**Comment by dirkwhoffmann** [comment]
Brief update: I am close to releasing v2.0 beta 1 which comes with hard drive support. The following video shows how a hard drive image can be attached to vAmiga via drag and drop (make sure to enable audio while watching):

https://user-images.githubusercontent.com/12561945/156930892-f091689f-4505-4fe8-a9b6-7b4b2a702bb9.mov

Some side notes: In this video, vAmiga is configured with two Zorro boards. When the emulator starts, it automatically creates a small 10MB default hard drive for each board, named DH0 and DH1, respectively. Both drives can be seen in the status bar. After dragging in an HDF into the drop zone for HD0, the first drive is replaced by the drive contained in the HDF (which contains a copy of the Workbench). After the restart, Kickstart finds a bootable HDF image and a few seconds later, the Workbench comes up. 

Hard drive operations are visualised by changing the drive led color. A green flash indicates a sector read, a red flash indicates a sector write. If somebody has suggestions for a more realistic head step sound, please let me know. It was difficult to find free mp3 effects that sound close to a real hard drive. 

Finally, let's thank @mras0 for his excellent implementation of the controller Rom. I would have newer managed to get hard drive support working in vAmiga on my own.
