### ISSUE TITLE
Add RDB support

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#655]
Since the new HDR device driver implemented by @mras0 works so well, it’s time to add RDB support to vAmiga.

In the first step, I’ll have to rework all my FileSystem classes. These classes are used to, e.g., write a macOS file to an ADF/HDF or to export all files from an ADF/HDF to the macOS file system. In short: These classes are my own internal xdftools. In addition, they define several datastructures (Geometry, FSDescriptor, FSPartitionDescriptor) which are used at multiple places. Due to a lack of understanding how partitions really work, I think I’ve screwed up the design of these classes. E.g., all block numbers are stored as absolute numbers which means that blocks can reference blocks in another partition. This is all wrong and only worked, because I’ve been dealing with single-partition devices until now (I am using my FileSystem classes mainly for managing ADFs, e.g., for creating a bootable disk when an EXE file is dragged in). 

The major design flaw, however, is best described by a picture:

![FSVolume](https://user-images.githubusercontent.com/12561945/155540828-ebc0f469-2531-45f3-94ad-ab4fcf0daa4c.png)

Right now, partitions live inside an FSDevice object, because the FSDevice mirrors all blocks in the HDFs one by one. This doesn’t make sense because then, the RDB would also belong to the FSDevice object. But if my understanding is correct, the RDB as well as some other blocks exist on the meta-level. I.e., they are blocks describing the file system(s), but they are not part of the file system itself. The new proposed design is shown to the right. The new class should know nothing about partitions, because it basically *is* a partition.

**Comment by mras0** [comment]
RDB disks are organized like this (not to scale):
![image](https://user-images.githubusercontent.com/9952017/155576056-0532b4e5-8e4b-40c4-ad6f-643b3442cce2.png)

Normal ADF/Non-RDB HDFs just have a single partition filling the whole disk. So you have the metadata at the start and the individual partitions in contiguous blocks, so if relevant you can probably get away with a simple offset + length of the partition if that makes things easier.

I think the classic abstraction is to have a block device (whether floppy or hard) with that holds the physical geometry and allows reading/writing blocks using LBA addressing, and filesystems that hold a LBA range where they live and a block device reference. Mounting a HDF would then entail creating a block device, analyzing it, and instantiating one or more filesystem objects.

**Comment by dirkwhoffmann** [comment]
I am still struggling with some basic RDB stuff. For getting startet, I've created a small test disk with `rdbtool`: 
[rdbtest.hdf.gz](https://github.com/dirkwhoffmann/vAmiga/files/8140272/rdbtest.hdf.gz)

The test disk has two partitions: 

```
BlockDevice:                0       21         704  352Ki  heads=1 sectors=32 block_size=512
PhysicalDisk:               0       21         704  352Ki  heads=1 sectors=32 block_size=512
LogicalDisk:                1       21         672  336Ki  rdb_blks=[0:31,#32] used=[hi=2,#3] cyl_blks=32
Partition: #0 'Partition1'        2       11         320  160Ki   47.62%  DOS0/0x444f5300
                                                                      blk_longs=128, sec/blk=1, surf=1, blk/trk=32
                                                                      fs_block_size=512
                                                                      max_transfer=0xffffff
                                                                      mask=0x7ffffffe
                                                                      num_buffer=30
                                                                      bootable=0
                                                                      automount=1
Partition: #1 'Partition2'       12       21         320  160Ki   47.62%  DOS0/0x444f5300
                                                                      blk_longs=128, sec/blk=1, surf=1, blk/trk=32
                                                                      fs_block_size=512
                                                                      max_transfer=0xffffff
                                                                      mask=0x7ffffffe
                                                                      num_buffer=30
                                                                      bootable=1 pri=0
                                                                      automount=1
```

The second partition is bootable and supposed to run the Kyrios demo:

```
Test                                             VOLUME  --------  25.02.2022 00:29:58.00  DOS0:ofs #512
  kyrios.exe                                     131784  ----rwed  25.02.2022 00:29:56.00  
  s                                                 DIR  ----rwed  25.02.2022 00:29:58.00  
    startup-sequence                                 11  ----rwed  25.02.2022 00:29:58.00  
sum:           279  139Ki        142848
data:          272  136Ki        139264  97.49%
fs:              7  3.5Ki          3584   2.51%
```

When vAmiga is started with this disk, the device driver reads blocks from both partitions:

```
HdrController0:211 Unit: 0 Blck: 64 Cmd: READ
HdrController0:211 Unit: 0 Blck: 224 Cmd: READ
HdrController0:211 Unit: 0 Blck: 225 Cmd: READ
HdrController0:211 Unit: 0 Blck: 224 Cmd: READ
HdrController0:211 Unit: 1 Blck: 384 Cmd: READ
HdrController0:211 Unit: 1 Blck: 544 Cmd: READ
HdrController0:211 Unit: 1 Blck: 545 Cmd: READ
```

However, it doesn't boot. 

@mras0: Could you perhaps check if your emulator boots from the HDF correctly? I'd like to rule out that there's an issue with the HDF.

**Comment by dirkwhoffmann** [comment]
Update: On this disk, it's  the other way round. The Kyrios demo is on the first partition which has been marked as bootable. The second partition is not bootable:
[rdb2.hdf.zip](https://github.com/dirkwhoffmann/vAmiga/files/8140503/rdb2.hdf.zip)
 
In this case, it boots just fine: 

<img width="958" alt="Bildschirmfoto 2022-02-25 um 11 46 56" src="https://user-images.githubusercontent.com/12561945/155702407-ca61e360-4a84-4636-8775-d2be3ef2353d.png">

**Comment by mras0** [comment]
I see the same behavior (hadn't checked this case before). Setting boot priority to -1 for the non-bootable partition seems to make it work. Don't know if this is a bug in my code, will check the docs later.

**Comment by mras0** [comment]
OK, that's a bug in the expansion ROM. I should have set boot priority to -128 when the disk isn't bootable (fixed). Luckily we don't have to produce a new mask and do a recall since it can be worked around in software :)

**Comment by dirkwhoffmann** [comment]
> OK, that's a bug in the expansion ROM. I should have set boot priority to -128 when the disk isn't bootable

Very cool, thank for fixing this! I'll patch my expansion ROM asap. 😎

Briefly on something else: Today I stumbled over the Amiga naming scheme (again). Up to now I mistakenly associated the names dh0, dh1 with two different physical hard drives. Now, I've learned that dh0, dh1, ... are usually used to enumerate logical devices, i.e., partitions. Is there a term that refers to the physical device, rather than a logical unit? I ask because in RetroShell the four floppy drives are addressed via df0, ..., df3. Following this scheme, I am currently using dh0 to dh3 for the four hard drives that can be connected (four separate Zorro boards). Unfortunately, this is misleading, because the user might think I am referring to logical devices rather than physical devices.

**Comment by idrougge** [comment]
uaescsi.device unit 0, uaescsi.device unit 1…

**Comment by dirkwhoffmann** [comment]
Hmm, it still doesn't boot the demo. It opens up a CLI window, but doesn't go further.

<img width="958" alt="Bildschirmfoto 2022-02-25 um 18 17 32" src="https://user-images.githubusercontent.com/12561945/155759333-c9e6d564-8962-4819-b896-fd5781fddfa9.png">

**Comment by mras0** [comment]
You're always passing 1 for [devn_bootflags](https://github.com/dirkwhoffmann/vAmiga/blob/064a73d49c7752190f22df344f88e2a482e95cf0/Emulator/Zorro/HdrController.cpp#L321). Change it to `part.flags` and it works as expected. 

Regarding the naming issue, maybe you just want to name them "HDx" in the retroshell. I don't think having multiple harddrive controllers was very common back in the day (maybe for hardcore BBS setups?). Usually you have one device handling multiple units (like trackdisk.device handling up to 3 units, one for each drive).

**Comment by dirkwhoffmann** [comment]
> You're always passing 1 for devn_bootflags

🤭 Now, as you told me, I see it, too. 

> Change it to part.flags and it works as expected.

Indeed. Works like a charm now 😎.

> HDx

OK, I'll go for that.
