### ISSUE TITLE
Diagnostic 2.0 Logica Diagnose ROM?

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#66]
Does anybody know if this Rom is available somewhere?

**Comment by Alessandro1970** [comment]
https://www.amigawiki.org/doku.php?id=de:service:basics:logica_diagnostic

<img width="534" alt="Schermata 2019-06-22 alle 10 37 36" src="https://user-images.githubusercontent.com/34916641/59961563-c5de3900-94d9-11e9-9321-db49084abeb9.png">

A friend of mine has the AmigaForever CD, an old version, I asked to him about it; next Monday if he will find it, he will send to me the files...

**Comment by dirkwhoffmann** [comment]
Solved. 😉

I'll inform about the diagnostic results in a separate thread.
