### ISSUE TITLE
Turning vAmiga into a sandboxed app

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#664]
Today, I've been trying to make vAmiga a sandboxed app and ... failed.

I've already changed the way how vAmiga retrieves the application folder URL since the old method was not compatible with sandboxing. 

Now I am facing a more severe problem: I can't execute `ffmpeg` any more, because...

(1) sandboxed apps have no access to /usr/local.
(2) temporary files are created in /tmp.

A workaround for (1) could be to ask the user to keep a copy of the `ffmpeg` executable in the Applications folder (however, I can only tell if this really works once (2) is resolved). As a solution for (2) I could add a function called `Amiga::tmp()` which  returns the path to a temporary folder. At start, the maOS GUI could tell the core emulator where this directory should be located at. Getting rid of the hard coded `/tmp` folder seems like a good idea anyway.

**Comment by emoon** [comment]
Would it be possible to include the `ffmpeg` exe with the Application instead?

**Comment by emoon** [comment]
So as a workaround you could perhaps include `curl` or `wget` and then when the user want to capture you tell them that ffmpeg will be downloaded (using curl or wget) and written to a directory inside the sandbox. Not perfect, but maybe better than fully manually? (and doesn't require you to add some http(s) code for downloading inside the UI, but maybe there is some Apple API that could be used, so might not be that bad)

**Comment by dirkwhoffmann** [comment]
> So as a workaround you could perhaps include curl or wget and then when the user want to capture you tell them that ffmpeg will be downloaded

Nice approach(!), but the idea behind my sandboxing efforts is to make vAmiga compliant with Apples App Store rules. Apple won't allow me to do things like that.

Side note: Even I manage to make vAmiga a sandboxed app and even if Apple allowed me to distribute vAmiga via App Store, I am unsure if I really want to go down this road. I just payed Apple 99 EUR to disable a warning message which really 🤐. It's not about the 99 EUR, it's about the fact that I simply get nothing in return. If Linux had a better desktop experience, I would have turned away already.

**Comment by emoon** [comment]
I see. I don't know what kind of rules is expected with the Sandboxing, but I assumed you would still be allowed to download executable code (in form of dynamic libs or external tools) but I guess that might not be the case then.

Yeah, I have been running Linux as primary OS for 5 years now (switch from mac) but I still have a mac as a secondary machine. They both has their pros and cons, but the overall desktop experiense may be nicer on a mac, but I really like my tiling window manager on Linux :) That is more of a "pro" style tho and not something for a "regular" user, but great for a developer (imo)

**Comment by mras0** [comment]
I've never done any MacOS desktop development, but there's native support for video encoding right? So you'd "just" have to do it using the native interfaces, which is probably easier done from Swift. Some quick websearching seems to indicate that it's possible, but I didn't find any easy to follow examples.

Now whether the effort is worth it is a whole other topic. Or maybe you can users to install /copy/symlink ffmpeg to [/usr/bin](https://developer.apple.com/forums/thread/654579) (though that seems a bit dirty, and I don't even know if that's possible or ill-advised, just an idea)

**Comment by mithrendal** [comment]
or you could put an "host additions installer" on your vAmiga website, which just does the installation job ... analog to "guest additions" for virtualBox. No?

**Comment by dirkwhoffmann** [comment]
First of all, thanks a lot for all the good advice. I did some experiments and here is what I've found out:

- C++ function `temp_directory_path()` returns a path in `/var` which is accessible from sandboxed apps. E.g., I got
`/var/folders/ms/sm04ytyj3k7cl_2fpz0ww60h0000gn/T/dirkwhoffmann.vAmiga/videoPipe`. Hence, handling sandbox-compliant tmp files are extremely easy to achieve. 
- Copying `ffmpeg` to the Applications folder works. Combined with the tmp-path changes, I did manage to run ffmpeg from within a sandboxed vAmiga. 
- Adding a symlink to `/usr/bin` would be a simple and clean solution, but Apple does not permit it: 

        % ln -s /usr/local/bin/ffmpeg /usr/bin/ffmpeg 
        ln: /usr/bin/ffmpeg: Operation not permitted

From https://stackoverflow.com/questions/36730549/cannot-create-a-symlink-inside-of-usr-bin-even-as-sudo
> El Capitan's new [System Integrity Protection](https://support.apple.com/en-us/HT204899) feature prevents changes to several core parts of OS X, including most of /usr/, even by root.

**Comment by dirkwhoffmann** [comment]
I've managed to make vAmiga a sandbox app (with the known limitations), so there might be a chance to get into the App Store (still unsure if I want to). 

If an FFmpeg instance in an inaccessible folder is selected, a warning message comes up:

<img width="641" alt="Bildschirmfoto 2022-03-20 um 16 36 29" src="https://user-images.githubusercontent.com/12561945/159170386-f0604009-8d9d-454c-a245-1f4787ce7615.png">

After copying ffmpeg into the application folder, everything works as expected:

<img width="641" alt="Bildschirmfoto 2022-03-20 um 16 36 40" src="https://user-images.githubusercontent.com/12561945/159170422-8b3c9dc5-d3c3-459b-ac99-b1dbfd3654ed.png">
