### ISSUE TITLE
Amiga 1000 hangs in Bootstrap Rom

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#67]
Don't select an A1000 and install a Bootstrap Rom yet 🤭:

<img width="929" alt="Screenshot 2019-06-22 at 15 03 56" src="https://user-images.githubusercontent.com/12561945/59964474-a6f39d00-9501-11e9-9379-05399a28aa93.png">

**Comment by dirkwhoffmann** [comment]
First time I see this screen 😎. Never had an A1000: 

<img width="929" alt="Screenshot 2019-06-23 at 10 08 50" src="https://user-images.githubusercontent.com/12561945/59973330-f4721780-959e-11e9-8080-bd24ede5e203.png">

OK, let's try to insert a Kickstart disk ... waiting waiting waiting ... ooohhhhhhh 😀
(No version number displayed. The original version from the Stone Age.....finally.)

<img width="929" alt="Screenshot 2019-06-23 at 10 01 50" src="https://user-images.githubusercontent.com/12561945/59973341-0e135f00-959f-11e9-93bd-a7f2e8edd357.png">

Let's try to boot the A2000 workbench 1.2... Oooupps 🤭:

<img width="929" alt="Screenshot 2019-06-23 at 09 59 56" src="https://user-images.githubusercontent.com/12561945/59973364-5c286280-959f-11e9-9638-da0daa4608f2.png">

Legend has it that an ancient Kickstart may require an ancient Workbench... 🤔. 

Yes, indeed 😎:

<img width="929" alt="Screenshot 2019-06-23 at 10 05 37" src="https://user-images.githubusercontent.com/12561945/59973371-75c9aa00-959f-11e9-97af-51e5896f1ab2.png">

Funny: The icons differ a little compared to 1.2 and 1.3. Trashcan's a little trashy.

**Comment by mithrendal** [comment]
I think the 1.1 trashcan looks more modern nowadays. Still have the original disks.

**Comment by dirkwhoffmann** [comment]
> Still have the original disks. 😉

Oooohhhhhh, never seen those. I wonder if they still work 🤔. The metal shift-thing-to-protect-the-surface (don't know how it is called) is still shining 😀.
