### ISSUE TITLE
extended ADF format

### ISSUE THREAD

**Issue by santiontanon** [dirkwhoffmann/vAmiga#672]
Hi, I was trying to insert an .adf disk into vAmiga (it is a savedisk for the game "Shadowlands", and upon inserting it, I get "This file utilizes encoding features of the extended  ADF format that are not supported by the emulator yet."

I was wondering if support for this extended ADF format is planned. I'd be happy to provide the ADF in question, which is loaded fine by UAE.

**Comment by dirkwhoffmann** [comment]
Yes, please provide the ADF. If it's just a save disk and has no copyright protected material on it, you can post it directly here.

**Comment by santiontanon** [comment]
Great! Thanks a lot for the very quick response. I just uploaded the adf here: https://braingames.santiontanon.dev/uploads/tmp/shadowlands-savedisk.adf

It is just a save disk for Shadowlands, not the game itself. So, I think there should be no copyright problems.

**Comment by santiontanon** [comment]
Oh, sorry. I only have this use case unfortunately. We can generate more savegames for this game to have more samples if this can help! But it will all be coming from the same game.

**Comment by dirkwhoffmann** [comment]
v2.1b1 is able to read extended ADFs that encode (some) tracks in standard format. With the new code, I was able to restore the saved state from the save disk:

<img width="1050" alt="Bildschirmfoto 2022-05-19 um 19 20 22" src="https://user-images.githubusercontent.com/12561945/169468830-c5ee07fc-57ad-4e48-972a-4b77d5c26093.png">

**Comment by santiontanon** [comment]
Oh, this is wonderful!!! Thank you so much!
