### ISSUE TITLE
Black screen on boot - 2.0b3 (possibly 2.0b2)  - M1

### ISSUE THREAD

**Issue by shinra-electric** [dirkwhoffmann/vAmiga#684]
I have selected the 1.3 kickstart rom, but get a black screen at launch. 

Preferences are all default.
![Screenshot 2022-04-12 at 14 29 42](https://user-images.githubusercontent.com/50119606/162973498-12e0c4e6-634f-48c3-97e8-c9a6bacd6be3.png)

I don't know if this was introduced in 2.0b3 or 2.0b2 as b2 did not work on the M1

**Comment by rjpontefract** [comment]
I'm not if this will help you, but I had this same problem and I believe I resolved it by going to the video tab in preferences and selecting "revert to recommended settings" and then clicking "use as default".

**Comment by shinra-electric** [comment]
Yes, that fixed it for me.

**Comment by shinra-electric** [comment]
This is probably related to #680. 

Should I leave this issue open?

**Comment by dirkwhoffmann** [comment]
> Should I leave this issue open?

Yes, please leave it open.

On my machine, it appears to be like this:

- The first time I open the app in the morning, all user settings read back as 0 (macOS even ignores the default values which are registered on app launch). One of the video settings is causing a black screen in this case (I don't know which one).
- When the app is closed and reopened, everything is back to normal.
- The issues started when I converted vAmiga into a sandboxed app. I never had such problems before. 

Frankly, I've become tired of debugging crappy Apple APIs. What I am going to do is to get rid of all the macOS related user defaults stuff. In future, I'll manage my own config file.

**Comment by dirkwhoffmann** [comment]
Should be fixed. In v2.0b4, user settings are managed by the emulator itself.

Settings are stored as key-value pairs in a file called `vAmiga.ini` in the application support folder, e.g.: 

    /Users/hoff/Library/Containers/dirkwhoffmann.vAmiga/Data/Library/Application Support/vAmiga/vAmiga.ini

It looks something like this: 

```
# vAmiga 2.0b4 [DEBUG BUILD] (Apr 18 2022 11:26:20)
# dirkwhoffmann.github.io/vAmiga

ACCURATE_KEYBOARD=1
AGNUS_REVISION=2
AUDPAN0=50
AUDPAN1=350
AUDPAN2=350
AUDPAN3=50

...

[Peripherals]
GameDevice1=0
GameDevice2=-1

[Controls]
Autofire=0
AutofireBullets=-3
AutofireFrequency=2.5
DisconnectKeys=1
JoyKeyMap1=W3sia2V5Q29kZSI6MTI1LCJjYXJib25GbGFncyI6MH0sMSx7ImtleUNvZGUiOjQ5LCJjY
XJib25GbGFncyI6MH0sNCx7ImtleUNvZGUiOjEyMywiY2FyYm9uRmxhZ3MiOjB9LDIseyJrZXlDb2RlI
joxMjQsImNhcmJvbkZsYWdzIjowfSwzLHsia2V5Q29kZSI6MTI2LCJjYXJib25GbGFncyI6MH0sMF0=
JoyKeyMap2=W3sia2V5Q29kZSI6MTQsImNhcmJvbkZsYWdzIjowfSwwLHsia2V5Q29kZSI6NywiY2FyY
m9uRmxhZ3MiOjB9LDEseyJrZXlDb2RlIjo4LCJjYXJib25GbGFncyI6MH0sNCx7ImtleUNvZGUiOjEsI
mNhcmJvbkZsYWdzIjowfSwyLHsia2V5Q29kZSI6MiwiY2FyYm9uRmxhZ3MiOjB9LDNd
MouseKeyMap=W10=
ReleaseMouseByShaking=1
ReleaseMouseKeyComb=0
ReleaseMouseWithKeys=1
RetainMouseByClick=1
RetainMouseByEntering=0
RetainMouseKeyComb=0
RetainMouseWithKeys=1
```
