### ISSUE TITLE
device name

### ISSUE THREAD

**Issue by polluks2** [dirkwhoffmann/vAmiga#685]
The first Amiga hard disk is called **dh**0:.

**Comment by idrougge** [comment]
It is called whatever you name it in HDToolbox.

**Comment by polluks2** [comment]
Never the less the default is `dh0:`.

**Comment by dirkwhoffmann** [comment]
> The first Amiga hard disk is called dh0:.

Where exactly did you expect to see `dh0` (instead of what? `hd0`?). Could you provide a screenshot?

**Comment by polluks** [comment]
Exactly, the old Tripos naming convention.![screenshot](http://wordpress.hertell.nu/wp-content/uploads/2014/10/CFuaehdtoolbox13.png)

**Comment by dirkwhoffmann** [comment]
Should be solved in v2.0.
