### ISSUE TITLE
lha drag and drop functionality 

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/vAmiga#686]
I want to drag and drop a LHA compressed [file](https://files.scene.org/get/parties/2022/revision22/amiga-demo/void-bunnycracktro.lha) onto vAmiga and have it mount/execute.

One way it to check if lha is installed on [Mac](https://formulae.brew.sh/formula/lha) and [Windows](http://gnuwin32.sourceforge.net/packages/lha.htm). If the Lha executable is not there, then stop and display and error.If the executable is there then uncompress the Lha and mount it. If there is only 1 executable file then execute that.

I see there was discussion in #387 and #446 . Is this still the same scenario 2 years later?
 It would be great to get this feature implemented.

**Comment by mithrendal** [comment]
https://github.com/temisu/ancient

they say 

`This is a collection of decompression routines for old formats popular in the Amiga, Atari computers and some other systems from 80's and 90's as well as some that are currently used which were used in a some specific way in these old systems.`


LHA format is also supported so maybe we can analyse the possibility to embed the LHA decrunching source code from them ... like dirk did with xdms package for DMS files

**Comment by dirkwhoffmann** [comment]
> One way it to check if lha is installed on [Mac](https://formulae.brew.sh/formula/lha) and [Windows](http://gnuwin32.sourceforge.net/packages/lha.htm). If the Lha executable is not there, then stop and display and error.If the executable is there then uncompress the Lha and mount it. If there is only 1 executable file then execute that.

I'm unsure if this is the way to got. There are so many "If"s. E.g., I am pretty sure that different users might expect different behaviours when the file mentioned above is dragged in. The file contains: 

```
-rw-r--r--@   1 hoff  staff    1059 16 Apr 11:05 Void-BunnyCracktro.readme
-rw-r--r--@   1 hoff  staff  165740 16 Apr 11:05 Void-BunnyCracktroCR.exe
-rw-r--r--@   1 hoff  staff     508 16 Apr 11:05 file_id.diz
```

Some users might expect the EXE being extracted and auto-bootet. Others might expect a disk being assembled which contains all three files. The expectation depends on the use case.

Wouldn't it be easier to utilise a small shell script to extract all EXE files before dragging them into the emulator?

**Comment by polluks2** [comment]
How about this library?
https://github.com/fragglet/lhasa

**Comment by DanBuchan** [comment]
Having been tinkering with amiberry recently, amiberry kindof supports a version of this.

You can drag and drop whdload packages in either zip or lha format and it'll run them. But this only works with LHAs that contain a whdload packaged piece of software AND for packages it already knows about. Amiberry ships with a json file that includes a "working" emulator config for every TOSEC whdload packaged game they know about. So when you drag and drop an lha; it unpackages the files, checks for a whdload slave, if it finds one it looks up it's json db, if it finds a config it configures amiberry and then loads the whdload slave. Obviously a lot of upfront work had to be done to prep that json file and it only works if the lha contents happen to be a whdload package.

As lha is just a compression/archiving format (like zip) which can contain just about anything, I don't really see how there can (or could) be a generic solution where an emulator (or an emulated amiga) just "knows" what to do with whatever it might find inside and lha. If it contains a whdload package you could implement a version of the amiberry solution. What if the lha contains 12 tiff files? Should your display one? Which one? Using what software? Answering these kinds of questions gets in to the weeds of having to implement things like mimetypes

**Comment by dirkwhoffmann** [comment]
I'll put the issue on hold because there are many higher priority things to do. Right now, I think the benefit of support lha is probably not worth the effort.
