### ISSUE TITLE
AROS and HDController issues

### ISSUE THREAD

**Issue by mras0** [dirkwhoffmann/vAmiga#688]
@mithrendal noticed that there are some issues with the HDController and AROS that I see as well (described [here](https://github.com/mras0/AmiEmu/issues/1)).

I'm trying to figure out a fix, but I'll be on vacation next week, so if you're planning a release soon you should consider some kind of stop-gap measure.

So far I can see that AROS *really* doesn't like [devn_numBuffers](https://github.com/dirkwhoffmann/vAmiga/blob/934b467b7fffb391c4e0529dd3736d01ba908ba5/Emulator/Zorro/HdController.cpp#L493) being just 1 for non-RBD disks (FWIW KS.3.1 sets it to 30 ($1e), you can see that in the rdbks13.hdf file I shared). However from testing I see that I have to increase it significantly more to avoid getting something like (in the serial console output):
```
[MM] Chunk allocator error
[MM] Attempt to free 4294770684 bytes at 0x00b700dc
[MM] The block does not belong to any MemHeader
```
Which seems to indicate that there's serious corruption going on. I'm not testing with the same AROS release though (for various reasons) so YMMV.

**Comment by dirkwhoffmann** [comment]
> I'm trying to figure out a fix, but I'll be on vacation next week

No worries. Take your time and enjoy your vacation. 

> I'm not testing with the same AROS release

vAmiga includes a rather old Aros version, because I didn't manage to get later ones to work. I remember that I had a lot of trouble in finding compatible Aros Roms. There don't seem to be "official stable" versions. At some point I gave up and simple used the Roms that shipped with SAE.

**Comment by mras0** [comment]
That was quite the pain to debug, but should be fixed now. Apart from the above-mentioned issue with AROS not liking only having one buffer, it also exposed a real bug in the expansion rom: I didn't have correct return value from the Close function (it should be 0, but was just whatever happened to be in D0 at the start). This meant that when the open count reached 0 it ended up calling UnLoadSeg on a bad address leading to all kinds of exciting memory corruption.

The reason it didn't show up before is that the device is never unloaded under real AmigaOS. AROS seems to do a weird open/close during startup for whatever reason, and that exposed the issue.

Updated [exprom.zip](https://github.com/dirkwhoffmann/vAmiga/files/8597108/exprom.zip) for testing.

**Comment by mithrendal** [comment]
So great 🫡 that you fixed it. But from now on you have to promise us to only think about your holidays 😎🌴

**Comment by dirkwhoffmann** [comment]
I've updated the HDC controller with the latest exprom. Works perfectly fine 😎: 

<img width="1044" alt="Bildschirmfoto 2022-04-30 um 22 31 46" src="https://user-images.githubusercontent.com/12561945/166121781-b2b1a6d8-09a5-459b-bb5e-4f4967449559.png">

Right now, I am using 128 buffers:

    mem.patch(ptr + devn_numBuffers,    u32(128));

> FWIW KS.3.1 sets it to 30 ($1e), 

OK, so I better go for this value.

**Comment by mras0** [comment]
Great! I've also managed to get "your" version of AROS working in my emulator (I had just used the one embedded in WinUAE) and in vAmigaSDL.

I'm not 100% sure, but I think the issue with AROS only having one buffer is [this](https://github.com/aros-development-team/AROS/blob/153c6e19d4c24b115432d92339842269764148b6/rom/filesys/afs/cache.c#L166) part of the code assuming it'll only run out if it has pending writes, but that's not true since it marks blocks as USED but not written during other operations (but I *think* it'll only be at most a couple of blocks, maybe only one). Either way, I though it safer to just go for 30 (like KS3.1 HD toolbox). The more used blocks the more memory is consumed (which is why I originally only allocated one), but otherwise any sufficiently high number should work. 128 blocks @ 512bytes per partition takes quite bit out if you're doing a 512K only setup.

**Comment by dirkwhoffmann** [comment]
> (I had just used the one embedded in WinUAE

UAE has Aros Roms embedded? Do I need to download an extra package?

I also tried latest Roms from [here](http://www.aros-platform.de/download.html), but they don't seem to work properly. Graphics is corrupted in both vAmiga and UAE (lines with garbage pixels):

<img width="717" alt="Bildschirmfoto 2022-05-01 um 06 47 12" src="https://user-images.githubusercontent.com/12561945/166133027-156ec9b3-3274-4a87-9728-189a45569c23.png">

**Comment by mras0** [comment]
It should be at the top of the "Main ROM file" dropdown in Hardware->Quickstart " AROS KS ROM (built-in) 1024K" (you don't need to select an extended rom, it'll handle that automatically). Version is "SVN54705 2017-05-20". They're embedded via a huge cpp file you have to download separately if you want to build WinUAE [step 6](https://github.com/tonioni/WinUAE/).

Here it is in a binary version, split up: [aros-SVN54705.zip](https://github.com/dirkwhoffmann/vAmiga/files/8598471/aros-SVN54705.zip). Seems to work fine in vAmiga.

**Comment by dirkwhoffmann** [comment]
> It should be at the top of the "Main ROM file" dropdown

Oups, OK, I was blind 🙄. 

Interestingly, UAE ships with an older revision (SVN54705) than SAE (SVN55696). I think it's best to offer both in vAmiga, because a) there might be a reason for UAE to ship an older version, b) it makes comparing vAmiga with UAE easier, c) I don't want to replace a newer working revision by an older one. Therefore, I've replaced the "Install Aros" button in the Rom panel by a popup button offering both revisions:

<img width="637" alt="Bildschirmfoto 2022-05-01 um 12 54 25" src="https://user-images.githubusercontent.com/12561945/166143099-0d89f1fb-2de6-4bfc-a065-202bc6df64e3.png">

**Comment by mras0** [comment]
Looks like WinUAE just uses an old version because there hasn't been a point to updating it (https://eab.abime.net/showpost.php?p=1526725&postcount=3). After trying a few different other versions I can see why. Easier just to stick with one you know works OK.
