### ISSUE TITLE
AROS questions

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#69]
In the last few days I have looked through several websites about AROS, but I am still lost in confusion. I'm summarising my questions here that I was not able to answer myself yet: 

1. Is there an official page where the latest and greatest Amiga Kickstart replacement ROMs can be downloaded?

2. Where can I obtain the 512-KB standalone Amiga Kickstart ROM replacement? So far, I only found versions that require an additional Ext ROM (2 x 512 KB). 

3. Are ROM images available that dump out more debugging messages to the serial port than the original ROMs do? 

Unfortunately, my attempt to compile AROS on macOS Mojave failed. After 20 minutes of compiling various stuff, the build script stopped: 

    [MMAKE] Making kernel-exec-unix in arch/all-unix/exec
    Makedepend arch/all-unix/exec/newstackswap.c...
    In file included from /Users/hoff/AROS/arch/all-unix/exec/newstackswap.c:10:0:
    /Users/hoff/AROS/bin/darwin-x86_64/gen/include/aros/debug.h:22:20: fatal error:string.h: No such file or directory
    #include <string.h>

Compiling it locally seems to be a dead end for me.

**Comment by naTmeg** [comment]
Hi Dirk,

it seem they removed the individual download of the rom-file recently.

>1: Go to http://www.aros.org/nightly1.php and grab amiga-m68k-boot-iso (~23mb) The actual roms are in /boot/amiga

>2: There is no 512k rom afaik, because the AROS rom-code is > 512k.

>3: I don't think so, but you can try to contact the AROS-team for that question.
