### ISSUE TITLE
License dependencies

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#693]
I am considering to bring vAmiga into the Apple App Store (as a free download). Unfortunately, Apples App Store policy seems to be incompatible with the GPL, so I might need to change / expand the licence. Right now, I am unsure about what licensing model would fit best. Before taking any decision, it's important to analyse dependencies. Right now, vAmiga has the following external dependencies:

| External code / library | Used by  | License  |
| -----|-----| -----|
| xdms library | Core  | Public Domain |
| iCarousel | GUI | zLib |
| AmiEmu HD controller | Core      | Unknown  |
| Icons from Oxygen icon set | GUI | LGPL |
| Icons from Crystal Clear icon set | GUI | LGPL |

@mras0 Are you planning to add a license to your emulator or the hard drive controller code?

**Comment by mras0** [comment]
For my other hobby projects, I've slapped a MIT license on it and called it a day, just haven't gotten around to doing that for my emulator. I'm fine with whatever, as long as I won't be held liable for anything :)

**Comment by mras0** [comment]
Added license to my repo, and also made sure the expansion roms assemble with vasm in case you or someone else wants/needs to make changes.

**Comment by dirkwhoffmann** [comment]
There is a nice article about some obstacles to publish in the App Store: 
https://rameerez.com/apple-mac-app-store-pros-and-cons-of-publishing-an-app-in-the-mas-and-validating-receipt/

This pretty much reflects my own experience with embedded provisioning profiles, entitlement certificates and other fancy-sounding, but half-baken Apple stuff. Bottom line: I don't want to waste my time with this. The App Store is not the right place for me.

**Comment by emoon** [comment]
Thanks for posting that link. I have thought about putting my music player on the App Store, but after reading that I will likely skip it as well.

**Comment by nekoniaow** [comment]
As a professional iOS game developer I must say that half of the issues this person encountered seem to stem from not finding and reading the Apple documentation. Granted, it's not necessarily the best documentation in the world but it's there and it's findable. It's really not as difficult as they make it to be.
