### ISSUE TITLE
CIA access does not require free bus from Agnus

### ISSUE THREAD

**Issue by mras0** [dirkwhoffmann/vAmiga#696]
As I mentioned in a comment to [another issue](https://github.com/dirkwhoffmann/vAmiga/issues/661#issuecomment-1126982848):

> Regarding CIA access, I had a look at Agnus::executeUntilBusIsFreeForCIA - I don't think CIA requires chip bus to be free.

Attached is a test case that tries to show this:

[ciatest.zip](https://github.com/dirkwhoffmann/vAmiga/files/8701217/ciatest.zip)

Core of the test is to start a D=A blit (w/o blitter nasty) and then write the current value of ciab todlo to color00 (via unrolled `move.w (a3), (a2)` instructions) until the blit is finished. Shorter area with color changes means the code ran too slow (or well, in principle it could be that it ran too fast, but that's unlikely to be the cause).

Copper is used to highlight the expected area and trigger the code. Note that the display isn't stable, but I expect more or less the entire area between the two white lines to be filled.

vAmiga 2.0 code (tested with vAmigaSDL, same result in the online versions):
![image](https://user-images.githubusercontent.com/9952017/168624823-f47c267b-678f-47e8-9bed-0c842244f6e5.png)

WinUAE 4.9.1 (Note: It seems like WinUAE does not give the right value for word reads from the CIA):
![image](https://user-images.githubusercontent.com/9952017/168625140-183d64cb-c2d1-45c6-b690-efad09429602.png)

Stock A1200 (just for reference):
![image](https://user-images.githubusercontent.com/9952017/168626131-6d490e24-0017-421b-8257-7e8584b1695d.png)

EDIT: Version with stable start: [ciatest_stable.zip](https://github.com/dirkwhoffmann/vAmiga/files/8701953/ciatest_stable.zip)

**Comment by dirkwhoffmann** [comment]
Very cool test case!

I haven't had time to look into the details yet, but I have run it on my A500 (with the ACA500+ plugged in). Interestingly, the colors are completely different: 

https://user-images.githubusercontent.com/12561945/168664168-c8d17119-7446-475e-97a6-616f573a797b.mov

This is what I get in vAmiga if the code for waiting for a free bus is removed for CIA accesses: 

https://user-images.githubusercontent.com/12561945/168664617-343633b8-5950-4088-8c77-0b4f281caade.mov

**Comment by mras0** [comment]
> Interestingly, the colors are completely different:

My initial statement about WinUAE being wrong with regards to word reads was too harsh. Reality is more complicated (on my a1200 the undefined bits are either $7f or $ff depending on value written to the other CIA).

Here's a version that doesn't rely on undefined values and uses value of a CIA timer for the colors instead 
[ciatest_stable2.zip](https://github.com/dirkwhoffmann/vAmiga/files/8705484/ciatest_stable2.zip)

It's still not 100% stable because Eclocks/frame is not a whole number (this is only emulated in pre-release versions of winuae), so it'll jump between 5 different start positions.

**Comment by dirkwhoffmann** [comment]
Test `ciastest_stable2`:

Amiga 500: 🥰
![IMG_2762](https://user-images.githubusercontent.com/12561945/168857192-22867e65-726d-46f4-82aa-dfd91cb7d999.JPG)

Latest vAmiga: 😎
<img width="937" alt="Bildschirmfoto 2022-05-17 um 18 02 40" src="https://user-images.githubusercontent.com/12561945/168857227-5cd0e87b-36f9-4443-a1fe-85b0312ab77d.png">

Looks like a perfect match to me.

**Comment by dirkwhoffmann** [comment]
Fixed in v2.1b1.
