### ISSUE TITLE
Screen shifts in the Global Trash (Silents) demo

### ISSUE THREAD

**Issue by nicolasbauw** [dirkwhoffmann/vAmiga#699]
When the first effect starts (vector routine), the whole screen begins to shift up and down at moments.
And with the demo going on, it continues to shift at times, sometimes even left and right (for example when the dot sphere shows).
I did not notice this behavior with 1.02, if I remember well.

it begins at this moment:
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/37193744/169857768-6dcb8524-34a2-4a44-971e-ab91f53aee27.png">

**Comment by dirkwhoffmann** [comment]
Could you try again with these two checkmarks set?

<img width="643" alt="Bildschirmfoto 2022-05-23 um 19 46 59" src="https://user-images.githubusercontent.com/12561945/169877831-bc61dd34-2710-4dd4-81b2-568b48113db9.png">

When disabled, vAmiga ignores the settings and automatically centers the screen depending on the visible display window.

**Comment by nicolasbauw** [comment]
With these checkmarks set, I do no longer see an horizontal / vertical shift happening at some moments, but the whole demo is uncentered, with the bottom right non visible:

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/37193744/169966699-2cc4c89b-2286-4c78-9bd6-d212a2598cb2.png">

**Comment by dirkwhoffmann** [comment]
When auto-centering is off, you need to center it manually (or simply use one of the geometry presets from the "Revert to..." menu at the lower left in the video panel).

**Comment by nicolasbauw** [comment]
With the "extreme" setting, I have an acceptable result, I guess the issue is specific to this demo and the way it creates its display. I've watched this demo for years on real machines and several emulators (even vAmiga) and I never had to fine tune the display settings, that's why I thought of an issue. Thank you, I think you can close the issue.
