### ISSUE TITLE
NTSC mode support

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#700]
There was some lengthy discussion [here](https://github.com/vAmigaWeb/vAmigaWeb/issues/79) about whether vAmiga should support NTSC mode or not. 

I never wanted to implement NTSC mode, because 
- only a very few titles rely on it,
- it has a negative impact on code complexity, 
- it has a negative impact on emulation speed.

However, for the sake of completeness, I agree that it would be nice to offer NTSC in addition to PAL. Hence, maybe I should give it a try. The most annoying NTSC issue is the differentiation between long lines and short lines. At the moment, the end of a DMA line is hard coded at multiple places which has to be replaced by some dynamic code. Emulation speed is affected, because the emulator has to choose between different code paths at various places which requires additional If-Statements. However, if the long line / short line issue can be dealt with in a smart way, the overhead might be acceptable. 

Another issue is validation. Because I don't have any NTSC hardware in my possession, I won't be able to validate the results on a real machine. It would be great if at least some tests of the vAmigaTS suite could be run on real NTSC hardware.

**Comment by Vweber73** [comment]
That's great news, thanks !

**Comment by dirkwhoffmann** [comment]
Most NTSC functionality is up and running:

<img width="1025" alt="Bildschirmfoto 2022-05-29 um 08 20 21" src="https://user-images.githubusercontent.com/12561945/170855901-5ec5957f-f7cf-4dd3-8166-02d616510264.png">

Texture layout in PAL mode: 

<img width="1025" alt="Bildschirmfoto 2022-05-29 um 08 21 20" src="https://user-images.githubusercontent.com/12561945/170855911-f7826feb-3df9-4d6a-930e-91a0af693513.png">

Texture layout in NTSC mode:

<img width="1025" alt="Bildschirmfoto 2022-05-29 um 08 20 56" src="https://user-images.githubusercontent.com/12561945/170855913-9e3b47ec-98fd-4944-a2d5-1d20d67ad03a.png">

Debug option `NTSC_DEBUG` encodes a debug pixel in the HBLANK area. A white pixel indicates a long line (red arrow). Switching between long lines and short lines seems to work as expected. I.e., vAmiga replicates correctly what is described in the HRM:

> In NTSC, the fields are 262, then 263 lines and in PAL, 312, then 313 lines. This alternation of lines and fields produces the standard NTSC 4 field repeating pattern: 
> 
> short field ending on short line 
> long field ending on long line 
> short field ending on long line 
> long field ending on short line 
> and back to the beginning... 
> 

Known / remaining issues:

- The Copper won't react to beam positions that are unreachable in PAL lines. 
- Agnus does not handle manual modifications of the LOL bit yet.
- The displayed texture rect jumps back if PAL/NTSC gets changed when the DMA debugger is open.
- The FPS value in the status bar is misleading, because it displays the GPU frame rate and not the emulator frame rate. There should be two options: FPS (GPU) and FPS (Amiga).

**Comment by Vweber73** [comment]
Wow... Amazing work, many thanks ! 
Can switch between PAL and NTSC can be done by software, as in ECS ?

**Comment by dirkwhoffmann** [comment]
Good news. The validation issue has vanished into thin air as the ACA500+ allows any (later) Amiga to run in PAL or NTSC mode:

![IMG_2830](https://user-images.githubusercontent.com/12561945/170880644-6beebbfe-5730-4c60-b633-663eaff96fb1.JPG)

My HDMI adapter handles the NTSC signal without any issue:

![IMG_2833](https://user-images.githubusercontent.com/12561945/170880704-3db5ebf3-7659-4b82-be68-a344ec563924.JPG)

Next step: Write some test cases that manipulate the LOL bit in various ways.

**Comment by dirkwhoffmann** [comment]
> Can switch between PAL and NTSC can be done by software, as in ECS ?

For earlier Agnus revisions, it's impossible as Commodore had designed two separate chips for both video modes. For later revision, the usual approach is to change the value on a certain pin. 

On a German site, I've found this quote:

> Es kann hard- und softwaremäßig zwischen PAL-Modus (50 Hz Bildwiederholfrequenz) und NTSC-Modus (60 Hz Bildwiederholfrequenz) umgeschaltet werden. Hardwaremäßig über Pin 41 des Agnus (High=PAL, Low=NTSC), softwaremäßig über eine (bisher inoffizielle) Speicherstelle.

This means:

> It can be switched between PAL mode (50 Hz refresh rate) and NTSC mode (60 Hz refresh rate) by hardware and software. In hardware via pin 41 of the Agnus (High=PAL, Low=NTSC), in software via a (so far unofficial) memory location.

I don't know if that's really true. At least I don't know of any unofficial memory location that would do the trick.

**Comment by Vweber73** [comment]
There was a program called palcon, right ? Maybe what it does is explained somewhere ?

**Comment by mras0** [comment]
It's probably referring to bit 5 of [BEAMCON0](https://amigadev.elowar.com/read/ADCD_2.1/Hardware_Manual_guide/node00A7.html). PAL/NTSC switch is AFAIK an ECS Agnus thing, while the programmable modes also require a ECS Denise. KS3.0 bootmenu allows switching between NTSC and PAL as well. Haven't really used those features much, but toggling that bit every frame makes my CRT go nuts :)

**Comment by Vweber73** [comment]
Well, so, next step... ECS Denise :)

**Comment by mras0** [comment]
Programmed modes (ECS Denise feature) took an insane amount of time to complete in WinUAE and it was only done for completeness purposes, so I don't think that should be a priority in this decade for vAmiga. Having some hacks to allow flicker free 640x512/400 modes might bring a benefit though, but I'll leave that to Dirk to decide.

BTW here's a super quick test program (modified showregs) that switches between PAL and NTSC mode every second using BEAMCON0:
[ntscswitch.zip](https://github.com/dirkwhoffmann/vAmiga/files/8794089/ntscswitch.zip)
 
Works in WinUAE (A500+, A600 and A1200 quickstarts) as well as on my real A1200.

**Comment by Vweber73** [comment]
Yes, SuperHires and Productivity maybe should be enough...

**Comment by dirkwhoffmann** [comment]
I've implemented some NTSC related test cases [here](https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Agnus/NTSC)

- `ntsc0`: Draws some Copper bars. Every frame is made a short frame. 
    ![ntsc0_ACA500_ECS_NTSC](https://user-images.githubusercontent.com/12561945/171816765-b5a94a63-1869-4568-86af-7ec318c1eeb4.JPG)

- `ntsc1`, `ntsc2`: Same setup as ntsc0. In addition, the LOL bit in VPOSW is modified in various ways. Screenshot of `ntsc1`: 
    ![ntsc1_ACA500_ECS_NTSC](https://user-images.githubusercontent.com/12561945/171816806-a5cee737-c93e-4caf-ba03-bf2d2b2858d3.JPG)

- `ntsc3`, `ntsc4`: Same setup as `ntsc0`. In addition, Agnus is forced to run in PAL (resp. NTSC) mode by setting (resp. clearing) bit 5 in BEAMCON0. Screenshot of `ntsc3`:

![ntsc3_ACA500_ECS_NTSC](https://user-images.githubusercontent.com/12561945/171816895-f17304e9-23ed-47f6-9d6f-50f88f79f1a1.JPG)

Output of `ntsc4` matches `ntsc0`(as expected).

Some strange magic happens with `ntsc1` and `ntsc2`. First of all, I don't understand the output of `ntsc1`. In first block below the reference line, the LOL bit is only modified at the beginning. Thus, I don't understand why the second and the third line show a shift of one pixel, but the fourth line doesn't. Moreover, `ntsc2` produces the exact same output which doesn't make sense to me at all. In test case `ntsc2`, I am using opposite values of the LOL bit compared to `ntsc1`.

**Comment by dirkwhoffmann** [comment]
> BTW here's a super quick test program (modified showregs) that switches between PAL and NTSC mode every second using BEAMCON0:
[ntscswitch.zip](https://github.com/dirkwhoffmann/vAmiga/files/8794089/ntscswitch.zip)

Result on my A500. Switching works as expected: 
<img width="987" alt="Bildschirmfoto 2022-06-03 um 10 33 38" src="https://user-images.githubusercontent.com/12561945/171819277-acd1c7c0-420f-407e-8186-5e844166c112.png">

<img width="987" alt="Bildschirmfoto 2022-06-03 um 10 33 14" src="https://user-images.githubusercontent.com/12561945/171819305-55ff92ef-c4bf-485f-9b9a-ac4b4feae73c.png">

**Comment by mras0** [comment]
Quick comment: Looks like you're enabling the VBlank interrupt without overriding the KS handler (not sure if that matters), and also note [this](https://eab.abime.net/showpost.php?p=1500097&postcount=256) post by Toni in the undocumented HW thread:

>  Very tiny and quite useless undocumented feature: ECS/AGA VPOSW LOL bit (NTSC Long Line) can't be set to 1. LOL bit is always cleared when VPOSW is accessed.

**Comment by dirkwhoffmann** [comment]
> Very tiny and quite useless undocumented feature: ECS/AGA VPOSW LOL bit (NTSC Long Line) can't be set to 1. LOL bit is always cleared when VPOSW is accessed.

Ah, OK, great! This explains everything.

**Comment by dirkwhoffmann** [comment]
`ntsc0` looks like this at the moment:

<img width="987" alt="Bildschirmfoto 2022-06-03 um 16 12 36" src="https://user-images.githubusercontent.com/12561945/171872748-7549bf4a-7118-4abe-b647-a6dbf5c1a78f.png">

It's not perfect as can be seen in the DMA debugger: 

<img width="987" alt="Bildschirmfoto 2022-06-03 um 16 12 51" src="https://user-images.githubusercontent.com/12561945/171872889-3a5d5706-111a-40a3-abcd-3f7bad31f5b9.png">

In long lines, the first refresh cycles moves from $E2 to $E3. As there are no pixels for this position in the texture, the first red line (first memory refresh cycle) appears dotted. 

Although not perfect, I plan to keep the current implementation for now because I don't want to spend too much time on a hardly used mode.  Most basic stuff is working though. I.e., the PAL bit in `BEAMCON0` is supported (`ntscswitch.adf` is working correctly in vAmiga now) and the `LOLDIS` bit is supported, too. In `BEAMCON0`, if `LOLDIS` equals 1 and `PAL` equals 0, the Amiga runs every line like a PAL line (short line) but terminates the frame early (NTSC frame). There is a new test for this (`ntsc5`) which is passed by vAmiga.
