### ISSUE TITLE
3.2.1 ROM (47.102) is marked as "Unknown or patched ROM"

### ISSUE THREAD

**Issue by nicolasbauw** [dirkwhoffmann/vAmiga#701]
With the updated ROM from the free update.
The 3.2 (47.96) reads "Kickstart 3.2 (Hyperion)" as expected.

**Comment by dirkwhoffmann** [comment]
Thanks for reporting! Could you post the CRC hash for the 3.2.1 Rom (it is displayed in the Rom dialog)? I can then add it to the database.

**Comment by nicolasbauw** [comment]
Sure ! here it is:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/37193744/170766342-3e64746e-e86d-4294-9a9b-9cf0ca808045.png">

**Comment by nicolasbauw** [comment]
Note : the update is 3.2.1, but the ROM is still labeled as 3.2:
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/37193744/170768791-fd2ac57f-cc4b-4604-a796-21b83d622067.png">

**Comment by dirkwhoffmann** [comment]
Fixed in v2.1b2
