### ISSUE TITLE
Download of 2.01 is corrupt

### ISSUE THREAD

**Issue by BrutalSoloH** [dirkwhoffmann/vAmiga#702]
I've tried multiple downloads of the 2.01 release, but MacOS complains it's damaged. 
The newer beta downloads are in good condition.

**Comment by dirkwhoffmann** [comment]
Can you provide a screenshot? What exactly does macOS complain? I can't reproduce anything like that on my machine.

**Comment by BrutalSoloH** [comment]
Hi Dirk,

Superb app you wrote, concrats.

I tried today and now I have no problems.. Perhaps it was a hosting problem which corrupted the downloa?. But weirdly enough the zip file was not corrupt, only the .app. 
I had the problem yesterday.

Greetings
Maarten Spoek aka SoloH

**Comment by dirkwhoffmann** [comment]
Closed as there is nothing to do at the moment.
