### ISSUE TITLE
The settlers map size 

### ISSUE THREAD

**Issue by Vweber73** [dirkwhoffmann/vAmiga#704]
The Settlers cannot have map size > 5 (max being 8), unless you have all 3 together:
-Hard disk (ok in vAmiga)
-1Mb chip and 4mb fast ram (ok in vAmiga)
-68030 or higher (68020 gives only map 7). Although vAmiga has the capacity to deal with the required speed with overclocking, the game does not see it as such, since only 68000 is reported. Without going into full 68020 emulation, which I understand is complex and that even WinUAE does not do 100% properly, would it be possible to change the chip id when overclocking, to fool the game into believing that it has a 68030 or 40 ? would this work, or would the game  then use specific 68020+ instructions that would then crash the emulation ?

**Comment by dirkwhoffmann** [comment]
Right now, I have no plans to support the MC68020. Anyway, I would have to add support for the MC68010 first (which I plan to do eventually).

**Comment by Vweber73** [comment]
I understand that. I was more talking about fooling the game by optionnally changing the processor identification bits and make it believe than an overcloked 68000 is a 68030. This of course would only work if the game relies only on the extra speed and not on specific 030 instructions, which would obviously crash the emulation. I am not sure what Settlers is doing once it detects a higher processor... Is the code 68K compatible or 020 specific ?

**Comment by emoon** [comment]
Another way would be to simply patch the settlers exe to return a higher value when the detection code is running and see if that works.

**Comment by dirkwhoffmann** [comment]
>  I was more talking about fooling the game

I don't know for sure what instructions are required by Settlers, but I don't like the idea of fooling the game. If vAmiga pretended to emulate an 68020, it might work for Settlers, but lots of other programs would crash.

**Comment by Vweber73** [comment]
That's why I said "optionally". An option to use at your own risk ! :)
