### ISSUE TITLE
Hunk parser errors out

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#707]
When analysing [kyrios.exe.zip](https://github.com/dirkwhoffmann/vAmiga/files/8854074/kyrios.exe.zip) my hunk parser throws an `ERROR_HUNK_UNSUPPORTED` exception. It happens after a hunk of type `BREAK` is parsed. 

The `BREAK` hunk appears here (red arrow):

<img width="1002" alt="Bildschirmfoto 2022-06-07 um 16 27 56" src="https://user-images.githubusercontent.com/12561945/172407436-181abf38-a20d-4c35-a610-0d619146f1d3.png">

At the moment, I can't interpret the data marked with the blue arrow. I.e., I can't figure out where the next hunk starts.

**Comment by mras0** [comment]
It's an overlay file. A good description about them is here: http://aminet.net/package/docs/misc/Overlay

From the guru book:
> This block [HUNK_BREAK] signifies the end of an overlay node and thus corresponds to the end of file
(EOF) for load modules without overlays

I haven't bothered supporting them properly in my tooling as they're most commonly used with crunched executables (where a normal disassembly isn't that useful anyway).

**Comment by dirkwhoffmann** [comment]
> A good description of them is here:

Great document. Thanks! 

It seems like I have to handle a `HUNK_BREAK` sections exactly the same as a `HUNK_END`section in my code. With this code change, my hunk parser does no longer complain.
