### ISSUE TITLE
Interrupts/inttim/doubleXX: OCS / ECS difference

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#711]
I've written some more tests to track down #709 and #643: `double0` - `double20`.

The good: Tests `double11` - `double20` all expose the OCS / ECS difference we are looking for.
The bad: I still have no clue what's causing the difference. 

`double12` on A500 OCS: 

![double12_A500_OCS](https://user-images.githubusercontent.com/12561945/173240537-20dbb39a-0aec-40d1-b03f-65157e42a8f4.JPG)

Same test on A500 ECS:

![double12_A500_ECS](https://user-images.githubusercontent.com/12561945/173240548-cd8fd696-a4fa-405e-9cab-d79bb004ef7b.JPG)

**Comment by mras0** [comment]
Just a suggestion, but it might be a good idea if the test case could be reduced as much as possible. E.g. copper blocks 1 and 2 look like they're not needed (but it's hard to see). Some simple "bisection" method of removing code/parts of copperlist could be useful.

Also your current "syncpu" method makes it quite hard to reason about exact cycle counts. Maybe we could devise a way to use "STOP" w/ VERTB interrupt to make it easier? (caveat: I saw Toni recently reworked STOP handling in WinUAE, but as long as it's predictable on real HW it shouldn't be an issue).

**Comment by dirkwhoffmann** [comment]
> E.g. copper blocks 1 and 2 look like they're not needed

The main problem is that the phenomenon is hard to reproduce. Some specific CPU cycle has to interfere with something else to produce the difference. Whenever I tried to simplify one of my tests, the OCS / ECS went away. 

The most simple test is still `timcpu2`. There is a difference in line 9 of the second block:

![cputest2](https://user-images.githubusercontent.com/12561945/173245989-df6e5d7f-8598-4311-a5db-dc3ddc13e30f.jpg)

Luckily, the orange line indicates that the CPU is at the same position in the OCS and the ECS machine. Hence, the difference must be caused by something happening between the two marked locations. The best way to debug it further would be to record the scanline with a logic analyzer. Unfortunately, I don't have such a device.

**Comment by dirkwhoffmann** [comment]
This issue needs to be solved. Hence, I am thinking about buying this logic analyzer: 

https://www.amazon.de/dp/B07W54MF5H/ref=sspa_dk_detail_1?pd_rd_i=B07D35FNYL&pd_rd_w=OvSIQ&content-id=amzn1.sym.6cf54639-a6a7-4e9c-83cd-9d370a7d6ef0&pf_rd_p=6cf54639-a6a7-4e9c-83cd-9d370a7d6ef0&pf_rd_r=84G9B04XN7AHHTSGHY9V&pd_rd_wg=6b3uz&pd_rd_r=924ede35-99a7-42fc-b628-71c7496f7a9e&s=automotive&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyOFE5VVNUSkRSUUZFJmVuY3J5cHRlZElkPUEwNTk4NjYzUU04UVlFWk5LODY5JmVuY3J5cHRlZEFkSWQ9QTA1NzMyMjAzSEdSME1ENUVEMFVTJndpZGdldE5hbWU9c3BfZGV0YWlsX3RoZW1hdGljJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ&th=1

It has 32 channels and a voltage threshold ranging from -4V to 4V. As far as I can see, this should be fine for analysing the Amiga. Or am I missing something important here?

**Comment by mras0** [comment]
I don't know about the EE part, but isn't amiga logic still 5V TTL? (i.e. above the ~4V listed, absolutely not sure, so check). Here's an EAB thread where Toni posted what he got: https://eab.abime.net/showpost.php?p=1471191&postcount=27. Ignoring cost 32 channels seems like the minimum you'd want (bus+data though 8-9 is probably fine for RGA bus so you still have spares), and 2x would also be nice so you didn't have to move them from OCS to ECS machine...

**Comment by dirkwhoffmann** [comment]
> Here's an EAB thread where Toni posted what he got

Thanks! That was very helpful. I did a quick comparison of the software of both devices. I would say that both aren't master pieces of good UX design, but the DSLogic software seems to be much better in terms of configurability (@tonioni's screenshot is quite impressive where custom registers are shown by names). Therefore, I've ordered the DSLogic. Let's see how long it takes to ship here. I had to order it from Amazon US because it's not directly available in Germany.

**Comment by HarjitSi** [comment]
The original logic analyzer had an input range of +/- 50V and the trigger threshold range of +/-4V (as Dirk mentioned). So, it should have been fine for the Amiga's 5V signals...

On Jun 12, 2022 10:45 PM, Dirk Hoffmann ***@***.***> wrote:

Here's an EAB thread where Toni posted what he got

Thanks! That was very helpful. I did a quick comparison of the software of both devices. I would say that both aren't master pieces of good UX design, but the DSLogic software seems to be much better in terms of configurability ***@***.***<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftonioni&data=05%7C01%7C%7C2d5e1915406848e2686608da4cffdd9f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637906959062927130%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3L%2Bk8cxn339hwu1rlzHnWJShlIGZAn06eTv2%2BUZVvIc%3D&reserved=0>'s screenshot is quite impressive where custom registers are shown by names). Therefore, I've ordered the DSLogic. Let's see how long it takes to ship here. I had to order it from Amazon US because it's not directly available in Germany.

**Comment by tonioni** [comment]
Are both bugs also happening when using 100% plain A500? (not even ACA500[plus] connected, cloaking mode does not count as disconnected)

**Comment by dirkwhoffmann** [comment]
> Are both bugs also happening when using 100% plain A500?

Yes, both machines are plain A500s (the ACA500+ is connected to a third machine). What I didn't check is the memory configuration (alI I can say at the moment is that none of them has FastRam installed).

**Comment by dirkwhoffmann** [comment]
Another parcel has been delivered. My new super weapon is here 😎: 

![Unknown-8](https://user-images.githubusercontent.com/12561945/174329141-e986a488-3f14-4155-9a1d-556642e07605.jpeg)

Sorry, wrong image. Here it is:

![IMG_2974](https://user-images.githubusercontent.com/12561945/174327426-672ab700-e02c-476b-a500-828d4a3ab705.JPG)

Just done a brief experiment to see if it works...

![IMG_2975](https://user-images.githubusercontent.com/12561945/174327667-0de0fc84-2546-476e-bc86-899913b0cd0f.JPG)

Red is the 7MHz clock, brown is the E-clock. Grey and orange are two of the three IPL pins.

Now, I need to get familiar with the software...

**Comment by dirkwhoffmann** [comment]
Here is my plan for tomorrow:

- Patch test `cputim2` by letting the Copper write into `NOOP` ($1FE) at the end of the suspicious scanline. Once this is done, I can use the write to `NOOP` as my trigger condition for the logic analyzer.

- Select some meaningful signals to record. My current setup looks as follows:

![IMG_2976](https://user-images.githubusercontent.com/12561945/174346080-78790013-16eb-42d1-b58c-a3576af63908.JPG)

- This grabs
    - CLK and the IPL pins from the CPU
    - The RGA bus from Paula

Are there any other signals I should record?

**Comment by mras0** [comment]
As usual take it with a grain of salt (like my wrong reading of the spec for the alternative probe), but the more the better if you're going to compare with another board. Thinking something like CPU.{A1,[A2,]DTACK} might help with correlating instructions + AGNUS.DBR (for interaction).

**Comment by dirkwhoffmann** [comment]
Running test case `cputim2` on my ECS A500 with an advanced logic analyser setup: 

![IMG_2977](https://user-images.githubusercontent.com/12561945/174396718-560f15b3-3b76-4629-84ae-835555333629.JPG)

Interestingly, the image is different now 🙈: 

![IMG_2978](https://user-images.githubusercontent.com/12561945/174396922-b9665fdc-fb07-483f-8e6b-0d9cfd7abf86.JPG)

So either a) I am doing something completely stupid or b) attaching the logic analyser alters the result. In the latter case, everything might be caused by some subtle race condition on some line. Of course, a) is always an option...

**Comment by dirkwhoffmann** [comment]
Update: I've removed the probes step by step.

- Removing probes from address and data bus: No effect
- Removing probes from DTACK, R/W etc.: No effect
- Removing probes from IPL pins: Image is back to normal

![IMG_2979](https://user-images.githubusercontent.com/12561945/174425067-0ee99e9c-6ff0-47c3-8599-eac8863aa4cd.JPG)

Remaining probes:

![IMG_2980](https://user-images.githubusercontent.com/12561945/174425070-d01b5e9c-acbe-45e9-9dc9-801814de3aa3.JPG)

Hence, I think we're dealing with a race condition on the IPL lines here.

**Comment by emoon** [comment]
Someone that knows electronics made this comment an the above:
```
probe loading on the inputs will cause a edge rate difference and delay
its probably coming in a clock later
poor metastate implementation
```

**Comment by tonioni** [comment]
I notied same, at least when aca500plus was also connected that IPL measurement affects IPL timing slightly. Paula probably is not strong enough to pull it down as quickly as without extra hardware.

Difference between models: probably 3 possible options: CPU was manufactured with different process (check Motorola identifier and manufacturer date on top of the CPU), Paula is different (unlikely) or rev3 has different IPL line pullup resistors. (or one of them have changed values).

**Comment by dirkwhoffmann** [comment]
>  CPU was manufactured with different process

I've replaced the CPU a couple of days ago which had no effect. I'll try to replace Paula, too. I've noticed that my Rev. 3 machine has a Paula chip manufactured by MOS whereas all other machines are equipped with one from CSG (which is the same company though).

**Comment by tonioni** [comment]
Try measuring resistance between each IPL line and +5v. Perhaps one of pull up resistors have changed value or something.

btw, do you want my RGA bus register name decoder code? It is nothing special but writing one can be boring..

**Comment by dirkwhoffmann** [comment]
> btw, do you want my RGA bus register name decoder code?

Based on your comments on EAB, I've already patched the `parallel` decoder in a similar way:
[chipset.zip](https://github.com/dirkwhoffmann/vAmiga/files/8957371/chipset.zip)
 
However, I'm not sure if I did it the way it is supposed to be done (I never coded in Python before). Without knowing better, I added an array 

```
regs = {
        0x000: "BLTDDAT",
        0x002: "DMACONR",
        0x004: "VPOSR",
        0x006: "VHPOSR",
        0x008: "DSKDATR",
        ...
```

and replaced this line

    self.putb([0, [self.fmt_item.format(self.saved_item)]])

by that: 

    self.putb([0, [self.regs.get(2*self.saved_item, "???")]])

Maybe your solution is more sophisticated. In that case I'd be happy to toss mine and replace it with yours.

**Comment by dirkwhoffmann** [comment]
I've replaced the Rev. 3 board in my OCS test machine by the Rev. 5 board. I'm closing the issue for now because I think it's not worth to debug it further at the moment.
