### ISSUE TITLE
Crash in Lazy Bones - Move Any Mountain

### ISSUE THREAD

**Issue by mras0** [dirkwhoffmann/vAmiga#712]
Old troublemaker. [pouet link](https://www.pouet.net/prod.php?which=61074). [EAB post](https://eab.abime.net/showpost.php?s=5c7e2d428ad68ceca20011098abefe73&p=417761&postcount=4)

Using CONFIG_A500_ECS_1MB + 512K CHIP + 512K slow I get an access violation in `Memory::poke16 <ACCESSOR_AGNUS, MEM_SLOW>` with `addr = 0x00096000` from `Agnus::doBlitterDmaWrite` early on. Tested with latest latest HEAD (45099e77c5beeb99a372f7c1d838af42a42bea03) in vAmigaSDL.

FWIW it seems to work in vAmigaWeb so maybe it's a new thing (or just doesn't show up in the javascript version). As expected it misbehaves with CONFIG_A500_OCS_1MB (but doesn't crash).

ADF (Note: turn down the volume on your speakers for the start)
[MoveAnyMountain.zip](https://github.com/dirkwhoffmann/vAmiga/files/8922437/MoveAnyMountain.zip)

**Comment by dirkwhoffmann** [comment]
Fixed. I introduced this bug when I added the option to support 1.5MB SlowRam. Since this value is not a power of two, I had to change my old code which used an AND mask to clamp addresses. Obviously, I did not test my changes thoroughly.

**Comment by dirkwhoffmann** [comment]
Fixed in v2.1b3.
