### ISSUE TITLE
FFmpeg not working

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/vAmiga#716]
I can't get ffmpeg to work.
Version 5.0.1 is installed on my iMac Retina 4K 2017 (macOS 12.4):

<img width="1002" alt="Schermata 2022-07-10 alle 17 54 07" src="https://user-images.githubusercontent.com/45571833/178152420-a6762897-0596-4932-b9db-851a5a788e98.png">

But vAmiga (v 2.01) not see it 🤔

<img width="758" alt="Schermata 2022-07-10 alle 17 54 32" src="https://user-images.githubusercontent.com/45571833/178152581-cc63e40f-2696-4fc7-bd47-1118db08a67d.png">

It worked until some versions ago 🫤

**Comment by Gianmarco72** [comment]
🫤

**Comment by dirkwhoffmann** [comment]
Fixed in v2.1b5
