### ISSUE TITLE
Kickstart 40.63

### ISSUE THREAD

**Issue by polluks** [dirkwhoffmann/vAmiga#718]
My image is not recognised.
Is there any option to bypass the check?

**Comment by dirkwhoffmann** [comment]
There are multiple 40.63 images around. vAmiga recognizes the following:

Kickstart v3.1 rev 40.63 (1993)(Commodore)(A500-A600-A2000)[!].rom

It's the one with this header signature: `0x11, 0x14, 0x4E, 0xF9, 0x00, 0xF8, 0x00`

<img width="641" alt="Bildschirmfoto 2022-07-18 um 20 21 51" src="https://user-images.githubusercontent.com/12561945/179577616-fd3dc62b-2d05-48a6-a168-a3b3eacdd872.png">

However, it doesn't seem to work any more. It's broken in v2.1b4:

<img width="912" alt="Bildschirmfoto 2022-07-18 um 20 20 13" src="https://user-images.githubusercontent.com/12561945/179577638-17c4edda-4de7-48e1-91cb-a81b3d519b1e.png">

It works in v2.01. Needs investigation...

**Comment by dirkwhoffmann** [comment]
Update: There are two other variants I know about: 

`Kickstart v3.1 rev 40.63 (1993)(Commodore)(A500-A600-A2000).rom`
`Kickstart v3.1 rev 40.63 (1993)(Commodore)(A500-A600-A2000)[b].rom`

The first one has CRC `88136ca9` and seems to be broken. The second one has an unusual file size (524293 instead of 524288) and is rejected because of this reason.

**Comment by polluks** [comment]
My ROM
`MD5 (Kickstart v3.1 rev 40.63 (1993)(Commodore)(A500-A600-A2000).rom) = 0b839c665635a249c5736118c68a69a7`
`00000000: 1116 4ef9 0020 00d2 0000 ffff 0028 0044  ..N.. .......(.D`

**Comment by dirkwhoffmann** [comment]
> MD5 = 0b839c665635a249c5736118c68a69a7

Yes, that's the one which I suppose is broken. Have out tried this Rom in UAE? In my UAE installation, I get a green screen of death. Of course there is always the chance that I was using an incompatible hardware configuration.

**Comment by dirkwhoffmann** [comment]
BTW, Cloanto has a [nice page](https://cloanto.com/amiga/roms) summarizing various Roms. Your Rom is listed as:

`V. 3.1 | Dec 1993 | 40.068 | ReCode |   | 524288 | 200000 | 68000 | A600 | Developer | Confirmed as hack of 8ECED804 by Rodney Hester`

Clicking on 'Details' reveals: 

```
The following bytes were changed from the original ROM (checksum AE733766):
0000008C-0000008D: Changed spaces after "3.1 ROM" to NULLs (why?)
00000511-00000513: Changed to 0x27FF0A (jump to cache clear code?)
000035DC-000035DD: Changed to 0x4A2E to disable beta alert
         0004D765: Changed to 0xEB to activate NoClick
0007F639-0007F663: Changed Workbench title to "OS 3.1   %lD graphics mem  %lD other mem   "
0007FF00-0007FF4B: Inserted the following block of code (clear caches?):

4C DF 41 01 4E F9 00 20 0A 90 48 E7 80 82 2C 78
00 04 08 2E 00 00 01 29 67 E6 20 6F 00 0E 30 10
02 40 FF C0 0C 40 40 C0 66 D6 00 10 00 02 08 2E
00 01 01 29 67 10 4E 7B 88 02 4E 7A 00 02 08 C0
00 02 4E 7B 00 02 4C DF 41 01 4E 73

0007FFE8-0007FFEB: Changed ROM checksum to DB4247E0
```

Interestingly, the Cloanto page also provides some screenshots for this Rom which means that it has to work somehow. The next step should be to find a working hardware configuration in UAE.

**Comment by mras0** [comment]
Note that it's a ReKick (ReCode) image meant to be loaded into fast ram. ($1116 identifier and $002000d2  starting address)

**Comment by dirkwhoffmann** [comment]
> Note that it's a ReKick

Interesting (never heard about that before).

I've a done  a quick experiment and added a Rom mirror where the Rom is supposed to reside:

<img width="980" alt="Bildschirmfoto 2022-07-19 um 16 55 06" src="https://user-images.githubusercontent.com/12561945/179781559-76652d3a-372b-4d74-8adf-85362f3ae53b.png">

Kickstart starts executing, but ends up in a green screen (which means the memory test fails). 

<img width="980" alt="Bildschirmfoto 2022-07-19 um 16 44 31" src="https://user-images.githubusercontent.com/12561945/179779818-1a1800b4-345e-4f6d-b82b-b1149812ce12.png">

I still need to check why it fails...

**Comment by mras0** [comment]
Looks like it expects OVL to be cleared in ciaapra (i.e. memory visible at $0). First thing it does is write exceptions vectors and check if they were written correctly. I don't know if it makes other assumptions about the system state that are not normally true after reset.

**Comment by dirkwhoffmann** [comment]
> Looks like it expects OVL to be cleared in ciaapra 

Yes, I have stepped through the first instructions and noticed this, too. I guess the Rom relies on a couple of initializations that would be carried out by the standard Rom in a normal setup (Original Rom at $F80000 and ReKick at $200000).

**Comment by dirkwhoffmann** [comment]
I think it's best to let vAmiga recognize ReKick images and inform the user that they won't work the same way as ordinary Roms: 

<img width="641" alt="Bildschirmfoto 2022-07-19 um 21 50 14" src="https://user-images.githubusercontent.com/12561945/179836499-ab39fbbf-9939-42bb-a8d8-8a8724192c7e.png">

**Comment by dirkwhoffmann** [comment]
#723 is a follow-up to this issue (ECS Denise graphics bug).
