### ISSUE TITLE
Custom Kickstarts

### ISSUE THREAD

**Issue by polluks** [dirkwhoffmann/vAmiga#720]
How about support of http://aminet.net/package/misc/emu/UAEQLKickROM?

**Comment by dirkwhoffmann** [comment]
I think it requires a 68020+ CPU. Won't work in vAmiga.

**Comment by dirkwhoffmann** [comment]
I've watched [this video](https://www.youtube.com/watch?v=olHIeWHg3Aw) about QDOS classic. In the video, it is run in a very old version of UAE using a 68000 CPU. It also shows that it does no longer run in later UAE versions. I guess the QDOS authors developed the Rom in UAE and accidentally relied on emulator bugs that have been ruled out later.

**Comment by dirkwhoffmann** [comment]
I am closing this issue because there is nothing to do at the moment. Fell free to reopen when a version of UAEQ comes up which works with latest UAE.

**Comment by polluks2** [comment]
Well, this ROM works on real [Q40 hardware](https://en.wikipedia.org/wiki/Q40_(motherboard)), why should it depend on emulator bugs?

**Comment by polluks** [comment]
Well, this ROM works on real [Q40 hardware](https://en.wikipedia.org/wiki/Q40_(motherboard)), why should it depend on emulator bugs?

**Comment by dirkwhoffmann** [comment]
What I mean is that I didn't manage to run the Rom in UAE. I need to know a UAE configuration which is compatible with the Rom. At the moment, I do not even know if a 68020, 030, or later CPU is required.
