### ISSUE TITLE
Red line blinking under ROM credits + saving machine issues ?

### ISSUE THREAD

**Issue by nicolasbauw** [dirkwhoffmann/vAmiga#721]
It seems my config file becomes corrupted (vAmiga says so - see screenshot below. Usually I just click on "use as default" on every single tab, but I wanted to try a specific A600 config file).
Note 1 : I saved the config file manually (Machine-> Save as) juste before quitting. When quitting, vAmiga asked a confirmation, saying machine was changed (I did not change anything since the save). After quitting, and reloading the config file, I had the message.
Note 2 : on this machine, I have 2.01 and 2.1b4. Maybe that could be a problem. I was using 2.1b4 during all the test.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/37193744/180464478-7aa52ffd-f55f-40ac-bb07-4c5d667a7afd.png">

With that happening, and amiga not booting, I noticed something:
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/37193744/180461982-cbc2c2a3-c9d6-46cf-a39e-111d1de2e999.png">

A red line "dancing" under the animated floppy. That does not happen when the chipset is OCS, from what I've seen.

EDIT: with 2.01, attached drives are kept in the "untitled" machine. With 2.1b4, I have to attach them each time. I did not observe this behavior on my other mac (wich has only 2.1b4 installed). So, it is very possible there is something happening when both versions are present.

**Comment by dirkwhoffmann** [comment]
Thanks for reporting!

> on this machine, I have 2.01 and 2.1b4. Maybe that could be a problem

Yes. Snapshots are not compatible between different versions. Normally, there is a version check that should display a message telling the user that the snapshot cannot be loaded. I guess I have changed the snapshot format without modifying the version signature in the snapshot header. When this happens, the "inconsistent state" error occurs. 

The dancing red line is a bug in the ECS Denise implementation. I've opened up a new issue for it (#723).
