### ISSUE TITLE
Settings issue

### ISSUE THREAD

**Issue by lauren7ino** [dirkwhoffmann/vAmiga#722]
Hi
Greetings from Portugal, sorry the basic English.
I've been testing vAmiga for the last hour.
It seem to be in the new beta 4 all the Settings=>Controls=>Emulation Keys/Disconnect keys from keyboard is non functional. Can't be reprogrammed and can't be saved.
Thanks, keep up the good work!

**Comment by dirkwhoffmann** [comment]
Confirmed. For some reason, the checkbox button had no outlet any more. I've already checked in a fix.  

Thanks for reporting! Those bugs are the the ones that are supposed to be catched in beta releases.

**Comment by lauren7ino** [comment]
👍🏼
And the joystick keyboard emulation?

**Comment by dirkwhoffmann** [comment]
I think it's fixed in v2.1b5. Can you give it a try? Please reopen if there are still issues.
