### ISSUE TITLE
Add support for 68010 and 68020

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#728]
Recently, I had another look at the Musashi core and noticed that supporting the 68010 and 68020 isn't as difficult as I originally thought. As a starting point, I've decided to add a 68010 and 68020 mode to Moira that tries to replicate Musashi to 100%. This worked quite well and I'm already able to run Sysinfo in vAmiga: 

<img width="932" alt="Bildschirmfoto 2022-08-13 um 10 16 06" src="https://user-images.githubusercontent.com/12561945/184475894-8ee67700-d11a-4633-a480-14c00c958caf.png">

As already stated, this is only a starting point. A lot of stuff is missing (the 68020 deals with all kinds of different stack frames, has multiple trace modes etc.). All these features are not emulated yet.

**Comment by Alessandro1970** [comment]
Great! 
…so il could be added the 68882 with 68020 ✌🏻

**Comment by Vweber73** [comment]
Hi,

Excellent news,  thanks!

1. I tried it with The Settlers and it works fine,  68020 reported.  Now map size can be up to 7 (against 5 for 68000). The absolute max (size 8) would need a 68030. Is 030 planned as well?
2. I tried Dungeon Master II,  which is one of these very few games marked as AGA but actually don't need AGA,  just a 68020, so a good test case (actually the only one I know). It starts working,  then freezes,  it seems that it eats up a lot of ressources,  the UI becomes very slow until you restart vAmigaWeb.  It is using one of these net yet implemented 020 features?

Cheers

**Comment by dirkwhoffmann** [comment]
>  It is using one of these net yet implemented 020 features?

I don't know yet. Which DM2 version did you use (please don't upload the game, just the exact filename)? Does it boot from floppy disk? I'm asking, because I found a version that needs to be installed on HD.

**Comment by Vweber73** [comment]
I'm using the hdf version which I found here:
https://www.planetemu.net/rom/commodore-amiga-hardfiles-hdf/dungeon-master-ii-1994-interplay-aga

**Comment by mithrendal** [comment]
I tried it and it actually works ... 

<img width="959" alt="image" src="https://user-images.githubusercontent.com/17108995/184697106-d2f1a644-b57d-448c-8445-5420b7c0cd16.png">


but it does floods the console with thousands of log output ... seems as if every cpu instruction is logged ...

```
execBitFieldEa(137,5,4,e9eb)
(Index):876 execExtb(155,0,4,49c3)
(Index):876 execBitFieldEa(137,5,4,e9eb)
(Index):876 execExtb(155,0,4,49c3)
(Index):876 execBitFieldEa(137,5,4,e9eb)
(Index):876 execExtb(155,0,4,49c3)
2(Index):876 execBitFieldEa(137,5,4,e9eb)
4(Index):876 execBitFieldEa(137,5,4,e9e8)

...
```
thats why it seems to freeze

**Comment by dirkwhoffmann** [comment]
> the line which is responsible for that logging is here I guess

Yes. This is a debug statement which gets active if a 68020-only instruction is executed. It's only meant to be used during debugging.

**Comment by Vweber73** [comment]
Yeah! I had the console still on,  I switched it off and now it is working fine! So it seems that this 020 emulation is quite complete and reliable after all? I think the main item is the bitfields instructions?

It also seems that The Settlers detect the processor type but doesn't use extra instructions,  otherwise it would have lagged as well when I tried?

**Comment by Vweber73** [comment]
When I wrote that it worked fine...  I hadn't switched the sound on.  Now I have done it,  and it is pretty sluggish.  I guess that the system is still slowed on with this logging even though I turned the console off!?

**Comment by mithrendal** [comment]
if you turn debugging console off reduces maybe the slow down a bit, but that extensive logging will still happen in background so, maybe I better will comment that printf statment out ...

@dirkwhoffmann what is the proper way to remove the logging ? maybe  some config setting e.g. in [MoiraConfig.h](https://github.com/dirkwhoffmann/vAmiga/blob/master/Emulator/CPU/Moira/MoiraConfig.h)?

**Comment by dirkwhoffmann** [comment]
> I guess that the system is still slowed on with this logging even though I turned the console off!?

Yes, the logging statement has to be removed. It's a performance killer.

> It also seems that The Settlers detects the processor type but doesn't use extra instructions

True. I think it simply uses the CPU modes as an estimate for overall system performance

**Comment by dirkwhoffmann** [comment]
> @dirkwhoffmann what is the proper way to remove the logging ? maybe some config setting e.g. in [MoiraConfig.h](https://github.com/dirkwhoffmann/vAmiga/blob/master/Emulator/CPU/Moira/MoiraConfig.h)?

Change the code to 

```
// if constexpr ((cpu) == M68020) { printf("%s(%d,%d,%d,%x)\n", __func__, I, M, S, opcode); }

#define AVAILABILITY(cpu) \
if constexpr (WILL_EXECUTE) willExecute(__func__, I, M, S, opcode); \
assert(C >= (cpu)); \
if constexpr (C == M68020) cp = 0;
```

**Comment by Vweber73** [comment]
I understand that the only differences between the 020 and 030 are not in the instruction set but in the MMU which is not useful in emulation,  and data cache + burst mode which probably add nothing much in performance either in emulation,  so could it be possible to have a 030 setting that would be identical to the 020 emulation save for the identification bits? So that Settlers can have map size to 8...

**Comment by mras0** [comment]
[Roots 2.0 by Sanity](https://www.pouet.net/prod.php?which=3251) is another good test case for 020 without AGA (requires ECS).

**Comment by Vweber73** [comment]
> [Roots 2.0 by Sanity](https://www.pouet.net/prod.php?which=3251) is another good test case for 020 without AGA (requires ECS).

Excellent stuff,  thanks! Seems to work quite well.  Except that after the credits the screen goes black and you only have the music...  Is it normal? Or maybe the start of the AGA part?

**Comment by dirkwhoffmann** [comment]
Brief update: 
- vAmiga passes all  68000, 68010, and 68020 tests from the [`SIMPLE`](https://github.com/dirkwhoffmann/vAmigaTS/blob/master/cputester/HDF/simple.hdf) test suite now.

Next steps:
- Merge changes back to the Moira repo and fix Musashi compatibility mode (which is obviously broken now).
- Generate more sophisticated test cases with cputester.
