### ISSUE TITLE
Sprite bug in Elfmania

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#750]
Reported by @chris70c: Colors of the player sprite are wrong and part of the score and health bar are missing.

![image](https://user-images.githubusercontent.com/12561945/201533624-05f36426-d919-415b-981d-bc60827952b4.png)

X-ray: 

<img width="943" alt="Bildschirm­foto 2022-11-13 um 17 43 51" src="https://user-images.githubusercontent.com/12561945/201533682-0d6114ca-b655-412e-9cf8-1443ad934a4a.png">

**Comment by dirkwhoffmann** [comment]
The Copper list reveals what I've expected: Sprites are created on-the-fly by the Copper.  Hence, it's most likely a sprite register timing issue.

<img width="980" alt="Bildschirm­foto 2022-11-13 um 21 05 57" src="https://user-images.githubusercontent.com/12561945/201542136-c95bdc27-7ac2-417a-afc8-5aa33e8c24fc.png">

TODO: 
- Check if the test repo already contains proper timing tests.
- Improve the tests or write new ones.

**Comment by mras0** [comment]
Probably related to [this comment](https://github.com/tonioni/WinUAE/blob/08bfaa8a9dc930aad5a9f64b14ffaa877f03133b/custom.cpp#L8867) in WinUAE:

> SPRxDATA and SPRxDATB is moved to shift register when SPRxPOS matches.
>  When copper writes to SPRxDATx exactly when SPRxPOS matches:
>  - If sprite low x bit (SPRCTL bit 0) is not set, shift register copy
>    is done first (previously loaded SPRxDATx value is shown) and then
>    new SPRxDATx gets stored for future use.
>  - If sprite low x bit is set, new SPRxDATx is stored, then SPRxPOS
>    matches and value written to SPRxDATx is visible.
>  - Writing to SPRxPOS when SPRxPOS matches: shift register
>    copy is always done first, then new SPRxPOS value is stored
>    for future use. (SPRxCTL not tested)

Here's a small test that shows a difference for SPRxPOS:
[sprxpos.zip](https://github.com/dirkwhoffmann/vAmiga/files/10002077/sprxpos.zip). There should be a striped rgb pattern in the middle of the screen, but the screen is blank in vAmiga. As a hack you can add 1 to pos in Denise::pokeSPRxPOS to make it show up.

**Comment by dirkwhoffmann** [comment]
For reference: `sprxpos.exe` on my Amiga 500 (ECS, 68010): 

![IMG_4752](https://user-images.githubusercontent.com/12561945/201747560-c53b6279-7416-4d67-9afd-d4c63f6566f6.JPG)

**Comment by dirkwhoffmann** [comment]
Fixed. The error was due to what @mras0 expected: Timing of SPRxPOS.

<img width="943" alt="Bildschirm­foto 2022-11-15 um 17 40 54" src="https://user-images.githubusercontent.com/12561945/201976964-136a30b9-d099-482f-baaa-62e482d8861a.png">

<img width="943" alt="Bildschirm­foto 2022-11-15 um 17 41 12" src="https://user-images.githubusercontent.com/12561945/201976861-06f3ad86-dd25-46b3-b236-978950a3883e.png">

Relevant new regression tests for this issue:

    Denise/Sprites/timing/sprtimpos1
    Denise/Sprites/timing/sprtimctl1
    Denise/Sprites/timing/sprxpos

Test `sprtimctl1` has shown that timing of the SPRxCTL register needed the same adjustment.

There are two more new tests:

    Denise/Sprites/timing/sprtimdat1
    Denise/Sprites/timing/sprtimdat2

They show that SPRxDATA and SPRxDATB have no issues in the old and the new code.

**Comment by dirkwhoffmann** [comment]
Fixed in v2.2b1
