### ISSUE TITLE
Add light pen / light gun support

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#751]
Requested by @chris70c. A list of gun games for the Amiga can be found [here](https://en.wikipedia.org/wiki/List_of_gun_games#Commodore_Amiga).

**Comment by dirkwhoffmann** [comment]
If anybody knows about simple test programs such as light pen drivers, calibration tools, etc., please let me know. It's much easier to start with such programs than starting with games.

**Comment by mras0** [comment]
There's [this thing](http://aminet.net/package/util/sys/Lightpen) with source included on Aminet. It does something, but I've never used the lightpen emulation in WinUAE (or IRL for that matter), so I can't say if it's working as expected.

Do you have a lightpen for testing? Looks like C64 ones are compatible judging by http://wiki.icomp.de/wiki/DE-9_Lightpen In principle it shouldn't be hard get some code working according to [HRM](http://amigadev.elowar.com/read/ADCD_2.1/Hardware_Manual_guide/node0189.html), but I couldn't get a small test program I just tried (in WinUAE) to play ball.

**Comment by dirkwhoffmann** [comment]
> Do you have a lightpen for testing?

No, I don't. I agree that having one is a good idea, just to see what the expected outcome would be. Unfortunately, they won't work with TFTs.

**Comment by dirkwhoffmann** [comment]
I didn't find any option to enable light pen emulation in UAE. Anyways, I think it's not worth spending time on it. The value-to-effort ratio is too low.

**Comment by dirkwhoffmann** [comment]
Contributed by @chris70c:

![Untitled](https://user-images.githubusercontent.com/12561945/210183090-07671f49-b843-4aa4-94a8-d7f9ed6e0d61.png)
