### ISSUE TITLE
Kickstart Rom Extension

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#752]
What exactly is a Kickstart Rom Extension? Can you give a few examples?

**Comment by MatzeLoCal** [comment]
Maybe [this article](https://retrocomputing.stackexchange.com/questions/1208/extended-roms-on-the-amiga-cd32-and-cdtv) on stackexchange helps

**Comment by dirkwhoffmann** [comment]
vAmiga only supports extension Roms, because the Aros replacement needs them. They are not used for anything else at the moment.

**Comment by dirkwhoffmann** [comment]
This can be closed, right?

**Comment by bluecursor** [comment]
Yes

BlueCursor
www.imacommodork.com
Sent with OSX/iOS Spark!
