### ISSUE TITLE
Are 10.15 dependencies listed in #492 still accurate?

### ISSUE THREAD

**Issue by nekoniaow** [dirkwhoffmann/vAmiga#775]
My Mac is still running on Mojave (10.14) and for various reasons I will not be updating to more recent versions for a few more months so I was wondering if the 10.15 dependencies listed in https://github.com/dirkwhoffmann/vAmiga/issues/492 are still correct as I am considering adapting vAmiga to 10.14 so I can use it before I eventually upgrade to 10.15+?

Also, would such adaptations be desirable as a feature?

**Comment by dirkwhoffmann** [comment]
> so I was wondering if the 10.15 dependencies are still correct

Yes, both vAmiga and VirtualC64 list 10.15 as the minimal deployment target.

> Also, would such adaptations be desirable as a feature?

I don't want to support revision prior to 10.15, because it would bloat the code with various wrappers. I am using the C++ filesystem classes a lot which are not available in macOS prior to 10.15.
