### ISSUE TITLE
V2.3

### ISSUE THREAD

**Issue by maskred5** [dirkwhoffmann/vAmiga#782]
Playing Pools of Darkness, music is noticeably slower and hitting the keys/mouse to get past the intro, is unresponsive. 2.0 doesn't have these issues.

**Comment by dirkwhoffmann** [comment]
I've run the game with both v2.0 and v2.3, but I don't see a difference on my machine. Could you provide some more details about the used hardware configuration and the exact name of the ADF? Please don't post the ADF.
