### ISSUE TITLE
Game: rings around the world CRASH

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#786]
https://retream.itch.io/ring-around-the-world

Game crashes when encountering first beast. It crashes when trying to access the disk drive. Works fine on FS-UAE

**Comment by dirkwhoffmann** [comment]
Where do I encounter the first beast?

<img width="932" alt="Bildschirm­foto 2023-03-18 um 08 11 22" src="https://user-images.githubusercontent.com/12561945/226091024-dc451f96-9aae-4edb-bd4a-ae3031a6676a.png">

**Comment by bluecursor** [comment]
South on the beach

BlueCursor
www.imacommodork.com
Sent with OSX/iOS Spark!

**Comment by dirkwhoffmann** [comment]
Doesn't crash here: 

<img width="986" alt="Bildschirm­foto 2023-03-19 um 15 36 48" src="https://user-images.githubusercontent.com/12561945/226183160-e31568dd-2482-4988-a708-c4b34334a9a6.png">

**Comment by bluecursor** [comment]
don't know what to say then. It backs out to a workbench screen. I a tried wb 1.3 and wb 3.1 and i get the same results.

**Comment by mras0** [comment]
@bluecursor It appears to do that if it runs out of memory. The behavior you're describing can also be reproduced in WinUAE w/ A500+1MB and exactly 3 floppy drives enabled (if you enable 4 drives it does the same thing, but earlier).

Try to increase the amount of chip ram to 2MB.
