### ISSUE TITLE
Chipset-settings not saved in .vAmiga 

### ISSUE THREAD

**Issue by ha24-1** [dirkwhoffmann/vAmiga#790]
Hi, maybe I'm wrong - but I noticed that the chipset-settings (CPU/MHz) seems not to be saved in a .vAmiga-configuration (Version 2.3 (230106)).

I'm using several settings (f.i. A500/68000/7 with Kick1.3 and A500/68020/14 with Kick2.04). Selected ROM will be saved in .vAmiga, but not the selected processor. 
If I choose "Use as default" all of my configs are from now with this default (as I expected).

No big issue... so, don't panic.
By-the-way: great work and many thanks for this perfect emulator (as your virtualC64, too!). 

Best regards!

**Comment by dirkwhoffmann** [comment]
Hmm, I haven't been able to reproduce this. You are talking about the two options marked with a red arrow in the picture below, aren't you? 

Did you press the "Use as Default" button inside the *Chipset* tab? If the "Use as Default" button in the *Rom* tab is pressed, only the Rom settings are saved. 

<img width="836" alt="Bildschirm­foto 2023-03-29 um 12 37 53" src="https://user-images.githubusercontent.com/12561945/228524879-fefa341f-8d85-4390-93d7-e30bf48a847c.png">

**Comment by dirkwhoffmann** [comment]
The default storage ("Use as default" button) and .vamiga files are two different things.

- The default storage stores the values that are used when a new emulator instance is created, either by launching the app or by opening a new window with Cmd+n.
- .vAmiga files are snapshots. These files contain everything (the emulator state together with all settings). Hence, when you restore a snapshot (either via drag and drop or by double clicking a .vAmiga file), the settings will always reflect what is stored in the snapshot.

**Comment by ha24-1** [comment]
thank you for clarifying my confusion! I will trying again... :-)

**Comment by dirkwhoffmann** [comment]
Can this one be closed?

**Comment by ha24-1** [comment]
yes, please close.
