### ISSUE TITLE
Mouse Selecting/Mouse Caputuring/Use As Default Bug v2.4

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/vAmiga#792]
When I first cold open VA2.4b1, Port1 Device Selection looks like:

![Screenshot 2023-04-19 at 6 13 39 PM](https://user-images.githubusercontent.com/31462938/233211421-3d986ac0-324b-4e6c-a76c-3e8376c37a0c.png)

Booting into Workbench or using Aros Roms, the mouse pointer doesn't move either using the trackpad or Deft Pro Trackball. Selecting the Trackapd, I can move the pointer with the Trackball but not with the Trackpad.  I set as Default then Close the window, reopen, and my port 1 device selection looks like:

![Screenshot 2023-04-19 at 6 23 19 PM](https://user-images.githubusercontent.com/31462938/233212809-e153d62d-7d8a-4ab7-98ea-3ac9bf234a33.png)

I cant move the mouse with the trackpad or the trackball, so I select the trackball and the mouse work  fine with the trackball. I set as Default then Close the window, reopen, and my port 1 device selection looks like:

![Screenshot 2023-04-19 at 6 29 37 PM](https://user-images.githubusercontent.com/31462938/233213700-b632f31a-f198-47e2-8d93-5c462cd41713.png)

The mouse pointer does not move with either the trackpad or the trackball. I close the window and quit VA, restart it and everything starts all over again.  Closing VA, Turning off the trackball and cold starting VA, trackpad is selected but still I can't move the mouse pointer.

I am using Ventura 13.3.1. I don't know if Ventura 13.3.1 broke VA2.4b1 or it's DIT:the other way around, but there seems to be a bug here.

EDIT: The same issue is happening in VirtualC64 4.6b1

**Comment by dirkwhoffmann** [comment]
Might be a bug, but it's kind of impossible to debug it here. I don't have the same hardware.

**Comment by bluecursor** [comment]
IS the checkmark remembering position or actually remember the mouse default selected name?

I think if you add two different types of mouses to a system you could replicate this error? It doesn't happen every restart but it happens more than often.

![Screenshot 2023-04-25 at 4 48 05 PM](https://user-images.githubusercontent.com/31462938/234400041-87572f84-77f9-4370-acad-dd2380058526.png)
![Screenshot 2023-04-25 at 4 48 39 PM](https://user-images.githubusercontent.com/31462938/234400130-5742d9e9-7b34-4bf9-832a-4201dc51ca72.png)

![Screenshot 2023-04-25 at 4 50 59 PM](https://user-images.githubusercontent.com/31462938/234400607-e9f9575a-277c-401c-af56-4459d5214e1e.png)

**Comment by dirkwhoffmann** [comment]
> The mouse pointer does not move with either the trackpad or the trackball. 

This seems to be an issue with the latest two macOS releases. On my machine, macOS's HID manager now reports the Magic mouse as an external device, but the device cannot be used via the HID API (everything coming from this device is directly mapped to the internal mouse). I don't know how to fix this. Apple is constantly changing HID-related stuff and constantly messing it up.
