### ISSUE TITLE
2.4 issues

### ISSUE THREAD

**Issue by maskred5** [dirkwhoffmann/vAmiga#794]
Just want to say, 2.0 is perfection. Best emulator I've ever used, this was the one that got me back into emulators. I hope I NEVER lose it to Mac OS updates. I'm glad you are always releasing new updates. 

I'm still noticing 2.4 seems sluggish in comparison, this is on a relatively fast 2018 Mac Mini with the latest version of Ventura. Could I maybe post a video comparison?

**Comment by dirkwhoffmann** [comment]
A video wouldn't help much, I guess. Somebody needs to crawl through the repo and find out which checkin caused the issue. However, this is a pretty boring job and requires hardware that exhibits the issue.

**Comment by mras0** [comment]
Don't know if it helps, but doing git bisect in my repo (vAmigaSDL, https://github.com/mras0/vAmigaSDL) there seems to have been a serious performance regression between 2.3 and 2.4. Finding the exact commit isn't so easy since interface changes between the two version means I can't just bisect vAmiga (and I could be doing this wrong).

**Comment by mras0** [comment]
Never mind, further bisection shows that it was just because I'd missed #779. Calling Amiga::wakeUp() after getting the buffer fixed it.

**Comment by dirkwhoffmann** [comment]
Just a quick comparison of v2.3 (left) with v2.4 (right) on my MacBook Pro M1:

<img width="1447" alt="Bildschirmfoto 2023-05-18 um 12 38 06" src="https://github.com/dirkwhoffmann/vAmiga/assets/12561945/63a1a738-7f26-4662-9dff-ee1caf81e664">

Roughly same performance. There might be differences on older machines though, but I am not able to reproduce them on my own hardware.

@maskred5: Do you experience a performance hit all the time or only in special situations (many sprites, heavy Copper activity etc.)? If yes, a video could help indeed (opposed to what I've written above).
