### ISSUE TITLE
New hardware

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#796]
Good news: I've got some new super-cool hardware to run real tests on: 

![A3000](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/99cca87f-9672-465e-938c-a65261286e46)

With the new machine at hand, it's probably time to give the MMU project a second try. 

Edit: The original post contained some stuff about a failing test case. It has been moved to a separate issue (#797).

**Comment by dirkwhoffmann** [comment]
After removing a myriad of screws, the newcomer looks like this:

![A3000](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/0e8b70e9-00f8-43b7-8635-975c851ed38d)

Before we do any further testing, the patient must undergo a minor surgical procedure. You might have already spotted the issue.

**Comment by dirkwhoffmann** [comment]
Backside looks pretty good to me.  I have already marked the solder joints that need to be removed:

![A3000_rear](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/2867d770-8c4d-4955-9e28-a5837ea920d3)

**Comment by mithrendal** [comment]
nice one 🤤 ... according to https://amiga.resource.cx/mod/a3000.html this is a most recent a3000 rev 9 board. I spotted a 68030 and a 68882 both runnable at 25 Mhz. The speedy version... ✌️😎

**Comment by webbasan** [comment]
Yep, bought it in 1992, late enough to get a decent revision :slightly_smiling_face:. 
Ok, and I can see on the board picture that I remembered correctly: I replaced some of the chips with the updated revisions, especially Buster and the WD chip, but I think others like Agnus were also updated.

**Comment by emoon** [comment]
What @mithrendal said

It's really important to remove the corrosion as it can/will get worse if not serviced.

**Comment by emoon** [comment]
btw I just ran into this :) https://www.youtube.com/watch?v=JJ6mkfcyGT8 it might be helpful for you.

**Comment by dirkwhoffmann** [comment]
I neutralized the leaked battery fluid with vinegar, cleaned with distilled water and IPA, and applied some electronic cleaner spray afterwards: 

![71154141022__93F6DE24-638C-46FD-9AB5-95A9EFA9C36D Kopie](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/06cb5b35-4330-4459-ba77-93421638dfcf)

Looks pretty good compared to the original photo. Seems like the battery did only cause minor damage to the board. Now, everything has to dry up thoroughly.

**Comment by emoon** [comment]
Looks much better indeed. I have seen other cases that are way worse when it comes to batteries/caps on various hardware.

**Comment by mithrendal** [comment]
Looks completely different ... so clean 😍... @dirkwhoffmann is the complete board that clean now ? what a beauty 

my eyes can spot only one tiny "potential" trace of corrosion maybe left at two of the the six holes at U450 ... @emoon do you think they still can do possibly any harm ?

**Comment by dirkwhoffmann** [comment]
![IMG_5068](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/272273b5-7070-45bd-bcca-2e09abf3911a)

Good news. The machine is still working 😎. Next step will be to replace the (broken) internal disk drive with a Gotek and the (still working) HD by a modern SCSI to SD adapter. Parts are already ordered.

**Comment by dirkwhoffmann** [comment]
Here's another one. Not sure if he's gonna make it 😬

![IMG_5103](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/b3b6203a-4ad2-45b1-a5d4-3417664adbee)

![IMG_5104](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/d63aed23-0d34-4542-bd63-b2cf068ebac7)

After removing the battery and applying some IPA to the most affected area, it doesn't look that bad any more.

![IMG_5106](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/87b639a3-389c-4280-90b1-02df3407dbff)

**Comment by emoon** [comment]
The good thing these days are that even if the motherboard can't be saved due to extensive damage saving the components and getting a replacement board like this http://wordpress.hertell.nu/?p=981 is an option.

Now this of course requires a fair amount of work, but at least there is that option in case the above doesn't save it.

**Comment by mithrendal** [comment]
@emoon interesstibg link. Did you spot ... the last mainboard photo is taken from a A2000. The A3000 (first pictures) seems to be already saved.

**Comment by emoon** [comment]
Ah! I missed that :) but such boards exists as well https://amigastore.eu/821-amiga-2000-remake-motherboard-rev-185.html

**Comment by dirkwhoffmann** [comment]
All cleaned up now. Now it needs to dry thoroughly. 

![IMG_5108](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/4f549306-a8e0-4d72-954b-a475b796615a)

The superfluous boot selector has been removed, along with the Kickstart Rom. I've ordered DiagRom which I want to try out on that machine.

**Comment by dirkwhoffmann** [comment]
Cured from "Varta". Based on the condition of the components, I expect the machine to run just fine for the next couple of years. 

![IMG_5151](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/1f9d5192-a02a-4307-bfdc-645c8e5baff3)

I didn't use DiagRom, because I got a Rom with 42 pins and the A2000 Kickstart Rom only has 40 pins. However, I did some tests with Amiga TestKit and everything looks fine so far.

**Comment by dirkwhoffmann** [comment]
I got this machine as a gift from my cousin yesterday:

![a500_1](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/7c9813fc-26d3-4de9-970b-3fb8f088c961)

He found it while cleaning out his attic. The machine is in perfect condition and looks like it was just taken from the store shelf. It doesn't even show any signs of yellowing. It's a Rev. 5 board (which is good, because I think all of my A500s have different boards). Unfortunately, I had to break the warranty seal to see what's inside 🙄.

![a500_3](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/037100c4-14b7-401b-b19c-2da1848ec8e7)

Most importantly, it still works just fine:

![a500_2](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/2c6eadad-4de9-4367-88e7-8b0f5f16ef1f)

**Comment by mithrendal** [comment]
Kickstart 1.2 ❤️, Rev5 board ... a real OCS powerhorse ❤️

so clean inside ... no traces of dust even after decades😳... how long was it in use by your cousin ? I bet his home was cleaned up twice a week 😅 at least...

**Comment by mithrendal** [comment]
😱OMG its a chicken lip one with space invader keys and a gold tinted main board !!!

https://www.amigalove.com/viewtopic.php?t=1266

this machine is a treasure !

**Comment by dirkwhoffmann** [comment]
Oh, yes, interesting. It has the Commodore Key instead of the Amiga key on the left. I haven't noticed this at first. I don't know what the color of the power LED is since I've only run the machine once with no keyboard connected. My personal A500 (which is lost) must have been a similar model. I think my cousin and I bought it around the same time.

**Comment by dirkwhoffmann** [comment]
Today, I received a mounting frame for installing a Gotek drive in a A1000. So, it's time to upgrade this guy 🥰:

![IMG_5302](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/29621a05-1647-487d-9177-6dd27fa32e49)

Now equipped with a Gotek: 

![IMG_5309](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/627be7cf-0761-4717-bef8-22522388a27d)

Works as expected. Just loaded Kickstart 1.3 from the USB stick:

![IMG_5305](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/95c5ca46-f893-47cd-9edb-b192ef8fe4d2)

The keyboard is working just fine, too: 

![IMG_5307](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/1e855eb5-ce77-41ed-af7c-259faeb0fcf1)

Speaking of keyboards. I've accidentally plugged in the A3000 keyboard into the A2000 while the machine was powered on (well, not really accidentally, I simply forgot that this is a no-go 🙈). 

Now, the keyboard is plain dead. It seems like I killed all diodes on the controller board (upper half). 

![71356100582__FF17CCD9-CE65-435A-9EC3-FB72A9F3E057](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/6453dd14-2d39-4f3d-9596-8fbe10c6ab70)

And the final question is. Who at Commodore had designed those clips?  Not sure if I should blame myself for breaking them 🙄.

![ ](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/f39b7214-04b6-463d-90af-ae3acb2b9077)

**Comment by mithrendal** [comment]
Oh boy 😬 I should have warned you about those clips… I broke all of my clips 🙄 in 1987 -1989 somewhen when trying to open my A1000 for the first time … I simply forgot about that breaking the clips issue on the A1000 … but the good thing is 😀that they not not really needed to properly close it again anyways …

**Comment by dirkwhoffmann** [comment]
Strange enough. I connected the keyboard to read the error code (number of light pulses on the caps lock key) when I discovered that the keyboard was fully working.  

![IMG_5311](https://github.com/dirkwhoffmann/vAmiga/assets/12561945/42169987-72a2-4082-8af4-872f093fc0ac)

So either the keyboard is working despite some damaged diodes (unlikely), or the diodes are no diodes (unlikely), or my multimeter is broken (unlikely).  The next natural step would be to reopen the keyboard and repeat the measurement. However, based on my habit to break Amiga stuff, I better keep it closed and pretend nothing ever happened 🙄.

**Comment by dirkwhoffmann** [comment]
Looking closer at the board reveals that the A1000 is an interesting machine. It's one of the early PAL Amigas (8367 Agnus)  that is based on the original NTSC board (WCS on daughterboard).  Furthermore, it has an R5 Denise which doesn't support EHB. This makes it an excellent test machine since all my other Amiga are equipped with later Denise revisions.

<img width="570" alt="PNG-Bild" src="https://github.com/dirkwhoffmann/vAmiga/assets/12561945/74a0772d-8584-4328-9898-e2eac2df5b41">
