### ISSUE TITLE
Let's twist again isn't displayed correctly

### ISSUE THREAD

**Issue by emoon** [dirkwhoffmann/vAmiga#800]
This bootblock intro https://www.pouet.net/prod.php?which=71703 isn't displayed correctly in vAmiga. The small booze logo shows up (it's a sprite) but the twist effect isn't there.

![001](https://github.com/dirkwhoffmann/vAmiga/assets/350822/1dee664d-3032-4417-a11d-c2cf4467fad8)

It should be noted that this product as set as "AGA" on pouet, but it doesn't require AGA, but it needs a 020 CPU so that might be whats causing the issue here, that said the thing is running and the CPU is executing code, but something is going wrong somewhere.

**Comment by dirkwhoffmann** [comment]
Just tried the demo. In vAmiga 2.4 (Kick 3.1 + 68020), it started like  this:

<img width="934" alt="Bildschirmfoto 2023-11-05 um 18 11 23" src="https://github.com/dirkwhoffmann/vAmiga/assets/12561945/587f01d1-de70-4536-a7b7-64a9ffa5023f">

The background image was slowly drawn, line by line. After a while, when all lines were drawn, it started twisting:

<img width="934" alt="Bildschirmfoto 2023-11-05 um 18 11 39" src="https://github.com/dirkwhoffmann/vAmiga/assets/12561945/776db051-207a-44a2-ab5f-9c7403597a19">

I've also tried in FS-UAE. With the A3000 config, the demo worked  as I think it is intended to work: It started twisting immediately (no slow line drawing at the beginning). However, selecting the A500 config and enabling a 68EC20 CPU manually, it looked like this:

<img width="1072" alt="Bildschirmfoto 2023-11-05 um 18 12 07" src="https://github.com/dirkwhoffmann/vAmiga/assets/12561945/8205b38b-f8a6-411e-9316-6b8f1dcd1291">

The demo seems to be very sensitive to either the HW specs, or the Kickstart version, or both. Needs more investigation.

**Comment by emoon** [comment]
I think the slow line drawing at the start can be as designed if the CPU is "too slow", but I'm unsure.

**Comment by dirkwhoffmann** [comment]
I close the issue for now, since it is open for a long time and it's unlikely that I work on 68020 accuracy any time soon.
