### ISSUE TITLE
SEC macro computes wrong cycle values 

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/vAmiga#801]
https://github.com/dirkwhoffmann/vAmiga/blob/6d5f076e747c2d1860001d3808cc72e5ed500022/Emulator/Base/Aliases.h#L46

with the latest commit 6d5f076e747c2d1860001d3808cc72e5ed500022 the SEC(number_in_seconds) macro above cuts the fractional part of the number. It therefore translates to

`SEC(0.5) == SEC(0) `

and 

`SEC(1.8) == SEC(1) `

when agnus schedules tasks for example every SEC(0.5) then it runs these tasks now in every slot ... which leads to higher host cpu load.

**solution**

use MSEC(500) instead of SEC(0.5)
use MSEC(1800) instead of SEC(1.8)

**Comment by dirkwhoffmann** [comment]
The best way to solve it cleanly is probably to replace the macros with inline functions overloaded for different types.

**Comment by dirkwhoffmann** [comment]
> The best way to solve it cleanly is probably to replace the macros with inline functions overloaded for different types.

Despite being the clearest solution, it is apparently not the best. The compiler does not optimize away the function call in debug builds, even for trivial functions: 

<img width="1228" alt="Bildschirmfoto 2023-12-29 um 17 33 47" src="https://github.com/dirkwhoffmann/vAmiga/assets/12561945/ffff6f98-8f7f-43c1-b4e3-8ccab9119ee4">

Using (overloaded) functions would thus slow down the emulator in debug mode, which I don't want to happen.

**Comment by dirkwhoffmann** [comment]
I went for this solution for now:

```C++
#define USEC(delay)           (Cycle((i64)delay * 28))
#define MSEC(delay)           (Cycle((i64)delay * 28000))
#define SEC(delay)            (Cycle((double)delay * 28000000))
```
