### ISSUE TITLE
Relicense the emulator core under a different license?

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#802]
Situation: For the next couple of months, I won't have time to work on vAmiga because I am involved in new book projects. After that, I am unsure if I want to spend my time coding on vAmiga or another (new) project. Therefore, I am thinking about relicensing the vAmiga core with the MIT license to let the community do with it whatever it wants. As far as I can see, the following licensing constraints exist: 

| External code / library | Used by  | License  |
| -----|-----| -----|
| xdms library | Core  | Public Domain |
| softfloat | Core | Own (MIT like) |
| AmiEmu HD controller | Core      | MIT  |
| Icons from Oxygen icon set | GUI | LGPL |
| Icons from Crystal Clear icon set | GUI | LGPL |

Since I want to keep the UI part under the GNU license for now, there should be no issues with releasing the core under the MIT license, as far as I can see.

Any feedback is welcome about the idea of relicensing the emulator core. Maybe there are reasons to stick to the GNU license, which I am unaware of at the moment.

**Comment by dirkwhoffmann** [comment]
> You: Which software license should I choose? I want to have something like MIT with attribution.

> ChatGPT: For a license similar to the MIT License but with attribution requirements, you might consider the Apache License 2.0 or the BSD 3-Clause License. Both licenses allow users to use, modify, and distribute your software, but they require attribution in certain circumstances.

>The Apache License 2.0 requires that you provide attribution to the original authors in your documentation or where you display notices within the software. It also outlines specific requirements when using any trademarks associated with the software.

>The BSD 3-Clause License, similar to the Apache License, requires users to provide attribution in your documentation or advertising materials but does not require mentioning the use of the software within the distributed software itself.

OK, maybe the BSD 3-Clause instead of MIT? 🤔

**Comment by dirkwhoffmann** [comment]
After digging a bit deeper into the different open-source licenses, I think the following combinations suits best for what I wish to accomplish:

- Starting with v2.5, the emulator core will use the Mozilla Public License 2.0.
- The Mac app (Core + GUI) will continue to be published under the GPL 3.0.

MPL persues file-based copyleft, making it easy to use the vAmiga core in commercial applications while granting the community access to enhancements to the core emulator.  

The GUI code uses GPL images, which means the GUI app needs to stay in the GPL world. 

As far as I understand the legal stuff, MPL 2.0 is compatible with GPL 2.0+ out of the box, so there shouldn't be any technical issues. I only need to replace all file headers in the `Emulator` directory.

**Comment by emoon** [comment]
Sounds great to me :)

**Comment by dirkwhoffmann** [comment]
Done
