### ISSUE TITLE
1541-II.355650-01.bin (x650 and not x640)

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#828]
Have a good day everyone,
confirming that as always I silently follow all the updates of your two great emulators, always satisfied with the great efficiency of the VirtualC64 which has not show any compatibility or other problems with the applications and games I use; I wanted to ask why I was loading my 1541rom-II.355640-01.bin and VirtualC64 detects it as 1541-II.355650-01.bin (50 and not 40). Are there two versions? 
I can't find revision 1541-II.355650-01 anywhere, is it difficult to find on the web ?

<img width="509" alt="Screenshot 2024-06-02 alle 09 55 38" src="https://github.com/dirkwhoffmann/vAmiga/assets/34916641/53c9d9e6-e2a9-44fe-b0c0-55df2a9303a0">

**Comment by dirkwhoffmann** [comment]
I think it's a typo and should display as 355640-01. I'll fix it...
