### ISSUE TITLE
Another World (The Company) freezes

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/vAmiga#842]
This is a follow up from issue vAmigaWeb/vAmigaWeb#254 opened in the vAmigaWeb repo.
The demo [TheCompany_AnotherWorld.hdf.zip](https://github.com/user-attachments/files/17033506/TheCompany_AnotherWorld.hdf.zip) freezes after a couple of seconds. 

> <img width="915" alt="Bildschirmfoto 2024-09-17 um 10 05 59" src="https://github.com/user-attachments/assets/1946da2c-3187-4b5f-a202-0de2dcce1a0b">
> 
> Seems to be a race condition to me. It depends on when exactly the VERTB bit is set during the execution of the BTST instruction. Interestingly, entering the debugger in vAmiga often makes the demo continue. It seems like suspending / pausing the emulator brings Agnus and the CPU slightly out of sync. This lets the demo continue, but shouldn't be the case, obviously.
> 

Regarding the first issue (why does the demo freeze), the following should be done first:

- Add more CPU tests for the BTST instruction in the vAmigaTS repo. I.e., 
  - add an IPL2 style test (directory CPU/IPL2)
  - add timing tests that read from the background color register (directories CPU/Timing, CPU/Timing2).

The second issue has to be tackled separately.

**Comment by dirkwhoffmann** [comment]
Second issue solved (why does the demo continue when entering the debugger in RetroShell?).

Here is the thing: I've entered the debugger by pressing Shift+Return. When RetroShell is open, all key events are intercepted and routed into the shell rather than the emulator. However, the interception check was missing for flag-changing keys such as Shift. As a result, pressing Shift+Return in RetroShell routed the Shift key into the Amiga (in addition to the shell). Pressing a key brings the CPU and Agnus a bit out of sync which lets the BTST instruction recognize VERTB and the demo continues. 

I bet something similar will happen on the real machine. Pressing a key is likely to continue the demo...

**Comment by mras0** [comment]
Here's my attempt at a testcase:
[btst_ipl.zip](https://github.com/user-attachments/files/17071351/btst_ipl.zip)

It uses this sequence before the btst loop to check various cycle "alignments" (d0)
```
        stop    #$2000
        lsr.w   d0,d1
.loop
```
With the vblank handler active the "stop" instruction should retire at the same point during the frame regardless of what happened before.

The output is the number of times the VERT bit was observed outside the interrupt. You may find that vAmiga already matches for this test in which case it's just a subtle timing difference in the time it takes to reach the loop start (probably not worth trying to track down as you can see being even a single CCK off matters).

**Comment by dirkwhoffmann** [comment]
<img width="915" alt="Bildschirmfoto 2024-09-20 um 10 49 27" src="https://github.com/user-attachments/assets/fc9a59fe-a2ee-4dad-9ccd-cafdec0eecef">

Cool test. I'll run this on my real A500 when I am back from vacation. As an aside, it revealed another bug in my latest beta. v3.0b1 didn't accept EXE files any more (🙈). That was easy to fix, though.

**Comment by dirkwhoffmann** [comment]
@mras0's test running on my A500: 

![btst](https://github.com/user-attachments/assets/3cd8a073-56bb-43d9-b130-29138be154c0)

Matches 1:1 with vAmiga. So I guess, we can consider the issue solved.

**Comment by mras0** [comment]
Yes, everything seems to be working fine 👍

**Comment by mras0** [comment]
Just a thought, but maybe you want to add it to vAmigaTS (feel free to adapt as you like of course). It doesn't currently work in WinUAE, but I have it on good word that it will soon, indicating that it's quite a tough test that you'd like to keep passing.

**Comment by dirkwhoffmann** [comment]
The test is now part of the test suite:
https://github.com/dirkwhoffmann/vAmigaTS/tree/master/CPU/Misc/Btstipl
