### ISSUE TITLE
Game Hybris (1988) hangs in infinite loop if turbo drive is selected

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/vAmiga#87]
vAmiga crashes after exiting the game intro.

**Report:**
[report.txt](https://github.com/dirkwhoffmann/vAmiga/files/3365412/report.txt)

**Game:**
[Hybris (1988)(Discovery Software)[cr QTX][t +6 LFC].adf.zip](https://github.com/dirkwhoffmann/vAmiga/files/3365413/Hybris.1988.Discovery.Software.cr.QTX.t.%2B6.LFC.adf.zip)

**Comment by dirkwhoffmann** [comment]
If Df0 is a turbo drive, the intro does not come up. The game polls the disk IRQ bit forever:

<img width="980" alt="Screenshot 2019-07-17 at 18 54 44" src="https://user-images.githubusercontent.com/12561945/61395430-b8905080-a8c5-11e9-868a-03ba88c60799.png">

In SAE it also works with a turbo drive. 

However, if you select an original drive (speed = 1 x), the new version rocks 😎: 

<img width="893" alt="Screenshot 2019-07-17 at 18 58 44" src="https://user-images.githubusercontent.com/12561945/61395481-ce9e1100-a8c5-11e9-94a3-1d393ff12a5e.png">

It's a little bit awkward to steer the spaceship with the mouse. Can't tell if it's supposed to be that way...

<img width="893" alt="Screenshot 2019-07-17 at 19 00 42" src="https://user-images.githubusercontent.com/12561945/61395528-ed040c80-a8c5-11e9-8fc3-ec12cdc42054.png">

**Comment by dirkwhoffmann** [comment]
What's happening is pretty obvious : 

<img width="980" alt="Screenshot 2019-07-19 at 16 43 18" src="https://user-images.githubusercontent.com/12561945/61543822-7e00f200-aa44-11e9-8396-63f836336a3c.png">

1. The game writes to DSKLEN somewhere above.
2. It clears the DSKBLK bit in INTREQ (first arrow where the breakpoint is set).
3. It waits until the DSKBLK bit is set in INTREQR (second arrow).

If a turbo drive is used, DSKBLK is already set in 1., therefore causing 3. to loop indefinitely.

The question is: Why does it work in SAE? Need to check the turbo drive implementation there...

**Comment by dirkwhoffmann** [comment]
Got it:

In SAE, if a turbo read is performed, the following happens (besides a trillion other things):

    done = 2;

Variable done is used later:

    if (done) {
        linecounter = done;

Linecounter is used in the hsync handler

    if (linecounter) {
        linecounter--;
        if (!linecounter)
        disk_dmafinished();
        return;
    }

And disk_dmafinished() does the following 

    SAER.custom.INTREQ(SAEC_Custom_INTF_SETCLR | SAEC_Custom_INTF_DSKBLK);

Hence, setting DSKBLK is delayed by (up to) two raster lines. 

Conclusion: Since it is likely that a lot of games behave like Hybris, the IRQ bit should not be set immediately. SAE / UAE use a delay of 2 raster lines, so let’s shamelessly steal that information from them…

**Comment by dirkwhoffmann** [comment]
Again an easy fix, because Paula is already capable of delaying interrupts.

If 

    // Trigger disk interrupt
    pokeINTREQ(0x8002);

is changed to

    // Trigger disk interrupt with some delay
    agnus->scheduleRel<IRQ_DSKBLK_SLOT>(DMA_CYCLES(512), IRQ_SET);

the game loads well with turbo drives, too 😎.

**Comment by Alessandro1970** [comment]
Game crashes, before loading,
[CRASH.TXT](https://github.com/dirkwhoffmann/vAmiga/files/3563225/CRASH.TXT)
 in v3:

**Comment by dirkwhoffmann** [comment]
Just had the same with Turrican: 

```
4   dirkwhoffmann.vAmiga          	0x0000000108d9729a Agnus::scheduleNextBplEvent(short) + 152 (EventHandler.cpp:377)
5   dirkwhoffmann.vAmiga          	0x0000000108d17caa Agnus::pokeDMACON(unsigned short, unsigned short) + 340 (Agnus.cpp:870)
6   dirkwhoffmann.vAmiga          	0x0000000108d17b43 Agnus::pokeDMACON(unsigned short) + 89 (Agnus.cpp:812)
7   dirkwhoffmann.vAmiga          	0x0000000108d97881 Agnus::serviceREGEvent(EventSlot) + 77
8   dirkwhoffmann.vAmiga          	0x0000000108d977d7 Agnus::executeEventsUntil(long long) + 1061 (EventHandler.cpp:413)
```

I know where to look at. pokeDMACON has to dynamically adjust the event table when it is modified in the middle of the raster line. Under some circumstances, the event table seems to get screwed up.
