### ISSUE TITLE
tools and strategies for compatibility fine tuning 

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/vAmiga#9]
Just wanted to bring this new and very cool project to your attention. In my opinion it is an incredible cool tool. And a good starting point of comparing vAmigas behaviour in detail with the latest generations of high compatible UAE Emulators .

In short, you can develop amiga code in VisualCode on your mac with full code completion, explanation for custom registers, assembler syntax hilighting and so on. Then you can switch to debug and run or debug your code with the integrated fsuae, inspect registers memory and so on. You can also let it generate an ADF file. This works really fast and fluenty.  I just had several debug sessions with the copper bar program from its example workspace. You start programming run stop edit change something start again see results and so on... make several trial and error cycles  in only 15 seconds or so.

The idea: it can be used to  write short mini test programs for vAmiga, to teach vAmiga compatibility of current versions of UAE. 
Strategy: We let it build ADFs with certain short test code mini programs, see the results in fsuae, inspect registers in VisualCode with integrated FSUAE debugger and then we can feed that same ADF into vAmiga and compare that same code in vAmigas debugger. Side by side comparison and debugging of fsuae and vAmiga.

you find the well documented visual studio extension of **Amiga-Assembly** here:
https://github.com/prb28/vscode-amiga-assembly

You install  the following extension inside visual studios extension finder.
https://marketplace.visualstudio.com/items?itemName=prb28.amiga-assembly

Once installed you can download an example workspace with a small copper mini program example:
https://github.com/prb28/vscode-amiga-wks-example

To debug and run the small copper mini program example, you still have to get the latest precompiled external binaries of FSUAE, ADF Tools for the mac with which Amiga-Assembly works together from the osx.zip file here
https://github.com/prb28/vscode-amiga-assembly/releases 

copy them into the bin folder of the example workspace. Now you will be able to build run debug and build short Amiga programs and export ADFs without leaving VisualStudioCode.😃

Dirk, if you have questions about setting up and how to run it, just ask me here. The developer is also very sympathic and currently still activly developing it.

**Comment by dirkwhoffmann** [comment]
Thanks a lot for pointing me to this!!!

I was already thinking a lot about the "second phase" of vAmiga development (which will be to improve emulation accuracy). For the C64, there exists a large set of small test programs (mostly done by VICE coders I think) which is an invaluable help to get the details right. For the Amiga, such a test collection doesn't exist and I think "Amiga Assembly for Visual Studio Code" will definitely help to close this gap! I already feared that I'll have to code inside the Amiga with the ancient development tools I used to teach myself the C programming language a couple of hundred years ago 😂. 

I'll try to install the tool on my machine once I'm done with rudimentary sprite support.

**Comment by mithrendal** [comment]
😂
I have also a ADF file with wonderful ancient world of the Aztec-C environment for you.

http://www.aztecmuseum.ca 
_(Harry Suckow (the Copyright holder for Aztec C) has given permission for that website to redistribute Manx Software Systems discontinued Aztec C compilers for now-obsolete platforms for educational purposes by researchers and enthusiasts. )_

**Comment by dirkwhoffmann** [comment]
I have copied the contents of this post to a separate Wiki page, because the Amiga-Assembly plugin will surely become important in the future. I have to admit that I still didn't look at this promising project, but I surely will...
